// Copyright 2022-2023 Beken
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This is a generated file, if you need to modify it, use the script to
// generate and modify all the struct.h, ll.h, reg.h, debug_dump.c files!

#pragma once


#ifdef __cplusplus
extern "C" {
#endif


#define SYS_AONP_REG0_ADDR (SOC_SYS_AONP_REG_BASE + (0x0 << 2))

#define SYS_AONP_REG0_DEVICEID_POS (0)
#define SYS_AONP_REG0_DEVICEID_MASK (0xffffffff)

#define SYS_AONP_REG1_ADDR (SOC_SYS_AONP_REG_BASE + (0x1 << 2))

#define SYS_AONP_REG1_VERSIONID_POS (0)
#define SYS_AONP_REG1_VERSIONID_MASK (0xffffffff)

#define SYS_AONP_REG2_ADDR (SOC_SYS_AONP_REG_BASE + (0x2 << 2))

#define SYS_AONP_REG2_BOOT_MODE_POS (0)
#define SYS_AONP_REG2_BOOT_MODE_MASK (0x1)

#define SYS_AONP_REG2_CLKG_BPS_POS (1)
#define SYS_AONP_REG2_CLKG_BPS_MASK (0x1)

#define SYS_AONP_REG2_RESERVED_BIT_2_3_POS (2)
#define SYS_AONP_REG2_RESERVED_BIT_2_3_MASK (0x3)

#define SYS_AONP_REG2_RF_SWITCH_MANUAL_EN_POS (4)
#define SYS_AONP_REG2_RF_SWITCH_MANUAL_EN_MASK (0x1)

#define SYS_AONP_REG2_RF_SOURCE_POS (5)
#define SYS_AONP_REG2_RF_SOURCE_MASK (0x3)

#define SYS_AONP_REG2_JTAG_CORE_SEL_POS (7)
#define SYS_AONP_REG2_JTAG_CORE_SEL_MASK (0x1)

#define SYS_AONP_REG2_RESERVED_BIT_8_8_POS (8)
#define SYS_AONP_REG2_RESERVED_BIT_8_8_MASK (0x1)

#define SYS_AONP_REG2_FLASH_SEL_POS (9)
#define SYS_AONP_REG2_FLASH_SEL_MASK (0x1)

#define SYS_AONP_REG2_FEM_BPS_TXEN_POS (10)
#define SYS_AONP_REG2_FEM_BPS_TXEN_MASK (0x1)

#define SYS_AONP_REG2_GPIO_FLASH_SYS_ENABLE_POS (11)
#define SYS_AONP_REG2_GPIO_FLASH_SYS_ENABLE_MASK (0x1)

#define SYS_AONP_REG2_BOOT_MODE_NORST_POS (12)
#define SYS_AONP_REG2_BOOT_MODE_NORST_MASK (0x1)

#define SYS_AONP_REG2_RESERVED_BIT_13_31_POS (13)
#define SYS_AONP_REG2_RESERVED_BIT_13_31_MASK (0x7ffff)

#define SYS_AONP_REG3_ADDR (SOC_SYS_AONP_REG_BASE + (0x3 << 2))

#define SYS_AONP_REG3_CORE0_HALTED_POS (0)
#define SYS_AONP_REG3_CORE0_HALTED_MASK (0x1)

#define SYS_AONP_REG3_CORE1_HALTED_POS (1)
#define SYS_AONP_REG3_CORE1_HALTED_MASK (0x1)

#define SYS_AONP_REG3_RESERVED_BIT_2_3_POS (2)
#define SYS_AONP_REG3_RESERVED_BIT_2_3_MASK (0x3)

#define SYS_AONP_REG3_CPU0_SW_RESET_POS (4)
#define SYS_AONP_REG3_CPU0_SW_RESET_MASK (0x1)

#define SYS_AONP_REG3_CPU1_SW_RESET_POS (5)
#define SYS_AONP_REG3_CPU1_SW_RESET_MASK (0x1)

#define SYS_AONP_REG3_RESERVED_BIT_6_7_POS (6)
#define SYS_AONP_REG3_RESERVED_BIT_6_7_MASK (0x3)

#define SYS_AONP_REG3_CPU0_PWR_DW_STATE_POS (8)
#define SYS_AONP_REG3_CPU0_PWR_DW_STATE_MASK (0x1)

#define SYS_AONP_REG3_CPU1_PWR_DW_STATE_POS (9)
#define SYS_AONP_REG3_CPU1_PWR_DW_STATE_MASK (0x1)

#define SYS_AONP_REG3_RESERVED_BIT_10_11_POS (10)
#define SYS_AONP_REG3_RESERVED_BIT_10_11_MASK (0x3)

#define SYS_AONP_REG3_CPU0_EXIST_POS (12)
#define SYS_AONP_REG3_CPU0_EXIST_MASK (0x1)

#define SYS_AONP_REG3_CPU1_EXIST_POS (13)
#define SYS_AONP_REG3_CPU1_EXIST_MASK (0x1)

#define SYS_AONP_REG3_CPU2_EXIST_POS (14)
#define SYS_AONP_REG3_CPU2_EXIST_MASK (0x1)

#define SYS_AONP_REG3_CPU3_EXIST_POS (15)
#define SYS_AONP_REG3_CPU3_EXIST_MASK (0x1)

#define SYS_AONP_REG3_RESERVED_BIT_16_31_POS (16)
#define SYS_AONP_REG3_RESERVED_BIT_16_31_MASK (0xffff)

#define SYS_AONP_REG4_ADDR (SOC_SYS_AONP_REG_BASE + (0x4 << 2))

#define SYS_AONP_REG4_CPU0_SW_RST_POS (0)
#define SYS_AONP_REG4_CPU0_SW_RST_MASK (0x1)

#define SYS_AONP_REG4_CPU0_PWR_DW_POS (1)
#define SYS_AONP_REG4_CPU0_PWR_DW_MASK (0x1)

#define SYS_AONP_REG4_CPU_INT_MASK_POS (2)
#define SYS_AONP_REG4_CPU_INT_MASK_MASK (0x1)

#define SYS_AONP_REG4_CPU0_HALT_POS (3)
#define SYS_AONP_REG4_CPU0_HALT_MASK (0x1)

#define SYS_AONP_REG4_RESERVED_BIT_4_4_POS (4)
#define SYS_AONP_REG4_RESERVED_BIT_4_4_MASK (0x1)

#define SYS_AONP_REG4_CPU0_RXEVT_SEL_POS (5)
#define SYS_AONP_REG4_CPU0_RXEVT_SEL_MASK (0x3)

#define SYS_AONP_REG4_RESERVED_7_7_POS (7)
#define SYS_AONP_REG4_RESERVED_7_7_MASK (0x1)

#define SYS_AONP_REG4_CPU0_OFFSET_POS (8)
#define SYS_AONP_REG4_CPU0_OFFSET_MASK (0xffffff)

#define SYS_AONP_REG5_ADDR (SOC_SYS_AONP_REG_BASE + (0x5 << 2))

#define SYS_AONP_REG5_CPU1_SW_RST_POS (0)
#define SYS_AONP_REG5_CPU1_SW_RST_MASK (0x1)

#define SYS_AONP_REG5_CPU1_PWR_DW_POS (1)
#define SYS_AONP_REG5_CPU1_PWR_DW_MASK (0x1)

#define SYS_AONP_REG5_RESERVED_2_2_POS (2)
#define SYS_AONP_REG5_RESERVED_2_2_MASK (0x1)

#define SYS_AONP_REG5_CPU1_HALT_POS (3)
#define SYS_AONP_REG5_CPU1_HALT_MASK (0x1)

#define SYS_AONP_REG5_RESERVED_BIT_4_4_POS (4)
#define SYS_AONP_REG5_RESERVED_BIT_4_4_MASK (0x1)

#define SYS_AONP_REG5_CPU1_RXEVT_SEL_POS (5)
#define SYS_AONP_REG5_CPU1_RXEVT_SEL_MASK (0x3)

#define SYS_AONP_REG5_RESERVED_7_7_POS (7)
#define SYS_AONP_REG5_RESERVED_7_7_MASK (0x1)

#define SYS_AONP_REG5_CPU1_OFFSET_POS (8)
#define SYS_AONP_REG5_CPU1_OFFSET_MASK (0xffffff)

#define SYS_AONP_REG8_ADDR (SOC_SYS_AONP_REG_BASE + (0x8 << 2))

#define SYS_AONP_REG8_CKSEL_CORE_POS (0)
#define SYS_AONP_REG8_CKSEL_CORE_MASK (0x3)

#define SYS_AONP_REG8_CKDIV_CORE_POS (2)
#define SYS_AONP_REG8_CKDIV_CORE_MASK (0xf)

#define SYS_AONP_REG8_CKSEL_FLASH_POS (6)
#define SYS_AONP_REG8_CKSEL_FLASH_MASK (0x3)

#define SYS_AONP_REG8_CKDIV_FLASH_POS (8)
#define SYS_AONP_REG8_CKDIV_FLASH_MASK (0x7)

#define SYS_AONP_REG8_CKSEL_AUXS_POS (11)
#define SYS_AONP_REG8_CKSEL_AUXS_MASK (0x3)

#define SYS_AONP_REG8_CKDIV_AUXS_POS (13)
#define SYS_AONP_REG8_CKDIV_AUXS_MASK (0x3f)

#define SYS_AONP_REG8_CKDIV_26MO_POS (19)
#define SYS_AONP_REG8_CKDIV_26MO_MASK (0x7)

#define SYS_AONP_REG8_RESERVED_22_23_POS (22)
#define SYS_AONP_REG8_RESERVED_22_23_MASK (0x3)

#define SYS_AONP_REG8_PHASE_CFG_960M_POS (24)
#define SYS_AONP_REG8_PHASE_CFG_960M_MASK (0xff)

#define SYS_AONP_REG9_ADDR (SOC_SYS_AONP_REG_BASE + (0x9 << 2))

#define SYS_AONP_REG9_CKSEL_I2C0_POS (0)
#define SYS_AONP_REG9_CKSEL_I2C0_MASK (0x1)

#define SYS_AONP_REG9_CKSEL_I2C3_POS (1)
#define SYS_AONP_REG9_CKSEL_I2C3_MASK (0x1)

#define SYS_AONP_REG9_CKSEL_UART0_POS (2)
#define SYS_AONP_REG9_CKSEL_UART0_MASK (0x1)

#define SYS_AONP_REG9_CKSEL_UART1_POS (3)
#define SYS_AONP_REG9_CKSEL_UART1_MASK (0x1)

#define SYS_AONP_REG9_CKSEL_UART2_POS (4)
#define SYS_AONP_REG9_CKSEL_UART2_MASK (0x1)

#define SYS_AONP_REG9_CKSEL_UART3_POS (5)
#define SYS_AONP_REG9_CKSEL_UART3_MASK (0x1)

#define SYS_AONP_REG9_CKSEL_UART4_POS (6)
#define SYS_AONP_REG9_CKSEL_UART4_MASK (0x1)

#define SYS_AONP_REG9_CKSEL_SPI0_POS (7)
#define SYS_AONP_REG9_CKSEL_SPI0_MASK (0x1)

#define SYS_AONP_REG9_CKSEL_SPI1_POS (8)
#define SYS_AONP_REG9_CKSEL_SPI1_MASK (0x1)

#define SYS_AONP_REG9_CKSEL_SPI2_POS (9)
#define SYS_AONP_REG9_CKSEL_SPI2_MASK (0x1)

#define SYS_AONP_REG9_CKSEL_SPI3_POS (10)
#define SYS_AONP_REG9_CKSEL_SPI3_MASK (0x1)

#define SYS_AONP_REG9_CKSEL_I2S0_POS (11)
#define SYS_AONP_REG9_CKSEL_I2S0_MASK (0x1)

#define SYS_AONP_REG9_CKDIV_I2S0_POS (12)
#define SYS_AONP_REG9_CKDIV_I2S0_MASK (0x3)

#define SYS_AONP_REG9_CKSEL_I2S1_POS (14)
#define SYS_AONP_REG9_CKSEL_I2S1_MASK (0x1)

#define SYS_AONP_REG9_CKDIV_I2S1_POS (15)
#define SYS_AONP_REG9_CKDIV_I2S1_MASK (0x3)

#define SYS_AONP_REG9_CKSEL_I2S2_POS (17)
#define SYS_AONP_REG9_CKSEL_I2S2_MASK (0x1)

#define SYS_AONP_REG9_CKDIV_I2S2_POS (18)
#define SYS_AONP_REG9_CKDIV_I2S2_MASK (0x3)

#define SYS_AONP_REG9_CKSEL_I2S3_POS (20)
#define SYS_AONP_REG9_CKSEL_I2S3_MASK (0x1)

#define SYS_AONP_REG9_CKDIV_I2S3_POS (21)
#define SYS_AONP_REG9_CKDIV_I2S3_MASK (0x3)

#define SYS_AONP_REG9_CKSEL_I2S4_POS (23)
#define SYS_AONP_REG9_CKSEL_I2S4_MASK (0x1)

#define SYS_AONP_REG9_CKDIV_I2S4_POS (24)
#define SYS_AONP_REG9_CKDIV_I2S4_MASK (0x3)

#define SYS_AONP_REG9_CKSEL_SADC_POS (26)
#define SYS_AONP_REG9_CKSEL_SADC_MASK (0x1)

#define SYS_AONP_REG9_CKSEL_I3C_POS (27)
#define SYS_AONP_REG9_CKSEL_I3C_MASK (0x1)

#define SYS_AONP_REG9_CKSEL_TIM0_POS (28)
#define SYS_AONP_REG9_CKSEL_TIM0_MASK (0x1)

#define SYS_AONP_REG9_CKSEL_TIM1_POS (29)
#define SYS_AONP_REG9_CKSEL_TIM1_MASK (0x1)

#define SYS_AONP_REG9_CKSEL_TIM2_POS (30)
#define SYS_AONP_REG9_CKSEL_TIM2_MASK (0x1)

#define SYS_AONP_REG9_CKSEL_TIM3_POS (31)
#define SYS_AONP_REG9_CKSEL_TIM3_MASK (0x1)

#define SYS_AONP_REGA_ADDR (SOC_SYS_AONP_REG_BASE + (0xa << 2))

#define SYS_AONP_REGA_CKSEL_PWM0_POS (0)
#define SYS_AONP_REGA_CKSEL_PWM0_MASK (0x1)

#define SYS_AONP_REGA_CKSEL_CAN0_POS (1)
#define SYS_AONP_REGA_CKSEL_CAN0_MASK (0x1)

#define SYS_AONP_REGA_CKSEL_CAN1_POS (2)
#define SYS_AONP_REGA_CKSEL_CAN1_MASK (0x1)

#define SYS_AONP_REGA_CKSEL_SCR0_POS (3)
#define SYS_AONP_REGA_CKSEL_SCR0_MASK (0x1)

#define SYS_AONP_REGA_CKSEL_AUDIO_POS (4)
#define SYS_AONP_REGA_CKSEL_AUDIO_MASK (0x1)

#define SYS_AONP_REGA_CKDIV_AUDIO_POS (5)
#define SYS_AONP_REGA_CKDIV_AUDIO_MASK (0x7)

#define SYS_AONP_REGA_CKSEL_AUDIF0_POS (8)
#define SYS_AONP_REGA_CKSEL_AUDIF0_MASK (0x1)

#define SYS_AONP_REGA_CKDIV_AUDIF0_POS (9)
#define SYS_AONP_REGA_CKDIV_AUDIF0_MASK (0x7)

#define SYS_AONP_REGA_CKSEL_AUDIF1_POS (12)
#define SYS_AONP_REGA_CKSEL_AUDIF1_MASK (0x1)

#define SYS_AONP_REGA_CKDIV_AUDIF1_POS (13)
#define SYS_AONP_REGA_CKDIV_AUDIF1_MASK (0x7)

#define SYS_AONP_REGA_CKDIV_I2SO_POS (16)
#define SYS_AONP_REGA_CKDIV_I2SO_MASK (0x7)

#define SYS_AONP_REGA_CKSEL_AUXS_ENET_POS (19)
#define SYS_AONP_REGA_CKSEL_AUXS_ENET_MASK (0x1)

#define SYS_AONP_REGA_CKDIV_AUXS_ENET_POS (20)
#define SYS_AONP_REGA_CKDIV_AUXS_ENET_MASK (0xf)

#define SYS_AONP_REGA_CKSEL_TRACE_POS (24)
#define SYS_AONP_REGA_CKSEL_TRACE_MASK (0x1)

#define SYS_AONP_REGA_CKDIV_TRACE_POS (25)
#define SYS_AONP_REGA_CKDIV_TRACE_MASK (0x7)

#define SYS_AONP_REGA_RESERVED_28_31_POS (28)
#define SYS_AONP_REGA_RESERVED_28_31_MASK (0xf)

#define SYS_AONP_REGB_ADDR (SOC_SYS_AONP_REG_BASE + (0xb << 2))

#define SYS_AONP_REGB_ANASPI_FREQ_POS (0)
#define SYS_AONP_REGB_ANASPI_FREQ_MASK (0x3f)

#define SYS_AONP_REGB_RESERVED_BIT_6_31_POS (6)
#define SYS_AONP_REGB_RESERVED_BIT_6_31_MASK (0x3ffffff)

#define SYS_AONP_REGC_ADDR (SOC_SYS_AONP_REG_BASE + (0xc << 2))

#define SYS_AONP_REGC_TIM0_CKEN_POS (0)
#define SYS_AONP_REGC_TIM0_CKEN_MASK (0x1)

#define SYS_AONP_REGC_TIM1_CKEN_POS (1)
#define SYS_AONP_REGC_TIM1_CKEN_MASK (0x1)

#define SYS_AONP_REGC_TIM2_CKEN_POS (2)
#define SYS_AONP_REGC_TIM2_CKEN_MASK (0x1)

#define SYS_AONP_REGC_TIM3_CKEN_POS (3)
#define SYS_AONP_REGC_TIM3_CKEN_MASK (0x1)

#define SYS_AONP_REGC_UART0_CKEN_POS (4)
#define SYS_AONP_REGC_UART0_CKEN_MASK (0x1)

#define SYS_AONP_REGC_UART1_CKEN_POS (5)
#define SYS_AONP_REGC_UART1_CKEN_MASK (0x1)

#define SYS_AONP_REGC_UART2_CKEN_POS (6)
#define SYS_AONP_REGC_UART2_CKEN_MASK (0x1)

#define SYS_AONP_REGC_UART3_CKEN_POS (7)
#define SYS_AONP_REGC_UART3_CKEN_MASK (0x1)

#define SYS_AONP_REGC_UART4_CKEN_POS (8)
#define SYS_AONP_REGC_UART4_CKEN_MASK (0x1)

#define SYS_AONP_REGC_SPI0_CKEN_POS (9)
#define SYS_AONP_REGC_SPI0_CKEN_MASK (0x1)

#define SYS_AONP_REGC_SPI1_CKEN_POS (10)
#define SYS_AONP_REGC_SPI1_CKEN_MASK (0x1)

#define SYS_AONP_REGC_SPI2_CKEN_POS (11)
#define SYS_AONP_REGC_SPI2_CKEN_MASK (0x1)

#define SYS_AONP_REGC_SPI3_CKEN_POS (12)
#define SYS_AONP_REGC_SPI3_CKEN_MASK (0x1)

#define SYS_AONP_REGC_SADC_CKEN_POS (13)
#define SYS_AONP_REGC_SADC_CKEN_MASK (0x1)

#define SYS_AONP_REGC_PWM0_CKEN_POS (14)
#define SYS_AONP_REGC_PWM0_CKEN_MASK (0x1)

#define SYS_AONP_REGC_OTP_CKEN_POS (15)
#define SYS_AONP_REGC_OTP_CKEN_MASK (0x1)

#define SYS_AONP_REGC_I3C_CKEN_POS (16)
#define SYS_AONP_REGC_I3C_CKEN_MASK (0x1)

#define SYS_AONP_REGC_I2S0_CKEN_POS (17)
#define SYS_AONP_REGC_I2S0_CKEN_MASK (0x1)

#define SYS_AONP_REGC_I2S1_CKEN_POS (18)
#define SYS_AONP_REGC_I2S1_CKEN_MASK (0x1)

#define SYS_AONP_REGC_I2S2_CKEN_POS (19)
#define SYS_AONP_REGC_I2S2_CKEN_MASK (0x1)

#define SYS_AONP_REGC_I2S3_CKEN_POS (20)
#define SYS_AONP_REGC_I2S3_CKEN_MASK (0x1)

#define SYS_AONP_REGC_I2S4_CKEN_POS (21)
#define SYS_AONP_REGC_I2S4_CKEN_MASK (0x1)

#define SYS_AONP_REGC_I2C0_CKEN_POS (22)
#define SYS_AONP_REGC_I2C0_CKEN_MASK (0x1)

#define SYS_AONP_REGC_I2C3_CKEN_POS (23)
#define SYS_AONP_REGC_I2C3_CKEN_MASK (0x1)

#define SYS_AONP_REGC_IRDA0_CKEN_POS (24)
#define SYS_AONP_REGC_IRDA0_CKEN_MASK (0x1)

#define SYS_AONP_REGC_IRDA1_CKEN_POS (25)
#define SYS_AONP_REGC_IRDA1_CKEN_MASK (0x1)

#define SYS_AONP_REGC_IRDA2_CKEN_POS (26)
#define SYS_AONP_REGC_IRDA2_CKEN_MASK (0x1)

#define SYS_AONP_REGC_IRDA3_CKEN_POS (27)
#define SYS_AONP_REGC_IRDA3_CKEN_MASK (0x1)

#define SYS_AONP_REGC_CAN0_CKEN_POS (28)
#define SYS_AONP_REGC_CAN0_CKEN_MASK (0x1)

#define SYS_AONP_REGC_CAN1_CKEN_POS (29)
#define SYS_AONP_REGC_CAN1_CKEN_MASK (0x1)

#define SYS_AONP_REGC_LIN0_CKEN_POS (30)
#define SYS_AONP_REGC_LIN0_CKEN_MASK (0x1)

#define SYS_AONP_REGC_SCR0_CKEN_POS (31)
#define SYS_AONP_REGC_SCR0_CKEN_MASK (0x1)

#define SYS_AONP_REGD_ADDR (SOC_SYS_AONP_REG_BASE + (0xd << 2))

#define SYS_AONP_REGD_AUDIO_CKEN_POS (0)
#define SYS_AONP_REGD_AUDIO_CKEN_MASK (0x1)

#define SYS_AONP_REGD_AUDIF0_CKEN_POS (1)
#define SYS_AONP_REGD_AUDIF0_CKEN_MASK (0x1)

#define SYS_AONP_REGD_AUDIF1_CKEN_POS (2)
#define SYS_AONP_REGD_AUDIF1_CKEN_MASK (0x1)

#define SYS_AONP_REGD_I2SO_CKEN_POS (3)
#define SYS_AONP_REGD_I2SO_CKEN_MASK (0x1)

#define SYS_AONP_REGD_CEC_CKEN_POS (4)
#define SYS_AONP_REGD_CEC_CKEN_MASK (0x1)

#define SYS_AONP_REGD_XDAC0_CKEN_POS (5)
#define SYS_AONP_REGD_XDAC0_CKEN_MASK (0x1)

#define SYS_AONP_REGD_XDAC1_CKEN_POS (6)
#define SYS_AONP_REGD_XDAC1_CKEN_MASK (0x1)

#define SYS_AONP_REGD_AUXS_CKEN_POS (7)
#define SYS_AONP_REGD_AUXS_CKEN_MASK (0x1)

#define SYS_AONP_REGD_AUXS_ENET_CKEN_POS (8)
#define SYS_AONP_REGD_AUXS_ENET_CKEN_MASK (0x1)

#define SYS_AONP_REGD_SIG_26MS_CKEN_POS (9)
#define SYS_AONP_REGD_SIG_26MS_CKEN_MASK (0x1)

#define SYS_AONP_REGD_SIG_32KS_CKEN_POS (10)
#define SYS_AONP_REGD_SIG_32KS_CKEN_MASK (0x1)

#define SYS_AONP_REGD_SIG_26MO_CKEN_POS (11)
#define SYS_AONP_REGD_SIG_26MO_CKEN_MASK (0x1)

#define SYS_AONP_REGD_SIG_240M_CKEN_POS (12)
#define SYS_AONP_REGD_SIG_240M_CKEN_MASK (0x1)

#define SYS_AONP_REGD_SIG_320M_CKEN_POS (13)
#define SYS_AONP_REGD_SIG_320M_CKEN_MASK (0x1)

#define SYS_AONP_REGD_SIG_480M_CKEN_POS (14)
#define SYS_AONP_REGD_SIG_480M_CKEN_MASK (0x1)

#define SYS_AONP_REGD_SIG_160M_CKEN_POS (15)
#define SYS_AONP_REGD_SIG_160M_CKEN_MASK (0x1)

#define SYS_AONP_REGD_SIG_120M_CKEN_POS (16)
#define SYS_AONP_REGD_SIG_120M_CKEN_MASK (0x1)

#define SYS_AONP_REGD_TRACE_CKEN_POS (17)
#define SYS_AONP_REGD_TRACE_CKEN_MASK (0x1)

#define SYS_AONP_REGD_RESERVED_18_21_POS (18)
#define SYS_AONP_REGD_RESERVED_18_21_MASK (0xf)

#define SYS_AONP_REGD_WLSS_CKEN_POS (22)
#define SYS_AONP_REGD_WLSS_CKEN_MASK (0x1)

#define SYS_AONP_REGD_BTDM_CKEN_POS (23)
#define SYS_AONP_REGD_BTDM_CKEN_MASK (0x1)

#define SYS_AONP_REGD_XVER_CKEN_POS (24)
#define SYS_AONP_REGD_XVER_CKEN_MASK (0x1)

#define SYS_AONP_REGD_MAC_CKEN_POS (25)
#define SYS_AONP_REGD_MAC_CKEN_MASK (0x1)

#define SYS_AONP_REGD_PHY_CKEN_POS (26)
#define SYS_AONP_REGD_PHY_CKEN_MASK (0x1)

#define SYS_AONP_REGD_THREAD_CKEN_POS (27)
#define SYS_AONP_REGD_THREAD_CKEN_MASK (0x1)

#define SYS_AONP_REGD_BK24_CKEN_POS (28)
#define SYS_AONP_REGD_BK24_CKEN_MASK (0x1)

#define SYS_AONP_REGD_RF_CKEN_POS (29)
#define SYS_AONP_REGD_RF_CKEN_MASK (0x1)

#define SYS_AONP_REGD_OFDM_CKEN_POS (30)
#define SYS_AONP_REGD_OFDM_CKEN_MASK (0x1)

#define SYS_AONP_REGD_RESERVED_31_31_POS (31)
#define SYS_AONP_REGD_RESERVED_31_31_MASK (0x1)

#define SYS_AONP_REGF_ADDR (SOC_SYS_AONP_REG_BASE + (0xf << 2))

#define SYS_AONP_REGF_RESERVED_0_0_POS (0)
#define SYS_AONP_REGF_RESERVED_0_0_MASK (0x1)

#define SYS_AONP_REGF_RESERVED_1_1_POS (1)
#define SYS_AONP_REGF_RESERVED_1_1_MASK (0x1)

#define SYS_AONP_REGF_RESERVED_2_2_POS (2)
#define SYS_AONP_REGF_RESERVED_2_2_MASK (0x1)

#define SYS_AONP_REGF_MACP_MEM_RET_POS (3)
#define SYS_AONP_REGF_MACP_MEM_RET_MASK (0x1)

#define SYS_AONP_REGF_PHYP_MEM_RET_POS (4)
#define SYS_AONP_REGF_PHYP_MEM_RET_MASK (0x1)

#define SYS_AONP_REGF_THREAD_MEM_RET_POS (5)
#define SYS_AONP_REGF_THREAD_MEM_RET_MASK (0x1)

#define SYS_AONP_REGF_ENCP_MEM_RET_POS (6)
#define SYS_AONP_REGF_ENCP_MEM_RET_MASK (0x1)

#define SYS_AONP_REGF_CAN0_MEM_RET_POS (7)
#define SYS_AONP_REGF_CAN0_MEM_RET_MASK (0x1)

#define SYS_AONP_REGF_CAN1_MEM_RET_POS (8)
#define SYS_AONP_REGF_CAN1_MEM_RET_MASK (0x1)

#define SYS_AONP_REGF_IRDA0_MEM_RET_POS (9)
#define SYS_AONP_REGF_IRDA0_MEM_RET_MASK (0x1)

#define SYS_AONP_REGF_IRDA1_MEM_RET_POS (10)
#define SYS_AONP_REGF_IRDA1_MEM_RET_MASK (0x1)

#define SYS_AONP_REGF_DMA0_MEM_RET_POS (11)
#define SYS_AONP_REGF_DMA0_MEM_RET_MASK (0x1)

#define SYS_AONP_REGF_SPI1_MEM_RET_POS (12)
#define SYS_AONP_REGF_SPI1_MEM_RET_MASK (0x1)

#define SYS_AONP_REGF_SPI2_MEM_RET_POS (13)
#define SYS_AONP_REGF_SPI2_MEM_RET_MASK (0x1)

#define SYS_AONP_REGF_UART1_MEM_RET_POS (14)
#define SYS_AONP_REGF_UART1_MEM_RET_MASK (0x1)

#define SYS_AONP_REGF_UART2_MEM_RET_POS (15)
#define SYS_AONP_REGF_UART2_MEM_RET_MASK (0x1)

#define SYS_AONP_REGF_UART3_MEM_RET_POS (16)
#define SYS_AONP_REGF_UART3_MEM_RET_MASK (0x1)

#define SYS_AONP_REGF_UART0_MEM_RET_POS (17)
#define SYS_AONP_REGF_UART0_MEM_RET_MASK (0x1)

#define SYS_AONP_REGF_SPI0_MEM_RET_POS (18)
#define SYS_AONP_REGF_SPI0_MEM_RET_MASK (0x1)

#define SYS_AONP_REGF_FLSH_MEM_RET_POS (19)
#define SYS_AONP_REGF_FLSH_MEM_RET_MASK (0x1)

#define SYS_AONP_REGF_AUDP_MEM_RET_POS (20)
#define SYS_AONP_REGF_AUDP_MEM_RET_MASK (0x1)

#define SYS_AONP_REGF_I3C_MEM_RET_POS (21)
#define SYS_AONP_REGF_I3C_MEM_RET_MASK (0x1)

#define SYS_AONP_REGF_XVR_MEM_RET_POS (22)
#define SYS_AONP_REGF_XVR_MEM_RET_MASK (0x1)

#define SYS_AONP_REGF_RESERVED_23_23_POS (23)
#define SYS_AONP_REGF_RESERVED_23_23_MASK (0x1)

#define SYS_AONP_REGF_BK24_MEM_RET_POS (24)
#define SYS_AONP_REGF_BK24_MEM_RET_MASK (0x1)

#define SYS_AONP_REGF_IRDA2_MEM_RET_POS (25)
#define SYS_AONP_REGF_IRDA2_MEM_RET_MASK (0x1)

#define SYS_AONP_REGF_IRDA3_MEM_RET_POS (26)
#define SYS_AONP_REGF_IRDA3_MEM_RET_MASK (0x1)

#define SYS_AONP_REGF_SPI3_MEM_RET_POS (27)
#define SYS_AONP_REGF_SPI3_MEM_RET_MASK (0x1)

#define SYS_AONP_REGF_UART4_MEM_RET_POS (28)
#define SYS_AONP_REGF_UART4_MEM_RET_MASK (0x1)

#define SYS_AONP_REGF_CPU0_MEM_RET_POS (29)
#define SYS_AONP_REGF_CPU0_MEM_RET_MASK (0x1)

#define SYS_AONP_REGF_CPU1_MEM_RET_POS (30)
#define SYS_AONP_REGF_CPU1_MEM_RET_MASK (0x1)

#define SYS_AONP_REGF_CORESIGHT_MEM_RET_POS (31)
#define SYS_AONP_REGF_CORESIGHT_MEM_RET_MASK (0x1)

#define SYS_AONP_REG10_ADDR (SOC_SYS_AONP_REG_BASE + (0x10 << 2))

#define SYS_AONP_REG10_PWD_CPU1_POS (0)
#define SYS_AONP_REG10_PWD_CPU1_MASK (0x1)

#define SYS_AONP_REG10_PWD_VEHP_POS (1)
#define SYS_AONP_REG10_PWD_VEHP_MASK (0x1)

#define SYS_AONP_REG10_PWD_WRLS_POS (2)
#define SYS_AONP_REG10_PWD_WRLS_MASK (0x1)

#define SYS_AONP_REG10_ROM_PGEN_POS (3)
#define SYS_AONP_REG10_ROM_PGEN_MASK (0x1)

#define SYS_AONP_REG10_CPU1_ISOLATE_STATE_POS (4)
#define SYS_AONP_REG10_CPU1_ISOLATE_STATE_MASK (0x1)

#define SYS_AONP_REG10_VEHP_ISOLATE_STATE_POS (5)
#define SYS_AONP_REG10_VEHP_ISOLATE_STATE_MASK (0x1)

#define SYS_AONP_REG10_WRLS_ISOLATE_STATE_POS (6)
#define SYS_AONP_REG10_WRLS_ISOLATE_STATE_MASK (0x1)

#define SYS_AONP_REG10_RESERVED_7_30_POS (7)
#define SYS_AONP_REG10_RESERVED_7_30_MASK (0xffffff)

#define SYS_AONP_REG10_BUSMATRIX_BUSY_POS (31)
#define SYS_AONP_REG10_BUSMATRIX_BUSY_MASK (0x1)

#define SYS_AONP_REG11_ADDR (SOC_SYS_AONP_REG_BASE + (0x11 << 2))

#define SYS_AONP_REG11_SLEEP_EN_GLOBAL_POS (0)
#define SYS_AONP_REG11_SLEEP_EN_GLOBAL_MASK (0x1)

#define SYS_AONP_REG11_SLEEP_EN_NEED_FLASH_IDLE_POS (1)
#define SYS_AONP_REG11_SLEEP_EN_NEED_FLASH_IDLE_MASK (0x1)

#define SYS_AONP_REG11_SLEEP_BUS_IDLE_BYPASS_POS (2)
#define SYS_AONP_REG11_SLEEP_BUS_IDLE_BYPASS_MASK (0x1)

#define SYS_AONP_REG11_SLEEP_EN_NEED_CPU0_WFI_POS (3)
#define SYS_AONP_REG11_SLEEP_EN_NEED_CPU0_WFI_MASK (0x1)

#define SYS_AONP_REG11_SLEEP_EN_NEED_CPU1_WFI_POS (4)
#define SYS_AONP_REG11_SLEEP_EN_NEED_CPU1_WFI_MASK (0x1)

#define SYS_AONP_REG11_RESERVED_BIT_5_11_POS (5)
#define SYS_AONP_REG11_RESERVED_BIT_5_11_MASK (0x7f)

#define SYS_AONP_REG11_RESERVED_12_15_POS (12)
#define SYS_AONP_REG11_RESERVED_12_15_MASK (0xf)

#define SYS_AONP_REG11_CPU0_TICKTIMER_32K_ENABLE_POS (16)
#define SYS_AONP_REG11_CPU0_TICKTIMER_32K_ENABLE_MASK (0x1)

#define SYS_AONP_REG11_CPU1_TICKTIMER_32K_ENABLE_POS (17)
#define SYS_AONP_REG11_CPU1_TICKTIMER_32K_ENABLE_MASK (0x1)

#define SYS_AONP_REG11_RESERVED_BIT_18_19_POS (18)
#define SYS_AONP_REG11_RESERVED_BIT_18_19_MASK (0x3)

#define SYS_AONP_REG11_RESERVED_20_24_POS (20)
#define SYS_AONP_REG11_RESERVED_20_24_MASK (0x1f)

#define SYS_AONP_REG11_BTS_SOFT_WAKEUP_REQ_POS (25)
#define SYS_AONP_REG11_BTS_SOFT_WAKEUP_REQ_MASK (0x1)

#define SYS_AONP_REG11_ROM_RD_DISABLE_POS (26)
#define SYS_AONP_REG11_ROM_RD_DISABLE_MASK (0x1)

#define SYS_AONP_REG11_OTP_RD_DISABLE_POS (27)
#define SYS_AONP_REG11_OTP_RD_DISABLE_MASK (0x1)

#define SYS_AONP_REG11_SHARE_MEM_CLKGATING_DISABLE_POS (28)
#define SYS_AONP_REG11_SHARE_MEM_CLKGATING_DISABLE_MASK (0x1)

#define SYS_AONP_REG11_RESERVED_29_31_POS (29)
#define SYS_AONP_REG11_RESERVED_29_31_MASK (0x7)

#define SYS_AONP_REG14_ADDR (SOC_SYS_AONP_REG_BASE + (0x14 << 2))

#define SYS_AONP_REG14_CPU0_INTEN_POS (0)
#define SYS_AONP_REG14_CPU0_INTEN_MASK (0xffffffff)

#define SYS_AONP_REG15_ADDR (SOC_SYS_AONP_REG_BASE + (0x15 << 2))

#define SYS_AONP_REG15_CPU0_INTEN_POS (0)
#define SYS_AONP_REG15_CPU0_INTEN_MASK (0xffffffff)

#define SYS_AONP_REG16_ADDR (SOC_SYS_AONP_REG_BASE + (0x16 << 2))

#define SYS_AONP_REG16_CPU0_INTEN_POS (0)
#define SYS_AONP_REG16_CPU0_INTEN_MASK (0xffffffff)

#define SYS_AONP_REG17_ADDR (SOC_SYS_AONP_REG_BASE + (0x17 << 2))

#define SYS_AONP_REG17_CPU1_INTEN_POS (0)
#define SYS_AONP_REG17_CPU1_INTEN_MASK (0xffffffff)

#define SYS_AONP_REG18_ADDR (SOC_SYS_AONP_REG_BASE + (0x18 << 2))

#define SYS_AONP_REG18_CPU1_INTEN_POS (0)
#define SYS_AONP_REG18_CPU1_INTEN_MASK (0xffffffff)

#define SYS_AONP_REG19_ADDR (SOC_SYS_AONP_REG_BASE + (0x19 << 2))

#define SYS_AONP_REG19_CPU1_INTEN_POS (0)
#define SYS_AONP_REG19_CPU1_INTEN_MASK (0xffffffff)

#define SYS_AONP_REG1A_ADDR (SOC_SYS_AONP_REG_BASE + (0x1a << 2))

#define SYS_AONP_REG1A_M55SUB_INTEN_POS (0)
#define SYS_AONP_REG1A_M55SUB_INTEN_MASK (0xffffffff)

#define SYS_AONP_REG1B_ADDR (SOC_SYS_AONP_REG_BASE + (0x1b << 2))

#define SYS_AONP_REG1B_M55SUB_INTEN_POS (0)
#define SYS_AONP_REG1B_M55SUB_INTEN_MASK (0xffffffff)

#define SYS_AONP_REG1C_ADDR (SOC_SYS_AONP_REG_BASE + (0x1c << 2))

#define SYS_AONP_REG1C_M55SUB_INTEN_POS (0)
#define SYS_AONP_REG1C_M55SUB_INTEN_MASK (0x7fffffff)

#define SYS_AONP_REG1C_M55SUB_WAKEUP_POS (31)
#define SYS_AONP_REG1C_M55SUB_WAKEUP_MASK (0x1)

#define SYS_AONP_REG1E_ADDR (SOC_SYS_AONP_REG_BASE + (0x1e << 2))

#define SYS_AONP_REG1E_SPSH_CFG_POS (0)
#define SYS_AONP_REG1E_SPSH_CFG_MASK (0x3ff)

#define SYS_AONP_REG1E_SPBH_CFG_POS (10)
#define SYS_AONP_REG1E_SPBH_CFG_MASK (0x7ff)

#define SYS_AONP_REG1E_RESERVED_BIT_21_23_POS (21)
#define SYS_AONP_REG1E_RESERVED_BIT_21_23_MASK (0x7)

#define SYS_AONP_REG1E_SET_KEY_POS (24)
#define SYS_AONP_REG1E_SET_KEY_MASK (0xff)

#define SYS_AONP_REG1F_ADDR (SOC_SYS_AONP_REG_BASE + (0x1f << 2))

#define SYS_AONP_REG1F_STPH_CFG_POS (0)
#define SYS_AONP_REG1F_STPH_CFG_MASK (0xfff)

#define SYS_AONP_REG1F_RESERVED_BIT_12_23_POS (12)
#define SYS_AONP_REG1F_RESERVED_BIT_12_23_MASK (0xfff)

#define SYS_AONP_REG1F_SET_KEY_POS (24)
#define SYS_AONP_REG1F_SET_KEY_MASK (0xff)

#define SYS_AONP_REG20_ADDR (SOC_SYS_AONP_REG_BASE + (0x20 << 2))

#define SYS_AONP_REG20_INTS_STATUS0_POS (0)
#define SYS_AONP_REG20_INTS_STATUS0_MASK (0xffffffff)

#define SYS_AONP_REG21_ADDR (SOC_SYS_AONP_REG_BASE + (0x21 << 2))

#define SYS_AONP_REG21_INTS_STATUS1_POS (0)
#define SYS_AONP_REG21_INTS_STATUS1_MASK (0xffffffff)

#define SYS_AONP_REG22_ADDR (SOC_SYS_AONP_REG_BASE + (0x22 << 2))

#define SYS_AONP_REG22_INTS_STATUS2_POS (0)
#define SYS_AONP_REG22_INTS_STATUS2_MASK (0xffffffff)

#define SYS_AONP_REG23_ADDR (SOC_SYS_AONP_REG_BASE + (0x23 << 2))

#define SYS_AONP_REG23_INTS_STATUS3_POS (0)
#define SYS_AONP_REG23_INTS_STATUS3_MASK (0xffffffff)

#define SYS_AONP_REG24_ADDR (SOC_SYS_AONP_REG_BASE + (0x24 << 2))

#define SYS_AONP_REG24_INTS_STATUS4_POS (0)
#define SYS_AONP_REG24_INTS_STATUS4_MASK (0xffffffff)

#define SYS_AONP_REG25_ADDR (SOC_SYS_AONP_REG_BASE + (0x25 << 2))

#define SYS_AONP_REG25_INTS_STATUS5_POS (0)
#define SYS_AONP_REG25_INTS_STATUS5_MASK (0xffffffff)

#define SYS_AONP_REG26_ADDR (SOC_SYS_AONP_REG_BASE + (0x26 << 2))

#define SYS_AONP_REG26_M55SUB_STATUS0_POS (0)
#define SYS_AONP_REG26_M55SUB_STATUS0_MASK (0xffffffff)

#define SYS_AONP_REG27_ADDR (SOC_SYS_AONP_REG_BASE + (0x27 << 2))

#define SYS_AONP_REG27_M55SUB_STATUS1_POS (0)
#define SYS_AONP_REG27_M55SUB_STATUS1_MASK (0xffffffff)

#define SYS_AONP_REG28_ADDR (SOC_SYS_AONP_REG_BASE + (0x28 << 2))

#define SYS_AONP_REG28_M55SUB_STATUS2_POS (0)
#define SYS_AONP_REG28_M55SUB_STATUS2_MASK (0xffffffff)

#define SYS_AONP_REG2A_ADDR (SOC_SYS_AONP_REG_BASE + (0x2a << 2))

#define SYS_AONP_REG2A_DEBUG_GPIO_IE_POS (0)
#define SYS_AONP_REG2A_DEBUG_GPIO_IE_MASK (0xffffffff)

#define SYS_AONP_REG2B_ADDR (SOC_SYS_AONP_REG_BASE + (0x2b << 2))

#define SYS_AONP_REG2B_DEBUG_GPIO_I_POS (0)
#define SYS_AONP_REG2B_DEBUG_GPIO_I_MASK (0xffffffff)

#define SYS_AONP_REG2C_ADDR (SOC_SYS_AONP_REG_BASE + (0x2c << 2))

#define SYS_AONP_REG2C_CACHE_CLEAN_MODE_POS (0)
#define SYS_AONP_REG2C_CACHE_CLEAN_MODE_MASK (0x1)

#define SYS_AONP_REG2C_CPU0_ICACHE_CLEAN_MODE_POS (1)
#define SYS_AONP_REG2C_CPU0_ICACHE_CLEAN_MODE_MASK (0x1)

#define SYS_AONP_REG2C_CPU0_ICACHE_CLEAN_TAG_SEL_POS (2)
#define SYS_AONP_REG2C_CPU0_ICACHE_CLEAN_TAG_SEL_MASK (0x1)

#define SYS_AONP_REG2C_L2_CACHE_CLEAN_MODE_POS (3)
#define SYS_AONP_REG2C_L2_CACHE_CLEAN_MODE_MASK (0x1)

#define SYS_AONP_REG2C_L2_CACHE_CLEAN_TAG_SEL_POS (4)
#define SYS_AONP_REG2C_L2_CACHE_CLEAN_TAG_SEL_MASK (0x3)

#define SYS_AONP_REG2C_RESERVED_6_23_POS (6)
#define SYS_AONP_REG2C_RESERVED_6_23_MASK (0x3ffff)

#define SYS_AONP_REG2C_SET_KEY_POS (24)
#define SYS_AONP_REG2C_SET_KEY_MASK (0xff)

#define SYS_AONP_REG2E_ADDR (SOC_SYS_AONP_REG_BASE + (0x2e << 2))

#define SYS_AONP_REG2E_SPSL_CFG_POS (0)
#define SYS_AONP_REG2E_SPSL_CFG_MASK (0x3ff)

#define SYS_AONP_REG2E_SPBL_CFG_POS (10)
#define SYS_AONP_REG2E_SPBL_CFG_MASK (0x7ff)

#define SYS_AONP_REG2E_RESERVED_BIT_21_23_POS (21)
#define SYS_AONP_REG2E_RESERVED_BIT_21_23_MASK (0x7)

#define SYS_AONP_REG2E_SET_KEY_POS (24)
#define SYS_AONP_REG2E_SET_KEY_MASK (0xff)

#define SYS_AONP_REG2F_ADDR (SOC_SYS_AONP_REG_BASE + (0x2f << 2))

#define SYS_AONP_REG2F_STPL_CFG_POS (0)
#define SYS_AONP_REG2F_STPL_CFG_MASK (0xfff)

#define SYS_AONP_REG2F_RESERVED_BIT_12_23_POS (12)
#define SYS_AONP_REG2F_RESERVED_BIT_12_23_MASK (0xfff)

#define SYS_AONP_REG2F_SET_KEY_POS (24)
#define SYS_AONP_REG2F_SET_KEY_MASK (0xff)

#define SYS_AONP_REG30_ADDR (SOC_SYS_AONP_REG_BASE + (0x30 << 2))

#define SYS_AONP_REG30_GPIO_INPUT_STATUS0_POS (0)
#define SYS_AONP_REG30_GPIO_INPUT_STATUS0_MASK (0xffffffff)

#define SYS_AONP_REG31_ADDR (SOC_SYS_AONP_REG_BASE + (0x31 << 2))

#define SYS_AONP_REG31_GPIO_INPUT_STATUS1_POS (0)
#define SYS_AONP_REG31_GPIO_INPUT_STATUS1_MASK (0xffffffff)

#define SYS_AONP_REG32_ADDR (SOC_SYS_AONP_REG_BASE + (0x32 << 2))

#define SYS_AONP_REG32_GPIO_INPUT_STATUS2_POS (0)
#define SYS_AONP_REG32_GPIO_INPUT_STATUS2_MASK (0xff)

#define SYS_AONP_REG32_RESERVED_BIT_8_30_POS (8)
#define SYS_AONP_REG32_RESERVED_BIT_8_30_MASK (0x7fffff)

#define SYS_AONP_REG32_GPIO_INPUT_STATUS_EN_POS (31)
#define SYS_AONP_REG32_GPIO_INPUT_STATUS_EN_MASK (0x1)

#define SYS_AONP_REG33_ADDR (SOC_SYS_AONP_REG_BASE + (0x33 << 2))

#define SYS_AONP_REG33_ACOMP0_PWM0_SAMPLE_EN_POS (0)
#define SYS_AONP_REG33_ACOMP0_PWM0_SAMPLE_EN_MASK (0x1)

#define SYS_AONP_REG33_ACOMP1_PWM0_SAMPLE_EN_POS (1)
#define SYS_AONP_REG33_ACOMP1_PWM0_SAMPLE_EN_MASK (0x1)

#define SYS_AONP_REG33_RESERVED_2_15_POS (2)
#define SYS_AONP_REG33_RESERVED_2_15_MASK (0x3fff)

#define SYS_AONP_REG33_L2_DIS_PWR_DOWN_MAINT_POS (16)
#define SYS_AONP_REG33_L2_DIS_PWR_DOWN_MAINT_MASK (0x1)

#define SYS_AONP_REG33_L2_APB_VIOLATION_RESP_POS (17)
#define SYS_AONP_REG33_L2_APB_VIOLATION_RESP_MASK (0x1)

#define SYS_AONP_REG33_CPU0_DBGEN_L2_RST_DIS_POS (18)
#define SYS_AONP_REG33_CPU0_DBGEN_L2_RST_DIS_MASK (0x1)

#define SYS_AONP_REG33_CPU1_DBGEN_L2_RST_DIS_POS (19)
#define SYS_AONP_REG33_CPU1_DBGEN_L2_RST_DIS_MASK (0x1)

#define SYS_AONP_REG33_RESERVED_20_23_POS (20)
#define SYS_AONP_REG33_RESERVED_20_23_MASK (0xf)

#define SYS_AONP_REG33_CPU0_WFE_SRC_POS (24)
#define SYS_AONP_REG33_CPU0_WFE_SRC_MASK (0x1)

#define SYS_AONP_REG33_CPU0_WFE_PULSE_POS (25)
#define SYS_AONP_REG33_CPU0_WFE_PULSE_MASK (0x1)

#define SYS_AONP_REG33_CPU1_WFE_SRC_POS (26)
#define SYS_AONP_REG33_CPU1_WFE_SRC_MASK (0x1)

#define SYS_AONP_REG33_CPU1_WFE_PULSE_POS (27)
#define SYS_AONP_REG33_CPU1_WFE_PULSE_MASK (0x1)

#define SYS_AONP_REG33_CPU0_SLEEPING_STATE_POS (28)
#define SYS_AONP_REG33_CPU0_SLEEPING_STATE_MASK (0x1)

#define SYS_AONP_REG33_CPU0_DEEPSLEEP_STATE_POS (29)
#define SYS_AONP_REG33_CPU0_DEEPSLEEP_STATE_MASK (0x1)

#define SYS_AONP_REG33_CPU1_SLEEPING_STATE_POS (30)
#define SYS_AONP_REG33_CPU1_SLEEPING_STATE_MASK (0x1)

#define SYS_AONP_REG33_CPU1_DEEPSLEEP_STATE_POS (31)
#define SYS_AONP_REG33_CPU1_DEEPSLEEP_STATE_MASK (0x1)

#define SYS_AONP_REG34_ADDR (SOC_SYS_AONP_REG_BASE + (0x34 << 2))

#define SYS_AONP_REG34_CPU0_CURPC_POS (0)
#define SYS_AONP_REG34_CPU0_CURPC_MASK (0xffffffff)

#define SYS_AONP_REG35_ADDR (SOC_SYS_AONP_REG_BASE + (0x35 << 2))

#define SYS_AONP_REG35_CPU0_FAULTSTAT_H_POS (0)
#define SYS_AONP_REG35_CPU0_FAULTSTAT_H_MASK (0x7ff)

#define SYS_AONP_REG35_RESERVED_11_31_POS (11)
#define SYS_AONP_REG35_RESERVED_11_31_MASK (0x1fffff)

#define SYS_AONP_REG36_ADDR (SOC_SYS_AONP_REG_BASE + (0x36 << 2))

#define SYS_AONP_REG36_CPU0_FAULTSTAT_L_POS (0)
#define SYS_AONP_REG36_CPU0_FAULTSTAT_L_MASK (0xffffffff)

#define SYS_AONP_REG37_ADDR (SOC_SYS_AONP_REG_BASE + (0x37 << 2))

#define SYS_AONP_REG37_CPU0_INTNUM_POS (0)
#define SYS_AONP_REG37_CPU0_INTNUM_MASK (0x1ff)

#define SYS_AONP_REG37_CPU0_CURRPRI_POS (9)
#define SYS_AONP_REG37_CPU0_CURRPRI_MASK (0xff)

#define SYS_AONP_REG37_CPU0_CURRNS_POS (17)
#define SYS_AONP_REG37_CPU0_CURRNS_MASK (0x1)

#define SYS_AONP_REG37_CPU0_HALTED_POS (18)
#define SYS_AONP_REG37_CPU0_HALTED_MASK (0x1)

#define SYS_AONP_REG37_CPU0_NC_HREADY_POS (19)
#define SYS_AONP_REG37_CPU0_NC_HREADY_MASK (0x1)

#define SYS_AONP_REG37_CPU_CACHE_M_HREADY_POS (20)
#define SYS_AONP_REG37_CPU_CACHE_M_HREADY_MASK (0x1)

#define SYS_AONP_REG37_CPU0_RESETN_POS (21)
#define SYS_AONP_REG37_CPU0_RESETN_MASK (0x1)

#define SYS_AONP_REG37_RESERVED_22_31_POS (22)
#define SYS_AONP_REG37_RESERVED_22_31_MASK (0x3ff)

#define SYS_AONP_REG38_ADDR (SOC_SYS_AONP_REG_BASE + (0x38 << 2))

#define SYS_AONP_REG38_DBUG_CONFIG0_POS (0)
#define SYS_AONP_REG38_DBUG_CONFIG0_MASK (0xffffffff)

#define SYS_AONP_REG39_ADDR (SOC_SYS_AONP_REG_BASE + (0x39 << 2))

#define SYS_AONP_REG39_DBUG_CONFIG1_POS (0)
#define SYS_AONP_REG39_DBUG_CONFIG1_MASK (0xffffffff)

#define SYS_AONP_REG3A_ADDR (SOC_SYS_AONP_REG_BASE + (0x3a << 2))

#define SYS_AONP_REG3A_ANAREG_STAT_POS (0)
#define SYS_AONP_REG3A_ANAREG_STAT_MASK (0xffffffff)

#define SYS_AONP_REG3B_ADDR (SOC_SYS_AONP_REG_BASE + (0x3b << 2))

#define SYS_AONP_REG3B_CORESIGHT_CHN_GATE_EN_POS (0)
#define SYS_AONP_REG3B_CORESIGHT_CHN_GATE_EN_MASK (0xffffff)

#define SYS_AONP_REG3B_CORESIGHT_TPMAXDATASIZE_POS (24)
#define SYS_AONP_REG3B_CORESIGHT_TPMAXDATASIZE_MASK (0x1f)

#define SYS_AONP_REG3B_CORESIGHT_VALID_POS (29)
#define SYS_AONP_REG3B_CORESIGHT_VALID_MASK (0x1)

#define SYS_AONP_REG3B_RESERVED_30_30_POS (30)
#define SYS_AONP_REG3B_RESERVED_30_30_MASK (0x1)

#define SYS_AONP_REG3B_ANAREGB_STAT_POS (31)
#define SYS_AONP_REG3B_ANAREGB_STAT_MASK (0x1)

#define SYS_AONP_REG3C_ADDR (SOC_SYS_AONP_REG_BASE + (0x3c << 2))

#define SYS_AONP_REG3C_CPU1_CURPC_POS (0)
#define SYS_AONP_REG3C_CPU1_CURPC_MASK (0xffffffff)

#define SYS_AONP_REG3D_ADDR (SOC_SYS_AONP_REG_BASE + (0x3d << 2))

#define SYS_AONP_REG3D_CPU1_FAULTSTAT_H_POS (0)
#define SYS_AONP_REG3D_CPU1_FAULTSTAT_H_MASK (0x7ff)

#define SYS_AONP_REG3D_RESERVED_11_31_POS (11)
#define SYS_AONP_REG3D_RESERVED_11_31_MASK (0x1fffff)

#define SYS_AONP_REG3E_ADDR (SOC_SYS_AONP_REG_BASE + (0x3e << 2))

#define SYS_AONP_REG3E_CPU1_FAULTSTAT_L_POS (0)
#define SYS_AONP_REG3E_CPU1_FAULTSTAT_L_MASK (0xffffffff)

#define SYS_AONP_REG3F_ADDR (SOC_SYS_AONP_REG_BASE + (0x3f << 2))

#define SYS_AONP_REG3F_CPU1_INTNUM_POS (0)
#define SYS_AONP_REG3F_CPU1_INTNUM_MASK (0x1ff)

#define SYS_AONP_REG3F_CPU1_CURRPRI_POS (9)
#define SYS_AONP_REG3F_CPU1_CURRPRI_MASK (0xff)

#define SYS_AONP_REG3F_CPU1_CURRNS_POS (17)
#define SYS_AONP_REG3F_CPU1_CURRNS_MASK (0x1)

#define SYS_AONP_REG3F_CPU1_HALTED_POS (18)
#define SYS_AONP_REG3F_CPU1_HALTED_MASK (0x1)

#define SYS_AONP_REG3F_CPU1_NC_HREADY_POS (19)
#define SYS_AONP_REG3F_CPU1_NC_HREADY_MASK (0x1)

#define SYS_AONP_REG3F_RESERVED_20_20_POS (20)
#define SYS_AONP_REG3F_RESERVED_20_20_MASK (0x1)

#define SYS_AONP_REG3F_CPU1_RESETN_POS (21)
#define SYS_AONP_REG3F_CPU1_RESETN_MASK (0x1)

#define SYS_AONP_REG3F_RESERVED_22_31_POS (22)
#define SYS_AONP_REG3F_RESERVED_22_31_MASK (0x3ff)

#define SYS_AONP_ANA_REG0_ADDR (SOC_SYS_AONP_REG_BASE + (0x40 << 2))

#define SYS_AONP_ANA_REG0_DPLL_TSTEN_POS (0)
#define SYS_AONP_ANA_REG0_DPLL_TSTEN_MASK (0x1)

#define SYS_AONP_ANA_REG0_CP_POS (1)
#define SYS_AONP_ANA_REG0_CP_MASK (0x7)

#define SYS_AONP_ANA_REG0_SPIDETEN_POS (4)
#define SYS_AONP_ANA_REG0_SPIDETEN_MASK (0x1)

#define SYS_AONP_ANA_REG0_HVREF_POS (5)
#define SYS_AONP_ANA_REG0_HVREF_MASK (0x3)

#define SYS_AONP_ANA_REG0_LVREF_POS (7)
#define SYS_AONP_ANA_REG0_LVREF_MASK (0x3)

#define SYS_AONP_ANA_REG0_RZCTRL26M_POS (9)
#define SYS_AONP_ANA_REG0_RZCTRL26M_MASK (0x1)

#define SYS_AONP_ANA_REG0_LOOPRZCTRL_POS (10)
#define SYS_AONP_ANA_REG0_LOOPRZCTRL_MASK (0xf)

#define SYS_AONP_ANA_REG0_RPC_POS (14)
#define SYS_AONP_ANA_REG0_RPC_MASK (0x3)

#define SYS_AONP_ANA_REG0_OPENLOOP_EN_POS (16)
#define SYS_AONP_ANA_REG0_OPENLOOP_EN_MASK (0x1)

#define SYS_AONP_ANA_REG0_CKSEL_POS (17)
#define SYS_AONP_ANA_REG0_CKSEL_MASK (0x3)

#define SYS_AONP_ANA_REG0_SPITRIG_POS (19)
#define SYS_AONP_ANA_REG0_SPITRIG_MASK (0x1)

#define SYS_AONP_ANA_REG0_BAND_POS (20)
#define SYS_AONP_ANA_REG0_BAND_MASK (0x1)

#define SYS_AONP_ANA_REG0_BAND_1_POS (21)
#define SYS_AONP_ANA_REG0_BAND_1_MASK (0x1)

#define SYS_AONP_ANA_REG0_BAND_2_POS (22)
#define SYS_AONP_ANA_REG0_BAND_2_MASK (0x7)

#define SYS_AONP_ANA_REG0_BANDMANUAL_POS (25)
#define SYS_AONP_ANA_REG0_BANDMANUAL_MASK (0x1)

#define SYS_AONP_ANA_REG0_DSPTRIG_POS (26)
#define SYS_AONP_ANA_REG0_DSPTRIG_MASK (0x1)

#define SYS_AONP_ANA_REG0_LPEN_DPLL_POS (27)
#define SYS_AONP_ANA_REG0_LPEN_DPLL_MASK (0x1)

#define SYS_AONP_ANA_REG0_NC_28_29_POS (28)
#define SYS_AONP_ANA_REG0_NC_28_29_MASK (0x3)

#define SYS_AONP_ANA_REG0_BP_CALDONE_POS (30)
#define SYS_AONP_ANA_REG0_BP_CALDONE_MASK (0x1)

#define SYS_AONP_ANA_REG0_VCTRL_DPLLLDO_POS (31)
#define SYS_AONP_ANA_REG0_VCTRL_DPLLLDO_MASK (0x1)

#define SYS_AONP_ANA_REG1_ADDR (SOC_SYS_AONP_REG_BASE + (0x41 << 2))

#define SYS_AONP_ANA_REG1_VCOOFFSET_POS (0)
#define SYS_AONP_ANA_REG1_VCOOFFSET_MASK (0x1)

#define SYS_AONP_ANA_REG1_SELPOL_POS (1)
#define SYS_AONP_ANA_REG1_SELPOL_MASK (0x1)

#define SYS_AONP_ANA_REG1_DLYSEL_POS (2)
#define SYS_AONP_ANA_REG1_DLYSEL_MASK (0x3)

#define SYS_AONP_ANA_REG1_EDGESEL_NCK_POS (4)
#define SYS_AONP_ANA_REG1_EDGESEL_NCK_MASK (0x1)

#define SYS_AONP_ANA_REG1_NLOAD_DLYEN_POS (5)
#define SYS_AONP_ANA_REG1_NLOAD_DLYEN_MASK (0x1)

#define SYS_AONP_ANA_REG1_CP_POS (6)
#define SYS_AONP_ANA_REG1_CP_MASK (0x7)

#define SYS_AONP_ANA_REG1_SPIDETEN_POS (9)
#define SYS_AONP_ANA_REG1_SPIDETEN_MASK (0x1)

#define SYS_AONP_ANA_REG1_CBEN_POS (10)
#define SYS_AONP_ANA_REG1_CBEN_MASK (0x1)

#define SYS_AONP_ANA_REG1_HVREF_POS (11)
#define SYS_AONP_ANA_REG1_HVREF_MASK (0x3)

#define SYS_AONP_ANA_REG1_LVREF_POS (13)
#define SYS_AONP_ANA_REG1_LVREF_MASK (0x3)

#define SYS_AONP_ANA_REG1_RZCTRL26M_POS (15)
#define SYS_AONP_ANA_REG1_RZCTRL26M_MASK (0x1)

#define SYS_AONP_ANA_REG1_LPFRZ_POS (16)
#define SYS_AONP_ANA_REG1_LPFRZ_MASK (0xf)

#define SYS_AONP_ANA_REG1_RPC_POS (20)
#define SYS_AONP_ANA_REG1_RPC_MASK (0x7)

#define SYS_AONP_ANA_REG1_DPLL_TSTEN_POS (23)
#define SYS_AONP_ANA_REG1_DPLL_TSTEN_MASK (0x1)

#define SYS_AONP_ANA_REG1_KCTRL_POS (24)
#define SYS_AONP_ANA_REG1_KCTRL_MASK (0x3)

#define SYS_AONP_ANA_REG1_VSEL_LDO_POS (26)
#define SYS_AONP_ANA_REG1_VSEL_LDO_MASK (0x3)

#define SYS_AONP_ANA_REG1_DIV_SW_POS (28)
#define SYS_AONP_ANA_REG1_DIV_SW_MASK (0x1)

#define SYS_AONP_ANA_REG1_BP_CALDONE_POS (29)
#define SYS_AONP_ANA_REG1_BP_CALDONE_MASK (0x1)

#define SYS_AONP_ANA_REG1_CK2XEN_POS (30)
#define SYS_AONP_ANA_REG1_CK2XEN_MASK (0x1)

#define SYS_AONP_ANA_REG1_INT_MOD_POS (31)
#define SYS_AONP_ANA_REG1_INT_MOD_MASK (0x1)

#define SYS_AONP_ANA_REG2_ADDR (SOC_SYS_AONP_REG_BASE + (0x42 << 2))

#define SYS_AONP_ANA_REG2_XTALH_CTUNE_POS (0)
#define SYS_AONP_ANA_REG2_XTALH_CTUNE_MASK (0xff)

#define SYS_AONP_ANA_REG2_FORCE_26MPLL_POS (8)
#define SYS_AONP_ANA_REG2_FORCE_26MPLL_MASK (0x1)

#define SYS_AONP_ANA_REG2_NC_9_11_POS (9)
#define SYS_AONP_ANA_REG2_NC_9_11_MASK (0x7)

#define SYS_AONP_ANA_REG2_GADC_SD1V_POS (12)
#define SYS_AONP_ANA_REG2_GADC_SD1V_MASK (0x1)

#define SYS_AONP_ANA_REG2_GADC_BSCALSAW_POS (13)
#define SYS_AONP_ANA_REG2_GADC_BSCALSAW_MASK (0x7)

#define SYS_AONP_ANA_REG2_GADC_VNCALSAW_POS (16)
#define SYS_AONP_ANA_REG2_GADC_VNCALSAW_MASK (0x7)

#define SYS_AONP_ANA_REG2_GADC_VPCALSAW_POS (19)
#define SYS_AONP_ANA_REG2_GADC_VPCALSAW_MASK (0x7)

#define SYS_AONP_ANA_REG2_NC_22_22_POS (22)
#define SYS_AONP_ANA_REG2_NC_22_22_MASK (0x1)

#define SYS_AONP_ANA_REG2_GADC_VBG_SEL_POS (23)
#define SYS_AONP_ANA_REG2_GADC_VBG_SEL_MASK (0x1)

#define SYS_AONP_ANA_REG2_GADC_CLK_RLTEN_POS (24)
#define SYS_AONP_ANA_REG2_GADC_CLK_RLTEN_MASK (0x1)

#define SYS_AONP_ANA_REG2_GADC_CALINTSAW_EN_POS (25)
#define SYS_AONP_ANA_REG2_GADC_CALINTSAW_EN_MASK (0x1)

#define SYS_AONP_ANA_REG2_GADC_CLK_SEL_POS (26)
#define SYS_AONP_ANA_REG2_GADC_CLK_SEL_MASK (0x1)

#define SYS_AONP_ANA_REG2_GADC_CLK_INV_POS (27)
#define SYS_AONP_ANA_REG2_GADC_CLK_INV_MASK (0x1)

#define SYS_AONP_ANA_REG2_GADC_CALCAP_CH_POS (28)
#define SYS_AONP_ANA_REG2_GADC_CALCAP_CH_MASK (0x3)

#define SYS_AONP_ANA_REG2_GADC_INBUF_EN_POS (30)
#define SYS_AONP_ANA_REG2_GADC_INBUF_EN_MASK (0x1)

#define SYS_AONP_ANA_REG2_GADC_EN_SPI_POS (31)
#define SYS_AONP_ANA_REG2_GADC_EN_SPI_MASK (0x1)

#define SYS_AONP_ANA_REG3_ADDR (SOC_SYS_AONP_REG_BASE + (0x43 << 2))

#define SYS_AONP_ANA_REG3_NC_0_6_POS (0)
#define SYS_AONP_ANA_REG3_NC_0_6_MASK (0x7f)

#define SYS_AONP_ANA_REG3_ANABUF_SEL_RX_POS (7)
#define SYS_AONP_ANA_REG3_ANABUF_SEL_RX_MASK (0x1)

#define SYS_AONP_ANA_REG3_HPSSREN_POS (8)
#define SYS_AONP_ANA_REG3_HPSSREN_MASK (0x1)

#define SYS_AONP_ANA_REG3_CK_SEL_POS (9)
#define SYS_AONP_ANA_REG3_CK_SEL_MASK (0x1)

#define SYS_AONP_ANA_REG3_ANABUF_SEL_TX_POS (10)
#define SYS_AONP_ANA_REG3_ANABUF_SEL_TX_MASK (0x1)

#define SYS_AONP_ANA_REG3_PWD_XTALLDO_POS (11)
#define SYS_AONP_ANA_REG3_PWD_XTALLDO_MASK (0x1)

#define SYS_AONP_ANA_REG3_IAMP_POS (12)
#define SYS_AONP_ANA_REG3_IAMP_MASK (0x1)

#define SYS_AONP_ANA_REG3_VDDREN_POS (13)
#define SYS_AONP_ANA_REG3_VDDREN_MASK (0x1)

#define SYS_AONP_ANA_REG3_XAMP_POS (14)
#define SYS_AONP_ANA_REG3_XAMP_MASK (0x3f)

#define SYS_AONP_ANA_REG3_VOSEL_POS (20)
#define SYS_AONP_ANA_REG3_VOSEL_MASK (0x1f)

#define SYS_AONP_ANA_REG3_EN_XTALH_SLEEP_POS (25)
#define SYS_AONP_ANA_REG3_EN_XTALH_SLEEP_MASK (0x1)

#define SYS_AONP_ANA_REG3_XTAL40_EN_POS (26)
#define SYS_AONP_ANA_REG3_XTAL40_EN_MASK (0x1)

#define SYS_AONP_ANA_REG3_BUFICTRL_POS (27)
#define SYS_AONP_ANA_REG3_BUFICTRL_MASK (0x1)

#define SYS_AONP_ANA_REG3_IBIAS_CTRL_POS (28)
#define SYS_AONP_ANA_REG3_IBIAS_CTRL_MASK (0x3)

#define SYS_AONP_ANA_REG3_ICORE_CTRL_POS (30)
#define SYS_AONP_ANA_REG3_ICORE_CTRL_MASK (0x3)

#define SYS_AONP_ANA_REG4_ADDR (SOC_SYS_AONP_REG_BASE + (0x44 << 2))

#define SYS_AONP_ANA_REG4_CKTST_SEL_POS (0)
#define SYS_AONP_ANA_REG4_CKTST_SEL_MASK (0x3)

#define SYS_AONP_ANA_REG4_CK_TST_EN_POS (2)
#define SYS_AONP_ANA_REG4_CK_TST_EN_MASK (0x1)

#define SYS_AONP_ANA_REG4_VUSBSEL_POS (3)
#define SYS_AONP_ANA_REG4_VUSBSEL_MASK (0x3)

#define SYS_AONP_ANA_REG4_NC_5_16_POS (5)
#define SYS_AONP_ANA_REG4_NC_5_16_MASK (0xfff)

#define SYS_AONP_ANA_REG4_GADC_INBUFF_ISEL_POS (17)
#define SYS_AONP_ANA_REG4_GADC_INBUFF_ISEL_MASK (0x7)

#define SYS_AONP_ANA_REG4_GADC_BIASAMP_ISEL_POS (20)
#define SYS_AONP_ANA_REG4_GADC_BIASAMP_ISEL_MASK (0x7)

#define SYS_AONP_ANA_REG4_GADC_COMP_ISEL_POS (23)
#define SYS_AONP_ANA_REG4_GADC_COMP_ISEL_MASK (0x7)

#define SYS_AONP_ANA_REG4_GADC_PREAMP_ISEL_POS (26)
#define SYS_AONP_ANA_REG4_GADC_PREAMP_ISEL_MASK (0x7)

#define SYS_AONP_ANA_REG4_GADC_BUFAMP_ISEL_POS (29)
#define SYS_AONP_ANA_REG4_GADC_BUFAMP_ISEL_MASK (0x7)

#define SYS_AONP_ANA_REG5_ADDR (SOC_SYS_AONP_REG_BASE + (0x45 << 2))

#define SYS_AONP_ANA_REG5_EN_VOUT_POS (0)
#define SYS_AONP_ANA_REG5_EN_VOUT_MASK (0x1)

#define SYS_AONP_ANA_REG5_EN_XTALL_POS (1)
#define SYS_AONP_ANA_REG5_EN_XTALL_MASK (0x1)

#define SYS_AONP_ANA_REG5_EN_DCO_POS (2)
#define SYS_AONP_ANA_REG5_EN_DCO_MASK (0x1)

#define SYS_AONP_ANA_REG5_NC_3_3_POS (3)
#define SYS_AONP_ANA_REG5_NC_3_3_MASK (0x1)

#define SYS_AONP_ANA_REG5_EN_TEMP_POS (4)
#define SYS_AONP_ANA_REG5_EN_TEMP_MASK (0x1)

#define SYS_AONP_ANA_REG5_EN_DPLL_POS (5)
#define SYS_AONP_ANA_REG5_EN_DPLL_MASK (0x1)

#define SYS_AONP_ANA_REG5_EN_CB_POS (6)
#define SYS_AONP_ANA_REG5_EN_CB_MASK (0x1)

#define SYS_AONP_ANA_REG5_GPIO_LATCH_POS (7)
#define SYS_AONP_ANA_REG5_GPIO_LATCH_MASK (0x1)

#define SYS_AONP_ANA_REG5_NC_8_11_POS (8)
#define SYS_AONP_ANA_REG5_NC_8_11_MASK (0xf)

#define SYS_AONP_ANA_REG5_ROSC_DISABLE_POS (12)
#define SYS_AONP_ANA_REG5_ROSC_DISABLE_MASK (0x1)

#define SYS_AONP_ANA_REG5_PWDAUDPLL_POS (13)
#define SYS_AONP_ANA_REG5_PWDAUDPLL_MASK (0x1)

#define SYS_AONP_ANA_REG5_PWD_ROSC_SPI_POS (14)
#define SYS_AONP_ANA_REG5_PWD_ROSC_SPI_MASK (0x1)

#define SYS_AONP_ANA_REG5_NC_15_15_POS (15)
#define SYS_AONP_ANA_REG5_NC_15_15_MASK (0x1)

#define SYS_AONP_ANA_REG5_ITUNE_XTALL_POS (16)
#define SYS_AONP_ANA_REG5_ITUNE_XTALL_MASK (0xf)

#define SYS_AONP_ANA_REG5_XTALL_TEN_POS (20)
#define SYS_AONP_ANA_REG5_XTALL_TEN_MASK (0x1)

#define SYS_AONP_ANA_REG5_ROSC_TSTEN_POS (21)
#define SYS_AONP_ANA_REG5_ROSC_TSTEN_MASK (0x1)

#define SYS_AONP_ANA_REG5_BCAL_START_POS (22)
#define SYS_AONP_ANA_REG5_BCAL_START_MASK (0x1)

#define SYS_AONP_ANA_REG5_BCAL_EN_POS (23)
#define SYS_AONP_ANA_REG5_BCAL_EN_MASK (0x1)

#define SYS_AONP_ANA_REG5_BCAL_SEL_POS (24)
#define SYS_AONP_ANA_REG5_BCAL_SEL_MASK (0x7)

#define SYS_AONP_ANA_REG5_VBIAS_POS (27)
#define SYS_AONP_ANA_REG5_VBIAS_MASK (0x1f)

#define SYS_AONP_ANA_REG6_ADDR (SOC_SYS_AONP_REG_BASE + (0x46 << 2))

#define SYS_AONP_ANA_REG6_CALIB_INTERVAL_POS (0)
#define SYS_AONP_ANA_REG6_CALIB_INTERVAL_MASK (0x3ff)

#define SYS_AONP_ANA_REG6_MODIFY_INTERVAL_POS (10)
#define SYS_AONP_ANA_REG6_MODIFY_INTERVAL_MASK (0x3f)

#define SYS_AONP_ANA_REG6_XTAL_WAKEUP_TIME_POS (16)
#define SYS_AONP_ANA_REG6_XTAL_WAKEUP_TIME_MASK (0xf)

#define SYS_AONP_ANA_REG6_SPI_TRIG_POS (20)
#define SYS_AONP_ANA_REG6_SPI_TRIG_MASK (0x1)

#define SYS_AONP_ANA_REG6_MODIFI_AUTO_POS (21)
#define SYS_AONP_ANA_REG6_MODIFI_AUTO_MASK (0x1)

#define SYS_AONP_ANA_REG6_CALIB_AUTO_POS (22)
#define SYS_AONP_ANA_REG6_CALIB_AUTO_MASK (0x1)

#define SYS_AONP_ANA_REG6_CAL_MODE_POS (23)
#define SYS_AONP_ANA_REG6_CAL_MODE_MASK (0x1)

#define SYS_AONP_ANA_REG6_MANU_ENA_POS (24)
#define SYS_AONP_ANA_REG6_MANU_ENA_MASK (0x1)

#define SYS_AONP_ANA_REG6_MANU_CIN_POS (25)
#define SYS_AONP_ANA_REG6_MANU_CIN_MASK (0x7f)

#define SYS_AONP_ANA_REG7_ADDR (SOC_SYS_AONP_REG_BASE + (0x47 << 2))

#define SYS_AONP_ANA_REG7_NSYN_POS (0)
#define SYS_AONP_ANA_REG7_NSYN_MASK (0x1)

#define SYS_AONP_ANA_REG7_BANDMANUAL_POS (1)
#define SYS_AONP_ANA_REG7_BANDMANUAL_MASK (0x3f)

#define SYS_AONP_ANA_REG7_CKREF_LOOP_SEL_POS (7)
#define SYS_AONP_ANA_REG7_CKREF_LOOP_SEL_MASK (0x1)

#define SYS_AONP_ANA_REG7_IOFFS_POS (8)
#define SYS_AONP_ANA_REG7_IOFFS_MASK (0x7)

#define SYS_AONP_ANA_REG7_RESET_NLOAD_POS (11)
#define SYS_AONP_ANA_REG7_RESET_NLOAD_MASK (0x1)

#define SYS_AONP_ANA_REG7_CLOSELOOP_EN_POS (12)
#define SYS_AONP_ANA_REG7_CLOSELOOP_EN_MASK (0x1)

#define SYS_AONP_ANA_REG7_MODECAL_POS (13)
#define SYS_AONP_ANA_REG7_MODECAL_MASK (0x1)

#define SYS_AONP_ANA_REG7_SPI_RSTN_POS (14)
#define SYS_AONP_ANA_REG7_SPI_RSTN_MASK (0x1)

#define SYS_AONP_ANA_REG7_OSCCAL_TRIG_POS (15)
#define SYS_AONP_ANA_REG7_OSCCAL_TRIG_MASK (0x1)

#define SYS_AONP_ANA_REG7_MANUAL_POS (16)
#define SYS_AONP_ANA_REG7_MANUAL_MASK (0x1)

#define SYS_AONP_ANA_REG7_DIFF_POS (17)
#define SYS_AONP_ANA_REG7_DIFF_MASK (0x7)

#define SYS_AONP_ANA_REG7_ICTRLMANUAL_POS (20)
#define SYS_AONP_ANA_REG7_ICTRLMANUAL_MASK (0x7)

#define SYS_AONP_ANA_REG7_CNTI_POS (23)
#define SYS_AONP_ANA_REG7_CNTI_MASK (0x1ff)

#define SYS_AONP_ANA_REG8_ADDR (SOC_SYS_AONP_REG_BASE + (0x48 << 2))

#define SYS_AONP_ANA_REG8_RESERVED_BIT_0_30_POS (0)
#define SYS_AONP_ANA_REG8_RESERVED_BIT_0_30_MASK (0x7fffffff)

#define SYS_AONP_ANA_REG8_N_POS (31)
#define SYS_AONP_ANA_REG8_N_MASK (0x1)

#define SYS_AONP_ANA_REG9_ADDR (SOC_SYS_AONP_REG_BASE + (0x49 << 2))

#define SYS_AONP_ANA_REG9_CLK_SEL_POS (0)
#define SYS_AONP_ANA_REG9_CLK_SEL_MASK (0x1)

#define SYS_AONP_ANA_REG9_CORELDO_HP_POS (1)
#define SYS_AONP_ANA_REG9_CORELDO_HP_MASK (0x1)

#define SYS_AONP_ANA_REG9_DLDOHP_POS (2)
#define SYS_AONP_ANA_REG9_DLDOHP_MASK (0x1)

#define SYS_AONP_ANA_REG9_T_VANALDOSEL_POS (3)
#define SYS_AONP_ANA_REG9_T_VANALDOSEL_MASK (0x7)

#define SYS_AONP_ANA_REG9_R_VANALDOSEL_POS (6)
#define SYS_AONP_ANA_REG9_R_VANALDOSEL_MASK (0x7)

#define SYS_AONP_ANA_REG9_EN_TRSW_POS (9)
#define SYS_AONP_ANA_REG9_EN_TRSW_MASK (0x1)

#define SYS_AONP_ANA_REG9_ALDOHP_POS (10)
#define SYS_AONP_ANA_REG9_ALDOHP_MASK (0x1)

#define SYS_AONP_ANA_REG9_ANACURLIM_POS (11)
#define SYS_AONP_ANA_REG9_ANACURLIM_MASK (0x1)

#define SYS_AONP_ANA_REG9_HSLDO_HP_POS (12)
#define SYS_AONP_ANA_REG9_HSLDO_HP_MASK (0x1)

#define SYS_AONP_ANA_REG9_PWD_HSLDO_POS (13)
#define SYS_AONP_ANA_REG9_PWD_HSLDO_MASK (0x1)

#define SYS_AONP_ANA_REG9_ENFAST_HSLDO_POS (14)
#define SYS_AONP_ANA_REG9_ENFAST_HSLDO_MASK (0x1)

#define SYS_AONP_ANA_REG9_NC_15_15_POS (15)
#define SYS_AONP_ANA_REG9_NC_15_15_MASK (0x1)

#define SYS_AONP_ANA_REG9_VALOLDOSEL_POS (16)
#define SYS_AONP_ANA_REG9_VALOLDOSEL_MASK (0x7)

#define SYS_AONP_ANA_REG9_ALOPOWSEL_POS (19)
#define SYS_AONP_ANA_REG9_ALOPOWSEL_MASK (0x1)

#define SYS_AONP_ANA_REG9_EN_FAST_ALOLDO_POS (20)
#define SYS_AONP_ANA_REG9_EN_FAST_ALOLDO_MASK (0x1)

#define SYS_AONP_ANA_REG9_ALOLDOHP_POS (21)
#define SYS_AONP_ANA_REG9_ALOLDOHP_MASK (0x1)

#define SYS_AONP_ANA_REG9_BGCAL_POS (22)
#define SYS_AONP_ANA_REG9_BGCAL_MASK (0x3f)

#define SYS_AONP_ANA_REG9_VBGCALMODE_POS (28)
#define SYS_AONP_ANA_REG9_VBGCALMODE_MASK (0x1)

#define SYS_AONP_ANA_REG9_VBGCALSTART_POS (29)
#define SYS_AONP_ANA_REG9_VBGCALSTART_MASK (0x1)

#define SYS_AONP_ANA_REG9_PWD_BGCAL_POS (30)
#define SYS_AONP_ANA_REG9_PWD_BGCAL_MASK (0x1)

#define SYS_AONP_ANA_REG9_SPI_ENVBG_POS (31)
#define SYS_AONP_ANA_REG9_SPI_ENVBG_MASK (0x1)

#define SYS_AONP_ANA_REG10_ADDR (SOC_SYS_AONP_REG_BASE + (0x4a << 2))

#define SYS_AONP_ANA_REG10_AZCD_MANUAL_POS (0)
#define SYS_AONP_ANA_REG10_AZCD_MANUAL_MASK (0x3f)

#define SYS_AONP_ANA_REG10_AZCDREFS_POS (6)
#define SYS_AONP_ANA_REG10_AZCDREFS_MASK (0x3)

#define SYS_AONP_ANA_REG10_RESERVED_BIT_8_8_POS (8)
#define SYS_AONP_ANA_REG10_RESERVED_BIT_8_8_MASK (0x1)

#define SYS_AONP_ANA_REG10_SPI_LATCHB_POS (9)
#define SYS_AONP_ANA_REG10_SPI_LATCHB_MASK (0x1)

#define SYS_AONP_ANA_REG10_DIGCURLIM_POS (10)
#define SYS_AONP_ANA_REG10_DIGCURLIM_MASK (0x1)

#define SYS_AONP_ANA_REG10_RTC_WKRSTN_POS (11)
#define SYS_AONP_ANA_REG10_RTC_WKRSTN_MASK (0x1)

#define SYS_AONP_ANA_REG10_RST_WKS_POS (12)
#define SYS_AONP_ANA_REG10_RST_WKS_MASK (0x1)

#define SYS_AONP_ANA_REG10_D_VEASEL1V_POS (13)
#define SYS_AONP_ANA_REG10_D_VEASEL1V_MASK (0x3)

#define SYS_AONP_ANA_REG10_ENSFSDD_POS (15)
#define SYS_AONP_ANA_REG10_ENSFSDD_MASK (0x1)

#define SYS_AONP_ANA_REG10_VCOREHSEL_POS (16)
#define SYS_AONP_ANA_REG10_VCOREHSEL_MASK (0xf)

#define SYS_AONP_ANA_REG10_VCORELSEL_POS (20)
#define SYS_AONP_ANA_REG10_VCORELSEL_MASK (0x7)

#define SYS_AONP_ANA_REG10_VLDEN_POS (23)
#define SYS_AONP_ANA_REG10_VLDEN_MASK (0x1)

#define SYS_AONP_ANA_REG10_EN_FAST_CORELDO_POS (24)
#define SYS_AONP_ANA_REG10_EN_FAST_CORELDO_MASK (0x1)

#define SYS_AONP_ANA_REG10_PWDCORELDO_POS (25)
#define SYS_AONP_ANA_REG10_PWDCORELDO_MASK (0x1)

#define SYS_AONP_ANA_REG10_VDIGHSEL_POS (26)
#define SYS_AONP_ANA_REG10_VDIGHSEL_MASK (0x7)

#define SYS_AONP_ANA_REG10_VDIGSEL_POS (29)
#define SYS_AONP_ANA_REG10_VDIGSEL_MASK (0x3)

#define SYS_AONP_ANA_REG10_VDD12LDEN_POS (31)
#define SYS_AONP_ANA_REG10_VDD12LDEN_MASK (0x1)

#define SYS_AONP_ANA_REG11_ADDR (SOC_SYS_AONP_REG_BASE + (0x4b << 2))

#define SYS_AONP_ANA_REG11_ALDO_CZSEL_POS (0)
#define SYS_AONP_ANA_REG11_ALDO_CZSEL_MASK (0x7)

#define SYS_AONP_ANA_REG11_ZLDO_RZSEL_POS (3)
#define SYS_AONP_ANA_REG11_ZLDO_RZSEL_MASK (0x3)

#define SYS_AONP_ANA_REG11_AZCDSWVS_POS (5)
#define SYS_AONP_ANA_REG11_AZCDSWVS_MASK (0x7)

#define SYS_AONP_ANA_REG11_AENZCDDY_POS (8)
#define SYS_AONP_ANA_REG11_AENZCDDY_MASK (0x1)

#define SYS_AONP_ANA_REG11_AENZCDMSEL_POS (9)
#define SYS_AONP_ANA_REG11_AENZCDMSEL_MASK (0x1)

#define SYS_AONP_ANA_REG11_AENZCDCALIB_POS (10)
#define SYS_AONP_ANA_REG11_AENZCDCALIB_MASK (0x1)

#define SYS_AONP_ANA_REG11_EN_COREPSW_POS (11)
#define SYS_AONP_ANA_REG11_EN_COREPSW_MASK (0x1)

#define SYS_AONP_ANA_REG11_EN_ALOPSW_POS (12)
#define SYS_AONP_ANA_REG11_EN_ALOPSW_MASK (0x1)

#define SYS_AONP_ANA_REG11_NC_13_14_POS (13)
#define SYS_AONP_ANA_REG11_NC_13_14_MASK (0x3)

#define SYS_AONP_ANA_REG11_SPI_TIMERWKEN_POS (15)
#define SYS_AONP_ANA_REG11_SPI_TIMERWKEN_MASK (0x1)

#define SYS_AONP_ANA_REG11_SPI_BYP32PWD_POS (16)
#define SYS_AONP_ANA_REG11_SPI_BYP32PWD_MASK (0x1)

#define SYS_AONP_ANA_REG11_SD_POS (17)
#define SYS_AONP_ANA_REG11_SD_MASK (0x1)

#define SYS_AONP_ANA_REG11_NC_18_18_POS (18)
#define SYS_AONP_ANA_REG11_NC_18_18_MASK (0x1)

#define SYS_AONP_ANA_REG11_GPIO_WKRST1V_POS (19)
#define SYS_AONP_ANA_REG11_GPIO_WKRST1V_MASK (0x1)

#define SYS_AONP_ANA_REG11_CKFS_POS (20)
#define SYS_AONP_ANA_REG11_CKFS_MASK (0x3)

#define SYS_AONP_ANA_REG11_CKINTSEL_POS (22)
#define SYS_AONP_ANA_REG11_CKINTSEL_MASK (0x1)

#define SYS_AONP_ANA_REG11_OSCCALTRIG_POS (23)
#define SYS_AONP_ANA_REG11_OSCCALTRIG_MASK (0x1)

#define SYS_AONP_ANA_REG11_MROSCSEL_POS (24)
#define SYS_AONP_ANA_REG11_MROSCSEL_MASK (0x1)

#define SYS_AONP_ANA_REG11_MROSCI_CAL_POS (25)
#define SYS_AONP_ANA_REG11_MROSCI_CAL_MASK (0x7)

#define SYS_AONP_ANA_REG11_MROSCCAP_CAL_POS (28)
#define SYS_AONP_ANA_REG11_MROSCCAP_CAL_MASK (0xf)

#define SYS_AONP_ANA_REG12_ADDR (SOC_SYS_AONP_REG_BASE + (0x4c << 2))

#define SYS_AONP_ANA_REG12_SFSR_POS (0)
#define SYS_AONP_ANA_REG12_SFSR_MASK (0xf)

#define SYS_AONP_ANA_REG12_ENSFSAA_POS (4)
#define SYS_AONP_ANA_REG12_ENSFSAA_MASK (0x1)

#define SYS_AONP_ANA_REG12_APFMS_POS (5)
#define SYS_AONP_ANA_REG12_APFMS_MASK (0x1f)

#define SYS_AONP_ANA_REG12_ATMPO_SEL_POS (10)
#define SYS_AONP_ANA_REG12_ATMPO_SEL_MASK (0x3)

#define SYS_AONP_ANA_REG12_AMPOEN_POS (12)
#define SYS_AONP_ANA_REG12_AMPOEN_MASK (0x1)

#define SYS_AONP_ANA_REG12_ENPOWA_POS (13)
#define SYS_AONP_ANA_REG12_ENPOWA_MASK (0x1)

#define SYS_AONP_ANA_REG12_AVEA_SEL_POS (14)
#define SYS_AONP_ANA_REG12_AVEA_SEL_MASK (0x3)

#define SYS_AONP_ANA_REG12_AFORCEPFM_POS (16)
#define SYS_AONP_ANA_REG12_AFORCEPFM_MASK (0x1)

#define SYS_AONP_ANA_REG12_ACLS_POS (17)
#define SYS_AONP_ANA_REG12_ACLS_MASK (0x7)

#define SYS_AONP_ANA_REG12_ASWRSTEN_POS (20)
#define SYS_AONP_ANA_REG12_ASWRSTEN_MASK (0x1)

#define SYS_AONP_ANA_REG12_ARIPC_POS (21)
#define SYS_AONP_ANA_REG12_ARIPC_MASK (0x7)

#define SYS_AONP_ANA_REG12_ARAMPC_POS (24)
#define SYS_AONP_ANA_REG12_ARAMPC_MASK (0xf)

#define SYS_AONP_ANA_REG12_ARAMPCEN_POS (28)
#define SYS_AONP_ANA_REG12_ARAMPCEN_MASK (0x1)

#define SYS_AONP_ANA_REG12_AENBURST_POS (29)
#define SYS_AONP_ANA_REG12_AENBURST_MASK (0x1)

#define SYS_AONP_ANA_REG12_APFMEN_POS (30)
#define SYS_AONP_ANA_REG12_APFMEN_MASK (0x1)

#define SYS_AONP_ANA_REG12_ALDOSEL_POS (31)
#define SYS_AONP_ANA_REG12_ALDOSEL_MASK (0x1)

#define SYS_AONP_ANA_REG13_ADDR (SOC_SYS_AONP_REG_BASE + (0x4d << 2))

#define SYS_AONP_ANA_REG13_BUCKD_SOFTST_POS (0)
#define SYS_AONP_ANA_REG13_BUCKD_SOFTST_MASK (0xf)

#define SYS_AONP_ANA_REG13_DENZCDCALIB_POS (4)
#define SYS_AONP_ANA_REG13_DENZCDCALIB_MASK (0x1)

#define SYS_AONP_ANA_REG13_NC_5_6_POS (5)
#define SYS_AONP_ANA_REG13_NC_5_6_MASK (0x3)

#define SYS_AONP_ANA_REG13_VDDGPIO_SEL_POS (7)
#define SYS_AONP_ANA_REG13_VDDGPIO_SEL_MASK (0x1)

#define SYS_AONP_ANA_REG13_DPFMS_POS (8)
#define SYS_AONP_ANA_REG13_DPFMS_MASK (0x1f)

#define SYS_AONP_ANA_REG13_DTMPO_SEL_POS (13)
#define SYS_AONP_ANA_REG13_DTMPO_SEL_MASK (0x3)

#define SYS_AONP_ANA_REG13_DMPOEN_POS (15)
#define SYS_AONP_ANA_REG13_DMPOEN_MASK (0x1)

#define SYS_AONP_ANA_REG13_DFORCEPFM_POS (16)
#define SYS_AONP_ANA_REG13_DFORCEPFM_MASK (0x1)

#define SYS_AONP_ANA_REG13_DCLS_POS (17)
#define SYS_AONP_ANA_REG13_DCLS_MASK (0x7)

#define SYS_AONP_ANA_REG13_DSWRSTEN_POS (20)
#define SYS_AONP_ANA_REG13_DSWRSTEN_MASK (0x1)

#define SYS_AONP_ANA_REG13_DRIPC_POS (21)
#define SYS_AONP_ANA_REG13_DRIPC_MASK (0x7)

#define SYS_AONP_ANA_REG13_DRAMPC_POS (24)
#define SYS_AONP_ANA_REG13_DRAMPC_MASK (0xf)

#define SYS_AONP_ANA_REG13_DRAMPCEN_POS (28)
#define SYS_AONP_ANA_REG13_DRAMPCEN_MASK (0x1)

#define SYS_AONP_ANA_REG13_DENBURST_POS (29)
#define SYS_AONP_ANA_REG13_DENBURST_MASK (0x1)

#define SYS_AONP_ANA_REG13_DPFMEN_POS (30)
#define SYS_AONP_ANA_REG13_DPFMEN_MASK (0x1)

#define SYS_AONP_ANA_REG13_DLDOSEL_POS (31)
#define SYS_AONP_ANA_REG13_DLDOSEL_MASK (0x1)

#define SYS_AONP_ANA_REG14_ADDR (SOC_SYS_AONP_REG_BASE + (0x4e << 2))

#define SYS_AONP_ANA_REG14_PWDOVP1V_POS (0)
#define SYS_AONP_ANA_REG14_PWDOVP1V_MASK (0x1)

#define SYS_AONP_ANA_REG14_ASOFT_STC_POS (1)
#define SYS_AONP_ANA_REG14_ASOFT_STC_MASK (0xf)

#define SYS_AONP_ANA_REG14_DLDO_CZSEL_POS (5)
#define SYS_AONP_ANA_REG14_DLDO_CZSEL_MASK (0x7)

#define SYS_AONP_ANA_REG14_DLDO_RZSEL_POS (8)
#define SYS_AONP_ANA_REG14_DLDO_RZSEL_MASK (0x3)

#define SYS_AONP_ANA_REG14_EN_USBVCC18_POS (10)
#define SYS_AONP_ANA_REG14_EN_USBVCC18_MASK (0x1)

#define SYS_AONP_ANA_REG14_EN_USBVCC3V_POS (11)
#define SYS_AONP_ANA_REG14_EN_USBVCC3V_MASK (0x1)

#define SYS_AONP_ANA_REG14_VTRXSPISEL_POS (12)
#define SYS_AONP_ANA_REG14_VTRXSPISEL_MASK (0x3)

#define SYS_AONP_ANA_REG14_DENZCDDY_POS (14)
#define SYS_AONP_ANA_REG14_DENZCDDY_MASK (0x1)

#define SYS_AONP_ANA_REG14_DZCD_SWVS_POS (15)
#define SYS_AONP_ANA_REG14_DZCD_SWVS_MASK (0x7)

#define SYS_AONP_ANA_REG14_DZCD_REFS_POS (18)
#define SYS_AONP_ANA_REG14_DZCD_REFS_MASK (0x7)

#define SYS_AONP_ANA_REG14_DZCD_MANU_POS (21)
#define SYS_AONP_ANA_REG14_DZCD_MANU_MASK (0x3f)

#define SYS_AONP_ANA_REG14_AZCDMSEL_POS (27)
#define SYS_AONP_ANA_REG14_AZCDMSEL_MASK (0x1)

#define SYS_AONP_ANA_REG14_PSLDO_SWB_POS (28)
#define SYS_AONP_ANA_REG14_PSLDO_SWB_MASK (0x1)

#define SYS_AONP_ANA_REG14_VPSRAMSEL_POS (29)
#define SYS_AONP_ANA_REG14_VPSRAMSEL_MASK (0x3)

#define SYS_AONP_ANA_REG14_ENPSRAM_POS (31)
#define SYS_AONP_ANA_REG14_ENPSRAM_MASK (0x1)

#define SYS_AONP_ANA_REG15_ADDR (SOC_SYS_AONP_REG_BASE + (0x4f << 2))

#define SYS_AONP_ANA_REG15_GPIOWKEN_POS (0)
#define SYS_AONP_ANA_REG15_GPIOWKEN_MASK (0xffffffff)

#define SYS_AONP_ANA_REG16_ADDR (SOC_SYS_AONP_REG_BASE + (0x50 << 2))

#define SYS_AONP_ANA_REG16_TIMER_SET_POS (0)
#define SYS_AONP_ANA_REG16_TIMER_SET_MASK (0xf)

#define SYS_AONP_ANA_REG16_RTC_SET_POS (4)
#define SYS_AONP_ANA_REG16_RTC_SET_MASK (0xf)

#define SYS_AONP_ANA_REG16_NC_8_10_POS (8)
#define SYS_AONP_ANA_REG16_NC_8_10_MASK (0x7)

#define SYS_AONP_ANA_REG16_VCOREHSSEL_POS (11)
#define SYS_AONP_ANA_REG16_VCOREHSSEL_MASK (0xf)

#define SYS_AONP_ANA_REG16_VBUCKHSSEL_POS (15)
#define SYS_AONP_ANA_REG16_VBUCKHSSEL_MASK (0x7)

#define SYS_AONP_ANA_REG16_HSENFAST_POS (18)
#define SYS_AONP_ANA_REG16_HSENFAST_MASK (0x1)

#define SYS_AONP_ANA_REG16_ENHSPW_POS (19)
#define SYS_AONP_ANA_REG16_ENHSPW_MASK (0x1)

#define SYS_AONP_ANA_REG16_BUCKHS_SOFT_STC_POS (20)
#define SYS_AONP_ANA_REG16_BUCKHS_SOFT_STC_MASK (0xf)

#define SYS_AONP_ANA_REG16_HS_VEASEL_POS (24)
#define SYS_AONP_ANA_REG16_HS_VEASEL_MASK (0x3)

#define SYS_AONP_ANA_REG16_HSZCD_MANUAL_POS (26)
#define SYS_AONP_ANA_REG16_HSZCD_MANUAL_MASK (0x3f)

#define SYS_AONP_ANA_REG17_ADDR (SOC_SYS_AONP_REG_BASE + (0x51 << 2))

#define SYS_AONP_ANA_REG17_RTC_SET_POS (0)
#define SYS_AONP_ANA_REG17_RTC_SET_MASK (0xffffffff)

#define SYS_AONP_ANA_REG18_ADDR (SOC_SYS_AONP_REG_BASE + (0x52 << 2))

#define SYS_AONP_ANA_REG18_TIMER_SET_POS (0)
#define SYS_AONP_ANA_REG18_TIMER_SET_MASK (0xffffffff)

#define SYS_AONP_ANA_REG19_ADDR (SOC_SYS_AONP_REG_BASE + (0x53 << 2))

#define SYS_AONP_ANA_REG19_HSENZCDDY_POS (0)
#define SYS_AONP_ANA_REG19_HSENZCDDY_MASK (0x1)

#define SYS_AONP_ANA_REG19_HSENZCDCALIB_POS (1)
#define SYS_AONP_ANA_REG19_HSENZCDCALIB_MASK (0x1)

#define SYS_AONP_ANA_REG19_HSZCDSWVS_POS (2)
#define SYS_AONP_ANA_REG19_HSZCDSWVS_MASK (0x7)

#define SYS_AONP_ANA_REG19_HSZCDREFS_POS (5)
#define SYS_AONP_ANA_REG19_HSZCDREFS_MASK (0x7)

#define SYS_AONP_ANA_REG19_HSZCDMSEL_POS (8)
#define SYS_AONP_ANA_REG19_HSZCDMSEL_MASK (0x1)

#define SYS_AONP_ANA_REG19_HSPFMS_POS (9)
#define SYS_AONP_ANA_REG19_HSPFMS_MASK (0x1f)

#define SYS_AONP_ANA_REG19_HSTMPO_SEL_POS (14)
#define SYS_AONP_ANA_REG19_HSTMPO_SEL_MASK (0x3)

#define SYS_AONP_ANA_REG19_HSMPOEN_POS (16)
#define SYS_AONP_ANA_REG19_HSMPOEN_MASK (0x1)

#define SYS_AONP_ANA_REG19_HSFORCEPFM_POS (17)
#define SYS_AONP_ANA_REG19_HSFORCEPFM_MASK (0x1)

#define SYS_AONP_ANA_REG19_HSCLS_POS (18)
#define SYS_AONP_ANA_REG19_HSCLS_MASK (0x7)

#define SYS_AONP_ANA_REG19_HSSWRSTEN_POS (21)
#define SYS_AONP_ANA_REG19_HSSWRSTEN_MASK (0x1)

#define SYS_AONP_ANA_REG19_HSRIPC_POS (22)
#define SYS_AONP_ANA_REG19_HSRIPC_MASK (0x7)

#define SYS_AONP_ANA_REG19_HSRAMPC_POS (25)
#define SYS_AONP_ANA_REG19_HSRAMPC_MASK (0xf)

#define SYS_AONP_ANA_REG19_HSRAMPCEN_POS (29)
#define SYS_AONP_ANA_REG19_HSRAMPCEN_MASK (0x1)

#define SYS_AONP_ANA_REG19_HSENBURST_POS (30)
#define SYS_AONP_ANA_REG19_HSENBURST_MASK (0x1)

#define SYS_AONP_ANA_REG19_HSPFMEN_POS (31)
#define SYS_AONP_ANA_REG19_HSPFMEN_MASK (0x1)

#define SYS_AONP_ANA_REG20_ADDR (SOC_SYS_AONP_REG_BASE + (0x54 << 2))

#define SYS_AONP_ANA_REG20_ISELAUD_POS (0)
#define SYS_AONP_ANA_REG20_ISELAUD_MASK (0x1)

#define SYS_AONP_ANA_REG20_AUDCK_RLCEN_POS (1)
#define SYS_AONP_ANA_REG20_AUDCK_RLCEN_MASK (0x1)

#define SYS_AONP_ANA_REG20_LCHCKINVEN_POS (2)
#define SYS_AONP_ANA_REG20_LCHCKINVEN_MASK (0x1)

#define SYS_AONP_ANA_REG20_ENAUDBIAS_POS (3)
#define SYS_AONP_ANA_REG20_ENAUDBIAS_MASK (0x1)

#define SYS_AONP_ANA_REG20_ENADCBIAS_POS (4)
#define SYS_AONP_ANA_REG20_ENADCBIAS_MASK (0x1)

#define SYS_AONP_ANA_REG20_ENMICBIAS_POS (5)
#define SYS_AONP_ANA_REG20_ENMICBIAS_MASK (0x1)

#define SYS_AONP_ANA_REG20_ADCCKINVEN_POS (6)
#define SYS_AONP_ANA_REG20_ADCCKINVEN_MASK (0x1)

#define SYS_AONP_ANA_REG20_SPI_POS (7)
#define SYS_AONP_ANA_REG20_SPI_MASK (0x1)

#define SYS_AONP_ANA_REG20_ADCTSTEN_POS (8)
#define SYS_AONP_ANA_REG20_ADCTSTEN_MASK (0x1)

#define SYS_AONP_ANA_REG20_MICBIAS_TRM_POS (9)
#define SYS_AONP_ANA_REG20_MICBIAS_TRM_MASK (0x3)

#define SYS_AONP_ANA_REG20_MICBIAS_VOC_POS (11)
#define SYS_AONP_ANA_REG20_MICBIAS_VOC_MASK (0x1f)

#define SYS_AONP_ANA_REG20_VREFSEL_POS (16)
#define SYS_AONP_ANA_REG20_VREFSEL_MASK (0x1)

#define SYS_AONP_ANA_REG20_CAPSW_POS (17)
#define SYS_AONP_ANA_REG20_CAPSW_MASK (0x1f)

#define SYS_AONP_ANA_REG20_ADCREF_SEL_POS (22)
#define SYS_AONP_ANA_REG20_ADCREF_SEL_MASK (0x3)

#define SYS_AONP_ANA_REG20_ADCVCMSEL_POS (24)
#define SYS_AONP_ANA_REG20_ADCVCMSEL_MASK (0x3)

#define SYS_AONP_ANA_REG20_SPI_1_POS (26)
#define SYS_AONP_ANA_REG20_SPI_1_MASK (0x1)

#define SYS_AONP_ANA_REG20_AUDADJREF_POS (27)
#define SYS_AONP_ANA_REG20_AUDADJREF_MASK (0x1f)

#define SYS_AONP_ANA_REG21_ADDR (SOC_SYS_AONP_REG_BASE + (0x55 << 2))

#define SYS_AONP_ANA_REG21_ISEL_MIC1_POS (0)
#define SYS_AONP_ANA_REG21_ISEL_MIC1_MASK (0x3)

#define SYS_AONP_ANA_REG21_MICIRSEL1_MIC1_POS (2)
#define SYS_AONP_ANA_REG21_MICIRSEL1_MIC1_MASK (0x1)

#define SYS_AONP_ANA_REG21_VCMSEL_MIC1_POS (3)
#define SYS_AONP_ANA_REG21_VCMSEL_MIC1_MASK (0x1)

#define SYS_AONP_ANA_REG21_ENFSR_MIC1_POS (4)
#define SYS_AONP_ANA_REG21_ENFSR_MIC1_MASK (0x1)

#define SYS_AONP_ANA_REG21_ENOPOCLIP_MIC1_POS (5)
#define SYS_AONP_ANA_REG21_ENOPOCLIP_MIC1_MASK (0x1)

#define SYS_AONP_ANA_REG21_DA2ADEN_MIC1_POS (6)
#define SYS_AONP_ANA_REG21_DA2ADEN_MIC1_MASK (0x1)

#define SYS_AONP_ANA_REG21_IMATCH_MIC1_POS (7)
#define SYS_AONP_ANA_REG21_IMATCH_MIC1_MASK (0xf)

#define SYS_AONP_ANA_REG21_IMATCH_EN_MIC1_POS (11)
#define SYS_AONP_ANA_REG21_IMATCH_EN_MIC1_MASK (0x1)

#define SYS_AONP_ANA_REG21_DCCOMPEN_MIC1_POS (12)
#define SYS_AONP_ANA_REG21_DCCOMPEN_MIC1_MASK (0x1)

#define SYS_AONP_ANA_REG21_MICSINGLEEN_MIC1_POS (13)
#define SYS_AONP_ANA_REG21_MICSINGLEEN_MIC1_MASK (0x1)

#define SYS_AONP_ANA_REG21_NC_14_14_POS (14)
#define SYS_AONP_ANA_REG21_NC_14_14_MASK (0x1)

#define SYS_AONP_ANA_REG21_MICGAIN_MIC1_POS (15)
#define SYS_AONP_ANA_REG21_MICGAIN_MIC1_MASK (0xf)

#define SYS_AONP_ANA_REG21_NC_19_23_POS (19)
#define SYS_AONP_ANA_REG21_NC_19_23_MASK (0x1f)

#define SYS_AONP_ANA_REG21_DWAMODE_MIC1_POS (24)
#define SYS_AONP_ANA_REG21_DWAMODE_MIC1_MASK (0x1)

#define SYS_AONP_ANA_REG21_NC_25_27_POS (25)
#define SYS_AONP_ANA_REG21_NC_25_27_MASK (0x7)

#define SYS_AONP_ANA_REG21_MICEN_MIC1_POS (28)
#define SYS_AONP_ANA_REG21_MICEN_MIC1_MASK (0x1)

#define SYS_AONP_ANA_REG21_RST_MIC1_POS (29)
#define SYS_AONP_ANA_REG21_RST_MIC1_MASK (0x1)

#define SYS_AONP_ANA_REG21_BPDWA1V_MIC1_POS (30)
#define SYS_AONP_ANA_REG21_BPDWA1V_MIC1_MASK (0x1)

#define SYS_AONP_ANA_REG21_HCEN1STG_MIC1_POS (31)
#define SYS_AONP_ANA_REG21_HCEN1STG_MIC1_MASK (0x1)

#define SYS_AONP_ANA_REG22_ADDR (SOC_SYS_AONP_REG_BASE + (0x56 << 2))

#define SYS_AONP_ANA_REG22_ICTRL_DSPPLL_POS (0)
#define SYS_AONP_ANA_REG22_ICTRL_DSPPLL_MASK (0x1)

#define SYS_AONP_ANA_REG22_LVREF_POS (1)
#define SYS_AONP_ANA_REG22_LVREF_MASK (0x3)

#define SYS_AONP_ANA_REG22_RESERVED_BIT_3_3_POS (3)
#define SYS_AONP_ANA_REG22_RESERVED_BIT_3_3_MASK (0x1)

#define SYS_AONP_ANA_REG22_NC_4_18_POS (4)
#define SYS_AONP_ANA_REG22_NC_4_18_MASK (0x7fff)

#define SYS_AONP_ANA_REG22_MODE_POS (19)
#define SYS_AONP_ANA_REG22_MODE_MASK (0x1)

#define SYS_AONP_ANA_REG22_IAMSEL_POS (20)
#define SYS_AONP_ANA_REG22_IAMSEL_MASK (0x1)

#define SYS_AONP_ANA_REG22_HVREF_POS (21)
#define SYS_AONP_ANA_REG22_HVREF_MASK (0x3)

#define SYS_AONP_ANA_REG22_LVREF_1_POS (23)
#define SYS_AONP_ANA_REG22_LVREF_1_MASK (0x3)

#define SYS_AONP_ANA_REG22_NC_25_31_POS (25)
#define SYS_AONP_ANA_REG22_NC_25_31_MASK (0x7f)

#define SYS_AONP_ANA_REG23_ADDR (SOC_SYS_AONP_REG_BASE + (0x57 << 2))

#define SYS_AONP_ANA_REG23_CAMSEL_POS (0)
#define SYS_AONP_ANA_REG23_CAMSEL_MASK (0x1)

#define SYS_AONP_ANA_REG23_MSW_POS (1)
#define SYS_AONP_ANA_REG23_MSW_MASK (0x1ff)

#define SYS_AONP_ANA_REG23_TSTCKEN_DPLL_POS (10)
#define SYS_AONP_ANA_REG23_TSTCKEN_DPLL_MASK (0x1)

#define SYS_AONP_ANA_REG23_OSCCAL_TRIG_POS (11)
#define SYS_AONP_ANA_REG23_OSCCAL_TRIG_MASK (0x1)

#define SYS_AONP_ANA_REG23_CNTI_POS (12)
#define SYS_AONP_ANA_REG23_CNTI_MASK (0x1ff)

#define SYS_AONP_ANA_REG23_NC_21_21_POS (21)
#define SYS_AONP_ANA_REG23_NC_21_21_MASK (0x1)

#define SYS_AONP_ANA_REG23_SPI_RST_POS (22)
#define SYS_AONP_ANA_REG23_SPI_RST_MASK (0x1)

#define SYS_AONP_ANA_REG23_CLOSELOOP_EN_POS (23)
#define SYS_AONP_ANA_REG23_CLOSELOOP_EN_MASK (0x1)

#define SYS_AONP_ANA_REG23_CALTIME_POS (24)
#define SYS_AONP_ANA_REG23_CALTIME_MASK (0x1)

#define SYS_AONP_ANA_REG23_LPFRZ_POS (25)
#define SYS_AONP_ANA_REG23_LPFRZ_MASK (0x3)

#define SYS_AONP_ANA_REG23_ICP_POS (27)
#define SYS_AONP_ANA_REG23_ICP_MASK (0xf)

#define SYS_AONP_ANA_REG23_CP2CTRL_POS (31)
#define SYS_AONP_ANA_REG23_CP2CTRL_MASK (0x1)

#define SYS_AONP_ANA_REG24_ADDR (SOC_SYS_AONP_REG_BASE + (0x58 << 2))

#define SYS_AONP_ANA_REG24_NC_0_31_POS (0)
#define SYS_AONP_ANA_REG24_NC_0_31_MASK (0xffffffff)

#define SYS_AONP_ANA_REG25_ADDR (SOC_SYS_AONP_REG_BASE + (0x59 << 2))

#define SYS_AONP_ANA_REG25_INT_MOD_POS (0)
#define SYS_AONP_ANA_REG25_INT_MOD_MASK (0x1)

#define SYS_AONP_ANA_REG25_NSYN_POS (1)
#define SYS_AONP_ANA_REG25_NSYN_MASK (0x1)

#define SYS_AONP_ANA_REG25_OPEN_ENB_POS (2)
#define SYS_AONP_ANA_REG25_OPEN_ENB_MASK (0x1)

#define SYS_AONP_ANA_REG25_RESET_POS (3)
#define SYS_AONP_ANA_REG25_RESET_MASK (0x1)

#define SYS_AONP_ANA_REG25_IOFFSETL_POS (4)
#define SYS_AONP_ANA_REG25_IOFFSETL_MASK (0x7)

#define SYS_AONP_ANA_REG25_LPFRZ_POS (7)
#define SYS_AONP_ANA_REG25_LPFRZ_MASK (0xf)

#define SYS_AONP_ANA_REG25_VSEL_POS (11)
#define SYS_AONP_ANA_REG25_VSEL_MASK (0x7)

#define SYS_AONP_ANA_REG25_VSEL_CAL_POS (14)
#define SYS_AONP_ANA_REG25_VSEL_CAL_MASK (0x1)

#define SYS_AONP_ANA_REG25_PWD_LOCKDET_POS (15)
#define SYS_AONP_ANA_REG25_PWD_LOCKDET_MASK (0x1)

#define SYS_AONP_ANA_REG25_LOCKDET_BYPASS_POS (16)
#define SYS_AONP_ANA_REG25_LOCKDET_BYPASS_MASK (0x1)

#define SYS_AONP_ANA_REG25_CKREF_LOOP_SEL_POS (17)
#define SYS_AONP_ANA_REG25_CKREF_LOOP_SEL_MASK (0x1)

#define SYS_AONP_ANA_REG25_SPI_TRIGGER_POS (18)
#define SYS_AONP_ANA_REG25_SPI_TRIGGER_MASK (0x1)

#define SYS_AONP_ANA_REG25_MANUAL_POS (19)
#define SYS_AONP_ANA_REG25_MANUAL_MASK (0x1)

#define SYS_AONP_ANA_REG25_TEST_CKAUDIO_EN_POS (20)
#define SYS_AONP_ANA_REG25_TEST_CKAUDIO_EN_MASK (0x1)

#define SYS_AONP_ANA_REG25_CK2XEN_POS (21)
#define SYS_AONP_ANA_REG25_CK2XEN_MASK (0x1)

#define SYS_AONP_ANA_REG25_ICP_POS (22)
#define SYS_AONP_ANA_REG25_ICP_MASK (0x3)

#define SYS_AONP_ANA_REG25_CKTST_SEL_POS (24)
#define SYS_AONP_ANA_REG25_CKTST_SEL_MASK (0x1)

#define SYS_AONP_ANA_REG25_EDGESEL_NCK_POS (25)
#define SYS_AONP_ANA_REG25_EDGESEL_NCK_MASK (0x1)

#define SYS_AONP_ANA_REG25_NLOADDLYEN_POS (26)
#define SYS_AONP_ANA_REG25_NLOADDLYEN_MASK (0x1)

#define SYS_AONP_ANA_REG25_BYPASS_CALDONE_AUTO_POS (27)
#define SYS_AONP_ANA_REG25_BYPASS_CALDONE_AUTO_MASK (0x1)

#define SYS_AONP_ANA_REG25_CAL_RES_SPI_POS (28)
#define SYS_AONP_ANA_REG25_CAL_RES_SPI_MASK (0x7)

#define SYS_AONP_ANA_REG25_AUDIOEN_POS (31)
#define SYS_AONP_ANA_REG25_AUDIOEN_MASK (0x1)

#define SYS_AONP_ANA_REG26_ADDR (SOC_SYS_AONP_REG_BASE + (0x5a << 2))

#define SYS_AONP_ANA_REG26_N_POS (0)
#define SYS_AONP_ANA_REG26_N_MASK (0x3fffffff)

#define SYS_AONP_ANA_REG26_CALRES_SPIEN_POS (30)
#define SYS_AONP_ANA_REG26_CALRES_SPIEN_MASK (0x1)

#define SYS_AONP_ANA_REG26_CALREFEN_POS (31)
#define SYS_AONP_ANA_REG26_CALREFEN_MASK (0x1)

#define SYS_AONP_ANA_REG27_ADDR (SOC_SYS_AONP_REG_BASE + (0x5b << 2))

#define SYS_AONP_ANA_REG27_ISEL_MIC2_POS (0)
#define SYS_AONP_ANA_REG27_ISEL_MIC2_MASK (0x3)

#define SYS_AONP_ANA_REG27_MICIRSEL1_MIC2_POS (2)
#define SYS_AONP_ANA_REG27_MICIRSEL1_MIC2_MASK (0x1)

#define SYS_AONP_ANA_REG27_VCMSEL_MIC2_POS (3)
#define SYS_AONP_ANA_REG27_VCMSEL_MIC2_MASK (0x1)

#define SYS_AONP_ANA_REG27_ENFSR_MIC2_POS (4)
#define SYS_AONP_ANA_REG27_ENFSR_MIC2_MASK (0x1)

#define SYS_AONP_ANA_REG27_ENOPOCLIP_MIC2_POS (5)
#define SYS_AONP_ANA_REG27_ENOPOCLIP_MIC2_MASK (0x1)

#define SYS_AONP_ANA_REG27_DA2ADEN_MIC2_POS (6)
#define SYS_AONP_ANA_REG27_DA2ADEN_MIC2_MASK (0x1)

#define SYS_AONP_ANA_REG27_IMATCH_MIC2_POS (7)
#define SYS_AONP_ANA_REG27_IMATCH_MIC2_MASK (0xf)

#define SYS_AONP_ANA_REG27_IMATCH_EN_MIC2_POS (11)
#define SYS_AONP_ANA_REG27_IMATCH_EN_MIC2_MASK (0x1)

#define SYS_AONP_ANA_REG27_DCCOMPEN_MIC2_POS (12)
#define SYS_AONP_ANA_REG27_DCCOMPEN_MIC2_MASK (0x1)

#define SYS_AONP_ANA_REG27_MICSINGLEEN_MIC2_POS (13)
#define SYS_AONP_ANA_REG27_MICSINGLEEN_MIC2_MASK (0x1)

#define SYS_AONP_ANA_REG27_NC_14_14_POS (14)
#define SYS_AONP_ANA_REG27_NC_14_14_MASK (0x1)

#define SYS_AONP_ANA_REG27_MICGAIN_MIC2_POS (15)
#define SYS_AONP_ANA_REG27_MICGAIN_MIC2_MASK (0xf)

#define SYS_AONP_ANA_REG27_NC_19_23_POS (19)
#define SYS_AONP_ANA_REG27_NC_19_23_MASK (0x1f)

#define SYS_AONP_ANA_REG27_DWAMODE_MIC2_POS (24)
#define SYS_AONP_ANA_REG27_DWAMODE_MIC2_MASK (0x1)

#define SYS_AONP_ANA_REG27_NC_25_27_POS (25)
#define SYS_AONP_ANA_REG27_NC_25_27_MASK (0x7)

#define SYS_AONP_ANA_REG27_MICEN_MIC2_POS (28)
#define SYS_AONP_ANA_REG27_MICEN_MIC2_MASK (0x1)

#define SYS_AONP_ANA_REG27_RST_MIC2_POS (29)
#define SYS_AONP_ANA_REG27_RST_MIC2_MASK (0x1)

#define SYS_AONP_ANA_REG27_BPDWA1V_MIC2_POS (30)
#define SYS_AONP_ANA_REG27_BPDWA1V_MIC2_MASK (0x1)

#define SYS_AONP_ANA_REG27_HCEN1STG_MIC2_POS (31)
#define SYS_AONP_ANA_REG27_HCEN1STG_MIC2_MASK (0x1)

#define SYS_AONP_ANA_REG28_ADDR (SOC_SYS_AONP_REG_BASE + (0x5c << 2))

#define SYS_AONP_ANA_REG28_ISEL_MIC3_POS (0)
#define SYS_AONP_ANA_REG28_ISEL_MIC3_MASK (0x3)

#define SYS_AONP_ANA_REG28_MICIRSEL1_MIC3_POS (2)
#define SYS_AONP_ANA_REG28_MICIRSEL1_MIC3_MASK (0x1)

#define SYS_AONP_ANA_REG28_VCMSEL_MIC3_POS (3)
#define SYS_AONP_ANA_REG28_VCMSEL_MIC3_MASK (0x1)

#define SYS_AONP_ANA_REG28_ENFSR_MIC3_POS (4)
#define SYS_AONP_ANA_REG28_ENFSR_MIC3_MASK (0x1)

#define SYS_AONP_ANA_REG28_ENOPOCLIP_MIC3_POS (5)
#define SYS_AONP_ANA_REG28_ENOPOCLIP_MIC3_MASK (0x1)

#define SYS_AONP_ANA_REG28_DA2ADEN_MIC3_POS (6)
#define SYS_AONP_ANA_REG28_DA2ADEN_MIC3_MASK (0x1)

#define SYS_AONP_ANA_REG28_IMATCH_MIC3_POS (7)
#define SYS_AONP_ANA_REG28_IMATCH_MIC3_MASK (0xf)

#define SYS_AONP_ANA_REG28_IMATCH_EN_MIC3_POS (11)
#define SYS_AONP_ANA_REG28_IMATCH_EN_MIC3_MASK (0x1)

#define SYS_AONP_ANA_REG28_DCCOMPEN_MIC3_POS (12)
#define SYS_AONP_ANA_REG28_DCCOMPEN_MIC3_MASK (0x1)

#define SYS_AONP_ANA_REG28_MICSINGLEEN_MIC3_POS (13)
#define SYS_AONP_ANA_REG28_MICSINGLEEN_MIC3_MASK (0x1)

#define SYS_AONP_ANA_REG28_NC_14_14_POS (14)
#define SYS_AONP_ANA_REG28_NC_14_14_MASK (0x1)

#define SYS_AONP_ANA_REG28_MICGAIN_MIC3_POS (15)
#define SYS_AONP_ANA_REG28_MICGAIN_MIC3_MASK (0xf)

#define SYS_AONP_ANA_REG28_NC_19_23_POS (19)
#define SYS_AONP_ANA_REG28_NC_19_23_MASK (0x1f)

#define SYS_AONP_ANA_REG28_DWAMODE_MIC3_POS (24)
#define SYS_AONP_ANA_REG28_DWAMODE_MIC3_MASK (0x1)

#define SYS_AONP_ANA_REG28_NC_25_27_POS (25)
#define SYS_AONP_ANA_REG28_NC_25_27_MASK (0x7)

#define SYS_AONP_ANA_REG28_MICEN_MIC3_POS (28)
#define SYS_AONP_ANA_REG28_MICEN_MIC3_MASK (0x1)

#define SYS_AONP_ANA_REG28_RST_MIC3_POS (29)
#define SYS_AONP_ANA_REG28_RST_MIC3_MASK (0x1)

#define SYS_AONP_ANA_REG28_BPDWA1V_MIC3_POS (30)
#define SYS_AONP_ANA_REG28_BPDWA1V_MIC3_MASK (0x1)

#define SYS_AONP_ANA_REG28_HCEN1STG_MIC3_POS (31)
#define SYS_AONP_ANA_REG28_HCEN1STG_MIC3_MASK (0x1)

#define SYS_AONP_ANA_REG29_ADDR (SOC_SYS_AONP_REG_BASE + (0x5d << 2))

#define SYS_AONP_ANA_REG29_HPDAC_POS (0)
#define SYS_AONP_ANA_REG29_HPDAC_MASK (0x1)

#define SYS_AONP_ANA_REG29_ISELSTG_POS (1)
#define SYS_AONP_ANA_REG29_ISELSTG_MASK (0x1)

#define SYS_AONP_ANA_REG29_OSCDAC_POS (2)
#define SYS_AONP_ANA_REG29_OSCDAC_MASK (0x3)

#define SYS_AONP_ANA_REG29_OCENDAC_POS (4)
#define SYS_AONP_ANA_REG29_OCENDAC_MASK (0x1)

#define SYS_AONP_ANA_REG29_VSELDCO_POS (5)
#define SYS_AONP_ANA_REG29_VSELDCO_MASK (0x1)

#define SYS_AONP_ANA_REG29_SRSEL_POS (6)
#define SYS_AONP_ANA_REG29_SRSEL_MASK (0x1)

#define SYS_AONP_ANA_REG29_HPOEN_POS (7)
#define SYS_AONP_ANA_REG29_HPOEN_MASK (0x1)

#define SYS_AONP_ANA_REG29_LBWEN_POS (8)
#define SYS_AONP_ANA_REG29_LBWEN_MASK (0x1)

#define SYS_AONP_ANA_REG29_CALSEL_POS (9)
#define SYS_AONP_ANA_REG29_CALSEL_MASK (0x1)

#define SYS_AONP_ANA_REG29_BP2VLDO_POS (10)
#define SYS_AONP_ANA_REG29_BP2VLDO_MASK (0x1)

#define SYS_AONP_ANA_REG29_DCOCHG_POS (11)
#define SYS_AONP_ANA_REG29_DCOCHG_MASK (0x3)

#define SYS_AONP_ANA_REG29_DIFFEN_POS (13)
#define SYS_AONP_ANA_REG29_DIFFEN_MASK (0x1)

#define SYS_AONP_ANA_REG29_ENDACCAL_POS (14)
#define SYS_AONP_ANA_REG29_ENDACCAL_MASK (0x1)

#define SYS_AONP_ANA_REG29_RENDCOC_POS (15)
#define SYS_AONP_ANA_REG29_RENDCOC_MASK (0x1)

#define SYS_AONP_ANA_REG29_LENDCOC_POS (16)
#define SYS_AONP_ANA_REG29_LENDCOC_MASK (0x1)

#define SYS_AONP_ANA_REG29_RENVCMD_POS (17)
#define SYS_AONP_ANA_REG29_RENVCMD_MASK (0x1)

#define SYS_AONP_ANA_REG29_LENVCMD_POS (18)
#define SYS_AONP_ANA_REG29_LENVCMD_MASK (0x1)

#define SYS_AONP_ANA_REG29_DACDRVEN_POS (19)
#define SYS_AONP_ANA_REG29_DACDRVEN_MASK (0x1)

#define SYS_AONP_ANA_REG29_DACREN_POS (20)
#define SYS_AONP_ANA_REG29_DACREN_MASK (0x1)

#define SYS_AONP_ANA_REG29_DACLEN_POS (21)
#define SYS_AONP_ANA_REG29_DACLEN_MASK (0x1)

#define SYS_AONP_ANA_REG29_DACG_POS (22)
#define SYS_AONP_ANA_REG29_DACG_MASK (0xf)

#define SYS_AONP_ANA_REG29_DACMUTE_POS (26)
#define SYS_AONP_ANA_REG29_DACMUTE_MASK (0x1)

#define SYS_AONP_ANA_REG29_DACDWAMODE_SEL_POS (27)
#define SYS_AONP_ANA_REG29_DACDWAMODE_SEL_MASK (0x1)

#define SYS_AONP_ANA_REG29_CKPSEL_POS (28)
#define SYS_AONP_ANA_REG29_CKPSEL_MASK (0x1)

#define SYS_AONP_ANA_REG29_NC_29_31_POS (29)
#define SYS_AONP_ANA_REG29_NC_29_31_MASK (0x7)

#define SYS_AONP_ANA_REG30_ADDR (SOC_SYS_AONP_REG_BASE + (0x5e << 2))

#define SYS_AONP_ANA_REG30_LMDCIN_POS (0)
#define SYS_AONP_ANA_REG30_LMDCIN_MASK (0xff)

#define SYS_AONP_ANA_REG30_RMDCIN_POS (8)
#define SYS_AONP_ANA_REG30_RMDCIN_MASK (0xff)

#define SYS_AONP_ANA_REG30_SPIRST_OVC_POS (16)
#define SYS_AONP_ANA_REG30_SPIRST_OVC_MASK (0x1)

#define SYS_AONP_ANA_REG30_ENIDACR_POS (17)
#define SYS_AONP_ANA_REG30_ENIDACR_MASK (0x1)

#define SYS_AONP_ANA_REG30_ENIDACL_POS (18)
#define SYS_AONP_ANA_REG30_ENIDACL_MASK (0x1)

#define SYS_AONP_ANA_REG30_DAC3RDHC0V9_POS (19)
#define SYS_AONP_ANA_REG30_DAC3RDHC0V9_MASK (0x1)

#define SYS_AONP_ANA_REG30_HC2S_POS (20)
#define SYS_AONP_ANA_REG30_HC2S_MASK (0x1)

#define SYS_AONP_ANA_REG30_SNG_FB_EN_POS (21)
#define SYS_AONP_ANA_REG30_SNG_FB_EN_MASK (0x1)

#define SYS_AONP_ANA_REG30_RFB_CTRL_POS (22)
#define SYS_AONP_ANA_REG30_RFB_CTRL_MASK (0x1)

#define SYS_AONP_ANA_REG30_ENBS_POS (23)
#define SYS_AONP_ANA_REG30_ENBS_MASK (0x1)

#define SYS_AONP_ANA_REG30_CALCK_SEL0V9_POS (24)
#define SYS_AONP_ANA_REG30_CALCK_SEL0V9_MASK (0x1)

#define SYS_AONP_ANA_REG30_BPDWA0V9_POS (25)
#define SYS_AONP_ANA_REG30_BPDWA0V9_MASK (0x1)

#define SYS_AONP_ANA_REG30_LOOPRST0V9_POS (26)
#define SYS_AONP_ANA_REG30_LOOPRST0V9_MASK (0x1)

#define SYS_AONP_ANA_REG30_OCT0V9_POS (27)
#define SYS_AONP_ANA_REG30_OCT0V9_MASK (0x3)

#define SYS_AONP_ANA_REG30_SOUT0V9_POS (29)
#define SYS_AONP_ANA_REG30_SOUT0V9_MASK (0x1)

#define SYS_AONP_ANA_REG30_HC0V9_POS (30)
#define SYS_AONP_ANA_REG30_HC0V9_MASK (0x3)

#define SYS_AONP_ANA_REG31_ADDR (SOC_SYS_AONP_REG_BASE + (0x5f << 2))

#define SYS_AONP_ANA_REG31_NC_0_31_POS (0)
#define SYS_AONP_ANA_REG31_NC_0_31_MASK (0xffffffff)

#define SYS_AONP_ANA_REG32_ADDR (SOC_SYS_AONP_REG_BASE + (0x60 << 2))

#define SYS_AONP_ANA_REG32_NEW_ANA_REG_POS (0)
#define SYS_AONP_ANA_REG32_NEW_ANA_REG_MASK (0xffffffff)

#define SYS_AONP_ANA_REG33_ADDR (SOC_SYS_AONP_REG_BASE + (0x61 << 2))

#define SYS_AONP_ANA_REG33_NEW_ANA_REG_POS (0)
#define SYS_AONP_ANA_REG33_NEW_ANA_REG_MASK (0xffffffff)

#define SYS_AONP_ANA_REG34_ADDR (SOC_SYS_AONP_REG_BASE + (0x62 << 2))

#define SYS_AONP_ANA_REG34_NEW_ANA_REG_POS (0)
#define SYS_AONP_ANA_REG34_NEW_ANA_REG_MASK (0xffffffff)

#define SYS_AONP_ANA_REG35_ADDR (SOC_SYS_AONP_REG_BASE + (0x63 << 2))

#define SYS_AONP_ANA_REG35_NEW_ANA_REG_POS (0)
#define SYS_AONP_ANA_REG35_NEW_ANA_REG_MASK (0xffffffff)

#define SYS_AONP_ANA_REG36_ADDR (SOC_SYS_AONP_REG_BASE + (0x64 << 2))

#define SYS_AONP_ANA_REG36_NEW_ANA_REG_POS (0)
#define SYS_AONP_ANA_REG36_NEW_ANA_REG_MASK (0xffffffff)

#define SYS_AONP_ANA_REG37_ADDR (SOC_SYS_AONP_REG_BASE + (0x65 << 2))

#define SYS_AONP_ANA_REG37_NEW_ANA_REG_POS (0)
#define SYS_AONP_ANA_REG37_NEW_ANA_REG_MASK (0xffffffff)

#define SYS_AONP_ANA_REG38_ADDR (SOC_SYS_AONP_REG_BASE + (0x66 << 2))

#define SYS_AONP_ANA_REG38_NEW_ANA_REG_POS (0)
#define SYS_AONP_ANA_REG38_NEW_ANA_REG_MASK (0xffffffff)

#define SYS_AONP_ANA_REG39_ADDR (SOC_SYS_AONP_REG_BASE + (0x67 << 2))

#define SYS_AONP_ANA_REG39_NEW_ANA_REG_POS (0)
#define SYS_AONP_ANA_REG39_NEW_ANA_REG_MASK (0xffffffff)

#define SYS_AONP_ANA_REG40_ADDR (SOC_SYS_AONP_REG_BASE + (0x68 << 2))

#define SYS_AONP_ANA_REG40_NEW_ANA_REG_POS (0)
#define SYS_AONP_ANA_REG40_NEW_ANA_REG_MASK (0xffffffff)

#define SYS_AONP_ANA_REG41_ADDR (SOC_SYS_AONP_REG_BASE + (0x69 << 2))

#define SYS_AONP_ANA_REG41_NEW_ANA_REG_POS (0)
#define SYS_AONP_ANA_REG41_NEW_ANA_REG_MASK (0xffffffff)

#define SYS_AONP_ANA_REG42_ADDR (SOC_SYS_AONP_REG_BASE + (0x6a << 2))

#define SYS_AONP_ANA_REG42_NEW_ANA_REG_POS (0)
#define SYS_AONP_ANA_REG42_NEW_ANA_REG_MASK (0xffffffff)

#define SYS_AONP_ANA_REG43_ADDR (SOC_SYS_AONP_REG_BASE + (0x6b << 2))

#define SYS_AONP_ANA_REG43_NEW_ANA_REG_POS (0)
#define SYS_AONP_ANA_REG43_NEW_ANA_REG_MASK (0xffffffff)

#define SYS_AONP_ANA_REG44_ADDR (SOC_SYS_AONP_REG_BASE + (0x6c << 2))

#define SYS_AONP_ANA_REG44_NEW_ANA_REG_POS (0)
#define SYS_AONP_ANA_REG44_NEW_ANA_REG_MASK (0xffffffff)

#define SYS_AONP_ANA_REG45_ADDR (SOC_SYS_AONP_REG_BASE + (0x6d << 2))

#define SYS_AONP_ANA_REG45_NEW_ANA_REG_POS (0)
#define SYS_AONP_ANA_REG45_NEW_ANA_REG_MASK (0xffffffff)

#define SYS_AONP_ANA_REG46_ADDR (SOC_SYS_AONP_REG_BASE + (0x6e << 2))

#define SYS_AONP_ANA_REG46_NEW_ANA_REG_POS (0)
#define SYS_AONP_ANA_REG46_NEW_ANA_REG_MASK (0xffffffff)

#define SYS_AONP_ANA_REG47_ADDR (SOC_SYS_AONP_REG_BASE + (0x6f << 2))

#define SYS_AONP_ANA_REG47_NEW_ANA_REG_POS (0)
#define SYS_AONP_ANA_REG47_NEW_ANA_REG_MASK (0xffffffff)

#ifdef __cplusplus
}
#endif
