// Copyright 2022-2023 Beken
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This is a generated file, if you need to modify it, use the script to
// generate and modify all the struct.h, ll.h, reg.h, debug_dump.c files!

#pragma once


#ifdef __cplusplus
extern "C" {
#endif


#define SYS_AHBP_REG0_ADDR (SOC_SYS_AHBP_REG_BASE + (0x0 << 2))

#define SYS_AHBP_REG0_DEVICEID_POS (0)
#define SYS_AHBP_REG0_DEVICEID_MASK (0xffffffff)

#define SYS_AHBP_REG1_ADDR (SOC_SYS_AHBP_REG_BASE + (0x1 << 2))

#define SYS_AHBP_REG1_VERSIONID_POS (0)
#define SYS_AHBP_REG1_VERSIONID_MASK (0xffffffff)

#define SYS_AHBP_REG2_ADDR (SOC_SYS_AHBP_REG_BASE + (0x2 << 2))

#define SYS_AHBP_REG2_RESERVED_0_0_POS (0)
#define SYS_AHBP_REG2_RESERVED_0_0_MASK (0x1)

#define SYS_AHBP_REG2_CLKG_BYPASS_POS (1)
#define SYS_AHBP_REG2_CLKG_BYPASS_MASK (0x1)

#define SYS_AHBP_REG2_RESERVED_2_31_POS (2)
#define SYS_AHBP_REG2_RESERVED_2_31_MASK (0x3fffffff)

#define SYS_AHBP_REG3_ADDR (SOC_SYS_AHBP_REG_BASE + (0x3 << 2))

#define SYS_AHBP_REG3_CPU0_SLEEPING_POS (0)
#define SYS_AHBP_REG3_CPU0_SLEEPING_MASK (0x1)

#define SYS_AHBP_REG3_CPU0_DEEPSLEEP_POS (1)
#define SYS_AHBP_REG3_CPU0_DEEPSLEEP_MASK (0x1)

#define SYS_AHBP_REG3_CPU1_SLEEPING_POS (2)
#define SYS_AHBP_REG3_CPU1_SLEEPING_MASK (0x1)

#define SYS_AHBP_REG3_CPU1_DEEPSLEEP_POS (3)
#define SYS_AHBP_REG3_CPU1_DEEPSLEEP_MASK (0x1)

#define SYS_AHBP_REG3_RESERVED_BIT_4_31_POS (4)
#define SYS_AHBP_REG3_RESERVED_BIT_4_31_MASK (0xfffffff)

#define SYS_AHBP_REG4_ADDR (SOC_SYS_AHBP_REG_BASE + (0x4 << 2))

#define SYS_AHBP_REG4_CPU0_SW_RSTN_POS (0)
#define SYS_AHBP_REG4_CPU0_SW_RSTN_MASK (0x1)

#define SYS_AHBP_REG4_CPU0_INIT_DTCM_EN_POS (1)
#define SYS_AHBP_REG4_CPU0_INIT_DTCM_EN_MASK (0x1)

#define SYS_AHBP_REG4_CPU0_SYS_NMI_POS (2)
#define SYS_AHBP_REG4_CPU0_SYS_NMI_MASK (0x1)

#define SYS_AHBP_REG4_CPU0_WFE_SRC_POS (3)
#define SYS_AHBP_REG4_CPU0_WFE_SRC_MASK (0x1)

#define SYS_AHBP_REG4_CPU0_WFE_PULSE_POS (4)
#define SYS_AHBP_REG4_CPU0_WFE_PULSE_MASK (0x1)

#define SYS_AHBP_REG4_CPU0_WAIT_POS (5)
#define SYS_AHBP_REG4_CPU0_WAIT_MASK (0x1)

#define SYS_AHBP_REG4_CPU0_DBG_RSTN_DISABLE_POS (6)
#define SYS_AHBP_REG4_CPU0_DBG_RSTN_DISABLE_MASK (0x1)

#define SYS_AHBP_REG4_RESERVED_7_7_POS (7)
#define SYS_AHBP_REG4_RESERVED_7_7_MASK (0x1)

#define SYS_AHBP_REG4_CPU0_OFFSET_POS (8)
#define SYS_AHBP_REG4_CPU0_OFFSET_MASK (0xffffff)

#define SYS_AHBP_REG5_ADDR (SOC_SYS_AHBP_REG_BASE + (0x5 << 2))

#define SYS_AHBP_REG5_CPU1_SW_RSTN_POS (0)
#define SYS_AHBP_REG5_CPU1_SW_RSTN_MASK (0x1)

#define SYS_AHBP_REG5_CPU1_INIT_DTCM_EN_POS (1)
#define SYS_AHBP_REG5_CPU1_INIT_DTCM_EN_MASK (0x1)

#define SYS_AHBP_REG5_CPU1_SYS_NMI_POS (2)
#define SYS_AHBP_REG5_CPU1_SYS_NMI_MASK (0x1)

#define SYS_AHBP_REG5_CPU1_WFE_SRC_POS (3)
#define SYS_AHBP_REG5_CPU1_WFE_SRC_MASK (0x1)

#define SYS_AHBP_REG5_CPU1_WFE_PULSE_POS (4)
#define SYS_AHBP_REG5_CPU1_WFE_PULSE_MASK (0x1)

#define SYS_AHBP_REG5_CPU1_WAIT_POS (5)
#define SYS_AHBP_REG5_CPU1_WAIT_MASK (0x1)

#define SYS_AHBP_REG5_CPU1_DBG_RSTN_DISABLE_POS (6)
#define SYS_AHBP_REG5_CPU1_DBG_RSTN_DISABLE_MASK (0x1)

#define SYS_AHBP_REG5_RESERVED_7_7_POS (7)
#define SYS_AHBP_REG5_RESERVED_7_7_MASK (0x1)

#define SYS_AHBP_REG5_CPU1_OFFSET_POS (8)
#define SYS_AHBP_REG5_CPU1_OFFSET_MASK (0xffffff)

#define SYS_AHBP_REG6_ADDR (SOC_SYS_AHBP_REG_BASE + (0x6 << 2))

#define SYS_AHBP_REG6_NPU_SW_RSTN_POS (0)
#define SYS_AHBP_REG6_NPU_SW_RSTN_MASK (0x1)

#define SYS_AHBP_REG6_NPU_CLKBPS_POS (1)
#define SYS_AHBP_REG6_NPU_CLKBPS_MASK (0x1)

#define SYS_AHBP_REG6_AXI0_AWCACHE_POS (2)
#define SYS_AHBP_REG6_AXI0_AWCACHE_MASK (0xf)

#define SYS_AHBP_REG6_AXI0_ARCACHE_POS (6)
#define SYS_AHBP_REG6_AXI0_ARCACHE_MASK (0xf)

#define SYS_AHBP_REG6_AXI1_AWCACHE_POS (10)
#define SYS_AHBP_REG6_AXI1_AWCACHE_MASK (0xf)

#define SYS_AHBP_REG6_AXI1_ARCACHE_POS (14)
#define SYS_AHBP_REG6_AXI1_ARCACHE_MASK (0xf)

#define SYS_AHBP_REG6_CACHE_SRC_POS (18)
#define SYS_AHBP_REG6_CACHE_SRC_MASK (0x1)

#define SYS_AHBP_REG6_RESERVED_19_31_POS (19)
#define SYS_AHBP_REG6_RESERVED_19_31_MASK (0x1fff)

#define SYS_AHBP_REG7_ADDR (SOC_SYS_AHBP_REG_BASE + (0x7 << 2))

#define SYS_AHBP_REG7_PSRAM_INV_CONFIG_POS (0)
#define SYS_AHBP_REG7_PSRAM_INV_CONFIG_MASK (0x3)

#define SYS_AHBP_REG7_VIDEOPOST_M_ARCACHE_POS (2)
#define SYS_AHBP_REG7_VIDEOPOST_M_ARCACHE_MASK (0xf)

#define SYS_AHBP_REG7_VIDEOPOST_M_AWCACHE_POS (6)
#define SYS_AHBP_REG7_VIDEOPOST_M_AWCACHE_MASK (0xf)

#define SYS_AHBP_REG7_RESERVED_10_15_POS (10)
#define SYS_AHBP_REG7_RESERVED_10_15_MASK (0x3f)

#define SYS_AHBP_REG7_ICACHE_CLEAN_MODE_POS (16)
#define SYS_AHBP_REG7_ICACHE_CLEAN_MODE_MASK (0x1)

#define SYS_AHBP_REG7_CPU0_ICACHE_CLEAN_MODE_POS (17)
#define SYS_AHBP_REG7_CPU0_ICACHE_CLEAN_MODE_MASK (0x1)

#define SYS_AHBP_REG7_CPU0_ICACHE_CLEAN_TAG_SEL_POS (18)
#define SYS_AHBP_REG7_CPU0_ICACHE_CLEAN_TAG_SEL_MASK (0x1)

#define SYS_AHBP_REG7_CPU1_ICACHE_CLEAN_MODE_POS (19)
#define SYS_AHBP_REG7_CPU1_ICACHE_CLEAN_MODE_MASK (0x1)

#define SYS_AHBP_REG7_CPU1_ICACHE_CLEAN_TAG_SEL_POS (20)
#define SYS_AHBP_REG7_CPU1_ICACHE_CLEAN_TAG_SEL_MASK (0x1)

#define SYS_AHBP_REG7_RESERVED_21_23_POS (21)
#define SYS_AHBP_REG7_RESERVED_21_23_MASK (0x7)

#define SYS_AHBP_REG7_ICACHE_CLEAN_KEY_POS (24)
#define SYS_AHBP_REG7_ICACHE_CLEAN_KEY_MASK (0xff)

#define SYS_AHBP_REG8_ADDR (SOC_SYS_AHBP_REG_BASE + (0x8 << 2))

#define SYS_AHBP_REG8_CKSEL_CORE_POS (0)
#define SYS_AHBP_REG8_CKSEL_CORE_MASK (0x3)

#define SYS_AHBP_REG8_CKDIV_CORE_POS (2)
#define SYS_AHBP_REG8_CKDIV_CORE_MASK (0x3)

#define SYS_AHBP_REG8_CKDIV_BUS_LS_POS (4)
#define SYS_AHBP_REG8_CKDIV_BUS_LS_MASK (0x1)

#define SYS_AHBP_REG8_RESERVED_5_5_POS (5)
#define SYS_AHBP_REG8_RESERVED_5_5_MASK (0x1)

#define SYS_AHBP_REG8_CKDIV_UART4_POS (6)
#define SYS_AHBP_REG8_CKDIV_UART4_MASK (0xf)

#define SYS_AHBP_REG8_CKSEL_QSPI0_POS (10)
#define SYS_AHBP_REG8_CKSEL_QSPI0_MASK (0x1)

#define SYS_AHBP_REG8_CKDIV_QSPI0_POS (11)
#define SYS_AHBP_REG8_CKDIV_QSPI0_MASK (0xf)

#define SYS_AHBP_REG8_CKSEL_QSPI1_POS (15)
#define SYS_AHBP_REG8_CKSEL_QSPI1_MASK (0x1)

#define SYS_AHBP_REG8_CKDIV_QSPI1_POS (16)
#define SYS_AHBP_REG8_CKDIV_QSPI1_MASK (0xf)

#define SYS_AHBP_REG8_CKSEL_PRAM0_POS (20)
#define SYS_AHBP_REG8_CKSEL_PRAM0_MASK (0x3)

#define SYS_AHBP_REG8_CKDIV_PRAM0_POS (22)
#define SYS_AHBP_REG8_CKDIV_PRAM0_MASK (0x1)

#define SYS_AHBP_REG8_CKSEL_MBIST_POS (23)
#define SYS_AHBP_REG8_CKSEL_MBIST_MASK (0x1)

#define SYS_AHBP_REG8_CKDIV_SDIO0_POS (24)
#define SYS_AHBP_REG8_CKDIV_SDIO0_MASK (0xf)

#define SYS_AHBP_REG8_CKDIV_SDIO1_POS (28)
#define SYS_AHBP_REG8_CKDIV_SDIO1_MASK (0xf)

#define SYS_AHBP_REG9_ADDR (SOC_SYS_AHBP_REG_BASE + (0x9 << 2))

#define SYS_AHBP_REG9_CKSEL_CIS_MCLK_POS (0)
#define SYS_AHBP_REG9_CKSEL_CIS_MCLK_MASK (0x3)

#define SYS_AHBP_REG9_CKDIV_CIS_MCLK_POS (2)
#define SYS_AHBP_REG9_CKDIV_CIS_MCLK_MASK (0xf)

#define SYS_AHBP_REG9_CKDIV_CIS_AUXS_POS (6)
#define SYS_AHBP_REG9_CKDIV_CIS_AUXS_MASK (0xf)

#define SYS_AHBP_REG9_CKSEL_CISP_POS (10)
#define SYS_AHBP_REG9_CKSEL_CISP_MASK (0x1)

#define SYS_AHBP_REG9_CKDIV_CISP_POS (11)
#define SYS_AHBP_REG9_CKDIV_CISP_MASK (0x3)

#define SYS_AHBP_REG9_CKSEL_GPU_POS (13)
#define SYS_AHBP_REG9_CKSEL_GPU_MASK (0x1)

#define SYS_AHBP_REG9_CKDIV_GPU_POS (14)
#define SYS_AHBP_REG9_CKDIV_GPU_MASK (0x3)

#define SYS_AHBP_REG9_CKSEL_H265_POS (16)
#define SYS_AHBP_REG9_CKSEL_H265_MASK (0x1)

#define SYS_AHBP_REG9_CKDIV_H265_POS (17)
#define SYS_AHBP_REG9_CKDIV_H265_MASK (0x3)

#define SYS_AHBP_REG9_CKSEL_DPU_POS (19)
#define SYS_AHBP_REG9_CKSEL_DPU_MASK (0x1)

#define SYS_AHBP_REG9_CKDIV_DPU_POS (20)
#define SYS_AHBP_REG9_CKDIV_DPU_MASK (0x1f)

#define SYS_AHBP_REG9_CKSEL_PRAM1_POS (25)
#define SYS_AHBP_REG9_CKSEL_PRAM1_MASK (0x3)

#define SYS_AHBP_REG9_CKDIV_PRAM1_POS (27)
#define SYS_AHBP_REG9_CKDIV_PRAM1_MASK (0x1)

#define SYS_AHBP_REG9_CKDIV_TRACE_POS (28)
#define SYS_AHBP_REG9_CKDIV_TRACE_MASK (0x3)

#define SYS_AHBP_REG9_CKSEL_CIS_AUXS_POS (30)
#define SYS_AHBP_REG9_CKSEL_CIS_AUXS_MASK (0x3)

#define SYS_AHBP_REGA_ADDR (SOC_SYS_AHBP_REG_BASE + (0xa << 2))

#define SYS_AHBP_REGA_CPUA_CKEN_POS (0)
#define SYS_AHBP_REGA_CPUA_CKEN_MASK (0x1)

#define SYS_AHBP_REGA_UART5_CKEN_POS (1)
#define SYS_AHBP_REGA_UART5_CKEN_MASK (0x1)

#define SYS_AHBP_REGA_USB_HS_CKEN_POS (2)
#define SYS_AHBP_REGA_USB_HS_CKEN_MASK (0x1)

#define SYS_AHBP_REGA_PRAM0_CKEN_POS (3)
#define SYS_AHBP_REGA_PRAM0_CKEN_MASK (0x1)

#define SYS_AHBP_REGA_PRAM1_CKEN_POS (4)
#define SYS_AHBP_REGA_PRAM1_CKEN_MASK (0x1)

#define SYS_AHBP_REGA_QSPI0_CKEN_POS (5)
#define SYS_AHBP_REGA_QSPI0_CKEN_MASK (0x1)

#define SYS_AHBP_REGA_QSPI1_CKEN_POS (6)
#define SYS_AHBP_REGA_QSPI1_CKEN_MASK (0x1)

#define SYS_AHBP_REGA_SDIO0_CKEN_POS (7)
#define SYS_AHBP_REGA_SDIO0_CKEN_MASK (0x1)

#define SYS_AHBP_REGA_SDIO1_CKEN_POS (8)
#define SYS_AHBP_REGA_SDIO1_CKEN_MASK (0x1)

#define SYS_AHBP_REGA_CISP_CKEN_POS (9)
#define SYS_AHBP_REGA_CISP_CKEN_MASK (0x1)

#define SYS_AHBP_REGA_GPU_CKEN_POS (10)
#define SYS_AHBP_REGA_GPU_CKEN_MASK (0x1)

#define SYS_AHBP_REGA_H26E_CKEN_POS (11)
#define SYS_AHBP_REGA_H26E_CKEN_MASK (0x1)

#define SYS_AHBP_REGA_CSI_CKEN_POS (12)
#define SYS_AHBP_REGA_CSI_CKEN_MASK (0x1)

#define SYS_AHBP_REGA_DSI_CKEN_POS (13)
#define SYS_AHBP_REGA_DSI_CKEN_MASK (0x1)

#define SYS_AHBP_REGA_DPU_CKEN_POS (14)
#define SYS_AHBP_REGA_DPU_CKEN_MASK (0x1)

#define SYS_AHBP_REGA_USB_FS_CKEN_POS (15)
#define SYS_AHBP_REGA_USB_FS_CKEN_MASK (0x1)

#define SYS_AHBP_REGA_CONF0_CKEN_POS (16)
#define SYS_AHBP_REGA_CONF0_CKEN_MASK (0x1)

#define SYS_AHBP_REGA_CONF1_CKEN_POS (17)
#define SYS_AHBP_REGA_CONF1_CKEN_MASK (0x1)

#define SYS_AHBP_REGA_CONF2_CKEN_POS (18)
#define SYS_AHBP_REGA_CONF2_CKEN_MASK (0x1)

#define SYS_AHBP_REGA_CONF3_CKEN_POS (19)
#define SYS_AHBP_REGA_CONF3_CKEN_MASK (0x1)

#define SYS_AHBP_REGA_CPU0_CKEN_POS (20)
#define SYS_AHBP_REGA_CPU0_CKEN_MASK (0x1)

#define SYS_AHBP_REGA_CPU1_CKEN_POS (21)
#define SYS_AHBP_REGA_CPU1_CKEN_MASK (0x1)

#define SYS_AHBP_REGA_NPU_CKEN_POS (22)
#define SYS_AHBP_REGA_NPU_CKEN_MASK (0x1)

#define SYS_AHBP_REGA_TIMER4_CKEN_POS (23)
#define SYS_AHBP_REGA_TIMER4_CKEN_MASK (0x1)

#define SYS_AHBP_REGA_TIMER5_CKEN_POS (24)
#define SYS_AHBP_REGA_TIMER5_CKEN_MASK (0x1)

#define SYS_AHBP_REGA_TRACE_CKEN_POS (25)
#define SYS_AHBP_REGA_TRACE_CKEN_MASK (0x1)

#define SYS_AHBP_REGA_RESERVED_26_31_POS (26)
#define SYS_AHBP_REGA_RESERVED_26_31_MASK (0x3f)

#define SYS_AHBP_REGB_ADDR (SOC_SYS_AHBP_REG_BASE + (0xb << 2))

#define SYS_AHBP_REGB_PHASE_CK640_POS (0)
#define SYS_AHBP_REGB_PHASE_CK640_MASK (0xff)

#define SYS_AHBP_REGB_RESERVED_8_31_POS (8)
#define SYS_AHBP_REGB_RESERVED_8_31_MASK (0xffffff)

#define SYS_AHBP_REGC_ADDR (SOC_SYS_AHBP_REG_BASE + (0xc << 2))

#define SYS_AHBP_REGC_CPU0_MEM_SD_POS (0)
#define SYS_AHBP_REGC_CPU0_MEM_SD_MASK (0x1)

#define SYS_AHBP_REGC_CPU1_MEM_SD_POS (1)
#define SYS_AHBP_REGC_CPU1_MEM_SD_MASK (0x1)

#define SYS_AHBP_REGC_DTCM_MEM_SD_POS (2)
#define SYS_AHBP_REGC_DTCM_MEM_SD_MASK (0x1)

#define SYS_AHBP_REGC_L2CH_MEM_SD_POS (3)
#define SYS_AHBP_REGC_L2CH_MEM_SD_MASK (0x1)

#define SYS_AHBP_REGC_MEM3_MEM_SD_POS (4)
#define SYS_AHBP_REGC_MEM3_MEM_SD_MASK (0x1)

#define SYS_AHBP_REGC_MEM4_MEM_SD_POS (5)
#define SYS_AHBP_REGC_MEM4_MEM_SD_MASK (0x1)

#define SYS_AHBP_REGC_MEM5_MEM_SD_POS (6)
#define SYS_AHBP_REGC_MEM5_MEM_SD_MASK (0x1)

#define SYS_AHBP_REGC_MEM6_MEM_SD_POS (7)
#define SYS_AHBP_REGC_MEM6_MEM_SD_MASK (0x1)

#define SYS_AHBP_REGC_AHBP_MEM_SD_POS (8)
#define SYS_AHBP_REGC_AHBP_MEM_SD_MASK (0x1)

#define SYS_AHBP_REGC_H265_MEM_SD_POS (9)
#define SYS_AHBP_REGC_H265_MEM_SD_MASK (0x1)

#define SYS_AHBP_REGC_GPUB_MEM_SD_POS (10)
#define SYS_AHBP_REGC_GPUB_MEM_SD_MASK (0x1)

#define SYS_AHBP_REGC_DPUB_MEM_SD_POS (11)
#define SYS_AHBP_REGC_DPUB_MEM_SD_MASK (0x1)

#define SYS_AHBP_REGC_DISB_MEM_SD_POS (12)
#define SYS_AHBP_REGC_DISB_MEM_SD_MASK (0x1)

#define SYS_AHBP_REGC_H264_MEM_SD_POS (13)
#define SYS_AHBP_REGC_H264_MEM_SD_MASK (0x1)

#define SYS_AHBP_REGC_ISPB_MEM_SD_POS (14)
#define SYS_AHBP_REGC_ISPB_MEM_SD_MASK (0x1)

#define SYS_AHBP_REGC_CSIB_MEM_SD_POS (15)
#define SYS_AHBP_REGC_CSIB_MEM_SD_MASK (0x1)

#define SYS_AHBP_REGC_NPUB_MEM_SD_POS (16)
#define SYS_AHBP_REGC_NPUB_MEM_SD_MASK (0x1)

#define SYS_AHBP_REGC_RESERVED_17_31_POS (17)
#define SYS_AHBP_REGC_RESERVED_17_31_MASK (0x7fff)

#define SYS_AHBP_REGD_ADDR (SOC_SYS_AHBP_REG_BASE + (0xd << 2))

#define SYS_AHBP_REGD_CPU0_MEM_DS_POS (0)
#define SYS_AHBP_REGD_CPU0_MEM_DS_MASK (0x1)

#define SYS_AHBP_REGD_CPU1_MEM_DS_POS (1)
#define SYS_AHBP_REGD_CPU1_MEM_DS_MASK (0x1)

#define SYS_AHBP_REGD_DTCM_MEM_DS_POS (2)
#define SYS_AHBP_REGD_DTCM_MEM_DS_MASK (0x1)

#define SYS_AHBP_REGD_L2CH_MEM_DS_POS (3)
#define SYS_AHBP_REGD_L2CH_MEM_DS_MASK (0x1)

#define SYS_AHBP_REGD_MEM3_MEM_DS_POS (4)
#define SYS_AHBP_REGD_MEM3_MEM_DS_MASK (0x1)

#define SYS_AHBP_REGD_MEM4_MEM_DS_POS (5)
#define SYS_AHBP_REGD_MEM4_MEM_DS_MASK (0x1)

#define SYS_AHBP_REGD_MEM5_MEM_DS_POS (6)
#define SYS_AHBP_REGD_MEM5_MEM_DS_MASK (0x1)

#define SYS_AHBP_REGD_MEM6_MEM_DS_POS (7)
#define SYS_AHBP_REGD_MEM6_MEM_DS_MASK (0x1)

#define SYS_AHBP_REGD_AHBP_MEM_DS_POS (8)
#define SYS_AHBP_REGD_AHBP_MEM_DS_MASK (0x1)

#define SYS_AHBP_REGD_H265_MEM_DS_POS (9)
#define SYS_AHBP_REGD_H265_MEM_DS_MASK (0x1)

#define SYS_AHBP_REGD_GPUB_MEM_DS_POS (10)
#define SYS_AHBP_REGD_GPUB_MEM_DS_MASK (0x1)

#define SYS_AHBP_REGD_DPUB_MEM_DS_POS (11)
#define SYS_AHBP_REGD_DPUB_MEM_DS_MASK (0x1)

#define SYS_AHBP_REGD_DISB_MEM_DS_POS (12)
#define SYS_AHBP_REGD_DISB_MEM_DS_MASK (0x1)

#define SYS_AHBP_REGD_H264_MEM_DS_POS (13)
#define SYS_AHBP_REGD_H264_MEM_DS_MASK (0x1)

#define SYS_AHBP_REGD_ISPB_MEM_DS_POS (14)
#define SYS_AHBP_REGD_ISPB_MEM_DS_MASK (0x1)

#define SYS_AHBP_REGD_CSIB_MEM_DS_POS (15)
#define SYS_AHBP_REGD_CSIB_MEM_DS_MASK (0x1)

#define SYS_AHBP_REGD_NPUB_MEM_DS_POS (16)
#define SYS_AHBP_REGD_NPUB_MEM_DS_MASK (0x1)

#define SYS_AHBP_REGD_RESERVED_17_31_POS (17)
#define SYS_AHBP_REGD_RESERVED_17_31_MASK (0x7fff)

#define SYS_AHBP_REGE_ADDR (SOC_SYS_AHBP_REG_BASE + (0xe << 2))

#define SYS_AHBP_REGE_SYSTEM_HALT_EN_POS (0)
#define SYS_AHBP_REGE_SYSTEM_HALT_EN_MASK (0x1)

#define SYS_AHBP_REGE_SYSTEM_HALT_HIGH_CPU0WFI_POS (1)
#define SYS_AHBP_REGE_SYSTEM_HALT_HIGH_CPU0WFI_MASK (0x1)

#define SYS_AHBP_REGE_SYSTEM_HALT_HIGH_CPU1WFI_POS (2)
#define SYS_AHBP_REGE_SYSTEM_HALT_HIGH_CPU1WFI_MASK (0x1)

#define SYS_AHBP_REGE_RESERVED_3_7_POS (3)
#define SYS_AHBP_REGE_RESERVED_3_7_MASK (0x1f)

#define SYS_AHBP_REGE_CPU_HALT_EN_POS (8)
#define SYS_AHBP_REGE_CPU_HALT_EN_MASK (0x1)

#define SYS_AHBP_REGE_CPU_HALT_HIGH_CPU0WFI_POS (9)
#define SYS_AHBP_REGE_CPU_HALT_HIGH_CPU0WFI_MASK (0x1)

#define SYS_AHBP_REGE_CPU_HALT_HIGH_CPU1WFI_POS (10)
#define SYS_AHBP_REGE_CPU_HALT_HIGH_CPU1WFI_MASK (0x1)

#define SYS_AHBP_REGE_RESERVED_11_15_POS (11)
#define SYS_AHBP_REGE_RESERVED_11_15_MASK (0x1f)

#define SYS_AHBP_REGE_PWD_M55_POS (16)
#define SYS_AHBP_REGE_PWD_M55_MASK (0x1)

#define SYS_AHBP_REGE_PWD_VIDEO_POST_POS (17)
#define SYS_AHBP_REGE_PWD_VIDEO_POST_MASK (0x1)

#define SYS_AHBP_REGE_PWD_H26E_POS (18)
#define SYS_AHBP_REGE_PWD_H26E_MASK (0x1)

#define SYS_AHBP_REGE_PWD_ISP_POS (19)
#define SYS_AHBP_REGE_PWD_ISP_MASK (0x1)

#define SYS_AHBP_REGE_PWD_NPU_POS (20)
#define SYS_AHBP_REGE_PWD_NPU_MASK (0x1)

#define SYS_AHBP_REGE_RESERVED_21_23_POS (21)
#define SYS_AHBP_REGE_RESERVED_21_23_MASK (0x7)

#define SYS_AHBP_REGE_SOFT_RSTN_ISP_POS (24)
#define SYS_AHBP_REGE_SOFT_RSTN_ISP_MASK (0x1)

#define SYS_AHBP_REGE_SOFT_RSTN_H264E_POS (25)
#define SYS_AHBP_REGE_SOFT_RSTN_H264E_MASK (0x1)

#define SYS_AHBP_REGE_SOFT_RSTN_H264D_POS (26)
#define SYS_AHBP_REGE_SOFT_RSTN_H264D_MASK (0x1)

#define SYS_AHBP_REGE_SOFT_RSTN_GPU_POS (27)
#define SYS_AHBP_REGE_SOFT_RSTN_GPU_MASK (0x1)

#define SYS_AHBP_REGE_SOFT_RSTN_DPU_POS (28)
#define SYS_AHBP_REGE_SOFT_RSTN_DPU_MASK (0x1)

#define SYS_AHBP_REGE_RESERVED_29_31_POS (29)
#define SYS_AHBP_REGE_RESERVED_29_31_MASK (0x7)

#define SYS_AHBP_REGF_ADDR (SOC_SYS_AHBP_REG_BASE + (0xf << 2))

#define SYS_AHBP_REGF_WWDT_REGION_WWDT_POS (0)
#define SYS_AHBP_REGF_WWDT_REGION_WWDT_MASK (0x1)

#define SYS_AHBP_REGF_WWDT_REGION_SYS_CFG_POS (1)
#define SYS_AHBP_REGF_WWDT_REGION_SYS_CFG_MASK (0x1)

#define SYS_AHBP_REGF_WWDT_REGION_BUSX_POS (2)
#define SYS_AHBP_REGF_WWDT_REGION_BUSX_MASK (0x1)

#define SYS_AHBP_REGF_WWDT_REGION_CPU0_POS (3)
#define SYS_AHBP_REGF_WWDT_REGION_CPU0_MASK (0x1)

#define SYS_AHBP_REGF_WWDT_REGION_CPU1_POS (4)
#define SYS_AHBP_REGF_WWDT_REGION_CPU1_MASK (0x1)

#define SYS_AHBP_REGF_WWDT_REGION_AHBP_POS (5)
#define SYS_AHBP_REGF_WWDT_REGION_AHBP_MASK (0x1)

#define SYS_AHBP_REGF_WWDT_REGION_SMEM3_POS (6)
#define SYS_AHBP_REGF_WWDT_REGION_SMEM3_MASK (0x1)

#define SYS_AHBP_REGF_WWDT_REGION_SMEM4_POS (7)
#define SYS_AHBP_REGF_WWDT_REGION_SMEM4_MASK (0x1)

#define SYS_AHBP_REGF_WWDT_REGION_SMEM5_POS (8)
#define SYS_AHBP_REGF_WWDT_REGION_SMEM5_MASK (0x1)

#define SYS_AHBP_REGF_WWDT_REGION_SMEM6_POS (9)
#define SYS_AHBP_REGF_WWDT_REGION_SMEM6_MASK (0x1)

#define SYS_AHBP_REGF_WWDT_REGION_NPU_POS (10)
#define SYS_AHBP_REGF_WWDT_REGION_NPU_MASK (0x1)

#define SYS_AHBP_REGF_WWDT_REGION_H26E_POS (11)
#define SYS_AHBP_REGF_WWDT_REGION_H26E_MASK (0x1)

#define SYS_AHBP_REGF_WWDT_REGION_ISP_POS (12)
#define SYS_AHBP_REGF_WWDT_REGION_ISP_MASK (0x1)

#define SYS_AHBP_REGF_WWDT_REGION_VIDEO_POST_POS (13)
#define SYS_AHBP_REGF_WWDT_REGION_VIDEO_POST_MASK (0x1)

#define SYS_AHBP_REGF_RESERVED_14_31_POS (14)
#define SYS_AHBP_REGF_RESERVED_14_31_MASK (0x3ffff)

#define SYS_AHBP_REG10_ADDR (SOC_SYS_AHBP_REG_BASE + (0x10 << 2))

#define SYS_AHBP_REG10_INTS_CONFIG_M55A_0_POS (0)
#define SYS_AHBP_REG10_INTS_CONFIG_M55A_0_MASK (0xffffffff)

#define SYS_AHBP_REG11_ADDR (SOC_SYS_AHBP_REG_BASE + (0x11 << 2))

#define SYS_AHBP_REG11_INTS_CONFIG_M55A_1_POS (0)
#define SYS_AHBP_REG11_INTS_CONFIG_M55A_1_MASK (0xffffffff)

#define SYS_AHBP_REG12_ADDR (SOC_SYS_AHBP_REG_BASE + (0x12 << 2))

#define SYS_AHBP_REG12_INTS_CONFIG_M55B_0_POS (0)
#define SYS_AHBP_REG12_INTS_CONFIG_M55B_0_MASK (0xffffffff)

#define SYS_AHBP_REG13_ADDR (SOC_SYS_AHBP_REG_BASE + (0x13 << 2))

#define SYS_AHBP_REG13_INTS_CONFIG_M55B_1_POS (0)
#define SYS_AHBP_REG13_INTS_CONFIG_M55B_1_MASK (0xffffffff)

#define SYS_AHBP_REG14_ADDR (SOC_SYS_AHBP_REG_BASE + (0x14 << 2))

#define SYS_AHBP_REG14_INTS_CONFIG_M52S_0_POS (0)
#define SYS_AHBP_REG14_INTS_CONFIG_M52S_0_MASK (0xffffffff)

#define SYS_AHBP_REG15_ADDR (SOC_SYS_AHBP_REG_BASE + (0x15 << 2))

#define SYS_AHBP_REG15_INTS_CONFIG_M52S_1_POS (0)
#define SYS_AHBP_REG15_INTS_CONFIG_M52S_1_MASK (0xffffffff)

#define SYS_AHBP_REG16_ADDR (SOC_SYS_AHBP_REG_BASE + (0x16 << 2))

#define SYS_AHBP_REG16_INTS_CONFIG_SCR1_0_POS (0)
#define SYS_AHBP_REG16_INTS_CONFIG_SCR1_0_MASK (0xffffffff)

#define SYS_AHBP_REG17_ADDR (SOC_SYS_AHBP_REG_BASE + (0x17 << 2))

#define SYS_AHBP_REG17_INTS_CONFIG_SCR1_1_POS (0)
#define SYS_AHBP_REG17_INTS_CONFIG_SCR1_1_MASK (0xffffffff)

#define SYS_AHBP_REG18_ADDR (SOC_SYS_AHBP_REG_BASE + (0x18 << 2))

#define SYS_AHBP_REG18_INTS_STATUS_M55A_0_POS (0)
#define SYS_AHBP_REG18_INTS_STATUS_M55A_0_MASK (0xffffffff)

#define SYS_AHBP_REG19_ADDR (SOC_SYS_AHBP_REG_BASE + (0x19 << 2))

#define SYS_AHBP_REG19_INTS_STATUS_M55A_1_POS (0)
#define SYS_AHBP_REG19_INTS_STATUS_M55A_1_MASK (0xffffffff)

#define SYS_AHBP_REG1A_ADDR (SOC_SYS_AHBP_REG_BASE + (0x1a << 2))

#define SYS_AHBP_REG1A_INTS_STATUS_M55B_0_POS (0)
#define SYS_AHBP_REG1A_INTS_STATUS_M55B_0_MASK (0xffffffff)

#define SYS_AHBP_REG1B_ADDR (SOC_SYS_AHBP_REG_BASE + (0x1b << 2))

#define SYS_AHBP_REG1B_INTS_STATUS_M55B_1_POS (0)
#define SYS_AHBP_REG1B_INTS_STATUS_M55B_1_MASK (0xffffffff)

#define SYS_AHBP_REG1C_ADDR (SOC_SYS_AHBP_REG_BASE + (0x1c << 2))

#define SYS_AHBP_REG1C_INTS_STATUS_M52S_0_POS (0)
#define SYS_AHBP_REG1C_INTS_STATUS_M52S_0_MASK (0xffffffff)

#define SYS_AHBP_REG1D_ADDR (SOC_SYS_AHBP_REG_BASE + (0x1d << 2))

#define SYS_AHBP_REG1D_INTS_STATUS_M52S_1_POS (0)
#define SYS_AHBP_REG1D_INTS_STATUS_M52S_1_MASK (0xffffffff)

#define SYS_AHBP_REG1E_ADDR (SOC_SYS_AHBP_REG_BASE + (0x1e << 2))

#define SYS_AHBP_REG1E_INTS_STATUS_SCR1_0_POS (0)
#define SYS_AHBP_REG1E_INTS_STATUS_SCR1_0_MASK (0xffffffff)

#define SYS_AHBP_REG1F_ADDR (SOC_SYS_AHBP_REG_BASE + (0x1f << 2))

#define SYS_AHBP_REG1F_INTS_STATUS_SCR1_1_POS (0)
#define SYS_AHBP_REG1F_INTS_STATUS_SCR1_1_MASK (0xffffffff)

#define SYS_AHBP_REG20_ADDR (SOC_SYS_AHBP_REG_BASE + (0x20 << 2))

#define SYS_AHBP_REG20_CPU0_QOS_POS (0)
#define SYS_AHBP_REG20_CPU0_QOS_MASK (0x3)

#define SYS_AHBP_REG20_DMA1_QOS_POS (2)
#define SYS_AHBP_REG20_DMA1_QOS_MASK (0x3)

#define SYS_AHBP_REG20_SDIO0_QOS_POS (4)
#define SYS_AHBP_REG20_SDIO0_QOS_MASK (0x3)

#define SYS_AHBP_REG20_SDIO1_QOS_POS (6)
#define SYS_AHBP_REG20_SDIO1_QOS_MASK (0x3)

#define SYS_AHBP_REG20_ENET0_QOS_POS (8)
#define SYS_AHBP_REG20_ENET0_QOS_MASK (0x3)

#define SYS_AHBP_REG20_ENET1_QOS_POS (10)
#define SYS_AHBP_REG20_ENET1_QOS_MASK (0x3)

#define SYS_AHBP_REG20_USB_QOS_POS (12)
#define SYS_AHBP_REG20_USB_QOS_MASK (0x3)

#define SYS_AHBP_REG20_H26E_QOS_POS (14)
#define SYS_AHBP_REG20_H26E_QOS_MASK (0x3)

#define SYS_AHBP_REG20_ISP_QOS_POS (16)
#define SYS_AHBP_REG20_ISP_QOS_MASK (0x3)

#define SYS_AHBP_REG20_VIDEOPOST_QOS_POS (18)
#define SYS_AHBP_REG20_VIDEOPOST_QOS_MASK (0x3)

#define SYS_AHBP_REG20_DPU_QOS_POS (20)
#define SYS_AHBP_REG20_DPU_QOS_MASK (0x3)

#define SYS_AHBP_REG20_CBUS_QOS_POS (22)
#define SYS_AHBP_REG20_CBUS_QOS_MASK (0x3)

#define SYS_AHBP_REG20_NPU0_QOS_POS (24)
#define SYS_AHBP_REG20_NPU0_QOS_MASK (0x3)

#define SYS_AHBP_REG20_NPU1_QOS_POS (26)
#define SYS_AHBP_REG20_NPU1_QOS_MASK (0x3)

#define SYS_AHBP_REG20_CPU1_QOS_POS (28)
#define SYS_AHBP_REG20_CPU1_QOS_MASK (0x3)

#define SYS_AHBP_REG20_RESERVED_30_31_POS (30)
#define SYS_AHBP_REG20_RESERVED_30_31_MASK (0x3)

#define SYS_AHBP_REG21_ADDR (SOC_SYS_AHBP_REG_BASE + (0x21 << 2))

#define SYS_AHBP_REG21_DPU_GATE_CPU_EN_POS (0)
#define SYS_AHBP_REG21_DPU_GATE_CPU_EN_MASK (0x1)

#define SYS_AHBP_REG21_DPU_GATE_VIDEOPOST_EN_POS (1)
#define SYS_AHBP_REG21_DPU_GATE_VIDEOPOST_EN_MASK (0x1)

#define SYS_AHBP_REG21_DPU_GATE_H26E_EN_POS (2)
#define SYS_AHBP_REG21_DPU_GATE_H26E_EN_MASK (0x1)

#define SYS_AHBP_REG21_RESERVED_3_7_POS (3)
#define SYS_AHBP_REG21_RESERVED_3_7_MASK (0x1f)

#define SYS_AHBP_REG21_RESERVED_8_8_POS (8)
#define SYS_AHBP_REG21_RESERVED_8_8_MASK (0x1)

#define SYS_AHBP_REG21_DPU_GATE_VIDEOPOST_OVERRIDE_POS (9)
#define SYS_AHBP_REG21_DPU_GATE_VIDEOPOST_OVERRIDE_MASK (0x1)

#define SYS_AHBP_REG21_DPU_GATE_H26E_OVERRIDE_POS (10)
#define SYS_AHBP_REG21_DPU_GATE_H26E_OVERRIDE_MASK (0x1)

#define SYS_AHBP_REG21_RESERVED_11_15_POS (11)
#define SYS_AHBP_REG21_RESERVED_11_15_MASK (0x1f)

#define SYS_AHBP_REG21_CPU_BUS_DIS_POS (16)
#define SYS_AHBP_REG21_CPU_BUS_DIS_MASK (0x1)

#define SYS_AHBP_REG21_VIDEOPOST_BUS_DIS_POS (17)
#define SYS_AHBP_REG21_VIDEOPOST_BUS_DIS_MASK (0x1)

#define SYS_AHBP_REG21_H26E_BUS_DIS_POS (18)
#define SYS_AHBP_REG21_H26E_BUS_DIS_MASK (0x1)

#define SYS_AHBP_REG21_RESERVED_19_23_POS (19)
#define SYS_AHBP_REG21_RESERVED_19_23_MASK (0x1f)

#define SYS_AHBP_REG21_DPU_GATE_KEY_POS (24)
#define SYS_AHBP_REG21_DPU_GATE_KEY_MASK (0xff)

#define SYS_AHBP_REG22_ADDR (SOC_SYS_AHBP_REG_BASE + (0x22 << 2))

#define SYS_AHBP_REG22_DBUG_CONFIG0_POS (0)
#define SYS_AHBP_REG22_DBUG_CONFIG0_MASK (0xffffffff)

#define SYS_AHBP_REG23_ADDR (SOC_SYS_AHBP_REG_BASE + (0x23 << 2))

#define SYS_AHBP_REG23_DBUG_MUX_POS (0)
#define SYS_AHBP_REG23_DBUG_MUX_MASK (0xf)

#define SYS_AHBP_REG23_DBUG_CONFIG1_POS (4)
#define SYS_AHBP_REG23_DBUG_CONFIG1_MASK (0xfffffff)

#define SYS_AHBP_REG24_ADDR (SOC_SYS_AHBP_REG_BASE + (0x24 << 2))

#define SYS_AHBP_REG24_TRACE_CONFIG_POS (0)
#define SYS_AHBP_REG24_TRACE_CONFIG_MASK (0xffffffff)

#define SYS_AHBP_REG25_ADDR (SOC_SYS_AHBP_REG_BASE + (0x25 << 2))

#define SYS_AHBP_REG25_GPIO_DBUG_READOUT_POS (0)
#define SYS_AHBP_REG25_GPIO_DBUG_READOUT_MASK (0xffffffff)

#define SYS_AHBP_REG26_ADDR (SOC_SYS_AHBP_REG_BASE + (0x26 << 2))

#define SYS_AHBP_REG26_GENERAL0_POS (0)
#define SYS_AHBP_REG26_GENERAL0_MASK (0xffffffff)

#define SYS_AHBP_REG27_ADDR (SOC_SYS_AHBP_REG_BASE + (0x27 << 2))

#define SYS_AHBP_REG27_GENERAL1_POS (0)
#define SYS_AHBP_REG27_GENERAL1_MASK (0xffffffff)

#define SYS_AHBP_REG28_ADDR (SOC_SYS_AHBP_REG_BASE + (0x28 << 2))

#define SYS_AHBP_REG28_GPU_BUFFA_ENABLE_POS (0)
#define SYS_AHBP_REG28_GPU_BUFFA_ENABLE_MASK (0x1)

#define SYS_AHBP_REG28_RESERVED_BIT_1_31_POS (1)
#define SYS_AHBP_REG28_RESERVED_BIT_1_31_MASK (0x7fffffff)

#define SYS_AHBP_REG29_ADDR (SOC_SYS_AHBP_REG_BASE + (0x29 << 2))

#define SYS_AHBP_REG29_GPU_BUFFA_BEGIN_POS (0)
#define SYS_AHBP_REG29_GPU_BUFFA_BEGIN_MASK (0xffffffff)

#define SYS_AHBP_REG2A_ADDR (SOC_SYS_AHBP_REG_BASE + (0x2a << 2))

#define SYS_AHBP_REG2A_GPU_BUFFA_SIZE_POS (0)
#define SYS_AHBP_REG2A_GPU_BUFFA_SIZE_MASK (0xffffffff)

#define SYS_AHBP_REG2B_ADDR (SOC_SYS_AHBP_REG_BASE + (0x2b << 2))

#define SYS_AHBP_REG2B_GPU_PICA_BEGIN_POS (0)
#define SYS_AHBP_REG2B_GPU_PICA_BEGIN_MASK (0xffffffff)

#define SYS_AHBP_REG2C_ADDR (SOC_SYS_AHBP_REG_BASE + (0x2c << 2))

#define SYS_AHBP_REG2C_GPU_PICA_HALFBUFF_END_POS (0)
#define SYS_AHBP_REG2C_GPU_PICA_HALFBUFF_END_MASK (0xffffffff)

#define SYS_AHBP_REG2D_ADDR (SOC_SYS_AHBP_REG_BASE + (0x2d << 2))

#define SYS_AHBP_REG2D_GPU_PICA_END_POS (0)
#define SYS_AHBP_REG2D_GPU_PICA_END_MASK (0xffffffff)

#define SYS_AHBP_REG2E_ADDR (SOC_SYS_AHBP_REG_BASE + (0x2e << 2))

#define SYS_AHBP_REG2E_RESERVED_0_31_POS (0)
#define SYS_AHBP_REG2E_RESERVED_0_31_MASK (0xffffffff)

#define SYS_AHBP_REG2F_ADDR (SOC_SYS_AHBP_REG_BASE + (0x2f << 2))

#define SYS_AHBP_REG2F_GPU_BUFFA_REMAP_ADDR_POS (0)
#define SYS_AHBP_REG2F_GPU_BUFFA_REMAP_ADDR_MASK (0xffffffff)

#define SYS_AHBP_REG30_ADDR (SOC_SYS_AHBP_REG_BASE + (0x30 << 2))

#define SYS_AHBP_REG30_GPU_BUFFB_ENABLE_POS (0)
#define SYS_AHBP_REG30_GPU_BUFFB_ENABLE_MASK (0x1)

#define SYS_AHBP_REG30_RESERVED_BIT_1_31_POS (1)
#define SYS_AHBP_REG30_RESERVED_BIT_1_31_MASK (0x7fffffff)

#define SYS_AHBP_REG31_ADDR (SOC_SYS_AHBP_REG_BASE + (0x31 << 2))

#define SYS_AHBP_REG31_GPU_BUFFB_BEGIN_POS (0)
#define SYS_AHBP_REG31_GPU_BUFFB_BEGIN_MASK (0xffffffff)

#define SYS_AHBP_REG32_ADDR (SOC_SYS_AHBP_REG_BASE + (0x32 << 2))

#define SYS_AHBP_REG32_GPU_BUFFB_SIZE_POS (0)
#define SYS_AHBP_REG32_GPU_BUFFB_SIZE_MASK (0xffffffff)

#define SYS_AHBP_REG33_ADDR (SOC_SYS_AHBP_REG_BASE + (0x33 << 2))

#define SYS_AHBP_REG33_GPU_PICB_BEGIN_POS (0)
#define SYS_AHBP_REG33_GPU_PICB_BEGIN_MASK (0xffffffff)

#define SYS_AHBP_REG34_ADDR (SOC_SYS_AHBP_REG_BASE + (0x34 << 2))

#define SYS_AHBP_REG34_GPU_PICB_HALFBUFF_END_POS (0)
#define SYS_AHBP_REG34_GPU_PICB_HALFBUFF_END_MASK (0xffffffff)

#define SYS_AHBP_REG35_ADDR (SOC_SYS_AHBP_REG_BASE + (0x35 << 2))

#define SYS_AHBP_REG35_GPU_PICB_END_POS (0)
#define SYS_AHBP_REG35_GPU_PICB_END_MASK (0xffffffff)

#define SYS_AHBP_REG36_ADDR (SOC_SYS_AHBP_REG_BASE + (0x36 << 2))

#define SYS_AHBP_REG36_RESERVED_0_31_POS (0)
#define SYS_AHBP_REG36_RESERVED_0_31_MASK (0xffffffff)

#define SYS_AHBP_REG37_ADDR (SOC_SYS_AHBP_REG_BASE + (0x37 << 2))

#define SYS_AHBP_REG37_GPU_BUFFB_REMAP_ADDR_POS (0)
#define SYS_AHBP_REG37_GPU_BUFFB_REMAP_ADDR_MASK (0xffffffff)

#define SYS_AHBP_REG38_ADDR (SOC_SYS_AHBP_REG_BASE + (0x38 << 2))

#define SYS_AHBP_REG38_H26D_BUFFA_ENABLE_POS (0)
#define SYS_AHBP_REG38_H26D_BUFFA_ENABLE_MASK (0x1)

#define SYS_AHBP_REG38_RESERVED_BIT_1_31_POS (1)
#define SYS_AHBP_REG38_RESERVED_BIT_1_31_MASK (0x7fffffff)

#define SYS_AHBP_REG39_ADDR (SOC_SYS_AHBP_REG_BASE + (0x39 << 2))

#define SYS_AHBP_REG39_H26D_BUFFA_BEGIN_POS (0)
#define SYS_AHBP_REG39_H26D_BUFFA_BEGIN_MASK (0xffffffff)

#define SYS_AHBP_REG3A_ADDR (SOC_SYS_AHBP_REG_BASE + (0x3a << 2))

#define SYS_AHBP_REG3A_H26D_BUFFA_SIZE_POS (0)
#define SYS_AHBP_REG3A_H26D_BUFFA_SIZE_MASK (0xffffffff)

#define SYS_AHBP_REG3B_ADDR (SOC_SYS_AHBP_REG_BASE + (0x3b << 2))

#define SYS_AHBP_REG3B_H26D_PICA_BEGIN_POS (0)
#define SYS_AHBP_REG3B_H26D_PICA_BEGIN_MASK (0xffffffff)

#define SYS_AHBP_REG3C_ADDR (SOC_SYS_AHBP_REG_BASE + (0x3c << 2))

#define SYS_AHBP_REG3C_H26D_PICA_HALFBUFF_END_POS (0)
#define SYS_AHBP_REG3C_H26D_PICA_HALFBUFF_END_MASK (0xffffffff)

#define SYS_AHBP_REG3D_ADDR (SOC_SYS_AHBP_REG_BASE + (0x3d << 2))

#define SYS_AHBP_REG3D_H26D_PICA_END_POS (0)
#define SYS_AHBP_REG3D_H26D_PICA_END_MASK (0xffffffff)

#define SYS_AHBP_REG3E_ADDR (SOC_SYS_AHBP_REG_BASE + (0x3e << 2))

#define SYS_AHBP_REG3E_RESERVED_0_31_POS (0)
#define SYS_AHBP_REG3E_RESERVED_0_31_MASK (0xffffffff)

#define SYS_AHBP_REG3F_ADDR (SOC_SYS_AHBP_REG_BASE + (0x3f << 2))

#define SYS_AHBP_REG3F_H26D_BUFFA_REMAP_ADDR_POS (0)
#define SYS_AHBP_REG3F_H26D_BUFFA_REMAP_ADDR_MASK (0xffffffff)

#define SYS_AHBP_REG40_ADDR (SOC_SYS_AHBP_REG_BASE + (0x40 << 2))

#define SYS_AHBP_REG40_H26D_BUFFB_ENABLE_POS (0)
#define SYS_AHBP_REG40_H26D_BUFFB_ENABLE_MASK (0x1)

#define SYS_AHBP_REG40_RESERVED_BIT_1_31_POS (1)
#define SYS_AHBP_REG40_RESERVED_BIT_1_31_MASK (0x7fffffff)

#define SYS_AHBP_REG41_ADDR (SOC_SYS_AHBP_REG_BASE + (0x41 << 2))

#define SYS_AHBP_REG41_H26D_BUFFB_BEGIN_POS (0)
#define SYS_AHBP_REG41_H26D_BUFFB_BEGIN_MASK (0xffffffff)

#define SYS_AHBP_REG42_ADDR (SOC_SYS_AHBP_REG_BASE + (0x42 << 2))

#define SYS_AHBP_REG42_H26D_BUFFB_SIZE_POS (0)
#define SYS_AHBP_REG42_H26D_BUFFB_SIZE_MASK (0xffffffff)

#define SYS_AHBP_REG43_ADDR (SOC_SYS_AHBP_REG_BASE + (0x43 << 2))

#define SYS_AHBP_REG43_H26D_PICB_BEGIN_POS (0)
#define SYS_AHBP_REG43_H26D_PICB_BEGIN_MASK (0xffffffff)

#define SYS_AHBP_REG44_ADDR (SOC_SYS_AHBP_REG_BASE + (0x44 << 2))

#define SYS_AHBP_REG44_H26D_PICB_HALFBUFF_END_POS (0)
#define SYS_AHBP_REG44_H26D_PICB_HALFBUFF_END_MASK (0xffffffff)

#define SYS_AHBP_REG45_ADDR (SOC_SYS_AHBP_REG_BASE + (0x45 << 2))

#define SYS_AHBP_REG45_H26D_PICB_END_POS (0)
#define SYS_AHBP_REG45_H26D_PICB_END_MASK (0xffffffff)

#define SYS_AHBP_REG46_ADDR (SOC_SYS_AHBP_REG_BASE + (0x46 << 2))

#define SYS_AHBP_REG46_RESERVED_0_31_POS (0)
#define SYS_AHBP_REG46_RESERVED_0_31_MASK (0xffffffff)

#define SYS_AHBP_REG47_ADDR (SOC_SYS_AHBP_REG_BASE + (0x47 << 2))

#define SYS_AHBP_REG47_H26D_BUFFB_REMAP_ADDR_POS (0)
#define SYS_AHBP_REG47_H26D_BUFFB_REMAP_ADDR_MASK (0xffffffff)

#define SYS_AHBP_REG48_ADDR (SOC_SYS_AHBP_REG_BASE + (0x48 << 2))

#define SYS_AHBP_REG48_H26D_BUFFC_ENABLE_POS (0)
#define SYS_AHBP_REG48_H26D_BUFFC_ENABLE_MASK (0x1)

#define SYS_AHBP_REG48_RESERVED_BIT_1_31_POS (1)
#define SYS_AHBP_REG48_RESERVED_BIT_1_31_MASK (0x7fffffff)

#define SYS_AHBP_REG49_ADDR (SOC_SYS_AHBP_REG_BASE + (0x49 << 2))

#define SYS_AHBP_REG49_H26D_BUFFC_BEGIN_POS (0)
#define SYS_AHBP_REG49_H26D_BUFFC_BEGIN_MASK (0xffffffff)

#define SYS_AHBP_REG4A_ADDR (SOC_SYS_AHBP_REG_BASE + (0x4a << 2))

#define SYS_AHBP_REG4A_H26D_BUFFC_SIZE_POS (0)
#define SYS_AHBP_REG4A_H26D_BUFFC_SIZE_MASK (0xffffffff)

#define SYS_AHBP_REG4B_ADDR (SOC_SYS_AHBP_REG_BASE + (0x4b << 2))

#define SYS_AHBP_REG4B_H26D_PICC_BEGIN_POS (0)
#define SYS_AHBP_REG4B_H26D_PICC_BEGIN_MASK (0xffffffff)

#define SYS_AHBP_REG4C_ADDR (SOC_SYS_AHBP_REG_BASE + (0x4c << 2))

#define SYS_AHBP_REG4C_H26D_PICC_HALFBUFF_END_POS (0)
#define SYS_AHBP_REG4C_H26D_PICC_HALFBUFF_END_MASK (0xffffffff)

#define SYS_AHBP_REG4D_ADDR (SOC_SYS_AHBP_REG_BASE + (0x4d << 2))

#define SYS_AHBP_REG4D_H26D_PICC_END_POS (0)
#define SYS_AHBP_REG4D_H26D_PICC_END_MASK (0xffffffff)

#define SYS_AHBP_REG4E_ADDR (SOC_SYS_AHBP_REG_BASE + (0x4e << 2))

#define SYS_AHBP_REG4E_RESERVED_0_31_POS (0)
#define SYS_AHBP_REG4E_RESERVED_0_31_MASK (0xffffffff)

#define SYS_AHBP_REG4F_ADDR (SOC_SYS_AHBP_REG_BASE + (0x4f << 2))

#define SYS_AHBP_REG4F_H26D_BUFFC_REMAP_ADDR_POS (0)
#define SYS_AHBP_REG4F_H26D_BUFFC_REMAP_ADDR_MASK (0xffffffff)

#define SYS_AHBP_REG50_ADDR (SOC_SYS_AHBP_REG_BASE + (0x50 << 2))

#define SYS_AHBP_REG50_RAM_SPSH_CFG_POS (0)
#define SYS_AHBP_REG50_RAM_SPSH_CFG_MASK (0x3ff)

#define SYS_AHBP_REG50_RAM_SPBH_CFG_POS (10)
#define SYS_AHBP_REG50_RAM_SPBH_CFG_MASK (0x7ff)

#define SYS_AHBP_REG50_RESERVED_BIT_21_23_POS (21)
#define SYS_AHBP_REG50_RESERVED_BIT_21_23_MASK (0x7)

#define SYS_AHBP_REG50_RAM_SPSH_SET_KEY_POS (24)
#define SYS_AHBP_REG50_RAM_SPSH_SET_KEY_MASK (0xff)

#define SYS_AHBP_REG51_ADDR (SOC_SYS_AHBP_REG_BASE + (0x51 << 2))

#define SYS_AHBP_REG51_RAM_STPH_CFG_POS (0)
#define SYS_AHBP_REG51_RAM_STPH_CFG_MASK (0xfff)

#define SYS_AHBP_REG51_RESERVED_BIT_12_23_POS (12)
#define SYS_AHBP_REG51_RESERVED_BIT_12_23_MASK (0xfff)

#define SYS_AHBP_REG51_RAM_STPH_SET_KEY_POS (24)
#define SYS_AHBP_REG51_RAM_STPH_SET_KEY_MASK (0xff)

#define SYS_AHBP_REG52_ADDR (SOC_SYS_AHBP_REG_BASE + (0x52 << 2))

#define SYS_AHBP_REG52_RAM_SPSL_CFG_POS (0)
#define SYS_AHBP_REG52_RAM_SPSL_CFG_MASK (0x3ff)

#define SYS_AHBP_REG52_RAM_SPBL_CFG_POS (10)
#define SYS_AHBP_REG52_RAM_SPBL_CFG_MASK (0x7ff)

#define SYS_AHBP_REG52_RESERVED_BIT_21_23_POS (21)
#define SYS_AHBP_REG52_RESERVED_BIT_21_23_MASK (0x7)

#define SYS_AHBP_REG52_RAM_SPSL_SET_KEY_POS (24)
#define SYS_AHBP_REG52_RAM_SPSL_SET_KEY_MASK (0xff)

#define SYS_AHBP_REG53_ADDR (SOC_SYS_AHBP_REG_BASE + (0x53 << 2))

#define SYS_AHBP_REG53_RAM_STPL_CFG_POS (0)
#define SYS_AHBP_REG53_RAM_STPL_CFG_MASK (0xfff)

#define SYS_AHBP_REG53_RESERVED_BIT_12_23_POS (12)
#define SYS_AHBP_REG53_RESERVED_BIT_12_23_MASK (0xfff)

#define SYS_AHBP_REG53_RAM_STPL_SET_KEY_POS (24)
#define SYS_AHBP_REG53_RAM_STPL_SET_KEY_MASK (0xff)

#ifdef __cplusplus
}
#endif
