;vela --config ./vela.ini --accelerator-config ethos-u65-256  --output-dir ./ --verbose-all lip.tflite --memory-mode Shared_Sram --system-config Ethos_U65_RAM > log.log


; Ethos-U65 RAM: SRAM (16 GB/s) and DRAM (16 GB/s)
[System_Config.Ethos_U65_RAM]
core_clock=480e6
axi0_port=Sram
axi1_port=Dram
Sram_clock_scale=1.0
Sram_burst_length=32
Sram_read_latency=32
Sram_write_latency=32
Sram_max_reads=16
Sram_max_writes=16
Dram_clock_scale=1.0
Dram_burst_length=32
Dram_read_latency=32
Dram_write_latency=32
Dram_max_reads=16
Dram_max_writes=16

; Ethos-U65
[System_Config.Ethos_U65_PSRAM]
core_clock=640e6
axi0_port=Sram
axi1_port=Dram
Sram_clock_scale=1.0
Sram_burst_length=32
Sram_read_latency=32
Sram_write_latency=32
Dram_clock_scale=0.04
Dram_burst_length=64
Dram_read_latency=250
Dram_write_latency=250

; Ethos-U65
[System_Config.Ethos_U65_ONLY_PSRAM]
core_clock=640e6
axi0_port=Sram
axi1_port=Sram
Sram_clock_scale=0.04
Sram_burst_length=32
Sram_read_latency=250
Sram_write_latency=250

; Ethos-U65
[System_Config.Ethos_U65_DUAL_PSRAM]
core_clock=640e6
axi0_port=Sram
axi1_port=Dram
Sram_clock_scale=0.04
Sram_burst_length=32
Sram_read_latency=32
Sram_write_latency=32
Dram_clock_scale=0.04
Dram_burst_length=64
Dram_read_latency=250
Dram_write_latency=250

; -----------------------------------------------------------------------------
; Memory Mode

; SRAM Only: only one AXI port is used and the SRAM is used for all storage
[Memory_Mode.Sram_Only]
const_mem_area=Axi0
arena_mem_area=Axi0
cache_mem_area=Axi0

; Shared SRAM: the SRAM is shared between the Ethos-U and the Cortex-M software
; The non-SRAM memory is assumed to be read-only
[Memory_Mode.Shared_Sram]
const_mem_area=Axi1
arena_mem_area=Axi0
cache_mem_area=Axi0

; Dedicated SRAM: the SRAM is only for use by the Ethos-U
; The non-SRAM memory is assumed to be read-writeable
[Memory_Mode.Dedicated_Sram]
const_mem_area=Axi1
arena_mem_area=Axi1
cache_mem_area=Axi0

; Dedicated SRAM 256KB: the SRAM (256KB) is only for use by the Ethos-U
; The non-SRAM memory is assumed to be read-writeable

[Memory_Mode.Shared_Sram_128KB]
inherit=Memory_Mode.Shared_Sram
arena_cache_size=131072

[Memory_Mode.Shared_Sram_256KB]
inherit=Memory_Mode.Shared_Sram
arena_cache_size=262144

[Memory_Mode.Shared_Sram_320KB]
inherit=Memory_Mode.Shared_Sram
arena_cache_size=327680

[Memory_Mode.Shared_Sram_384KB]
inherit=Memory_Mode.Shared_Sram
arena_cache_size=393216

[Memory_Mode.Shared_Sram_448KB]
inherit=Memory_Mode.Shared_Sram
arena_cache_size=458752

[Memory_Mode.Shared_Sram_512KB]
inherit=Memory_Mode.Shared_Sram
arena_cache_size=524288

[Memory_Mode.Dedicated_Sram_128KB]
inherit=Memory_Mode.Dedicated_Sram
arena_cache_size=131072

[Memory_Mode.Dedicated_Sram_256KB]
inherit=Memory_Mode.Dedicated_Sram
arena_cache_size=262144

[Memory_Mode.Dedicated_Sram_384KB]
inherit=Memory_Mode.Dedicated_Sram
arena_cache_size=393216

[Memory_Mode.Dedicated_Sram_448KB]
inherit=Memory_Mode.Dedicated_Sram
arena_cache_size=458752

[Memory_Mode.Dedicated_Sram_512KB]
inherit=Memory_Mode.Dedicated_Sram
arena_cache_size=524288

[Memory_Mode.Dedicated_Sram_768KB]
inherit=Memory_Mode.Dedicated_Sram
arena_cache_size=786432

[Memory_Mode.Dedicated_Sram_1024KB]
inherit=Memory_Mode.Dedicated_Sram
arena_cache_size=1048576

[Memory_Mode.Dedicated_Sram_1280KB]
inherit=Memory_Mode.Dedicated_Sram
arena_cache_size=1310720

[Memory_Mode.Dedicated_Sram_1536KB]
inherit=Memory_Mode.Dedicated_Sram
arena_cache_size=1572864

[Memory_Mode.Dedicated_Sram_2048KB]
inherit=Memory_Mode.Dedicated_Sram
arena_cache_size=2097152

[Memory_Mode.Sram_Only_256KB]
inherit=Memory_Mode.Sram_Only
arena_cache_size=262144

[Memory_Mode.Sram_Only_320KB]
inherit=Memory_Mode.Sram_Only
arena_cache_size=327680

[Memory_Mode.Sram_Only_384KB]
inherit=Memory_Mode.Sram_Only
arena_cache_size=393216

[Memory_Mode.Sram_Only_512KB]
inherit=Memory_Mode.Sram_Only
arena_cache_size=524288