#ifndef RISCV_USB_PROBE_DEFS_H
#define RISCV_USB_PROBE_DEFS_H

#define RISCV_USB_PROBE_MAGIC          0x52555342UL
#define RISCV_USB_PROBE_OWNER_NONE     0U
#define RISCV_USB_PROBE_OWNER_AP       1U
#define RISCV_USB_PROBE_OWNER_RISCV    2U

#endif
