// Copyright 2022-2025 Beken
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This is a generated file, if you need to modify it, use the script to
// generate and modify all the struct.h, ll.h, reg.h, debug_dump.c files!

#pragma once


#ifdef __cplusplus
extern "C" {
#endif


#define GPU_AQHICLKCTRL_ADDR (SOC_GPU_REG_BASE + (0x0 << 2))

#define GPU_AQHICLKCTRL_CLK3DDIS_POS (0)
#define GPU_AQHICLKCTRL_CLK3DDIS_MASK (0x1)

#define GPU_AQHICLKCTRL_CLK2DDIS_POS (1)
#define GPU_AQHICLKCTRL_CLK2DDIS_MASK (0x1)

#define GPU_AQHICLKCTRL_FSCALE_VAL_POS (2)
#define GPU_AQHICLKCTRL_FSCALE_VAL_MASK (0x7f)

#define GPU_AQHICLKCTRL_FSCALE_CMD_LOAD_POS (9)
#define GPU_AQHICLKCTRL_FSCALE_CMD_LOAD_MASK (0x1)

#define GPU_AQHICLKCTRL_DIS_RAM_CLK_GATING_POS (10)
#define GPU_AQHICLKCTRL_DIS_RAM_CLK_GATING_MASK (0x1)

#define GPU_AQHICLKCTRL_DIS_DBG_REGISTER_POS (11)
#define GPU_AQHICLKCTRL_DIS_DBG_REGISTER_MASK (0x1)

#define GPU_AQHICLKCTRL_SOFT_RST_POS (12)
#define GPU_AQHICLKCTRL_SOFT_RST_MASK (0x1)

#define GPU_AQHICLKCTRL_RESERVED_13_15_POS (13)
#define GPU_AQHICLKCTRL_RESERVED_13_15_MASK (0x7)

#define GPU_AQHICLKCTRL_IDLE3_D_POS (16)
#define GPU_AQHICLKCTRL_IDLE3_D_MASK (0x1)

#define GPU_AQHICLKCTRL_IDLE2_D_POS (17)
#define GPU_AQHICLKCTRL_IDLE2_D_MASK (0x1)

#define GPU_AQHICLKCTRL_IDLE_VG_POS (18)
#define GPU_AQHICLKCTRL_IDLE_VG_MASK (0x1)

#define GPU_AQHICLKCTRL_ISOLATEGPU_POS (19)
#define GPU_AQHICLKCTRL_ISOLATEGPU_MASK (0x1)

#define GPU_AQHICLKCTRL_RESERVED_BIT_20_31_POS (20)
#define GPU_AQHICLKCTRL_RESERVED_BIT_20_31_MASK (0xfff)

#define GPU_AQHIIDLEREG_ADDR (SOC_GPU_REG_BASE + (0x1 << 2))

#define GPU_AQHIIDLEREG_IDLE_FE_POS (0)
#define GPU_AQHIIDLEREG_IDLE_FE_MASK (0x1)

#define GPU_AQHIIDLEREG_IDLE_DE_POS (1)
#define GPU_AQHIIDLEREG_IDLE_DE_MASK (0x1)

#define GPU_AQHIIDLEREG_IDLE_PE_POS (2)
#define GPU_AQHIIDLEREG_IDLE_PE_MASK (0x1)

#define GPU_AQHIIDLEREG_IDLE_SH_POS (3)
#define GPU_AQHIIDLEREG_IDLE_SH_MASK (0x1)

#define GPU_AQHIIDLEREG_IDLE_PA_POS (4)
#define GPU_AQHIIDLEREG_IDLE_PA_MASK (0x1)

#define GPU_AQHIIDLEREG_IDLE_SE_POS (5)
#define GPU_AQHIIDLEREG_IDLE_SE_MASK (0x1)

#define GPU_AQHIIDLEREG_IDLE_RA_POS (6)
#define GPU_AQHIIDLEREG_IDLE_RA_MASK (0x1)

#define GPU_AQHIIDLEREG_IDLE_TX_POS (7)
#define GPU_AQHIIDLEREG_IDLE_TX_MASK (0x1)

#define GPU_AQHIIDLEREG_IDLE_VG_POS (8)
#define GPU_AQHIIDLEREG_IDLE_VG_MASK (0x1)

#define GPU_AQHIIDLEREG_IDLE_IM_POS (9)
#define GPU_AQHIIDLEREG_IDLE_IM_MASK (0x1)

#define GPU_AQHIIDLEREG_IDLE_FP_POS (10)
#define GPU_AQHIIDLEREG_IDLE_FP_MASK (0x1)

#define GPU_AQHIIDLEREG_IDLE_TS_POS (11)
#define GPU_AQHIIDLEREG_IDLE_TS_MASK (0x1)

#define GPU_AQHIIDLEREG_IDLE_BLT_POS (12)
#define GPU_AQHIIDLEREG_IDLE_BLT_MASK (0x1)

#define GPU_AQHIIDLEREG_RESERVED_13_30_POS (13)
#define GPU_AQHIIDLEREG_RESERVED_13_30_MASK (0x3ffff)

#define GPU_AQHIIDLEREG_AXI_LP_POS (31)
#define GPU_AQHIIDLEREG_AXI_LP_MASK (0x1)

#define GPU_AQAXICONFIG_ADDR (SOC_GPU_REG_BASE + (0x2 << 2))

#define GPU_AQAXICONFIG_RESERVED_0_7_POS (0)
#define GPU_AQAXICONFIG_RESERVED_0_7_MASK (0xff)

#define GPU_AQAXICONFIG_AWCACHE_POS (8)
#define GPU_AQAXICONFIG_AWCACHE_MASK (0xf)

#define GPU_AQAXICONFIG_ARCACHE_POS (12)
#define GPU_AQAXICONFIG_ARCACHE_MASK (0xf)

#define GPU_AQAXICONFIG_AXDOMAIN_SHARED_POS (16)
#define GPU_AQAXICONFIG_AXDOMAIN_SHARED_MASK (0x3)

#define GPU_AQAXICONFIG_AXDOMAIN_NOSHARED_POS (18)
#define GPU_AQAXICONFIG_AXDOMAIN_NOSHARED_MASK (0x3)

#define GPU_AQAXICONFIG_AXCACHE_OVERRIDE_SHARED_POS (20)
#define GPU_AQAXICONFIG_AXCACHE_OVERRIDE_SHARED_MASK (0xf)

#define GPU_AQAXICONFIG_RESERVED_BIT_24_31_POS (24)
#define GPU_AQAXICONFIG_RESERVED_BIT_24_31_MASK (0xff)

#define GPU__ADDR (SOC_GPU_REG_BASE + (0x3 << 2))

#define GPU__WR_ERR_ID_POS (0)
#define GPU__WR_ERR_ID_MASK (0xf)

#define GPU__RD_ERR_ID_POS (4)
#define GPU__RD_ERR_ID_MASK (0xf)

#define GPU__DET_WR_ERR_POS (8)
#define GPU__DET_WR_ERR_MASK (0x1)

#define GPU__DET_RD_ERR_POS (9)
#define GPU__DET_RD_ERR_MASK (0x1)

#define GPU__RESERVED_BIT_10_31_POS (10)
#define GPU__RESERVED_BIT_10_31_MASK (0x3fffff)

#define GPU_AQINTRACK_ADDR (SOC_GPU_REG_BASE + (0x4 << 2))

#define GPU_AQINTRACK_INTR_VEC_POS (0)
#define GPU_AQINTRACK_INTR_VEC_MASK (0xffffffff)

#define GPU_AQINTREN_ADDR (SOC_GPU_REG_BASE + (0x5 << 2))

#define GPU_AQINTREN_INTR_ENBL_VEC_POS (0)
#define GPU_AQINTREN_INTR_ENBL_VEC_MASK (0xffffffff)

#define GPU_AQIDENTREG_ADDR (SOC_GPU_REG_BASE + (0x6 << 2))

#define GPU_AQIDENTREG_AQIDENT_POS (0)
#define GPU_AQIDENTREG_AQIDENT_MASK (0xffffffff)

#define GPU_GCFEATURESERVED_ADDR (SOC_GPU_REG_BASE + (0x7 << 2))

#define GPU_GCFEATURESERVED_FEATURESERVED_POS (0)
#define GPU_GCFEATURESERVED_FEATURESERVED_MASK (0xffffffff)

#define GPU_GCCHIPIDREG_ADDR (SOC_GPU_REG_BASE + (0x8 << 2))

#define GPU_GCCHIPIDREG_GCCHIPID_POS (0)
#define GPU_GCCHIPIDREG_GCCHIPID_MASK (0xffffffff)

#define GPU_GCCHIPREV_ADDR (SOC_GPU_REG_BASE + (0x9 << 2))

#define GPU_GCCHIPREV_REV_POS (0)
#define GPU_GCCHIPREV_REV_MASK (0xffffffff)

#define GPU_GCCHIPDATE_ADDR (SOC_GPU_REG_BASE + (0xa << 2))

#define GPU_GCCHIPDATE_DATE_POS (0)
#define GPU_GCCHIPDATE_DATE_MASK (0xffffffff)

#define GPU_GCCHIPTIME_ADDR (SOC_GPU_REG_BASE + (0xb << 2))

#define GPU_GCCHIPTIME_CHIPTIME_POS (0)
#define GPU_GCCHIPTIME_CHIPTIME_MASK (0xffffffff)

#define GPU_GCCHIPCUSTOMER_ADDR (SOC_GPU_REG_BASE + (0xc << 2))

#define GPU_GCCHIPCUSTOMER_CHIPCUSTOMER_POS (0)
#define GPU_GCCHIPCUSTOMER_CHIPCUSTOMER_MASK (0xffffffff)

#define GPU_GCMINORFEATURESERVED_ADDR (SOC_GPU_REG_BASE + (0xd << 2))

#define GPU_GCMINORFEATURESERVED_MINORFEATURESERVED_POS (0)
#define GPU_GCMINORFEATURESERVED_MINORFEATURESERVED_MASK (0xffffffff)

#define GPU_GCRESERVEDETMEM_ADDR (SOC_GPU_REG_BASE + (0xf << 2))

#define GPU_GCRESERVEDETMEM_RESERVEDETMEM_POS (0)
#define GPU_GCRESERVEDETMEM_RESERVEDETMEM_MASK (0xffffffff)

#define GPU_GCREGHICHIPPATCHREV_ADDR (SOC_GPU_REG_BASE + (0x26 << 2))

#define GPU_GCREGHICHIPPATCHREV_PATCH_REV_POS (0)
#define GPU_GCREGHICHIPPATCHREV_PATCH_REV_MASK (0xffffffff)

#define GPU_GCPRODUCTID_ADDR (SOC_GPU_REG_BASE + (0x2a << 2))

#define GPU_GCPRODUCTID_GRADE_LEVEL_POS (0)
#define GPU_GCPRODUCTID_GRADE_LEVEL_MASK (0xf)

#define GPU_GCPRODUCTID_NUM_POS (4)
#define GPU_GCPRODUCTID_NUM_MASK (0xfffff)

#define GPU_GCPRODUCTID_TYPE_POS (24)
#define GPU_GCPRODUCTID_TYPE_MASK (0xf)

#define GPU_GCPRODUCTID_RESERVED_BIT_28_31_POS (28)
#define GPU_GCPRODUCTID_RESERVED_BIT_28_31_MASK (0xf)

#define GPU_MODULEPOWERCTRL_ADDR (SOC_GPU_REG_BASE + (0x40 << 2))

#define GPU_MODULEPOWERCTRL_EN_MODULE_CLK_GATING_POS (0)
#define GPU_MODULEPOWERCTRL_EN_MODULE_CLK_GATING_MASK (0x1)

#define GPU_MODULEPOWERCTRL_DIS_STALL_MODULE_CLK_GATING_POS (1)
#define GPU_MODULEPOWERCTRL_DIS_STALL_MODULE_CLK_GATING_MASK (0x1)

#define GPU_MODULEPOWERCTRL_DIS_STARVE_MODULE_CLK_GATING_POS (2)
#define GPU_MODULEPOWERCTRL_DIS_STARVE_MODULE_CLK_GATING_MASK (0x1)

#define GPU_MODULEPOWERCTRL_RESERVED_BIT_3_3_POS (3)
#define GPU_MODULEPOWERCTRL_RESERVED_BIT_3_3_MASK (0x1)

#define GPU_MODULEPOWERCTRL_TURN_ON_COUNTER_POS (4)
#define GPU_MODULEPOWERCTRL_TURN_ON_COUNTER_MASK (0xf)

#define GPU_MODULEPOWERCTRL_RESERVED_BIT_8_15_POS (8)
#define GPU_MODULEPOWERCTRL_RESERVED_BIT_8_15_MASK (0xff)

#define GPU_MODULEPOWERCTRL_TURN_OFF_CONUTER_POS (16)
#define GPU_MODULEPOWERCTRL_TURN_OFF_CONUTER_MASK (0xffff)

#define GPU_POWERMODULECTRL_ADDR (SOC_GPU_REG_BASE + (0x41 << 2))

#define GPU_POWERMODULECTRL_DIS_CLK_GATING_FE_POS (0)
#define GPU_POWERMODULECTRL_DIS_CLK_GATING_FE_MASK (0x1)

#define GPU_POWERMODULECTRL_RESERVED_BIT_1_1_POS (1)
#define GPU_POWERMODULECTRL_RESERVED_BIT_1_1_MASK (0x1)

#define GPU_POWERMODULECTRL_DIS_CLK_GATING_PE_POS (2)
#define GPU_POWERMODULECTRL_DIS_CLK_GATING_PE_MASK (0x1)

#define GPU_POWERMODULECTRL_RESERVED_BIT_3_7_POS (3)
#define GPU_POWERMODULECTRL_RESERVED_BIT_3_7_MASK (0x1f)

#define GPU_POWERMODULECTRL_DIS_CLK_GATING_VG_POS (8)
#define GPU_POWERMODULECTRL_DIS_CLK_GATING_VG_MASK (0x1)

#define GPU_POWERMODULECTRL_DIS_CLK_GATING_IM_POS (9)
#define GPU_POWERMODULECTRL_DIS_CLK_GATING_IM_MASK (0x1)

#define GPU_POWERMODULECTRL_RESERVED_BIT_10_10_POS (10)
#define GPU_POWERMODULECTRL_RESERVED_BIT_10_10_MASK (0x1)

#define GPU_POWERMODULECTRL_DIS_CLK_GATING_TS_POS (11)
#define GPU_POWERMODULECTRL_DIS_CLK_GATING_TS_MASK (0x1)

#define GPU_POWERMODULECTRL_RESERVED_BIT_12_31_POS (12)
#define GPU_POWERMODULECTRL_RESERVED_BIT_12_31_MASK (0xfffff)

#define GPU_POWERMODULESTATUS_ADDR (SOC_GPU_REG_BASE + (0x42 << 2))

#define GPU_POWERMODULESTATUS_CLK_GATING_FE_S_POS (0)
#define GPU_POWERMODULESTATUS_CLK_GATING_FE_S_MASK (0x1)

#define GPU_POWERMODULESTATUS_RESERVED_BIT_1_1_POS (1)
#define GPU_POWERMODULESTATUS_RESERVED_BIT_1_1_MASK (0x1)

#define GPU_POWERMODULESTATUS_CLK_GATING_PE_S_POS (2)
#define GPU_POWERMODULESTATUS_CLK_GATING_PE_S_MASK (0x1)

#define GPU_POWERMODULESTATUS_RESERVED_BIT_3_7_POS (3)
#define GPU_POWERMODULESTATUS_RESERVED_BIT_3_7_MASK (0x1f)

#define GPU_POWERMODULESTATUS_CLK_GATING_VG_S_POS (8)
#define GPU_POWERMODULESTATUS_CLK_GATING_VG_S_MASK (0x1)

#define GPU_POWERMODULESTATUS_CLK_GATING_IM_S_POS (9)
#define GPU_POWERMODULESTATUS_CLK_GATING_IM_S_MASK (0x1)

#define GPU_POWERMODULESTATUS_RESERVED_BIT_10_10_POS (10)
#define GPU_POWERMODULESTATUS_RESERVED_BIT_10_10_MASK (0x1)

#define GPU_POWERMODULESTATUS_CLK_GATING_TS_S_POS (11)
#define GPU_POWERMODULESTATUS_CLK_GATING_TS_S_MASK (0x1)

#define GPU_POWERMODULESTATUS_CLK_GATING_FLEXA_S_POS (12)
#define GPU_POWERMODULESTATUS_CLK_GATING_FLEXA_S_MASK (0x1)

#define GPU_POWERMODULESTATUS_RESERVED_BIT_13_31_POS (13)
#define GPU_POWERMODULESTATUS_RESERVED_BIT_13_31_MASK (0x7ffff)

#define GPU_AQMEMORYDEBUG_ADDR (SOC_GPU_REG_BASE + (0x105 << 2))

#define GPU_AQMEMORYDEBUG_MAX_OUTSTANDING_READS_POS (0)
#define GPU_AQMEMORYDEBUG_MAX_OUTSTANDING_READS_MASK (0xff)

#define GPU_AQMEMORYDEBUG_RESERVED_BIT_8_31_POS (8)
#define GPU_AQMEMORYDEBUG_RESERVED_BIT_8_31_MASK (0xffffff)

#define GPU_AQREGTIMINGCTRL_ADDR (SOC_GPU_REG_BASE + (0x10b << 2))

#define GPU_AQREGTIMINGCTRL_FOR_RF1P_POS (0)
#define GPU_AQREGTIMINGCTRL_FOR_RF1P_MASK (0xff)

#define GPU_AQREGTIMINGCTRL_FOR_RF2P_POS (8)
#define GPU_AQREGTIMINGCTRL_FOR_RF2P_MASK (0xff)

#define GPU_AQREGTIMINGCTRL_FAST_RTC_POS (16)
#define GPU_AQREGTIMINGCTRL_FAST_RTC_MASK (0x3)

#define GPU_AQREGTIMINGCTRL_FAST_WTC_POS (18)
#define GPU_AQREGTIMINGCTRL_FAST_WTC_MASK (0x3)

#define GPU_AQREGTIMINGCTRL_POWER_DOWN_POS (20)
#define GPU_AQREGTIMINGCTRL_POWER_DOWN_MASK (0x1)

#define GPU_AQREGTIMINGCTRL_RESERVED_BIT_21_31_POS (21)
#define GPU_AQREGTIMINGCTRL_RESERVED_BIT_21_31_MASK (0x7ff)

#define GPU_FETCHADDRESERVEDS_ADDR (SOC_GPU_REG_BASE + (0x140 << 2))

#define GPU_FETCHADDRESERVEDS_TYPE_POS (0)
#define GPU_FETCHADDRESERVEDS_TYPE_MASK (0x3)

#define GPU_FETCHADDRESERVEDS_ADDRESERVEDS_POS (2)
#define GPU_FETCHADDRESERVEDS_ADDRESERVEDS_MASK (0x3fffffff)

#define GPU_FETCHCTRL_ADDR (SOC_GPU_REG_BASE + (0x141 << 2))

#define GPU_FETCHCTRL_COUNT_POS (0)
#define GPU_FETCHCTRL_COUNT_MASK (0x1fffff)

#define GPU_FETCHCTRL_RESERVED_BIT_21_31_POS (21)
#define GPU_FETCHCTRL_RESERVED_BIT_21_31_MASK (0x7ff)

#define GPU_CURRENTFETCHADDR_ADDR (SOC_GPU_REG_BASE + (0x142 << 2))

#define GPU_CURRENTFETCHADDR_ADDRESERVEDS_POS (0)
#define GPU_CURRENTFETCHADDR_ADDRESERVEDS_MASK (0xffffffff)

#ifdef __cplusplus
}
#endif
