#ifndef _MIPI_DSI_HOST_REG_H_
#define _MIPI_DSI_HOST_REG_H_

#include "soc/bk7259/reg_base.h"

#if CONFIG_DSI_DRIVER

#define BK7259_MIPI_BASE_ADDR   SOC_DSI_REG_BASE

//====[MIPI CONTROLLER]============================================================================================
#define reg_VERSION                         (*((volatile unsigned int*)(BK7259_MIPI_BASE_ADDR + 0x000)))
#define reg_PWR_UP                          (*((volatile unsigned int*)(BK7259_MIPI_BASE_ADDR + 0x004)))
#define reg_CLKMGR_CFG                      (*((volatile unsigned int*)(BK7259_MIPI_BASE_ADDR + 0x008)))
#define reg_DPI_VCID                        (*((volatile unsigned int*)(BK7259_MIPI_BASE_ADDR + 0x00c)))
#define reg_DPI_COLOR_CODING                (*((volatile unsigned int*)(BK7259_MIPI_BASE_ADDR + 0x010)))
#define reg_DPI_CFG_POL                     (*((volatile unsigned int*)(BK7259_MIPI_BASE_ADDR + 0x014)))
#define reg_DPI_LP_CMD_TIM                  (*((volatile unsigned int*)(BK7259_MIPI_BASE_ADDR + 0x018)))
#define reg_PCKHDL_CFG                      (*((volatile unsigned int*)(BK7259_MIPI_BASE_ADDR + 0x02c)))
#define reg_GEN_VCID                        (*((volatile unsigned int*)(BK7259_MIPI_BASE_ADDR + 0x030)))
#define reg_MODE_CFG                        (*((volatile unsigned int*)(BK7259_MIPI_BASE_ADDR + 0x034)))
#define reg_VID_MODE_CFG                    (*((volatile unsigned int*)(BK7259_MIPI_BASE_ADDR + 0x038)))
#define reg_VID_PKT_SIZE                    (*((volatile unsigned int*)(BK7259_MIPI_BASE_ADDR + 0x03c)))
#define reg_VID_NUM_CHUNKS                  (*((volatile unsigned int*)(BK7259_MIPI_BASE_ADDR + 0x040)))
#define reg_VID_NULL_SIZE                   (*((volatile unsigned int*)(BK7259_MIPI_BASE_ADDR + 0x044)))
#define reg_VID_HSA_TIME                    (*((volatile unsigned int*)(BK7259_MIPI_BASE_ADDR + 0x048)))
#define reg_VID_HBP_TIME                    (*((volatile unsigned int*)(BK7259_MIPI_BASE_ADDR + 0x04c)))
#define reg_VID_HLINE_TIME                  (*((volatile unsigned int*)(BK7259_MIPI_BASE_ADDR + 0x050)))
#define reg_VID_VSA_LINES                   (*((volatile unsigned int*)(BK7259_MIPI_BASE_ADDR + 0x054)))
#define reg_VID_VBP_LINES                   (*((volatile unsigned int*)(BK7259_MIPI_BASE_ADDR + 0x058)))
#define reg_VID_VFP_LINES                   (*((volatile unsigned int*)(BK7259_MIPI_BASE_ADDR + 0x05c)))
#define reg_VID_VACTIVE_LINES               (*((volatile unsigned int*)(BK7259_MIPI_BASE_ADDR + 0x060)))
#define reg_EDPI_CMD_SIZE                   (*((volatile unsigned int*)(BK7259_MIPI_BASE_ADDR + 0x064)))
#define reg_CMD_MODE_CFG                    (*((volatile unsigned int*)(BK7259_MIPI_BASE_ADDR + 0x068)))
#define reg_GEN_HDR                         (*((volatile unsigned int*)(BK7259_MIPI_BASE_ADDR + 0x06c)))
#define reg_GEN_PLD_DATA                    (*((volatile unsigned int*)(BK7259_MIPI_BASE_ADDR + 0x070)))
#define reg_CMD_PKT_STATUS                  (*((volatile unsigned int*)(BK7259_MIPI_BASE_ADDR + 0x074)))
#define reg_TO_CNT_CFG                      (*((volatile unsigned int*)(BK7259_MIPI_BASE_ADDR + 0x078)))
#define reg_HS_RD_TO_CNT                    (*((volatile unsigned int*)(BK7259_MIPI_BASE_ADDR + 0x07c)))
#define reg_LP_RD_TO_CNT                    (*((volatile unsigned int*)(BK7259_MIPI_BASE_ADDR + 0x080)))
#define reg_HS_WR_TO_CNT                    (*((volatile unsigned int*)(BK7259_MIPI_BASE_ADDR + 0x084)))
#define reg_LP_WR_TO_CNT                    (*((volatile unsigned int*)(BK7259_MIPI_BASE_ADDR + 0x088)))
#define reg_BTA_TO_CNT                      (*((volatile unsigned int*)(BK7259_MIPI_BASE_ADDR + 0x08c)))
#define reg_SDF_3D                          (*((volatile unsigned int*)(BK7259_MIPI_BASE_ADDR + 0x090)))
#define reg_LPCLK_CTRL                      (*((volatile unsigned int*)(BK7259_MIPI_BASE_ADDR + 0x094)))
#define reg_PHY_TMR_LPCLK_CFG               (*((volatile unsigned int*)(BK7259_MIPI_BASE_ADDR + 0x098)))
#define reg_PHY_TMR_CFG                     (*((volatile unsigned int*)(BK7259_MIPI_BASE_ADDR + 0x09c)))
#define reg_PHY_RSTZ                        (*((volatile unsigned int*)(BK7259_MIPI_BASE_ADDR + 0x0a0)))
#define reg_PHY_IF_CFG                      (*((volatile unsigned int*)(BK7259_MIPI_BASE_ADDR + 0x0a4)))
#define reg_PHY_ULPS_CTRL                   (*((volatile unsigned int*)(BK7259_MIPI_BASE_ADDR + 0x0a8)))
#define reg_PHY_TX_TRIGGERS                 (*((volatile unsigned int*)(BK7259_MIPI_BASE_ADDR + 0x0ac)))
#define reg_PHY_STATUS                      (*((volatile unsigned int*)(BK7259_MIPI_BASE_ADDR + 0x0b0)))
#define reg_PHY_TST_CTRL0                   (*((volatile unsigned int*)(BK7259_MIPI_BASE_ADDR + 0x0b4)))
#define reg_PHY_TST_CTRL1                   (*((volatile unsigned int*)(BK7259_MIPI_BASE_ADDR + 0x0b8)))
#define reg_INT_ST0                         (*((volatile unsigned int*)(BK7259_MIPI_BASE_ADDR + 0x0bc)))
#define reg_INT_ST1                         (*((volatile unsigned int*)(BK7259_MIPI_BASE_ADDR + 0x0c0)))
#define reg_INT_MSK0                        (*((volatile unsigned int*)(BK7259_MIPI_BASE_ADDR + 0x0c4)))
#define reg_INT_MSK1                        (*((volatile unsigned int*)(BK7259_MIPI_BASE_ADDR + 0x0c8)))
#define reg_PHY_CAL                         (*((volatile unsigned int*)(BK7259_MIPI_BASE_ADDR + 0x0cc)))
#define reg_INT_FORCE0                      (*((volatile unsigned int*)(BK7259_MIPI_BASE_ADDR + 0x0d8)))
#define reg_INT_FORCE1                      (*((volatile unsigned int*)(BK7259_MIPI_BASE_ADDR + 0x0dc)))
#define reg_AUTO_ULPS_MODE                  (*((volatile unsigned int*)(BK7259_MIPI_BASE_ADDR + 0x0e0)))
#define reg_AUTO_ULPS_ENTRY_DELAY           (*((volatile unsigned int*)(BK7259_MIPI_BASE_ADDR + 0x0e4)))
#define reg_AUTO_ULPS_WAKEUP_TIME           (*((volatile unsigned int*)(BK7259_MIPI_BASE_ADDR + 0x0e8)))
#define reg_DSC_PARAMETER                   (*((volatile unsigned int*)(BK7259_MIPI_BASE_ADDR + 0x0f0)))
#define reg_PHY_TMR_RD_CFG                  (*((volatile unsigned int*)(BK7259_MIPI_BASE_ADDR + 0x0f4)))
#define reg_AUTO_ULPS_MIN_TIME              (*((volatile unsigned int*)(BK7259_MIPI_BASE_ADDR + 0x0f8)))
#define reg_VID_SHADOW_CTRL                 (*((volatile unsigned int*)(BK7259_MIPI_BASE_ADDR + 0x100)))
#define reg_DPI_VCID_ACT                    (*((volatile unsigned int*)(BK7259_MIPI_BASE_ADDR + 0x10c)))
#define reg_DPI_COLOR_CODING_ACT            (*((volatile unsigned int*)(BK7259_MIPI_BASE_ADDR + 0x110)))
#define reg_DPI_LP_CMD_TIM_ACT              (*((volatile unsigned int*)(BK7259_MIPI_BASE_ADDR + 0x118)))
#define reg_EDPI_TE_HW_CFG                  (*((volatile unsigned int*)(BK7259_MIPI_BASE_ADDR + 0x11c)))
#define reg_VID_MODE_CFG_ACT                (*((volatile unsigned int*)(BK7259_MIPI_BASE_ADDR + 0x138)))
#define reg_VID_PKT_SIZE_ACT                (*((volatile unsigned int*)(BK7259_MIPI_BASE_ADDR + 0x13c)))
#define reg_VID_NUM_CHUNKS_ACT              (*((volatile unsigned int*)(BK7259_MIPI_BASE_ADDR + 0x140)))
#define reg_VID_NULL_SIZE_ACT               (*((volatile unsigned int*)(BK7259_MIPI_BASE_ADDR + 0x144)))
#define reg_VID_HSA_TIME_ACT                (*((volatile unsigned int*)(BK7259_MIPI_BASE_ADDR + 0x148)))
#define reg_VID_HBP_TIME_ACT                (*((volatile unsigned int*)(BK7259_MIPI_BASE_ADDR + 0x14c)))
#define reg_VID_HLINE_TIME_ACT              (*((volatile unsigned int*)(BK7259_MIPI_BASE_ADDR + 0x150)))
#define reg_VID_VSA_LINES_ACT               (*((volatile unsigned int*)(BK7259_MIPI_BASE_ADDR + 0x154)))
#define reg_VID_VBP_LINES_ACT               (*((volatile unsigned int*)(BK7259_MIPI_BASE_ADDR + 0x158)))
#define reg_VID_VFP_LINES_ACT               (*((volatile unsigned int*)(BK7259_MIPI_BASE_ADDR + 0x15c)))
#define reg_VID_VACTIVE_LINES_ACT           (*((volatile unsigned int*)(BK7259_MIPI_BASE_ADDR + 0x160)))
#define reg_VID_PKT_STATUS                  (*((volatile unsigned int*)(BK7259_MIPI_BASE_ADDR + 0x168)))
#define reg_SDF_3D_ACT                      (*((volatile unsigned int*)(BK7259_MIPI_BASE_ADDR + 0x190)))

#endif
#endif