#pragma once

#ifdef CONFIG_PP_EXAMPLE_ENABLE_MIPI_DISPLAY
#define PP_EXAMPLE_ENABLE_MIPI_DISPLAY 1
#else
#define PP_EXAMPLE_ENABLE_MIPI_DISPLAY 0
#endif

#define PP_EXAMPLE_GPU_FLEXA_LINES       16U
#define PP_EXAMPLE_GPU_DISPLAY_WIDTH     1088U
#define PP_EXAMPLE_GPU_DISPLAY_HEIGHT    1920U
#define PP_EXAMPLE_GPU_ROTATE_DEGREE     90U

#if PP_EXAMPLE_GPU_ROTATE_DEGREE == 90U || PP_EXAMPLE_GPU_ROTATE_DEGREE == 270U
#define PP_EXAMPLE_GPU_DST_WIDTH         PP_EXAMPLE_GPU_DISPLAY_HEIGHT
#define PP_EXAMPLE_GPU_DST_HEIGHT        PP_EXAMPLE_GPU_DISPLAY_WIDTH
#else
#define PP_EXAMPLE_GPU_DST_WIDTH         PP_EXAMPLE_GPU_DISPLAY_WIDTH
#define PP_EXAMPLE_GPU_DST_HEIGHT        PP_EXAMPLE_GPU_DISPLAY_HEIGHT
#endif
