#pragma once

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @brief Initialize the platform Ethos-U NPU driver.
 *
 * This function powers up the NPU domain, enables the NPU clock, releases NPU
 * reset, initializes the Arm Ethos-U core driver, registers the NPU interrupt
 * handler, and enables the NPU interrupt after the driver state is ready.
 *
 * @param fast_memory Pointer to the optional fast scratch memory used by the
 *                    Ethos-U driver. The buffer should be accessible by the NPU
 *                    and meet the alignment/placement requirements of the model
 *                    generated by Vela. Pass NULL if no fast memory is used.
 * @param fast_memory_size Size of @p fast_memory in bytes. Use 0 when
 *                         @p fast_memory is NULL.
 *
 * @return 0 on success, otherwise a negative error code returned by the
 *         Ethos-U core driver initialization path.
 *
 * @note Call this function once before creating/running a TFLite Micro
 *       interpreter that uses the Ethos-U delegate/op.
 * @note This function is not intended to be called concurrently with
 *       bk_ethosu_deinit() or while another task is using the NPU.
 */
int bk_ethosu_init(void *fast_memory, uint32_t fast_memory_size);

/**
 * @brief Deinitialize the platform Ethos-U NPU driver.
 *
 * This function disables and unregisters the NPU interrupt first, then
 * deinitializes the Arm Ethos-U core driver and powers down the NPU clock/domain.
 *
 * @note This function does not actively cancel or wait for an in-flight
 *       inference. The caller must ensure that no TFLite Micro Invoke() or
 *       Ethos-U inference is running, and that no task is blocked in the
 *       Ethos-U wait path, before calling this function.
 * @note Calling this function while an inference is running can leave the
 *       waiting task blocked or cause access to deinitialized driver resources.
 * @note This function is not intended to be called concurrently with
 *       bk_ethosu_init() or from interrupt context.
 */
void bk_ethosu_deinit(void);


#ifdef __cplusplus
}
#endif