#pragma once

#ifdef __cplusplus
extern "C" {
#endif

#define LE_AUDIO_LOCAL_NAME          "BK7259_LE_AUDIO"
#define LE_AUDIO_PAGE_SCAN_INTV      0x800
#define LE_AUDIO_PAGE_SCAN_WIN       0x12
#define LE_AUDIO_PAGE_TIMEOUT        0x2000
#define LE_AUDIO_RECONN_INTERVAL_MS  5000
#define LE_AUDIO_MAX_RECONN_COUNT    0

#ifndef CONFIG_LE_AUDIO_BROADCAST_NAME
#define CONFIG_LE_AUDIO_BROADCAST_NAME "BK7259_LE_AUDIO"
#endif

#ifndef CONFIG_LE_AUDIO_SAMPLE_RATE
#define CONFIG_LE_AUDIO_SAMPLE_RATE 48000
#endif

#ifndef CONFIG_LE_AUDIO_FRAME_US
#define CONFIG_LE_AUDIO_FRAME_US 10000
#endif

#ifndef CONFIG_LE_AUDIO_FRAME_BYTES
#define CONFIG_LE_AUDIO_FRAME_BYTES 120
#endif

#ifdef __cplusplus
}
#endif
