/*
 * Automatically generated file. DO NOT EDIT.
 * BEKEN IoT Development Framework (BEKEN-ARMINO)  Configuration Header
 */
#pragma once
#define CONFIG_SOC_BK7259 1
#define CONFIG_CPU_CNT 1
#define CONFIG_SOC_STR "bk7259"
#define CONFIG_SOC_ARCH "cm55"
#define CONFIG_COMPILER_STACK_CHECK_MODE_NORM 1
#define CONFIG_OBJDUMP 1
#define CONFIG_BUILD_DEFAULT_VERSION 1
#define CONFIG_ASSERT_REBOOT 1
#define CONFIG_NO_HOSTED 1
#define CONFIG_UID 1
#define CONFIG_UID_GET_ITEM_FROM_OTP 30
#define CONFIG_UID_GET_SIZE_FROM_OTP 5
#define CONFIG_UID_GET_OFFSET_FROM_OTP 0x3C0
#define CONFIG_USB 1
#define CONFIG_USB_OS 1
#define CONFIG_ISP_LOG_LEVEL 3
#define CONFIG_ISP_BLS_V10 1
#define CONFIG_ISP_GAMMA_IN_V10 1
#define CONFIG_ISP_LSC_V10 1
#define CONFIG_ISP_WB_V10 1
#define CONFIG_ISP_DMSC_V10 1
#define CONFIG_ISP_CCM_V10 1
#define CONFIG_ISP_GAMMA_OUT_V20 1
#define CONFIG_ISP_CSM_V10 1
#define CONFIG_ISP_CPROC_V11 1
#define CONFIG_ISP_HIST256 1
#define CONFIG_ISP_DPF_V10 1
#define CONFIG_ISP_DG_V11 1
#define CONFIG_ISP_DPCC_V10 1
#define CONFIG_ISP_2DNR_V30 1
#define CONFIG_ISP_SCALE_V20 1
#define CONFIG_ISP_GE_V20 1
#define CONFIG_ISP_AE_V10 1
#define CONFIG_ISP_WBM_V10 1
#define CONFIG_ISP_SBI_V10 1
#define CONFIG_ISP_FLEXA_V10 1
#define CONFIG_ISP_WDR_V30 1
#define CONFIG_ISP_SENSOR "ov2775"
#define CONFIG_ISP_OS "freertos"
#define CONFIG_ISP_AE_ALGO_V10 1
#define CONFIG_ISP_AWB_ALGO_V10 1
#define CONFIG_ISP_FLT_V10 1
#define CONFIG_VG_LITE_LOG_LEVEL 0x0
