set(CSI_CAMERA_DEVICE_FILES "")
set(CSI_CAMERA_PATH src/csi)

if (CONFIG_CSI_CAMERA)
	if (CONFIG_CSI_F58)
		list(APPEND CSI_CAMERA_DEVICE_FILES ${CSI_CAMERA_PATH}/csi_f58.c)
		list(APPEND GLOBAL_FUNCTION_SYMBOLS "f58_detect")
	endif()

	if (CONFIG_CSI_GC2053)
		list(APPEND CSI_CAMERA_DEVICE_FILES ${CSI_CAMERA_PATH}/csi_gc2053.c)
		list(APPEND GLOBAL_FUNCTION_SYMBOLS "gc2053_detect")
	endif()

	if (CONFIG_CSI_CV2005)
		list(APPEND CSI_CAMERA_DEVICE_FILES ${CSI_CAMERA_PATH}/csi_cv2005.c)
		list(APPEND GLOBAL_FUNCTION_SYMBOLS "cv2005_detect")
	endif()

	if (CONFIG_CSI_GC4653)
		list(APPEND CSI_CAMERA_DEVICE_FILES ${CSI_CAMERA_PATH}/csi_gc4653.c)
		list(APPEND GLOBAL_FUNCTION_SYMBOLS "gc4653_detect")
	endif()

	if (CONFIG_CSI_OV2775)
		list(APPEND CSI_CAMERA_DEVICE_FILES ${CSI_CAMERA_PATH}/csi_ov2775.c)
		list(APPEND GLOBAL_FUNCTION_SYMBOLS "ov2775_detect")
	endif()

	if (CONFIG_CSI_SC4336)
		list(APPEND CSI_CAMERA_DEVICE_FILES ${CSI_CAMERA_PATH}/csi_sc4336.c)
		list(APPEND CSI_CAMERA_FUNCTION_SYMBOLS "sc4336_detect")
	endif()

endif()


