// Copyright 2022-2025 Beken
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This is a generated file, if you need to modify it, use the script to
// generate and modify all the struct.h, ll.h, reg.h, debug_dump.c files!

#pragma once


#ifdef __cplusplus
extern "C" {
#endif

#define BK7259_DPU_REG_BASE_ADDR  0x4C2C0000

//====[DPU CONTROLLER]============================================================================================
#define dcreg_DPU_Beken_01               (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x30004))
#define dcreg_DPU_Beken_02               (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x30008))
#define dcreg_DPU_Beken_03               (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x3000c))
#define dcreg_DPU_Beken_04               (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x30010))

#define dcregFe0IntrEnable               (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x2400))
#define dcregFe0IntrStatus               (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x2404))
#define dcregFe0IntrTest                 (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x2408))
#define dcregFe0IntrMask                 (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x240c))
#define dcregFe0IntrOverflow             (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x2410))
#define dcregFe0SwReset                  (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x2414))
#define dcregFe0Qos                      (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x2418))
#define dcregFe0ClockGaterDisable        (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x241c))
#define dcregFe0ClockGaterDisable1       (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x2420))
#define dcregFe0WatchDogEnable           (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x24a0))
#define dcregFe0WatchApbTimeout          (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x24a4))
#define dcregFe0WatchAxi0ARTimeout       (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x24a8))
#define dcregFe0WatchAxi0RDTimeout       (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x24ac))
#define dcregLayer0Config                (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x5000))
#define dcregLayer0Start                 (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x5004))
#define dcregShLayer0Config              (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x502c))
#define dcregShLayer0Address             (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x5040))
#define dcregShLayer0UAddress            (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x5044))
#define dcregShLayer0Stride              (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x504c))
#define dcregShLayer0UStride             (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x5050))
#define dcregShLayer0Size                (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x5058))
#define dcregShLayer0OutROIOrigin        (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x505c))
#define dcregShLayer0ClearValue          (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x5074))
#define dcregShLayer0ColorKeyLow         (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x5078))
#define dcregShLayer0ColorKeyHigh        (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x507c))
#define dcregShLayer0PreFetchConfig      (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x5080))
#define dcregLayer1Config                (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x6000))
#define dcregLayer1Start                 (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x6004))
#define dcregShLayer1Config              (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x602c))
#define dcregShLayer1Address             (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x6040))
#define dcregShLayer1UAddress            (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x6044))
#define dcregShLayer1Stride              (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x604c))
#define dcregShLayer1UStride             (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x6050))
#define dcregShLayer1Size                (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x6058))
#define dcregShLayer1OutROIOrigin        (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x605c))
#define dcregShLayer1ClearValue          (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x6074))
#define dcregShLayer1ColorKeyLow         (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x6078))
#define dcregShLayer1ColorKeyHigh        (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x607c))
#define dcregLayer2Config                (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x7000))
#define dcregLayer2Start                 (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x7004))
#define dcregShLayer2Config              (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x702c))
#define dcregShLayer2Address             (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x7040))
#define dcregShLayer2UAddress            (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x7044))
#define dcregShLayer2Stride              (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x704c))
#define dcregShLayer2UStride             (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x7050))
#define dcregShLayer2Size                (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x7058))
#define dcregShLayer2OutROIOrigin        (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x705c))
#define dcregShLayer2ClearValue          (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x7074))
#define dcregShLayer2ColorKeyLow         (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x7078))
#define dcregShLayer2ColorKeyHigh        (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x707c))
#define dcregLayer3Config                (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x8000))
#define dcregLayer3Start                 (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x8004))
#define dcregShLayer3Config              (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x802c))
#define dcregShLayer3Address             (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x8040))
#define dcregShLayer3UAddress            (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x8044))
#define dcregShLayer3Stride              (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x804c))
#define dcregShLayer3UStride             (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x8050))
#define dcregShLayer3Size                (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x8058))
#define dcregShLayer3OutROIOrigin        (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x805c))
#define dcregShLayer3ClearValue          (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x8074))
#define dcregShLayer3ColorKeyLow         (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x8078))
#define dcregShLayer3ColorKeyHigh        (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x807c))
#define dcregBeIntrEnable                (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x16004))
#define dcregBeIntrStatus                (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x16008))
#define dcregBeIntrTest                  (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x1600c))
#define dcregBeIntrMask                  (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x16010))
#define dcregBeIntrOverflow              (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x16014))
#define dcregBeIntrEnable1               (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x16018))
#define dcregBeIntrStatus1               (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x1601c))
#define dcregBeIntrTest1                 (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x16020))
#define dcregBeIntrMask1                 (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x16024))
#define dcregBeIntrOverflow1             (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x16028))
#define dcregBeClockGaterDisable         (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x1602c))
#define dcregBeSwReset                   (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x16038))
#define dcregPanel0Config                (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x18000))
#define dcregShPanel0OTNumber            (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x18010))
#define dcregShPanel0Config              (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x1801c))
#define dcregShPanel0Background          (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x18038))
#define dcregPanel0GammaIndex            (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x1803c))
#define dcregShPanel0GammaData           (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x18040))
#define dcregShPanel0DitherTableLow      (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x18044))
#define dcregShPanel0DitherTableHigh     (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x18048))
#define dcregShPanel0GlobalAlpha0        (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x1804c))
#define dcregShPanel0GlobalAlpha1        (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x18050))
#define dcregShPanel0GlobalAlpha2        (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x18054))
#define dcregShPanel0GlobalAlpha3        (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x18058))
#define dcregShPanel0AlphaBlendConfig0   (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x18064))
#define dcregShPanel0AlphaBlendConfig1   (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x18068))
#define dcregShPanel0AlphaBlendConfig2   (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x1806c))
#define dcregShPanel0AlphaBlendConfig3   (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x18070))
#define dcregShPanel0RGBToYUVPreCoefD0   (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x1807c))
#define dcregShPanel0RGBToYUVPreCoefD1   (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x18080))
#define dcregShPanel0RGBToYUVPreCoefD2   (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x18084))
#define dcregShPanel0RGBToYUVCoef0       (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x18088))
#define dcregShPanel0RGBToYUVCoef1       (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x1808c))
#define dcregShPanel0RGBToYUVCoef2       (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x18090))
#define dcregShPanel0RGBToYUVCoef3       (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x18094))
#define dcregShPanel0RGBToYUVCoef4       (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x18098))
#define dcregShPanel0RGBToYUVCoef5       (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x1809c))
#define dcregShPanel0RGBToYUVCoef6       (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x180a0))
#define dcregShPanel0RGBToYUVCoef7       (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x180a4))
#define dcregShPanel0RGBToYUVCoef8       (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x180a8))
#define dcregShPanel0RGBToYUVPostCoefD0  (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x180ac))
#define dcregShPanel0RGBToYUVPostCoefD1  (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x180b0))
#define dcregShPanel0RGBToYUVPostCoefD2  (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x180b4))
#define dcregLayer0CrcStart              (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x22000))
#define dcregLayer0DmaAlphaCrcSeed       (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x22004))
#define dcregLayer0DmaRedCrcSeed         (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x22008))
#define dcregLayer0DmaGreenCrcSeed       (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x2200c))
#define dcregLayer0DmaBlueCrcSeed        (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x22010))
#define dcregLayer0DmaAlphaCrcValue      (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x22014))
#define dcregLayer0DmaRedCrcValue        (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x22018))
#define dcregLayer0DmaGreenCrcValue      (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x2201c))
#define dcregLayer0DmaBlueCrcValue       (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x22020))
#define dcregLayer0PreBlendAlphaCrcSeed  (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x22024))
#define dcregLayer0PreBlendRedCrcSeed    (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x22028))
#define dcregLayer0PreBlendGreenCrcSeed  (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x2202c))
#define dcregLayer0PreBlendBlueCrcSeed   (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x22030))
#define dcregLayer0PreBlendAlphaCrcValue (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x22034))
#define dcregLayer0PreBlendRedCrcValue   (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x22038))
#define dcregLayer0PreBlendGreenCrcValue (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x2203c))
#define dcregLayer0PreBlendBlueCrcValue  (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x22040))
#define dcregLayer1CrcStart              (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x22044))
#define dcregLayer1DmaAlphaCrcSeed       (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x22048))
#define dcregLayer1DmaRedCrcSeed         (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x2204c))
#define dcregLayer1DmaGreenCrcSeed       (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x22050))
#define dcregLayer1DmaBlueCrcSeed        (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x22054))
#define dcregLayer1DmaAlphaCrcValue      (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x22058))
#define dcregLayer1DmaRedCrcValue        (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x2205c))
#define dcregLayer1DmaGreenCrcValue      (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x22060))
#define dcregLayer1DmaBlueCrcValue       (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x22064))
#define dcregLayer1PreBlendAlphaCrcSeed  (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x22068))
#define dcregLayer1PreBlendRedCrcSeed    (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x2206c))
#define dcregLayer1PreBlendGreenCrcSeed  (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x22070))
#define dcregLayer1PreBlendBlueCrcSeed   (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x22074))
#define dcregLayer1PreBlendAlphaCrcValue (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x22078))
#define dcregLayer1PreBlendRedCrcValue   (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x2207c))
#define dcregLayer1PreBlendGreenCrcValue (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x22080))
#define dcregLayer1PreBlendBlueCrcValue  (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x22084))
#define dcregLayer2CrcStart              (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x22088))
#define dcregLayer2DmaAlphaCrcSeed       (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x2208c))
#define dcregLayer2DmaRedCrcSeed         (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x22090))
#define dcregLayer2DmaGreenCrcSeed       (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x22094))
#define dcregLayer2DmaBlueCrcSeed        (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x22098))
#define dcregLayer2DmaAlphaCrcValue      (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x2209c))
#define dcregLayer2DmaRedCrcValue        (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x220a0))
#define dcregLayer2DmaGreenCrcValue      (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x220a4))
#define dcregLayer2DmaBlueCrcValue       (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x220a8))
#define dcregLayer2PreBlendAlphaCrcSeed  (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x220ac))
#define dcregLayer2PreBlendRedCrcSeed    (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x220b0))
#define dcregLayer2PreBlendGreenCrcSeed  (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x220b4))
#define dcregLayer2PreBlendBlueCrcSeed   (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x220b8))
#define dcregLayer2PreBlendAlphaCrcValue (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x220bc))
#define dcregLayer2PreBlendRedCrcValue   (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x220c0))
#define dcregLayer2PreBlendGreenCrcValue (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x220c4))
#define dcregLayer2PreBlendBlueCrcValue  (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x220c8))
#define dcregLayer3CrcStart              (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x220cc))
#define dcregLayer3DmaAlphaCrcSeed       (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x220d0))
#define dcregLayer3DmaRedCrcSeed         (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x220d4))
#define dcregLayer3DmaGreenCrcSeed       (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x220d8))
#define dcregLayer3DmaBlueCrcSeed        (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x220dc))
#define dcregLayer3DmaAlphaCrcValue      (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x220e0))
#define dcregLayer3DmaRedCrcValue        (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x220e4))
#define dcregLayer3DmaGreenCrcValue      (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x220e8))
#define dcregLayer3DmaBlueCrcValue       (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x220ec))
#define dcregLayer3PreBlendAlphaCrcSeed  (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x220f0))
#define dcregLayer3PreBlendRedCrcSeed    (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x220f4))
#define dcregLayer3PreBlendGreenCrcSeed  (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x220f8))
#define dcregLayer3PreBlendBlueCrcSeed   (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x220fc))
#define dcregLayer3PreBlendAlphaCrcValue (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x22100))
#define dcregLayer3PreBlendRedCrcValue   (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x22104))
#define dcregLayer3PreBlendGreenCrcValue (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x22108))
#define dcregLayer3PreBlendBlueCrcValue  (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x2210c))
#define dcregPanel0CrcStart              (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x24000))
#define dcregPanel0BlendAlphaCrcSeed     (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x24004))
#define dcregPanel0BlendRedCrcSeed       (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x24008))
#define dcregPanel0BlendGreenCrcSeed     (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x2400c))
#define dcregPanel0BlendBlueCrcSeed      (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x24010))
#define dcregPanel0BlendAlphaCrcValue    (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x24014))
#define dcregPanel0BlendRedCrcValue      (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x24018))
#define dcregPanel0BlendGreenCrcValue    (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x2401c))
#define dcregPanel0BlendBlueCrcValue     (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x24020))
#define dcregPanel0OfifoAlphaCrcSeed     (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x24024))
#define dcregPanel0OfifoRedCrcSeed       (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x24028))
#define dcregPanel0OfifoGreenCrcSeed     (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x2402c))
#define dcregPanel0OfifoBlueCrcSeed      (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x24030))
#define dcregPanel0OfifoAlphaCrcValue    (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x24034))
#define dcregPanel0OfifoRedCrcValue      (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x24038))
#define dcregPanel0OfifoGreenCrcValue    (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x2403c))
#define dcregPanel0OfifoBlueCrcValue     (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x24040))
#define dcregPanel0OutputConfig          (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x2500c))
#define dcregShPanel0QosThreshold0       (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x25010))
#define dcregShPanel0QosThreshold1       (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x25014))
#define dcregShPanel0QosThreshold2       (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x25018))
#define dcregShPanel0UrgentThreshold0    (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x2501c))
#define dcregShPanel0UrgentThreshold1    (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x25020))
#define dcregShPanel0UrgentThreshold2    (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x25024))
#define dcregShPanel0HealthyThreshold    (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x25028))
#define dcregShPanel0UrgentLow           (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x25030))
#define dcregShPanel0UrgentHigh          (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x25034))
#define dcregPanel0ReadData0             (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x25038))
#define dcregShPanel0DisplayEnd          (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x25048))
#define dcregShPanel0DpiConfig           (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x2504c))
#define dcregShPanel0DpiDisplayTotal     (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x25050))
#define dcregShPanel0DpiDisplayHsync     (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x25054))
#define dcregShPanel0DpiDisplayVsync     (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x25058))
#define dcregPanel0QspiConfig0           (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x25068))
#define dcregPanel0QspiConfig1           (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x2506c))
#define dcregPanel0QspiCmdData           (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x25070))
#define dcregPanel0QspiAddrStartData     (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x25074))
#define dcregPanel0QspiAddrContinueData  (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x25078))
#define dcregPanel0QspiParaData          (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x2507c))
#define dcregPanel0QspiDummyCycle        (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x25080))
#define dcregShPanel0DpiDisplayStart     (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x250e4))
#define dcregShPanel0OutputMode          (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x250e8))
#define dcregPanel0Start                 (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x250ec))
#define dcregShPanel0WorkMode            (*(volatile unsigned int*) (BK7259_DPU_REG_BASE_ADDR + 0x250f0))

#ifdef __cplusplus
}
#endif
