// Copyright 2022-2023 Beken
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This is a generated file, if you need to modify it, use the script to
// generate and modify all the struct.h, ll.h, reg.h, debug_dump.c files!

#pragma once


#ifdef __cplusplus
extern "C" {
#endif


#define AUDIO_REG_DEVICE_ID_ADDR (SOC_AUDIO_REG_REG_BASE + (0x0 << 2))

#define AUDIO_REG_DEVICE_ID_DEVICE_ID_POS (0)
#define AUDIO_REG_DEVICE_ID_DEVICE_ID_MASK (0xffffffff)

#define AUDIO_REG_VERSION_ID_ADDR (SOC_AUDIO_REG_REG_BASE + (0x1 << 2))

#define AUDIO_REG_VERSION_ID_VERSION_ID_POS (0)
#define AUDIO_REG_VERSION_ID_VERSION_ID_MASK (0xffffffff)

#define AUDIO_REG_RESERVED0_ADDR (SOC_AUDIO_REG_REG_BASE + (0x2 << 2))

#define AUDIO_REG_RESERVED0_RESERVED0_POS (0)
#define AUDIO_REG_RESERVED0_RESERVED0_MASK (0xffffffff)

#define AUDIO_REG_RESERVED1_ADDR (SOC_AUDIO_REG_REG_BASE + (0x3 << 2))

#define AUDIO_REG_RESERVED1_RESERVED1_POS (0)
#define AUDIO_REG_RESERVED1_RESERVED1_MASK (0xffffffff)

#define AUDIO_REG_SYS_CFG_ADDR (SOC_AUDIO_REG_REG_BASE + (0x4 << 2))

#define AUDIO_REG_SYS_CFG_DIGMIC_EN_POS (0)
#define AUDIO_REG_SYS_CFG_DIGMIC_EN_MASK (0x1f)

#define AUDIO_REG_SYS_CFG_DMIC_SEL_POS (5)
#define AUDIO_REG_SYS_CFG_DMIC_SEL_MASK (0x7)

#define AUDIO_REG_SYS_CFG_SPL_SEL_ADC_POS (8)
#define AUDIO_REG_SYS_CFG_SPL_SEL_ADC_MASK (0x3)

#define AUDIO_REG_SYS_CFG_RESERVED_BIT_10_17_POS (10)
#define AUDIO_REG_SYS_CFG_RESERVED_BIT_10_17_MASK (0xff)

#define AUDIO_REG_SYS_CFG_MEM_DAC_IIR1X_SW_INIT_POS (18)
#define AUDIO_REG_SYS_CFG_MEM_DAC_IIR1X_SW_INIT_MASK (0x1)

#define AUDIO_REG_SYS_CFG_MEM_AUTO_INIT_TRIG_POS (19)
#define AUDIO_REG_SYS_CFG_MEM_AUTO_INIT_TRIG_MASK (0x1)

#define AUDIO_REG_SYS_CFG_MEM_DAC_SW_INIT_POS (20)
#define AUDIO_REG_SYS_CFG_MEM_DAC_SW_INIT_MASK (0x1)

#define AUDIO_REG_SYS_CFG_MEM_MIC_SW_INIT_POS (21)
#define AUDIO_REG_SYS_CFG_MEM_MIC_SW_INIT_MASK (0x1)

#define AUDIO_REG_SYS_CFG_MEM_ANC_SW_INIT_POS (22)
#define AUDIO_REG_SYS_CFG_MEM_ANC_SW_INIT_MASK (0x1)

#define AUDIO_REG_SYS_CFG_CLK_MIC_SEL_POS (23)
#define AUDIO_REG_SYS_CFG_CLK_MIC_SEL_MASK (0x3)

#define AUDIO_REG_SYS_CFG_RX_SP_SEL_POS (25)
#define AUDIO_REG_SYS_CFG_RX_SP_SEL_MASK (0xf)

#define AUDIO_REG_SYS_CFG_MEM_DAC_EQ_SW_INIT_POS (29)
#define AUDIO_REG_SYS_CFG_MEM_DAC_EQ_SW_INIT_MASK (0x1)

#define AUDIO_REG_SYS_CFG_MEM_DAC_COMP_SW_INIT_POS (30)
#define AUDIO_REG_SYS_CFG_MEM_DAC_COMP_SW_INIT_MASK (0x1)

#define AUDIO_REG_SYS_CFG_APB_CLK_EN_DIS_POS (31)
#define AUDIO_REG_SYS_CFG_APB_CLK_EN_DIS_MASK (0x1)

#define AUDIO_REG_A2DP_COMP_ADDR (SOC_AUDIO_REG_REG_BASE + (0x5 << 2))

#define AUDIO_REG_A2DP_COMP_ANC_COMP_ST_VAL_POS (0)
#define AUDIO_REG_A2DP_COMP_ANC_COMP_ST_VAL_MASK (0x3ff)

#define AUDIO_REG_A2DP_COMP_RESERVED_BIT_10_30_POS (10)
#define AUDIO_REG_A2DP_COMP_RESERVED_BIT_10_30_MASK (0x1fffff)

#define AUDIO_REG_A2DP_COMP_ANC_COMP_EN_FRC_POS (31)
#define AUDIO_REG_A2DP_COMP_ANC_COMP_EN_FRC_MASK (0x1)

#define AUDIO_REG_ADC_CFG_ADDR (SOC_AUDIO_REG_REG_BASE + (0x6 << 2))

#define AUDIO_REG_ADC_CFG_AEC_EN_POS (0)
#define AUDIO_REG_ADC_CFG_AEC_EN_MASK (0x3)

#define AUDIO_REG_ADC_CFG_RESERVED_BIT_2_2_POS (2)
#define AUDIO_REG_ADC_CFG_RESERVED_BIT_2_2_MASK (0x1)

#define AUDIO_REG_ADC_CFG_ADC_16B_SEL_POS (3)
#define AUDIO_REG_ADC_CFG_ADC_16B_SEL_MASK (0x1f)

#define AUDIO_REG_ADC_CFG_AEC_16B_SEL_POS (8)
#define AUDIO_REG_ADC_CFG_AEC_16B_SEL_MASK (0x3)

#define AUDIO_REG_ADC_CFG_RESERVED_BIT_10_11_POS (10)
#define AUDIO_REG_ADC_CFG_RESERVED_BIT_10_11_MASK (0x3)

#define AUDIO_REG_ADC_CFG_ADC_EN_POS (12)
#define AUDIO_REG_ADC_CFG_ADC_EN_MASK (0x1f)

#define AUDIO_REG_ADC_CFG_RESERVED_BIT_17_24_POS (17)
#define AUDIO_REG_ADC_CFG_RESERVED_BIT_17_24_MASK (0xff)

#define AUDIO_REG_ADC_CFG_ADC_LPF_BPS1_POS (25)
#define AUDIO_REG_ADC_CFG_ADC_LPF_BPS1_MASK (0x1)

#define AUDIO_REG_ADC_CFG_ADC_LPF_BPS2_POS (26)
#define AUDIO_REG_ADC_CFG_ADC_LPF_BPS2_MASK (0x1)

#define AUDIO_REG_ADC_CFG_ADC_LPF_BPS3_POS (27)
#define AUDIO_REG_ADC_CFG_ADC_LPF_BPS3_MASK (0x1)

#define AUDIO_REG_ADC_CFG_ADC_HPF_BPS_POS (28)
#define AUDIO_REG_ADC_CFG_ADC_HPF_BPS_MASK (0x1)

#define AUDIO_REG_ADC_CFG_RESERVED_BIT_29_29_POS (29)
#define AUDIO_REG_ADC_CFG_RESERVED_BIT_29_29_MASK (0x1)

#define AUDIO_REG_ADC_CFG_CLK_ADC_INV_POS (30)
#define AUDIO_REG_ADC_CFG_CLK_ADC_INV_MASK (0x1)

#define AUDIO_REG_ADC_CFG_RESERVED_BIT_31_31_POS (31)
#define AUDIO_REG_ADC_CFG_RESERVED_BIT_31_31_MASK (0x1)

#define AUDIO_REG_ANC_CFG_ADDR (SOC_AUDIO_REG_REG_BASE + (0x7 << 2))

#define AUDIO_REG_ANC_CFG_ANC_FRC_ON_POS (0)
#define AUDIO_REG_ANC_CFG_ANC_FRC_ON_MASK (0x1)

#define AUDIO_REG_ANC_CFG_ANC0_RAMP_BPS_POS (1)
#define AUDIO_REG_ANC_CFG_ANC0_RAMP_BPS_MASK (0x7)

#define AUDIO_REG_ANC_CFG_ANC1_RAMP_BPS_POS (4)
#define AUDIO_REG_ANC_CFG_ANC1_RAMP_BPS_MASK (0x7)

#define AUDIO_REG_ANC_CFG_ANC0_RAMP_DOWN_TRIG_POS (7)
#define AUDIO_REG_ANC_CFG_ANC0_RAMP_DOWN_TRIG_MASK (0x7)

#define AUDIO_REG_ANC_CFG_ANC1_RAMP_DOWN_TRIG_POS (10)
#define AUDIO_REG_ANC_CFG_ANC1_RAMP_DOWN_TRIG_MASK (0x7)

#define AUDIO_REG_ANC_CFG_ANC_RAMP_CFG_POS (13)
#define AUDIO_REG_ANC_CFG_ANC_RAMP_CFG_MASK (0x7)

#define AUDIO_REG_ANC_CFG_ANC_CIC_SETP_3_POS (16)
#define AUDIO_REG_ANC_CFG_ANC_CIC_SETP_3_MASK (0x1)

#define AUDIO_REG_ANC_CFG_DAC_CIC_STEP_2_POS (17)
#define AUDIO_REG_ANC_CFG_DAC_CIC_STEP_2_MASK (0x1)

#define AUDIO_REG_ANC_CFG_ANC0_RAMP_UP_TRIG_POS (18)
#define AUDIO_REG_ANC_CFG_ANC0_RAMP_UP_TRIG_MASK (0x7)

#define AUDIO_REG_ANC_CFG_ANC1_RAMP_UP_TRIG_POS (21)
#define AUDIO_REG_ANC_CFG_ANC1_RAMP_UP_TRIG_MASK (0x7)

#define AUDIO_REG_ANC_CFG_RESERVED_BIT_24_25_POS (24)
#define AUDIO_REG_ANC_CFG_RESERVED_BIT_24_25_MASK (0x3)

#define AUDIO_REG_ANC_CFG_ANC_EN0_POS (26)
#define AUDIO_REG_ANC_CFG_ANC_EN0_MASK (0x7)

#define AUDIO_REG_ANC_CFG_ANC_EN1_POS (29)
#define AUDIO_REG_ANC_CFG_ANC_EN1_MASK (0x7)

#define AUDIO_REG_DAC_CFG_ADDR (SOC_AUDIO_REG_REG_BASE + (0x8 << 2))

#define AUDIO_REG_DAC_CFG_RESERVED_0_0_POS (0)
#define AUDIO_REG_DAC_CFG_RESERVED_0_0_MASK (0x1)

#define AUDIO_REG_DAC_CFG_DAC_ENABLE_L_POS (1)
#define AUDIO_REG_DAC_CFG_DAC_ENABLE_L_MASK (0x1)

#define AUDIO_REG_DAC_CFG_DAC_ENABLE_R_POS (2)
#define AUDIO_REG_DAC_CFG_DAC_ENABLE_R_MASK (0x1)

#define AUDIO_REG_DAC_CFG_DAC_IIR_BPS_POS (3)
#define AUDIO_REG_DAC_CFG_DAC_IIR_BPS_MASK (0x1)

#define AUDIO_REG_DAC_CFG_DAC_LPF_BPS1_POS (4)
#define AUDIO_REG_DAC_CFG_DAC_LPF_BPS1_MASK (0x1)

#define AUDIO_REG_DAC_CFG_DAC_LPF_BPS2_POS (5)
#define AUDIO_REG_DAC_CFG_DAC_LPF_BPS2_MASK (0x1)

#define AUDIO_REG_DAC_CFG_DAC_LPF_BPS3_POS (6)
#define AUDIO_REG_DAC_CFG_DAC_LPF_BPS3_MASK (0x1)

#define AUDIO_REG_DAC_CFG_DAC_TX_ANC_D2_POS (7)
#define AUDIO_REG_DAC_CFG_DAC_TX_ANC_D2_MASK (0x3)

#define AUDIO_REG_DAC_CFG_DAC_16B_SEL_POS (9)
#define AUDIO_REG_DAC_CFG_DAC_16B_SEL_MASK (0x7)

#define AUDIO_REG_DAC_CFG_RESERVED_BIT_12_12_POS (12)
#define AUDIO_REG_DAC_CFG_RESERVED_BIT_12_12_MASK (0x1)

#define AUDIO_REG_DAC_CFG_DAC_SPL_SEL_POS (13)
#define AUDIO_REG_DAC_CFG_DAC_SPL_SEL_MASK (0x1)

#define AUDIO_REG_DAC_CFG_RESERVED_BIT_14_14_POS (14)
#define AUDIO_REG_DAC_CFG_RESERVED_BIT_14_14_MASK (0x1)

#define AUDIO_REG_DAC_CFG_DAC_HPF_BPS_POS (15)
#define AUDIO_REG_DAC_CFG_DAC_HPF_BPS_MASK (0x1)

#define AUDIO_REG_DAC_CFG_STEREO_EN_POS (16)
#define AUDIO_REG_DAC_CFG_STEREO_EN_MASK (0x7)

#define AUDIO_REG_DAC_CFG_RESERVED_BIT_19_21_POS (19)
#define AUDIO_REG_DAC_CFG_RESERVED_BIT_19_21_MASK (0x7)

#define AUDIO_REG_DAC_CFG_SPK2MIC_TST_POS (22)
#define AUDIO_REG_DAC_CFG_SPK2MIC_TST_MASK (0x1)

#define AUDIO_REG_DAC_CFG_MONO_SEL_POS (23)
#define AUDIO_REG_DAC_CFG_MONO_SEL_MASK (0x7)

#define AUDIO_REG_DAC_CFG_HINT_SPL_SEL_POS (26)
#define AUDIO_REG_DAC_CFG_HINT_SPL_SEL_MASK (0x3)

#define AUDIO_REG_DAC_CFG_CALL_SPL_SEL_POS (28)
#define AUDIO_REG_DAC_CFG_CALL_SPL_SEL_MASK (0x3)

#define AUDIO_REG_DAC_CFG_DITH_EN_POS (30)
#define AUDIO_REG_DAC_CFG_DITH_EN_MASK (0x1)

#define AUDIO_REG_DAC_CFG_CLK_DAC_INV_POS (31)
#define AUDIO_REG_DAC_CFG_CLK_DAC_INV_MASK (0x1)

#define AUDIO_REG_ADC_CIC_COEF0_ADDR (SOC_AUDIO_REG_REG_BASE + (0x9 << 2))

#define AUDIO_REG_ADC_CIC_COEF0_REG_CIC_COEF0_POS (0)
#define AUDIO_REG_ADC_CIC_COEF0_REG_CIC_COEF0_MASK (0x3ffff)

#define AUDIO_REG_ADC_CIC_COEF0_RESERVED_BIT_18_31_POS (18)
#define AUDIO_REG_ADC_CIC_COEF0_RESERVED_BIT_18_31_MASK (0x3fff)

#define AUDIO_REG_ADC_CIC_COEF1_ADDR (SOC_AUDIO_REG_REG_BASE + (0xa << 2))

#define AUDIO_REG_ADC_CIC_COEF1_REG_CIC_COEF1_POS (0)
#define AUDIO_REG_ADC_CIC_COEF1_REG_CIC_COEF1_MASK (0x3ffff)

#define AUDIO_REG_ADC_CIC_COEF1_RESERVED_BIT_18_31_POS (18)
#define AUDIO_REG_ADC_CIC_COEF1_RESERVED_BIT_18_31_MASK (0x3fff)

#define AUDIO_REG_ADC_CIC_COEF2_ADDR (SOC_AUDIO_REG_REG_BASE + (0xb << 2))

#define AUDIO_REG_ADC_CIC_COEF2_REG_CIC_COEF2_POS (0)
#define AUDIO_REG_ADC_CIC_COEF2_REG_CIC_COEF2_MASK (0x3ffff)

#define AUDIO_REG_ADC_CIC_COEF2_RESERVED_BIT_18_31_POS (18)
#define AUDIO_REG_ADC_CIC_COEF2_RESERVED_BIT_18_31_MASK (0x3fff)

#define AUDIO_REG_ADC_CIC_COEF3_ADDR (SOC_AUDIO_REG_REG_BASE + (0xc << 2))

#define AUDIO_REG_ADC_CIC_COEF3_REG_CIC_COEF3_POS (0)
#define AUDIO_REG_ADC_CIC_COEF3_REG_CIC_COEF3_MASK (0x3ffff)

#define AUDIO_REG_ADC_CIC_COEF3_RESERVED_BIT_18_31_POS (18)
#define AUDIO_REG_ADC_CIC_COEF3_RESERVED_BIT_18_31_MASK (0x3fff)

#define AUDIO_REG_ADC_CIC_COEF4_ADDR (SOC_AUDIO_REG_REG_BASE + (0xd << 2))

#define AUDIO_REG_ADC_CIC_COEF4_REG_CIC_COEF4_POS (0)
#define AUDIO_REG_ADC_CIC_COEF4_REG_CIC_COEF4_MASK (0x3ffff)

#define AUDIO_REG_ADC_CIC_COEF4_RESERVED_BIT_18_31_POS (18)
#define AUDIO_REG_ADC_CIC_COEF4_RESERVED_BIT_18_31_MASK (0x3fff)

#define AUDIO_REG_ADC_CIC_COEF5_ADDR (SOC_AUDIO_REG_REG_BASE + (0xe << 2))

#define AUDIO_REG_ADC_CIC_COEF5_REG_CIC_COEF5_POS (0)
#define AUDIO_REG_ADC_CIC_COEF5_REG_CIC_COEF5_MASK (0x3ffff)

#define AUDIO_REG_ADC_CIC_COEF5_RESERVED_BIT_18_31_POS (18)
#define AUDIO_REG_ADC_CIC_COEF5_RESERVED_BIT_18_31_MASK (0x3fff)

#define AUDIO_REG_ADC_CIC_COEF6_ADDR (SOC_AUDIO_REG_REG_BASE + (0xf << 2))

#define AUDIO_REG_ADC_CIC_COEF6_REG_CIC_COEF6_POS (0)
#define AUDIO_REG_ADC_CIC_COEF6_REG_CIC_COEF6_MASK (0x3ffff)

#define AUDIO_REG_ADC_CIC_COEF6_RESERVED_BIT_18_31_POS (18)
#define AUDIO_REG_ADC_CIC_COEF6_RESERVED_BIT_18_31_MASK (0x3fff)

#define AUDIO_REG_ADC_CIC_COEF7_ADDR (SOC_AUDIO_REG_REG_BASE + (0x10 << 2))

#define AUDIO_REG_ADC_CIC_COEF7_REG_CIC_COEF7_POS (0)
#define AUDIO_REG_ADC_CIC_COEF7_REG_CIC_COEF7_MASK (0x3ffff)

#define AUDIO_REG_ADC_CIC_COEF7_RESERVED_BIT_18_31_POS (18)
#define AUDIO_REG_ADC_CIC_COEF7_RESERVED_BIT_18_31_MASK (0x3fff)

#define AUDIO_REG_MIC1_DBG_CTRL_ADDR (SOC_AUDIO_REG_REG_BASE + (0x11 << 2))

#define AUDIO_REG_MIC1_DBG_CTRL_RESERVED_BIT_0_3_POS (0)
#define AUDIO_REG_MIC1_DBG_CTRL_RESERVED_BIT_0_3_MASK (0xf)

#define AUDIO_REG_MIC1_DBG_CTRL_SPK2MIC_DBG_EN_POS (4)
#define AUDIO_REG_MIC1_DBG_CTRL_SPK2MIC_DBG_EN_MASK (0xff)

#define AUDIO_REG_MIC1_DBG_CTRL_RESERVED_BIT_12_15_POS (12)
#define AUDIO_REG_MIC1_DBG_CTRL_RESERVED_BIT_12_15_MASK (0xf)

#define AUDIO_REG_MIC1_DBG_CTRL_DAC_CFG_ANC_ADD_POS (16)
#define AUDIO_REG_MIC1_DBG_CTRL_DAC_CFG_ANC_ADD_MASK (0xf)

#define AUDIO_REG_MIC1_DBG_CTRL_DAC_CFG_DAC_ADD_POS (20)
#define AUDIO_REG_MIC1_DBG_CTRL_DAC_CFG_DAC_ADD_MASK (0x3)

#define AUDIO_REG_MIC1_DBG_CTRL_RESERVED_BIT_22_31_POS (22)
#define AUDIO_REG_MIC1_DBG_CTRL_RESERVED_BIT_22_31_MASK (0x3ff)

#define AUDIO_REG_BUF_CTRL_ADDR (SOC_AUDIO_REG_REG_BASE + (0x12 << 2))

#define AUDIO_REG_BUF_CTRL_EN_SPK0_POS (0)
#define AUDIO_REG_BUF_CTRL_EN_SPK0_MASK (0x7)

#define AUDIO_REG_BUF_CTRL_EN_SPK1_POS (3)
#define AUDIO_REG_BUF_CTRL_EN_SPK1_MASK (0x7)

#define AUDIO_REG_BUF_CTRL_EN_MIC_POS (6)
#define AUDIO_REG_BUF_CTRL_EN_MIC_MASK (0x3)

#define AUDIO_REG_BUF_CTRL_RESERVED_BIT_8_10_POS (8)
#define AUDIO_REG_BUF_CTRL_RESERVED_BIT_8_10_MASK (0x7)

#define AUDIO_REG_BUF_CTRL_DMA_MASK_SPK0_POS (11)
#define AUDIO_REG_BUF_CTRL_DMA_MASK_SPK0_MASK (0x7)

#define AUDIO_REG_BUF_CTRL_DMA_MASK_SPK1_POS (14)
#define AUDIO_REG_BUF_CTRL_DMA_MASK_SPK1_MASK (0x7)

#define AUDIO_REG_BUF_CTRL_DMA_MASK_MIC_POS (17)
#define AUDIO_REG_BUF_CTRL_DMA_MASK_MIC_MASK (0x3)

#define AUDIO_REG_BUF_CTRL_RESERVED_BIT_19_31_POS (19)
#define AUDIO_REG_BUF_CTRL_RESERVED_BIT_19_31_MASK (0x1fff)

#define AUDIO_REG_MIC_FIFO_CFG_ADDR (SOC_AUDIO_REG_REG_BASE + (0x13 << 2))

#define AUDIO_REG_MIC_FIFO_CFG_MIC0_WR_THRD_POS (0)
#define AUDIO_REG_MIC_FIFO_CFG_MIC0_WR_THRD_MASK (0x7f)

#define AUDIO_REG_MIC_FIFO_CFG_RESERVED_BIT_7_7_POS (7)
#define AUDIO_REG_MIC_FIFO_CFG_RESERVED_BIT_7_7_MASK (0x1)

#define AUDIO_REG_MIC_FIFO_CFG_MIC0_RD_THRD_POS (8)
#define AUDIO_REG_MIC_FIFO_CFG_MIC0_RD_THRD_MASK (0x7f)

#define AUDIO_REG_MIC_FIFO_CFG_MIC1_WR_THRD_POS (15)
#define AUDIO_REG_MIC_FIFO_CFG_MIC1_WR_THRD_MASK (0xf)

#define AUDIO_REG_MIC_FIFO_CFG_RESERVED_BIT_19_19_POS (19)
#define AUDIO_REG_MIC_FIFO_CFG_RESERVED_BIT_19_19_MASK (0x1)

#define AUDIO_REG_MIC_FIFO_CFG_MIC1_RD_THRD_POS (20)
#define AUDIO_REG_MIC_FIFO_CFG_MIC1_RD_THRD_MASK (0xf)

#define AUDIO_REG_MIC_FIFO_CFG_RESERVED_BIT_24_31_POS (24)
#define AUDIO_REG_MIC_FIFO_CFG_RESERVED_BIT_24_31_MASK (0xff)

#define AUDIO_REG_SPK0_FIFO_CFG_ADDR (SOC_AUDIO_REG_REG_BASE + (0x14 << 2))

#define AUDIO_REG_SPK0_FIFO_CFG_SPK0_HINT_WR_THRD_POS (0)
#define AUDIO_REG_SPK0_FIFO_CFG_SPK0_HINT_WR_THRD_MASK (0xf)

#define AUDIO_REG_SPK0_FIFO_CFG_SPK0_HINT_RD_THRD_POS (4)
#define AUDIO_REG_SPK0_FIFO_CFG_SPK0_HINT_RD_THRD_MASK (0xf)

#define AUDIO_REG_SPK0_FIFO_CFG_SPK0_CALL_WR_THRD_POS (8)
#define AUDIO_REG_SPK0_FIFO_CFG_SPK0_CALL_WR_THRD_MASK (0xf)

#define AUDIO_REG_SPK0_FIFO_CFG_SPK0_CALL_RD_THRD_POS (12)
#define AUDIO_REG_SPK0_FIFO_CFG_SPK0_CALL_RD_THRD_MASK (0xf)

#define AUDIO_REG_SPK0_FIFO_CFG_SPK0_A2DP_WR_THRD_POS (16)
#define AUDIO_REG_SPK0_FIFO_CFG_SPK0_A2DP_WR_THRD_MASK (0xf)

#define AUDIO_REG_SPK0_FIFO_CFG_SPK0_A2DP_RD_THRD_POS (20)
#define AUDIO_REG_SPK0_FIFO_CFG_SPK0_A2DP_RD_THRD_MASK (0xf)

#define AUDIO_REG_SPK0_FIFO_CFG_RESERVED_BIT_24_31_POS (24)
#define AUDIO_REG_SPK0_FIFO_CFG_RESERVED_BIT_24_31_MASK (0xff)

#define AUDIO_REG_SPK1_FIFO_CFG_ADDR (SOC_AUDIO_REG_REG_BASE + (0x15 << 2))

#define AUDIO_REG_SPK1_FIFO_CFG_SPK1_HINT_WR_THRD_POS (0)
#define AUDIO_REG_SPK1_FIFO_CFG_SPK1_HINT_WR_THRD_MASK (0xf)

#define AUDIO_REG_SPK1_FIFO_CFG_SPK1_HINT_RD_THRD_POS (4)
#define AUDIO_REG_SPK1_FIFO_CFG_SPK1_HINT_RD_THRD_MASK (0xf)

#define AUDIO_REG_SPK1_FIFO_CFG_SPK1_CALL_WR_THRD_POS (8)
#define AUDIO_REG_SPK1_FIFO_CFG_SPK1_CALL_WR_THRD_MASK (0xf)

#define AUDIO_REG_SPK1_FIFO_CFG_SPK1_CALL_RD_THRD_POS (12)
#define AUDIO_REG_SPK1_FIFO_CFG_SPK1_CALL_RD_THRD_MASK (0xf)

#define AUDIO_REG_SPK1_FIFO_CFG_SPK1_A2DP_WR_THRD_POS (16)
#define AUDIO_REG_SPK1_FIFO_CFG_SPK1_A2DP_WR_THRD_MASK (0xf)

#define AUDIO_REG_SPK1_FIFO_CFG_SPK1_A2DP_RD_THRD_POS (20)
#define AUDIO_REG_SPK1_FIFO_CFG_SPK1_A2DP_RD_THRD_MASK (0xf)

#define AUDIO_REG_SPK1_FIFO_CFG_RESERVED_BIT_24_31_POS (24)
#define AUDIO_REG_SPK1_FIFO_CFG_RESERVED_BIT_24_31_MASK (0xff)

#define AUDIO_REG_ADC_CUT_CFG_ADDR (SOC_AUDIO_REG_REG_BASE + (0x16 << 2))

#define AUDIO_REG_ADC_CUT_CFG_ADC_CUT0_POS (0)
#define AUDIO_REG_ADC_CUT_CFG_ADC_CUT0_MASK (0xf)

#define AUDIO_REG_ADC_CUT_CFG_ADC_CUT1_POS (4)
#define AUDIO_REG_ADC_CUT_CFG_ADC_CUT1_MASK (0xf)

#define AUDIO_REG_ADC_CUT_CFG_ADC_CUT2_POS (8)
#define AUDIO_REG_ADC_CUT_CFG_ADC_CUT2_MASK (0xf)

#define AUDIO_REG_ADC_CUT_CFG_ADC_CUT3_POS (12)
#define AUDIO_REG_ADC_CUT_CFG_ADC_CUT3_MASK (0xf)

#define AUDIO_REG_ADC_CUT_CFG_ADC_CUT4_POS (16)
#define AUDIO_REG_ADC_CUT_CFG_ADC_CUT4_MASK (0xf)

#define AUDIO_REG_ADC_CUT_CFG_RESERVED_BIT_20_31_POS (20)
#define AUDIO_REG_ADC_CUT_CFG_RESERVED_BIT_20_31_MASK (0xfff)

#define AUDIO_REG_IIR_SFT_CFG_ADDR (SOC_AUDIO_REG_REG_BASE + (0x17 << 2))

#define AUDIO_REG_IIR_SFT_CFG_DAC_EQ_SFT_R_SEL_0_POS (0)
#define AUDIO_REG_IIR_SFT_CFG_DAC_EQ_SFT_R_SEL_0_MASK (0x7)

#define AUDIO_REG_IIR_SFT_CFG_RESERVED_BIT_3_3_POS (3)
#define AUDIO_REG_IIR_SFT_CFG_RESERVED_BIT_3_3_MASK (0x1)

#define AUDIO_REG_IIR_SFT_CFG_DAC_EQ_SFT_R_SEL_1_POS (4)
#define AUDIO_REG_IIR_SFT_CFG_DAC_EQ_SFT_R_SEL_1_MASK (0x7)

#define AUDIO_REG_IIR_SFT_CFG_RESERVED_BIT_7_7_POS (7)
#define AUDIO_REG_IIR_SFT_CFG_RESERVED_BIT_7_7_MASK (0x1)

#define AUDIO_REG_IIR_SFT_CFG_DAC_EQ_SFT_L_SEL_0_POS (8)
#define AUDIO_REG_IIR_SFT_CFG_DAC_EQ_SFT_L_SEL_0_MASK (0x7)

#define AUDIO_REG_IIR_SFT_CFG_RESERVED_BIT_11_11_POS (11)
#define AUDIO_REG_IIR_SFT_CFG_RESERVED_BIT_11_11_MASK (0x1)

#define AUDIO_REG_IIR_SFT_CFG_DAC_EQ_SFT_L_SEL_1_POS (12)
#define AUDIO_REG_IIR_SFT_CFG_DAC_EQ_SFT_L_SEL_1_MASK (0x7)

#define AUDIO_REG_IIR_SFT_CFG_RESERVED_BIT_15_15_POS (15)
#define AUDIO_REG_IIR_SFT_CFG_RESERVED_BIT_15_15_MASK (0x1)

#define AUDIO_REG_IIR_SFT_CFG_COMP_EQ_SFT_R_SEL_0_POS (16)
#define AUDIO_REG_IIR_SFT_CFG_COMP_EQ_SFT_R_SEL_0_MASK (0x7)

#define AUDIO_REG_IIR_SFT_CFG_RESERVED_BIT_19_19_POS (19)
#define AUDIO_REG_IIR_SFT_CFG_RESERVED_BIT_19_19_MASK (0x1)

#define AUDIO_REG_IIR_SFT_CFG_COMP_EQ_SFT_R_SEL_1_POS (20)
#define AUDIO_REG_IIR_SFT_CFG_COMP_EQ_SFT_R_SEL_1_MASK (0x7)

#define AUDIO_REG_IIR_SFT_CFG_RESERVED_BIT_23_23_POS (23)
#define AUDIO_REG_IIR_SFT_CFG_RESERVED_BIT_23_23_MASK (0x1)

#define AUDIO_REG_IIR_SFT_CFG_COMP_EQ_SFT_L_SEL_0_POS (24)
#define AUDIO_REG_IIR_SFT_CFG_COMP_EQ_SFT_L_SEL_0_MASK (0x7)

#define AUDIO_REG_IIR_SFT_CFG_RESERVED_BIT_27_27_POS (27)
#define AUDIO_REG_IIR_SFT_CFG_RESERVED_BIT_27_27_MASK (0x1)

#define AUDIO_REG_IIR_SFT_CFG_COMP_EQ_SFT_L_SEL_1_POS (28)
#define AUDIO_REG_IIR_SFT_CFG_COMP_EQ_SFT_L_SEL_1_MASK (0x7)

#define AUDIO_REG_IIR_SFT_CFG_RESERVED_BIT_31_31_POS (31)
#define AUDIO_REG_IIR_SFT_CFG_RESERVED_BIT_31_31_MASK (0x1)

#define AUDIO_REG_DAC_CFG1_ADDR (SOC_AUDIO_REG_REG_BASE + (0x18 << 2))

#define AUDIO_REG_DAC_CFG1_DAC_PN_CONF_POS (0)
#define AUDIO_REG_DAC_CFG1_DAC_PN_CONF_MASK (0xf)

#define AUDIO_REG_DAC_CFG1_NOTCHEN_POS (4)
#define AUDIO_REG_DAC_CFG1_NOTCHEN_MASK (0x1)

#define AUDIO_REG_DAC_CFG1_SW_BOARD_POS (5)
#define AUDIO_REG_DAC_CFG1_SW_BOARD_MASK (0xf)

#define AUDIO_REG_DAC_CFG1_RESERVED_BIT_9_9_POS (9)
#define AUDIO_REG_DAC_CFG1_RESERVED_BIT_9_9_MASK (0x1)

#define AUDIO_REG_DAC_CFG1_CFG_DAC_WAIT_CNT_POS (10)
#define AUDIO_REG_DAC_CFG1_CFG_DAC_WAIT_CNT_MASK (0x1f)

#define AUDIO_REG_DAC_CFG1_RESERVED_BIT_15_15_POS (15)
#define AUDIO_REG_DAC_CFG1_RESERVED_BIT_15_15_MASK (0x1)

#define AUDIO_REG_DAC_CFG1_DAC_EQ_BPS_POS (16)
#define AUDIO_REG_DAC_CFG1_DAC_EQ_BPS_MASK (0x3ff)

#define AUDIO_REG_DAC_CFG1_RSP_BPS_POS (26)
#define AUDIO_REG_DAC_CFG1_RSP_BPS_MASK (0x1)

#define AUDIO_REG_DAC_CFG1_DAC_FRC_O_POS (27)
#define AUDIO_REG_DAC_CFG1_DAC_FRC_O_MASK (0x1)

#define AUDIO_REG_DAC_CFG1_DAC_FRC_HW_POS (28)
#define AUDIO_REG_DAC_CFG1_DAC_FRC_HW_MASK (0x1)

#define AUDIO_REG_DAC_CFG1_DAC_FRC_HW_MASK_POS (29)
#define AUDIO_REG_DAC_CFG1_DAC_FRC_HW_MASK_MASK (0x1)

#define AUDIO_REG_DAC_CFG1_RESERVED_BIT_30_31_POS (30)
#define AUDIO_REG_DAC_CFG1_RESERVED_BIT_30_31_MASK (0x3)

#define AUDIO_REG_ANC_CFG2_ADDR (SOC_AUDIO_REG_REG_BASE + (0x19 << 2))

#define AUDIO_REG_ANC_CFG2_ANC1_SFT_SEL_1_POS (0)
#define AUDIO_REG_ANC_CFG2_ANC1_SFT_SEL_1_MASK (0x7)

#define AUDIO_REG_ANC_CFG2_ANC1_SFT_SEL_2_POS (3)
#define AUDIO_REG_ANC_CFG2_ANC1_SFT_SEL_2_MASK (0x7)

#define AUDIO_REG_ANC_CFG2_ANC1_RSHIFT0_POS (6)
#define AUDIO_REG_ANC_CFG2_ANC1_RSHIFT0_MASK (0x7)

#define AUDIO_REG_ANC_CFG2_ANC1_RSHIFT1_POS (9)
#define AUDIO_REG_ANC_CFG2_ANC1_RSHIFT1_MASK (0x7)

#define AUDIO_REG_ANC_CFG2_RESERVED_BIT_12_12_POS (12)
#define AUDIO_REG_ANC_CFG2_RESERVED_BIT_12_12_MASK (0x1)

#define AUDIO_REG_ANC_CFG2_UP_SPL_SEL_POS (13)
#define AUDIO_REG_ANC_CFG2_UP_SPL_SEL_MASK (0x3)

#define AUDIO_REG_ANC_CFG2_RESERVED_BIT_15_16_POS (15)
#define AUDIO_REG_ANC_CFG2_RESERVED_BIT_15_16_MASK (0x3)

#define AUDIO_REG_ANC_CFG2_ANC2_SFT_SEL_1_POS (17)
#define AUDIO_REG_ANC_CFG2_ANC2_SFT_SEL_1_MASK (0x7)

#define AUDIO_REG_ANC_CFG2_ANC2_SFT_SEL_2_POS (20)
#define AUDIO_REG_ANC_CFG2_ANC2_SFT_SEL_2_MASK (0x7)

#define AUDIO_REG_ANC_CFG2_ANC2_RSHIFT0_POS (23)
#define AUDIO_REG_ANC_CFG2_ANC2_RSHIFT0_MASK (0x7)

#define AUDIO_REG_ANC_CFG2_ANC2_RSHIFT1_POS (26)
#define AUDIO_REG_ANC_CFG2_ANC2_RSHIFT1_MASK (0x7)

#define AUDIO_REG_ANC_CFG2_ANC_SPL_SEL_POS (29)
#define AUDIO_REG_ANC_CFG2_ANC_SPL_SEL_MASK (0x3)

#define AUDIO_REG_ANC_CFG2_DAC_SDM_DIS_POS (31)
#define AUDIO_REG_ANC_CFG2_DAC_SDM_DIS_MASK (0x1)

#define AUDIO_REG_RAMP_UP_CFG_ADDR (SOC_AUDIO_REG_REG_BASE + (0x1a << 2))

#define AUDIO_REG_RAMP_UP_CFG_ANC_COMP_EN_POS (0)
#define AUDIO_REG_RAMP_UP_CFG_ANC_COMP_EN_MASK (0x3)

#define AUDIO_REG_RAMP_UP_CFG_COMP_RAMP_DOWN_TRIG_POS (2)
#define AUDIO_REG_RAMP_UP_CFG_COMP_RAMP_DOWN_TRIG_MASK (0x3)

#define AUDIO_REG_RAMP_UP_CFG_COMP_RAMP_CFG_POS (4)
#define AUDIO_REG_RAMP_UP_CFG_COMP_RAMP_CFG_MASK (0x7)

#define AUDIO_REG_RAMP_UP_CFG_RESERVED_BIT_7_10_POS (7)
#define AUDIO_REG_RAMP_UP_CFG_RESERVED_BIT_7_10_MASK (0xf)

#define AUDIO_REG_RAMP_UP_CFG_COMP_RAMP_BPS_POS (11)
#define AUDIO_REG_RAMP_UP_CFG_COMP_RAMP_BPS_MASK (0x3)

#define AUDIO_REG_RAMP_UP_CFG_EQ_RAMP_DOWN_TRIG_POS (13)
#define AUDIO_REG_RAMP_UP_CFG_EQ_RAMP_DOWN_TRIG_MASK (0x3)

#define AUDIO_REG_RAMP_UP_CFG_EQ_RAMP_CFG_POS (15)
#define AUDIO_REG_RAMP_UP_CFG_EQ_RAMP_CFG_MASK (0x7)

#define AUDIO_REG_RAMP_UP_CFG_RESERVED_BIT_18_21_POS (18)
#define AUDIO_REG_RAMP_UP_CFG_RESERVED_BIT_18_21_MASK (0xf)

#define AUDIO_REG_RAMP_UP_CFG_EQ_RAMP_BPS_POS (22)
#define AUDIO_REG_RAMP_UP_CFG_EQ_RAMP_BPS_MASK (0x3)

#define AUDIO_REG_RAMP_UP_CFG_EQ_RAMP_UP_TRIG_POS (24)
#define AUDIO_REG_RAMP_UP_CFG_EQ_RAMP_UP_TRIG_MASK (0x3)

#define AUDIO_REG_RAMP_UP_CFG_COMP_RAMP_UP_TRIG_POS (26)
#define AUDIO_REG_RAMP_UP_CFG_COMP_RAMP_UP_TRIG_MASK (0x3)

#define AUDIO_REG_RAMP_UP_CFG_RESERVED_BIT_28_31_POS (28)
#define AUDIO_REG_RAMP_UP_CFG_RESERVED_BIT_28_31_MASK (0xf)

#define AUDIO_REG_ANC1_GAIN_CFG1_ADDR (SOC_AUDIO_REG_REG_BASE + (0x1b << 2))

#define AUDIO_REG_ANC1_GAIN_CFG1_ANC1_GAIN1_1_POS (0)
#define AUDIO_REG_ANC1_GAIN_CFG1_ANC1_GAIN1_1_MASK (0x7fffffff)

#define AUDIO_REG_ANC1_GAIN_CFG1_RESERVED_BIT_31_31_POS (31)
#define AUDIO_REG_ANC1_GAIN_CFG1_RESERVED_BIT_31_31_MASK (0x1)

#define AUDIO_REG_ANC1_GAIN_CFG2_ADDR (SOC_AUDIO_REG_REG_BASE + (0x1c << 2))

#define AUDIO_REG_ANC1_GAIN_CFG2_ANC1_GAIN_COMP_POS (0)
#define AUDIO_REG_ANC1_GAIN_CFG2_ANC1_GAIN_COMP_MASK (0x7fffffff)

#define AUDIO_REG_ANC1_GAIN_CFG2_RESERVED_BIT_31_31_POS (31)
#define AUDIO_REG_ANC1_GAIN_CFG2_RESERVED_BIT_31_31_MASK (0x1)

#define AUDIO_REG_ANC1_GAIN_CFG3_ADDR (SOC_AUDIO_REG_REG_BASE + (0x1d << 2))

#define AUDIO_REG_ANC1_GAIN_CFG3_ANC1_GAIN0_1_POS (0)
#define AUDIO_REG_ANC1_GAIN_CFG3_ANC1_GAIN0_1_MASK (0x7fffffff)

#define AUDIO_REG_ANC1_GAIN_CFG3_RESERVED_BIT_31_31_POS (31)
#define AUDIO_REG_ANC1_GAIN_CFG3_RESERVED_BIT_31_31_MASK (0x1)

#define AUDIO_REG_ANC1_GAIN_CFG4_ADDR (SOC_AUDIO_REG_REG_BASE + (0x1f << 2))

#define AUDIO_REG_ANC1_GAIN_CFG4_ANC1_GAIN0_0_POS (0)
#define AUDIO_REG_ANC1_GAIN_CFG4_ANC1_GAIN0_0_MASK (0x7fffffff)

#define AUDIO_REG_ANC1_GAIN_CFG4_RESERVED_BIT_31_31_POS (31)
#define AUDIO_REG_ANC1_GAIN_CFG4_RESERVED_BIT_31_31_MASK (0x1)

#define AUDIO_REG_SYNC_CTRL1_ADDR (SOC_AUDIO_REG_REG_BASE + (0x20 << 2))

#define AUDIO_REG_SYNC_CTRL1_SYNC_A2DP_CNT_POS (0)
#define AUDIO_REG_SYNC_CTRL1_SYNC_A2DP_CNT_MASK (0x1fff)

#define AUDIO_REG_SYNC_CTRL1_START_A2DP_CNT_POS (13)
#define AUDIO_REG_SYNC_CTRL1_START_A2DP_CNT_MASK (0x7)

#define AUDIO_REG_SYNC_CTRL1_SYNC_CALL_CNT_POS (16)
#define AUDIO_REG_SYNC_CTRL1_SYNC_CALL_CNT_MASK (0x1fff)

#define AUDIO_REG_SYNC_CTRL1_START_CALL_CNT_POS (29)
#define AUDIO_REG_SYNC_CTRL1_START_CALL_CNT_MASK (0x7)

#define AUDIO_REG_SYNC_CTRL2_ADDR (SOC_AUDIO_REG_REG_BASE + (0x21 << 2))

#define AUDIO_REG_SYNC_CTRL2_SYNC_HINT_CNT_POS (0)
#define AUDIO_REG_SYNC_CTRL2_SYNC_HINT_CNT_MASK (0x1fff)

#define AUDIO_REG_SYNC_CTRL2_START_HINT_CNT_POS (13)
#define AUDIO_REG_SYNC_CTRL2_START_HINT_CNT_MASK (0x7)

#define AUDIO_REG_SYNC_CTRL2_RESERVED_BIT_16_31_POS (16)
#define AUDIO_REG_SYNC_CTRL2_RESERVED_BIT_16_31_MASK (0xffff)

#define AUDIO_REG_DAC_RO_STS_ADDR (SOC_AUDIO_REG_REG_BASE + (0x24 << 2))

#define AUDIO_REG_DAC_RO_STS_DAC_FIFO_STATUS_POS (0)
#define AUDIO_REG_DAC_RO_STS_DAC_FIFO_STATUS_MASK (0xfff)

#define AUDIO_REG_DAC_RO_STS_RESERVED_BIT_12_30_POS (12)
#define AUDIO_REG_DAC_RO_STS_RESERVED_BIT_12_30_MASK (0x7ffff)

#define AUDIO_REG_DAC_RO_STS_MEM_AUTO_INIT_DONE_POS (31)
#define AUDIO_REG_DAC_RO_STS_MEM_AUTO_INIT_DONE_MASK (0x1)

#define AUDIO_REG_ADC_RO_STS_ADDR (SOC_AUDIO_REG_REG_BASE + (0x25 << 2))

#define AUDIO_REG_ADC_RO_STS_ADC_FIFO_STATUS_POS (0)
#define AUDIO_REG_ADC_RO_STS_ADC_FIFO_STATUS_MASK (0xf)

#define AUDIO_REG_ADC_RO_STS_RESERVED_BIT_4_31_POS (4)
#define AUDIO_REG_ADC_RO_STS_RESERVED_BIT_4_31_MASK (0xfffffff)

#define AUDIO_REG_ANC_STS_ADDR (SOC_AUDIO_REG_REG_BASE + (0x26 << 2))

#define AUDIO_REG_ANC_STS_ANC_STATUS_POS (0)
#define AUDIO_REG_ANC_STS_ANC_STATUS_MASK (0xffffffff)

#define AUDIO_REG_RAMP_INTR_CTRL_ADDR (SOC_AUDIO_REG_REG_BASE + (0x27 << 2))

#define AUDIO_REG_RAMP_INTR_CTRL_RAMP_INTERRUPT_MASK_POS (0)
#define AUDIO_REG_RAMP_INTR_CTRL_RAMP_INTERRUPT_MASK_MASK (0x3ff)

#define AUDIO_REG_RAMP_INTR_CTRL_IIR_OVL_INT_MASK_POS (10)
#define AUDIO_REG_RAMP_INTR_CTRL_IIR_OVL_INT_MASK_MASK (0x3f)

#define AUDIO_REG_RAMP_INTR_CTRL_RAMP_INTERRUPT_CLR_POS (16)
#define AUDIO_REG_RAMP_INTR_CTRL_RAMP_INTERRUPT_CLR_MASK (0x3ff)

#define AUDIO_REG_RAMP_INTR_CTRL_IIR_OVL_INT_CLR_POS (26)
#define AUDIO_REG_RAMP_INTR_CTRL_IIR_OVL_INT_CLR_MASK (0x3f)

#define AUDIO_REG_AUD_INT_CTRL_ADDR (SOC_AUDIO_REG_REG_BASE + (0x28 << 2))

#define AUDIO_REG_AUD_INT_CTRL_AUD_INTERRUPT_MASK_POS (0)
#define AUDIO_REG_AUD_INT_CTRL_AUD_INTERRUPT_MASK_MASK (0xffff)

#define AUDIO_REG_AUD_INT_CTRL_AUD_INTERRUPT_CLR_POS (16)
#define AUDIO_REG_AUD_INT_CTRL_AUD_INTERRUPT_CLR_MASK (0xffff)

#define AUDIO_REG_AUD_INT_STS_ADDR (SOC_AUDIO_REG_REG_BASE + (0x29 << 2))

#define AUDIO_REG_AUD_INT_STS_AUD_INTERRUPT_STATUS_POS (0)
#define AUDIO_REG_AUD_INT_STS_AUD_INTERRUPT_STATUS_MASK (0x7fffffff)

#define AUDIO_REG_AUD_INT_STS_RESERVED_BIT_31_31_POS (31)
#define AUDIO_REG_AUD_INT_STS_RESERVED_BIT_31_31_MASK (0x1)

#define AUDIO_REG_ANC2_LIMIT_CFG1_ADDR (SOC_AUDIO_REG_REG_BASE + (0x2a << 2))

#define AUDIO_REG_ANC2_LIMIT_CFG1_ANC2_LIMIT_VAL1_POS (0)
#define AUDIO_REG_ANC2_LIMIT_CFG1_ANC2_LIMIT_VAL1_MASK (0xffffff)

#define AUDIO_REG_ANC2_LIMIT_CFG1_RESERVED_BIT_24_30_POS (24)
#define AUDIO_REG_ANC2_LIMIT_CFG1_RESERVED_BIT_24_30_MASK (0x7f)

#define AUDIO_REG_ANC2_LIMIT_CFG1_ANC2_LIMIT_BPS1_POS (31)
#define AUDIO_REG_ANC2_LIMIT_CFG1_ANC2_LIMIT_BPS1_MASK (0x1)

#define AUDIO_REG_ANC2_LIMIT_CFG2_ADDR (SOC_AUDIO_REG_REG_BASE + (0x2b << 2))

#define AUDIO_REG_ANC2_LIMIT_CFG2_ANC2_LIMIT_VAL2_POS (0)
#define AUDIO_REG_ANC2_LIMIT_CFG2_ANC2_LIMIT_VAL2_MASK (0xffffff)

#define AUDIO_REG_ANC2_LIMIT_CFG2_RESERVED_BIT_24_30_POS (24)
#define AUDIO_REG_ANC2_LIMIT_CFG2_RESERVED_BIT_24_30_MASK (0x7f)

#define AUDIO_REG_ANC2_LIMIT_CFG2_ANC2_LIMIT_BPS2_POS (31)
#define AUDIO_REG_ANC2_LIMIT_CFG2_ANC2_LIMIT_BPS2_MASK (0x1)

#define AUDIO_REG_ANC1_LIMIT_CFG1_ADDR (SOC_AUDIO_REG_REG_BASE + (0x2c << 2))

#define AUDIO_REG_ANC1_LIMIT_CFG1_ANC1_LIMIT_VAL1_POS (0)
#define AUDIO_REG_ANC1_LIMIT_CFG1_ANC1_LIMIT_VAL1_MASK (0xffffff)

#define AUDIO_REG_ANC1_LIMIT_CFG1_RESERVED_BIT_24_30_POS (24)
#define AUDIO_REG_ANC1_LIMIT_CFG1_RESERVED_BIT_24_30_MASK (0x7f)

#define AUDIO_REG_ANC1_LIMIT_CFG1_ANC1_LIMIT_BPS1_POS (31)
#define AUDIO_REG_ANC1_LIMIT_CFG1_ANC1_LIMIT_BPS1_MASK (0x1)

#define AUDIO_REG_ANC1_LIMIT_CFG2_ADDR (SOC_AUDIO_REG_REG_BASE + (0x2d << 2))

#define AUDIO_REG_ANC1_LIMIT_CFG2_ANC1_LIMIT_VAL2_POS (0)
#define AUDIO_REG_ANC1_LIMIT_CFG2_ANC1_LIMIT_VAL2_MASK (0xffffff)

#define AUDIO_REG_ANC1_LIMIT_CFG2_RESERVED_BIT_24_30_POS (24)
#define AUDIO_REG_ANC1_LIMIT_CFG2_RESERVED_BIT_24_30_MASK (0x7f)

#define AUDIO_REG_ANC1_LIMIT_CFG2_ANC1_LIMIT_BPS2_POS (31)
#define AUDIO_REG_ANC1_LIMIT_CFG2_ANC1_LIMIT_BPS2_MASK (0x1)

#define AUDIO_REG_ANC2_GAIN_CFG1_ADDR (SOC_AUDIO_REG_REG_BASE + (0x2e << 2))

#define AUDIO_REG_ANC2_GAIN_CFG1_ANC2_GAIN1_1_POS (0)
#define AUDIO_REG_ANC2_GAIN_CFG1_ANC2_GAIN1_1_MASK (0x7fffffff)

#define AUDIO_REG_ANC2_GAIN_CFG1_RESERVED_BIT_31_31_POS (31)
#define AUDIO_REG_ANC2_GAIN_CFG1_RESERVED_BIT_31_31_MASK (0x1)

#define AUDIO_REG_ANC2_GAIN_CFG2_ADDR (SOC_AUDIO_REG_REG_BASE + (0x2f << 2))

#define AUDIO_REG_ANC2_GAIN_CFG2_ANC2_GAIN_COMP_POS (0)
#define AUDIO_REG_ANC2_GAIN_CFG2_ANC2_GAIN_COMP_MASK (0x7fffffff)

#define AUDIO_REG_ANC2_GAIN_CFG2_RESERVED_BIT_31_31_POS (31)
#define AUDIO_REG_ANC2_GAIN_CFG2_RESERVED_BIT_31_31_MASK (0x1)

#define AUDIO_REG_ANC2_GAIN_CFG3_ADDR (SOC_AUDIO_REG_REG_BASE + (0x30 << 2))

#define AUDIO_REG_ANC2_GAIN_CFG3_ANC2_GAIN0_1_POS (0)
#define AUDIO_REG_ANC2_GAIN_CFG3_ANC2_GAIN0_1_MASK (0x7fffffff)

#define AUDIO_REG_ANC2_GAIN_CFG3_RESERVED_BIT_31_31_POS (31)
#define AUDIO_REG_ANC2_GAIN_CFG3_RESERVED_BIT_31_31_MASK (0x1)

#define AUDIO_REG_ANC2_GAIN_CFG4_ADDR (SOC_AUDIO_REG_REG_BASE + (0x31 << 2))

#define AUDIO_REG_ANC2_GAIN_CFG4_ANC2_GAIN0_0_POS (0)
#define AUDIO_REG_ANC2_GAIN_CFG4_ANC2_GAIN0_0_MASK (0x7fffffff)

#define AUDIO_REG_ANC2_GAIN_CFG4_RESERVED_BIT_31_31_POS (31)
#define AUDIO_REG_ANC2_GAIN_CFG4_RESERVED_BIT_31_31_MASK (0x1)

#define AUDIO_REG_ANC_COMP_CFG_ADDR (SOC_AUDIO_REG_REG_BASE + (0x32 << 2))

#define AUDIO_REG_ANC_COMP_CFG_COMP_IIR_BPS_POS (0)
#define AUDIO_REG_ANC_COMP_CFG_COMP_IIR_BPS_MASK (0x3ff)

#define AUDIO_REG_ANC_COMP_CFG_DAC_COMP_SPL_POS (10)
#define AUDIO_REG_ANC_COMP_CFG_DAC_COMP_SPL_MASK (0x3)

#define AUDIO_REG_ANC_COMP_CFG_RESERVED_BIT_12_15_POS (12)
#define AUDIO_REG_ANC_COMP_CFG_RESERVED_BIT_12_15_MASK (0xf)

#define AUDIO_REG_ANC_COMP_CFG_ANC_CFG_START_VAL_POS (16)
#define AUDIO_REG_ANC_COMP_CFG_ANC_CFG_START_VAL_MASK (0x1ff)

#define AUDIO_REG_ANC_COMP_CFG_RESERVED_BIT_25_31_POS (25)
#define AUDIO_REG_ANC_COMP_CFG_RESERVED_BIT_25_31_MASK (0x7f)

#define AUDIO_REG_DAC_GAIN_CFG0_ADDR (SOC_AUDIO_REG_REG_BASE + (0x33 << 2))

#define AUDIO_REG_DAC_GAIN_CFG0_SPK0_A2DP_GAIN_POS (0)
#define AUDIO_REG_DAC_GAIN_CFG0_SPK0_A2DP_GAIN_MASK (0x7fffffff)

#define AUDIO_REG_DAC_GAIN_CFG0_RESERVED_BIT_31_31_POS (31)
#define AUDIO_REG_DAC_GAIN_CFG0_RESERVED_BIT_31_31_MASK (0x1)

#define AUDIO_REG_DAC_GAIN_CFG1_ADDR (SOC_AUDIO_REG_REG_BASE + (0x34 << 2))

#define AUDIO_REG_DAC_GAIN_CFG1_SPK0_CALL_GAIN_POS (0)
#define AUDIO_REG_DAC_GAIN_CFG1_SPK0_CALL_GAIN_MASK (0x7fffffff)

#define AUDIO_REG_DAC_GAIN_CFG1_RESERVED_BIT_31_31_POS (31)
#define AUDIO_REG_DAC_GAIN_CFG1_RESERVED_BIT_31_31_MASK (0x1)

#define AUDIO_REG_DAC_GAIN_CFG2_ADDR (SOC_AUDIO_REG_REG_BASE + (0x35 << 2))

#define AUDIO_REG_DAC_GAIN_CFG2_SPK0_HINT_GAIN_POS (0)
#define AUDIO_REG_DAC_GAIN_CFG2_SPK0_HINT_GAIN_MASK (0x7fffffff)

#define AUDIO_REG_DAC_GAIN_CFG2_RESERVED_BIT_31_31_POS (31)
#define AUDIO_REG_DAC_GAIN_CFG2_RESERVED_BIT_31_31_MASK (0x1)

#define AUDIO_REG_DAC_GAIN_CFG3_ADDR (SOC_AUDIO_REG_REG_BASE + (0x36 << 2))

#define AUDIO_REG_DAC_GAIN_CFG3_SPK1_A2DP_GAIN_POS (0)
#define AUDIO_REG_DAC_GAIN_CFG3_SPK1_A2DP_GAIN_MASK (0x7fffffff)

#define AUDIO_REG_DAC_GAIN_CFG3_RESERVED_BIT_31_31_POS (31)
#define AUDIO_REG_DAC_GAIN_CFG3_RESERVED_BIT_31_31_MASK (0x1)

#define AUDIO_REG_DAC_GAIN_CFG4_ADDR (SOC_AUDIO_REG_REG_BASE + (0x37 << 2))

#define AUDIO_REG_DAC_GAIN_CFG4_SPK1_CALL_GAIN_POS (0)
#define AUDIO_REG_DAC_GAIN_CFG4_SPK1_CALL_GAIN_MASK (0x7fffffff)

#define AUDIO_REG_DAC_GAIN_CFG4_RESERVED_BIT_31_31_POS (31)
#define AUDIO_REG_DAC_GAIN_CFG4_RESERVED_BIT_31_31_MASK (0x1)

#define AUDIO_REG_DAC_GAIN_CFG5_ADDR (SOC_AUDIO_REG_REG_BASE + (0x38 << 2))

#define AUDIO_REG_DAC_GAIN_CFG5_SPK1_HINT_GAIN_POS (0)
#define AUDIO_REG_DAC_GAIN_CFG5_SPK1_HINT_GAIN_MASK (0x7fffffff)

#define AUDIO_REG_DAC_GAIN_CFG5_RESERVED_BIT_31_31_POS (31)
#define AUDIO_REG_DAC_GAIN_CFG5_RESERVED_BIT_31_31_MASK (0x1)

#define AUDIO_REG_ADC_GAIN_CFG1_ADDR (SOC_AUDIO_REG_REG_BASE + (0x39 << 2))

#define AUDIO_REG_ADC_GAIN_CFG1_ADC_CHN1_GAIN_POS (0)
#define AUDIO_REG_ADC_GAIN_CFG1_ADC_CHN1_GAIN_MASK (0x1ffff)

#define AUDIO_REG_ADC_GAIN_CFG1_RESERVED_BIT_17_31_POS (17)
#define AUDIO_REG_ADC_GAIN_CFG1_RESERVED_BIT_17_31_MASK (0x7fff)

#define AUDIO_REG_DAC_L_GAIN_MIX_ADDR (SOC_AUDIO_REG_REG_BASE + (0x3a << 2))

#define AUDIO_REG_DAC_L_GAIN_MIX_DAC_L_GAIN_POS (0)
#define AUDIO_REG_DAC_L_GAIN_MIX_DAC_L_GAIN_MASK (0x7fffffff)

#define AUDIO_REG_DAC_L_GAIN_MIX_RESERVED_BIT_31_31_POS (31)
#define AUDIO_REG_DAC_L_GAIN_MIX_RESERVED_BIT_31_31_MASK (0x1)

#define AUDIO_REG_DAC_R_GAIN_MIX_ADDR (SOC_AUDIO_REG_REG_BASE + (0x3b << 2))

#define AUDIO_REG_DAC_R_GAIN_MIX_DAC_R_GAIN_POS (0)
#define AUDIO_REG_DAC_R_GAIN_MIX_DAC_R_GAIN_MASK (0x7fffffff)

#define AUDIO_REG_DAC_R_GAIN_MIX_RESERVED_BIT_31_31_POS (31)
#define AUDIO_REG_DAC_R_GAIN_MIX_RESERVED_BIT_31_31_MASK (0x1)

#define AUDIO_REG_ADC_GAIN_CFG2_ADDR (SOC_AUDIO_REG_REG_BASE + (0x40 << 2))

#define AUDIO_REG_ADC_GAIN_CFG2_ADC_CHN0_GAIN_POS (0)
#define AUDIO_REG_ADC_GAIN_CFG2_ADC_CHN0_GAIN_MASK (0x1ffff)

#define AUDIO_REG_ADC_GAIN_CFG2_RESERVED_BIT_17_31_POS (17)
#define AUDIO_REG_ADC_GAIN_CFG2_RESERVED_BIT_17_31_MASK (0x7fff)

#define AUDIO_REG_ADC_GAIN_CFG3_ADDR (SOC_AUDIO_REG_REG_BASE + (0x41 << 2))

#define AUDIO_REG_ADC_GAIN_CFG3_ADC_CHN4_GAIN_POS (0)
#define AUDIO_REG_ADC_GAIN_CFG3_ADC_CHN4_GAIN_MASK (0x1ffff)

#define AUDIO_REG_ADC_GAIN_CFG3_RESERVED_BIT_17_31_POS (17)
#define AUDIO_REG_ADC_GAIN_CFG3_RESERVED_BIT_17_31_MASK (0x7fff)

#define AUDIO_REG_ADC_GAIN_CFG4_ADDR (SOC_AUDIO_REG_REG_BASE + (0x42 << 2))

#define AUDIO_REG_ADC_GAIN_CFG4_ADC_CHN3_GAIN_POS (0)
#define AUDIO_REG_ADC_GAIN_CFG4_ADC_CHN3_GAIN_MASK (0x1ffff)

#define AUDIO_REG_ADC_GAIN_CFG4_RESERVED_BIT_17_31_POS (17)
#define AUDIO_REG_ADC_GAIN_CFG4_RESERVED_BIT_17_31_MASK (0x7fff)

#define AUDIO_REG_ADC_GAIN_CFG5_ADDR (SOC_AUDIO_REG_REG_BASE + (0x43 << 2))

#define AUDIO_REG_ADC_GAIN_CFG5_ADC_CHN2_GAIN_POS (0)
#define AUDIO_REG_ADC_GAIN_CFG5_ADC_CHN2_GAIN_MASK (0x1ffff)

#define AUDIO_REG_ADC_GAIN_CFG5_RESERVED_BIT_17_31_POS (17)
#define AUDIO_REG_ADC_GAIN_CFG5_RESERVED_BIT_17_31_MASK (0x7fff)

#define AUDIO_REG_ANC_SFT_L_PARA_ADDR (SOC_AUDIO_REG_REG_BASE + (0x44 << 2))

#define AUDIO_REG_ANC_SFT_L_PARA_ANC_IF_SFT_L_0_POS (0)
#define AUDIO_REG_ANC_SFT_L_PARA_ANC_IF_SFT_L_0_MASK (0x7)

#define AUDIO_REG_ANC_SFT_L_PARA_RESERVED_BIT_3_3_POS (3)
#define AUDIO_REG_ANC_SFT_L_PARA_RESERVED_BIT_3_3_MASK (0x1)

#define AUDIO_REG_ANC_SFT_L_PARA_ANC_IF_SFT_L_1_POS (4)
#define AUDIO_REG_ANC_SFT_L_PARA_ANC_IF_SFT_L_1_MASK (0x7)

#define AUDIO_REG_ANC_SFT_L_PARA_RESERVED_BIT_7_7_POS (7)
#define AUDIO_REG_ANC_SFT_L_PARA_RESERVED_BIT_7_7_MASK (0x1)

#define AUDIO_REG_ANC_SFT_L_PARA_ANC_IF_SFT_L_2_POS (8)
#define AUDIO_REG_ANC_SFT_L_PARA_ANC_IF_SFT_L_2_MASK (0x7)

#define AUDIO_REG_ANC_SFT_L_PARA_RESERVED_BIT_11_11_POS (11)
#define AUDIO_REG_ANC_SFT_L_PARA_RESERVED_BIT_11_11_MASK (0x1)

#define AUDIO_REG_ANC_SFT_L_PARA_ANC_IF_SFT_L_3_POS (12)
#define AUDIO_REG_ANC_SFT_L_PARA_ANC_IF_SFT_L_3_MASK (0x7)

#define AUDIO_REG_ANC_SFT_L_PARA_RESERVED_BIT_15_15_POS (15)
#define AUDIO_REG_ANC_SFT_L_PARA_RESERVED_BIT_15_15_MASK (0x1)

#define AUDIO_REG_ANC_SFT_L_PARA_ANC_IF_SFT_L_4_POS (16)
#define AUDIO_REG_ANC_SFT_L_PARA_ANC_IF_SFT_L_4_MASK (0x7)

#define AUDIO_REG_ANC_SFT_L_PARA_RESERVED_BIT_19_19_POS (19)
#define AUDIO_REG_ANC_SFT_L_PARA_RESERVED_BIT_19_19_MASK (0x1)

#define AUDIO_REG_ANC_SFT_L_PARA_ANC_IF_SFT_L_5_POS (20)
#define AUDIO_REG_ANC_SFT_L_PARA_ANC_IF_SFT_L_5_MASK (0x7)

#define AUDIO_REG_ANC_SFT_L_PARA_RESERVED_BIT_23_31_POS (23)
#define AUDIO_REG_ANC_SFT_L_PARA_RESERVED_BIT_23_31_MASK (0x1ff)

#define AUDIO_REG_ANC_SFT_R_PARA_ADDR (SOC_AUDIO_REG_REG_BASE + (0x45 << 2))

#define AUDIO_REG_ANC_SFT_R_PARA_ANC_IF_SFT_R_0_POS (0)
#define AUDIO_REG_ANC_SFT_R_PARA_ANC_IF_SFT_R_0_MASK (0x7)

#define AUDIO_REG_ANC_SFT_R_PARA_RESERVED_BIT_3_3_POS (3)
#define AUDIO_REG_ANC_SFT_R_PARA_RESERVED_BIT_3_3_MASK (0x1)

#define AUDIO_REG_ANC_SFT_R_PARA_ANC_IF_SFT_R_1_POS (4)
#define AUDIO_REG_ANC_SFT_R_PARA_ANC_IF_SFT_R_1_MASK (0x7)

#define AUDIO_REG_ANC_SFT_R_PARA_RESERVED_BIT_7_7_POS (7)
#define AUDIO_REG_ANC_SFT_R_PARA_RESERVED_BIT_7_7_MASK (0x1)

#define AUDIO_REG_ANC_SFT_R_PARA_ANC_IF_SFT_R_2_POS (8)
#define AUDIO_REG_ANC_SFT_R_PARA_ANC_IF_SFT_R_2_MASK (0x7)

#define AUDIO_REG_ANC_SFT_R_PARA_RESERVED_BIT_11_11_POS (11)
#define AUDIO_REG_ANC_SFT_R_PARA_RESERVED_BIT_11_11_MASK (0x1)

#define AUDIO_REG_ANC_SFT_R_PARA_ANC_IF_SFT_R_3_POS (12)
#define AUDIO_REG_ANC_SFT_R_PARA_ANC_IF_SFT_R_3_MASK (0x7)

#define AUDIO_REG_ANC_SFT_R_PARA_RESERVED_BIT_15_15_POS (15)
#define AUDIO_REG_ANC_SFT_R_PARA_RESERVED_BIT_15_15_MASK (0x1)

#define AUDIO_REG_ANC_SFT_R_PARA_ANC_IF_SFT_R_4_POS (16)
#define AUDIO_REG_ANC_SFT_R_PARA_ANC_IF_SFT_R_4_MASK (0x7)

#define AUDIO_REG_ANC_SFT_R_PARA_RESERVED_BIT_19_19_POS (19)
#define AUDIO_REG_ANC_SFT_R_PARA_RESERVED_BIT_19_19_MASK (0x1)

#define AUDIO_REG_ANC_SFT_R_PARA_ANC_IF_SFT_R_5_POS (20)
#define AUDIO_REG_ANC_SFT_R_PARA_ANC_IF_SFT_R_5_MASK (0x7)

#define AUDIO_REG_ANC_SFT_R_PARA_RESERVED_BIT_23_31_POS (23)
#define AUDIO_REG_ANC_SFT_R_PARA_RESERVED_BIT_23_31_MASK (0x1ff)

#define AUDIO_REG_K_VAL_0_ADDR (SOC_AUDIO_REG_REG_BASE + (0x46 << 2))

#define AUDIO_REG_K_VAL_0_K_VAL_0_POS (0)
#define AUDIO_REG_K_VAL_0_K_VAL_0_MASK (0xffff)

#define AUDIO_REG_K_VAL_0_RESERVED_BIT_16_31_POS (16)
#define AUDIO_REG_K_VAL_0_RESERVED_BIT_16_31_MASK (0xffff)

#define AUDIO_REG_K_VAL_1_ADDR (SOC_AUDIO_REG_REG_BASE + (0x47 << 2))

#define AUDIO_REG_K_VAL_1_K_VAL_1_POS (0)
#define AUDIO_REG_K_VAL_1_K_VAL_1_MASK (0xffff)

#define AUDIO_REG_K_VAL_1_RESERVED_BIT_16_31_POS (16)
#define AUDIO_REG_K_VAL_1_RESERVED_BIT_16_31_MASK (0xffff)

#define AUDIO_REG_K_VAL_2_ADDR (SOC_AUDIO_REG_REG_BASE + (0x48 << 2))

#define AUDIO_REG_K_VAL_2_K_VAL_2_POS (0)
#define AUDIO_REG_K_VAL_2_K_VAL_2_MASK (0xffff)

#define AUDIO_REG_K_VAL_2_RESERVED_BIT_16_31_POS (16)
#define AUDIO_REG_K_VAL_2_RESERVED_BIT_16_31_MASK (0xffff)

#define AUDIO_REG_K_VAL_3_ADDR (SOC_AUDIO_REG_REG_BASE + (0x49 << 2))

#define AUDIO_REG_K_VAL_3_K_VAL_3_POS (0)
#define AUDIO_REG_K_VAL_3_K_VAL_3_MASK (0xffff)

#define AUDIO_REG_K_VAL_3_RESERVED_BIT_16_31_POS (16)
#define AUDIO_REG_K_VAL_3_RESERVED_BIT_16_31_MASK (0xffff)

#define AUDIO_REG_K_VAL_4_ADDR (SOC_AUDIO_REG_REG_BASE + (0x4a << 2))

#define AUDIO_REG_K_VAL_4_K_VAL_4_POS (0)
#define AUDIO_REG_K_VAL_4_K_VAL_4_MASK (0xffff)

#define AUDIO_REG_K_VAL_4_RESERVED_BIT_16_31_POS (16)
#define AUDIO_REG_K_VAL_4_RESERVED_BIT_16_31_MASK (0xffff)

#define AUDIO_REG_K_VAL_5_ADDR (SOC_AUDIO_REG_REG_BASE + (0x4b << 2))

#define AUDIO_REG_K_VAL_5_K_VAL_5_POS (0)
#define AUDIO_REG_K_VAL_5_K_VAL_5_MASK (0xffff)

#define AUDIO_REG_K_VAL_5_RESERVED_BIT_16_31_POS (16)
#define AUDIO_REG_K_VAL_5_RESERVED_BIT_16_31_MASK (0xffff)

#define AUDIO_REG_K_VAL_6_ADDR (SOC_AUDIO_REG_REG_BASE + (0x4c << 2))

#define AUDIO_REG_K_VAL_6_K_VAL_6_POS (0)
#define AUDIO_REG_K_VAL_6_K_VAL_6_MASK (0xffff)

#define AUDIO_REG_K_VAL_6_RESERVED_BIT_16_31_POS (16)
#define AUDIO_REG_K_VAL_6_RESERVED_BIT_16_31_MASK (0xffff)

#define AUDIO_REG_K_VAL_7_ADDR (SOC_AUDIO_REG_REG_BASE + (0x4d << 2))

#define AUDIO_REG_K_VAL_7_K_VAL_7_POS (0)
#define AUDIO_REG_K_VAL_7_K_VAL_7_MASK (0xffff)

#define AUDIO_REG_K_VAL_7_RESERVED_BIT_16_31_POS (16)
#define AUDIO_REG_K_VAL_7_RESERVED_BIT_16_31_MASK (0xffff)

#define AUDIO_REG_ST_VAL_0_ADDR (SOC_AUDIO_REG_REG_BASE + (0x4e << 2))

#define AUDIO_REG_ST_VAL_0_ST_VAL_0_POS (0)
#define AUDIO_REG_ST_VAL_0_ST_VAL_0_MASK (0xffffff)

#define AUDIO_REG_ST_VAL_0_RESERVED_BIT_24_31_POS (24)
#define AUDIO_REG_ST_VAL_0_RESERVED_BIT_24_31_MASK (0xff)

#define AUDIO_REG_ST_VAL_1_ADDR (SOC_AUDIO_REG_REG_BASE + (0x4f << 2))

#define AUDIO_REG_ST_VAL_1_ST_VAL_1_POS (0)
#define AUDIO_REG_ST_VAL_1_ST_VAL_1_MASK (0xffffff)

#define AUDIO_REG_ST_VAL_1_RESERVED_BIT_24_31_POS (24)
#define AUDIO_REG_ST_VAL_1_RESERVED_BIT_24_31_MASK (0xff)

#define AUDIO_REG_ST_VAL_2_ADDR (SOC_AUDIO_REG_REG_BASE + (0x50 << 2))

#define AUDIO_REG_ST_VAL_2_ST_VAL_2_POS (0)
#define AUDIO_REG_ST_VAL_2_ST_VAL_2_MASK (0xffffff)

#define AUDIO_REG_ST_VAL_2_RESERVED_BIT_24_31_POS (24)
#define AUDIO_REG_ST_VAL_2_RESERVED_BIT_24_31_MASK (0xff)

#define AUDIO_REG_ST_VAL_3_ADDR (SOC_AUDIO_REG_REG_BASE + (0x51 << 2))

#define AUDIO_REG_ST_VAL_3_ST_VAL_3_POS (0)
#define AUDIO_REG_ST_VAL_3_ST_VAL_3_MASK (0xffffff)

#define AUDIO_REG_ST_VAL_3_RESERVED_BIT_24_31_POS (24)
#define AUDIO_REG_ST_VAL_3_RESERVED_BIT_24_31_MASK (0xff)

#define AUDIO_REG_ST_VAL_4_ADDR (SOC_AUDIO_REG_REG_BASE + (0x52 << 2))

#define AUDIO_REG_ST_VAL_4_ST_VAL_4_POS (0)
#define AUDIO_REG_ST_VAL_4_ST_VAL_4_MASK (0xffffff)

#define AUDIO_REG_ST_VAL_4_RESERVED_BIT_24_31_POS (24)
#define AUDIO_REG_ST_VAL_4_RESERVED_BIT_24_31_MASK (0xff)

#define AUDIO_REG_ST_VAL_5_ADDR (SOC_AUDIO_REG_REG_BASE + (0x53 << 2))

#define AUDIO_REG_ST_VAL_5_ST_VAL_5_POS (0)
#define AUDIO_REG_ST_VAL_5_ST_VAL_5_MASK (0xffffff)

#define AUDIO_REG_ST_VAL_5_RESERVED_BIT_24_31_POS (24)
#define AUDIO_REG_ST_VAL_5_RESERVED_BIT_24_31_MASK (0xff)

#define AUDIO_REG_ST_VAL_6_ADDR (SOC_AUDIO_REG_REG_BASE + (0x54 << 2))

#define AUDIO_REG_ST_VAL_6_ST_VAL_6_POS (0)
#define AUDIO_REG_ST_VAL_6_ST_VAL_6_MASK (0xffffff)

#define AUDIO_REG_ST_VAL_6_RESERVED_BIT_24_31_POS (24)
#define AUDIO_REG_ST_VAL_6_RESERVED_BIT_24_31_MASK (0xff)

#define AUDIO_REG_ST_VAL_7_ADDR (SOC_AUDIO_REG_REG_BASE + (0x55 << 2))

#define AUDIO_REG_ST_VAL_7_ST_VAL_7_POS (0)
#define AUDIO_REG_ST_VAL_7_ST_VAL_7_MASK (0xffffff)

#define AUDIO_REG_ST_VAL_7_RESERVED_BIT_24_31_POS (24)
#define AUDIO_REG_ST_VAL_7_RESERVED_BIT_24_31_MASK (0xff)

#define AUDIO_REG_P_VAL_0_ADDR (SOC_AUDIO_REG_REG_BASE + (0x56 << 2))

#define AUDIO_REG_P_VAL_0_P_VAL_0_POS (0)
#define AUDIO_REG_P_VAL_0_P_VAL_0_MASK (0xff)

#define AUDIO_REG_P_VAL_0_RESERVED_BIT_8_31_POS (8)
#define AUDIO_REG_P_VAL_0_RESERVED_BIT_8_31_MASK (0xffffff)

#define AUDIO_REG_P_VAL_1_ADDR (SOC_AUDIO_REG_REG_BASE + (0x57 << 2))

#define AUDIO_REG_P_VAL_1_P_VAL_1_POS (0)
#define AUDIO_REG_P_VAL_1_P_VAL_1_MASK (0xff)

#define AUDIO_REG_P_VAL_1_RESERVED_BIT_8_31_POS (8)
#define AUDIO_REG_P_VAL_1_RESERVED_BIT_8_31_MASK (0xffffff)

#define AUDIO_REG_P_VAL_2_ADDR (SOC_AUDIO_REG_REG_BASE + (0x58 << 2))

#define AUDIO_REG_P_VAL_2_P_VAL_2_POS (0)
#define AUDIO_REG_P_VAL_2_P_VAL_2_MASK (0xff)

#define AUDIO_REG_P_VAL_2_RESERVED_BIT_8_31_POS (8)
#define AUDIO_REG_P_VAL_2_RESERVED_BIT_8_31_MASK (0xffffff)

#define AUDIO_REG_P_VAL_3_ADDR (SOC_AUDIO_REG_REG_BASE + (0x59 << 2))

#define AUDIO_REG_P_VAL_3_P_VAL_3_POS (0)
#define AUDIO_REG_P_VAL_3_P_VAL_3_MASK (0xff)

#define AUDIO_REG_P_VAL_3_RESERVED_BIT_8_31_POS (8)
#define AUDIO_REG_P_VAL_3_RESERVED_BIT_8_31_MASK (0xffffff)

#define AUDIO_REG_P_VAL_4_ADDR (SOC_AUDIO_REG_REG_BASE + (0x5a << 2))

#define AUDIO_REG_P_VAL_4_P_VAL_4_POS (0)
#define AUDIO_REG_P_VAL_4_P_VAL_4_MASK (0xff)

#define AUDIO_REG_P_VAL_4_RESERVED_BIT_8_31_POS (8)
#define AUDIO_REG_P_VAL_4_RESERVED_BIT_8_31_MASK (0xffffff)

#define AUDIO_REG_P_VAL_5_ADDR (SOC_AUDIO_REG_REG_BASE + (0x5b << 2))

#define AUDIO_REG_P_VAL_5_P_VAL_5_POS (0)
#define AUDIO_REG_P_VAL_5_P_VAL_5_MASK (0xff)

#define AUDIO_REG_P_VAL_5_RESERVED_BIT_8_31_POS (8)
#define AUDIO_REG_P_VAL_5_RESERVED_BIT_8_31_MASK (0xffffff)

#define AUDIO_REG_P_VAL_6_ADDR (SOC_AUDIO_REG_REG_BASE + (0x5c << 2))

#define AUDIO_REG_P_VAL_6_P_VAL_6_POS (0)
#define AUDIO_REG_P_VAL_6_P_VAL_6_MASK (0xff)

#define AUDIO_REG_P_VAL_6_RESERVED_BIT_8_31_POS (8)
#define AUDIO_REG_P_VAL_6_RESERVED_BIT_8_31_MASK (0xffffff)

#define AUDIO_REG_ANC_IIR_BPS_ADDR (SOC_AUDIO_REG_REG_BASE + (0x5d << 2))

#define AUDIO_REG_ANC_IIR_BPS_ANC_IIR_BPS0_POS (0)
#define AUDIO_REG_ANC_IIR_BPS_ANC_IIR_BPS0_MASK (0x3ff)

#define AUDIO_REG_ANC_IIR_BPS_ANC_IIR_BPS1_POS (10)
#define AUDIO_REG_ANC_IIR_BPS_ANC_IIR_BPS1_MASK (0x3ff)

#define AUDIO_REG_ANC_IIR_BPS_ANC_IIR_BPS2_POS (20)
#define AUDIO_REG_ANC_IIR_BPS_ANC_IIR_BPS2_MASK (0x3ff)

#define AUDIO_REG_ANC_IIR_BPS_RESERVED_BIT_30_31_POS (30)
#define AUDIO_REG_ANC_IIR_BPS_RESERVED_BIT_30_31_MASK (0x3)

#define AUDIO_REG_INTERFACE_MATRIX_ADDR (SOC_AUDIO_REG_REG_BASE + (0x5e << 2))

#define AUDIO_REG_INTERFACE_MATRIX_ADC_CHN0_SEL_POS (0)
#define AUDIO_REG_INTERFACE_MATRIX_ADC_CHN0_SEL_MASK (0x7)

#define AUDIO_REG_INTERFACE_MATRIX_RESERVED_BIT_3_3_POS (3)
#define AUDIO_REG_INTERFACE_MATRIX_RESERVED_BIT_3_3_MASK (0x1)

#define AUDIO_REG_INTERFACE_MATRIX_ADC_CHN1_SEL_POS (4)
#define AUDIO_REG_INTERFACE_MATRIX_ADC_CHN1_SEL_MASK (0x7)

#define AUDIO_REG_INTERFACE_MATRIX_RESERVED_BIT_7_7_POS (7)
#define AUDIO_REG_INTERFACE_MATRIX_RESERVED_BIT_7_7_MASK (0x1)

#define AUDIO_REG_INTERFACE_MATRIX_ADC_CHN2_SEL_POS (8)
#define AUDIO_REG_INTERFACE_MATRIX_ADC_CHN2_SEL_MASK (0x7)

#define AUDIO_REG_INTERFACE_MATRIX_RESERVED_BIT_11_11_POS (11)
#define AUDIO_REG_INTERFACE_MATRIX_RESERVED_BIT_11_11_MASK (0x1)

#define AUDIO_REG_INTERFACE_MATRIX_ADC_CHN3_SEL_POS (12)
#define AUDIO_REG_INTERFACE_MATRIX_ADC_CHN3_SEL_MASK (0x7)

#define AUDIO_REG_INTERFACE_MATRIX_RESERVED_BIT_15_15_POS (15)
#define AUDIO_REG_INTERFACE_MATRIX_RESERVED_BIT_15_15_MASK (0x1)

#define AUDIO_REG_INTERFACE_MATRIX_ADC_CHN4_SEL_POS (16)
#define AUDIO_REG_INTERFACE_MATRIX_ADC_CHN4_SEL_MASK (0x7)

#define AUDIO_REG_INTERFACE_MATRIX_RESERVED_BIT_19_19_POS (19)
#define AUDIO_REG_INTERFACE_MATRIX_RESERVED_BIT_19_19_MASK (0x1)

#define AUDIO_REG_INTERFACE_MATRIX_DAC_R_CHN_SEL_POS (20)
#define AUDIO_REG_INTERFACE_MATRIX_DAC_R_CHN_SEL_MASK (0x1)

#define AUDIO_REG_INTERFACE_MATRIX_DAC_L_CHN_SEL_POS (21)
#define AUDIO_REG_INTERFACE_MATRIX_DAC_L_CHN_SEL_MASK (0x1)

#define AUDIO_REG_INTERFACE_MATRIX_CLK_FRC_ON_POS (22)
#define AUDIO_REG_INTERFACE_MATRIX_CLK_FRC_ON_MASK (0x1f)

#define AUDIO_REG_INTERFACE_MATRIX_RESERVED_BIT_27_31_POS (27)
#define AUDIO_REG_INTERFACE_MATRIX_RESERVED_BIT_27_31_MASK (0x1f)

#ifdef __cplusplus
}
#endif
