// Copyright 2020-2025 Beken
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#pragma once

#ifdef __cplusplus
extern "C" {
#endif

#include <stdio.h>
#include <driver/hal/hal_gpio_types.h>
#include <driver/hal/hal_io_matrix_types.h>
#include <soc/soc.h>
#include "sdkconfig.h"

#define GPIO_DEV_MAP  \
{\
	{GPIO_0, {GPIO_DEV_UART1_TXD, GPIO_DEV_I2C1_SCL, GPIO_DEV_JTAG_TCK, GPIO_DEV_SCR_IO, GPIO_DEV_ADC12, GPIO_DEV_LIN_TXD, GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
	{GPIO_1, {GPIO_DEV_UART1_RXD, GPIO_DEV_I2C1_SDA, GPIO_DEV_JTAG_TMS, GPIO_DEV_SCR_CLK, GPIO_DEV_ADC13, GPIO_DEV_LIN_RXD, GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
	{GPIO_2, {GPIO_DEV_SPI1_SCK, GPIO_DEV_SDIO_HOST_CLK, GPIO_DEV_INVALID, GPIO_DEV_SCR_RSTN, GPIO_DEV_LIN_SLEEP, GPIO_DEV_DEBUG0, GPIO_DEV_QSPI1_CLK, GPIO_DEV_INVALID}},\
	{GPIO_3, {GPIO_DEV_SPI1_CSN, GPIO_DEV_SDIO_HOST_CMD, GPIO_DEV_INVALID, GPIO_DEV_SCR_VCC, GPIO_DEV_INVALID, GPIO_DEV_DEBUG1, GPIO_DEV_QSPI1_CSN, GPIO_DEV_INVALID}},\
	{GPIO_4, {GPIO_DEV_SPI1_MOSI, GPIO_DEV_SDIO_HOST_DATA0, GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_DEBUG2, GPIO_DEV_QSPI1_IO0, GPIO_DEV_INVALID}},\
	{GPIO_5, {GPIO_DEV_SPI1_MISO, GPIO_DEV_SDIO_HOST_DATA1, GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_DEBUG3, GPIO_DEV_QSPI1_IO1, GPIO_DEV_INVALID}},\
	{GPIO_6, {GPIO_DEV_CLK13M, GPIO_DEV_PWM0, GPIO_DEV_I2S1_CLK, GPIO_DEV_INVALID, GPIO_DEV_ADC8, GPIO_DEV_DEBUG4, GPIO_DEV_QSPI1_IO2, GPIO_DEV_INVALID}},\
	{GPIO_7, {GPIO_DEV_WIFI_ACTIVE, GPIO_DEV_PWM1, GPIO_DEV_I2S1_SYNC, GPIO_DEV_INVALID, GPIO_DEV_ADC9, GPIO_DEV_DEBUG5, GPIO_DEV_QSPI1_IO3, GPIO_DEV_INVALID}},\
	{GPIO_8, {GPIO_DEV_BT_ACTIVE, GPIO_DEV_PWM2, GPIO_DEV_I2S1_DIN, GPIO_DEV_DMIC1_CLK, GPIO_DEV_ADC10, GPIO_DEV_DEBUG6, GPIO_DEV_CLK_32K_XO, GPIO_DEV_INVALID}},\
	{GPIO_9, {GPIO_DEV_BT_PRIORITY, GPIO_DEV_PWM3, GPIO_DEV_I2S1_DOUT, GPIO_DEV_DMIC1_DAT, GPIO_DEV_ADC11, GPIO_DEV_DEBUG7, GPIO_DEV_CLK_32K_XI, GPIO_DEV_INVALID}},\
	{GPIO_10,{GPIO_DEV_UART0_RXD, GPIO_DEV_SDIO_HOST_DATA2, GPIO_DEV_CLK_AUXS, GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
	{GPIO_11, {GPIO_DEV_UART0_TXD, GPIO_DEV_SDIO_HOST_DATA3, GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
	{GPIO_12, {GPIO_DEV_UART0_RTS, GPIO_DEV_USB0_DP, GPIO_DEV_INVALID, GPIO_DEV_TOUCH0, GPIO_DEV_ADC14, GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
	{GPIO_13, {GPIO_DEV_UART0_CTS, GPIO_DEV_USB0_DN, GPIO_DEV_INVALID, GPIO_DEV_TOUCH1, GPIO_DEV_ADC15, GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
	{GPIO_14, {GPIO_DEV_SDIO_HOST_CLK, GPIO_DEV_SPI0_SCK, GPIO_DEV_BT_ANT0, GPIO_DEV_I2C1_SCL, GPIO_DEV_LCD_CLK, GPIO_DEV_DEBUG8, GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
	{GPIO_15, {GPIO_DEV_SDIO_HOST_CMD, GPIO_DEV_SPI0_CSN, GPIO_DEV_BT_ANT1, GPIO_DEV_I2C1_SDA, GPIO_DEV_LCD_DISP, GPIO_DEV_DEBUG9, GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
	{GPIO_16, {GPIO_DEV_SDIO_HOST_DATA0, GPIO_DEV_SPI0_MOSI, GPIO_DEV_BT_ANT2, GPIO_DEV_INVALID, GPIO_DEV_LCD_DE, GPIO_DEV_DEBUG10, GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
	{GPIO_17, {GPIO_DEV_SDIO_HOST_DATA1, GPIO_DEV_SPI0_MISO, GPIO_DEV_BT_ANT3, GPIO_DEV_INVALID, GPIO_DEV_LCD_HSYNC, GPIO_DEV_DEBUG11, GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
	{GPIO_18, {GPIO_DEV_SDIO_HOST_DATA2, GPIO_DEV_PWM0, GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_LCD_VSYNC, GPIO_DEV_DEBUG12, GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
	{GPIO_19, {GPIO_DEV_SDIO_HOST_DATA3, GPIO_DEV_PWM1, GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_LCD_R7, GPIO_DEV_DEBUG13, GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
	{GPIO_20, {GPIO_DEV_I2C0_SCL, GPIO_DEV_JTAG_TCK, GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_LCD_R6, GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
	{GPIO_21, {GPIO_DEV_I2C0_SDA, GPIO_DEV_JTAG_TMS, GPIO_DEV_ADC6,  GPIO_DEV_INVALID, GPIO_DEV_LCD_R5, GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
	{GPIO_22, {GPIO_DEV_CLK26M, GPIO_DEV_PWM2, GPIO_DEV_ADC5, GPIO_DEV_QSPI0_CLK, GPIO_DEV_LCD_R4, GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
	{GPIO_23, {GPIO_DEV_INVALID, GPIO_DEV_PWM3, GPIO_DEV_ADC3, GPIO_DEV_QSPI0_CSN, GPIO_DEV_LCD_R3, GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
	{GPIO_24, {GPIO_DEV_LPO_CLK, GPIO_DEV_PWM4, GPIO_DEV_ADC2,  GPIO_DEV_QSPI0_IO0, GPIO_DEV_LCD_G7, GPIO_DEV_DEBUG14, GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
	{GPIO_25, {GPIO_DEV_IRDA, GPIO_DEV_PWM5, GPIO_DEV_ADC1, GPIO_DEV_QSPI0_IO1, GPIO_DEV_LCD_G6, GPIO_DEV_DEBUG15, GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
	{GPIO_26, {GPIO_DEV_TXEN, GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_QSPI0_IO2, GPIO_DEV_LCD_G5, GPIO_DEV_DEBUG16, GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
	{GPIO_27, {GPIO_DEV_JPEG_MCLK, GPIO_DEV_CLK_AUXS_CIS, GPIO_DEV_ENET_PHY_INT, GPIO_DEV_QSPI0_IO3, GPIO_DEV_INVALID, GPIO_DEV_DEBUG17, GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
	{GPIO_28, {GPIO_DEV_RXEN, GPIO_DEV_I2S1_MCLK,  GPIO_DEV_ADC4, GPIO_DEV_TOUCH2, GPIO_DEV_CLK_AUXS, GPIO_DEV_DEBUG18, GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
	{GPIO_29, {GPIO_DEV_JPEG_PCLK, GPIO_DEV_INVALID, GPIO_DEV_ENET_MDC, GPIO_DEV_TOUCH3, GPIO_DEV_INVALID, GPIO_DEV_DEBUG19, GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
	{GPIO_30, {GPIO_DEV_JPEG_HSYNC, GPIO_DEV_UART2_RXD, GPIO_DEV_LIN_RXD, GPIO_DEV_TOUCH4, GPIO_DEV_SCR_CLK, GPIO_DEV_DEBUG20, GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
	{GPIO_31, {GPIO_DEV_JPEG_VSYNC, GPIO_DEV_UART2_TXD, GPIO_DEV_LIN_TXD, GPIO_DEV_TOUCH5, GPIO_DEV_SCR_IO, GPIO_DEV_DEBUG21, GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
	{GPIO_32, {GPIO_DEV_JPEG_PXDATA0, GPIO_DEV_PWM6, GPIO_DEV_ENET_MDIO, GPIO_DEV_TOUCH6, GPIO_DEV_SCR_RSTN, GPIO_DEV_DEBUG22, GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
	{GPIO_33, {GPIO_DEV_JPEG_PXDATA1, GPIO_DEV_PWM7, GPIO_DEV_ENET_RXD0, GPIO_DEV_TOUCH7, GPIO_DEV_SPI0_SCK, GPIO_DEV_DEBUG23, GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
	{GPIO_34, {GPIO_DEV_JPEG_PXDATA2, GPIO_DEV_PWM8, GPIO_DEV_ENET_RXD1, GPIO_DEV_TOUCH8, GPIO_DEV_SPI0_CSN, GPIO_DEV_DEBUG24, GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
	{GPIO_35, {GPIO_DEV_JPEG_PXDATA3, GPIO_DEV_PWM9, GPIO_DEV_ENET_RXDV, GPIO_DEV_TOUCH9, GPIO_DEV_SPI0_MOSI, GPIO_DEV_DEBUG25, GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
	{GPIO_36, {GPIO_DEV_JPEG_PXDATA4, GPIO_DEV_PWM10, GPIO_DEV_ENET_TXD0, GPIO_DEV_TOUCH10, GPIO_DEV_SPI0_MISO, GPIO_DEV_DEBUG26, GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
	{GPIO_37, {GPIO_DEV_JPEG_PXDATA5, GPIO_DEV_PWM11, GPIO_DEV_ENET_TXD1, GPIO_DEV_TOUCH11, GPIO_DEV_INVALID, GPIO_DEV_DEBUG27, GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
	{GPIO_38, {GPIO_DEV_JPEG_PXDATA6, GPIO_DEV_I2C1_SCL, GPIO_DEV_ENET_TXEN, GPIO_DEV_TOUCH12, GPIO_DEV_INVALID, GPIO_DEV_DEBUG28, GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
	{GPIO_39, {GPIO_DEV_JPEG_PXDATA7, GPIO_DEV_I2C1_SDA, GPIO_DEV_ENET_REF_CLK, GPIO_DEV_TOUCH13, GPIO_DEV_INVALID, GPIO_DEV_DEBUG29, GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
	{GPIO_40, {GPIO_DEV_UART2_RXD, GPIO_DEV_I2S2_CLK, GPIO_DEV_LIN_RXD, GPIO_DEV_SCR_CLK, GPIO_DEV_LCD_G4, GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
	{GPIO_41, {GPIO_DEV_UART2_TXD, GPIO_DEV_I2S2_SYNC, GPIO_DEV_LIN_TXD, GPIO_DEV_SCR_IO, GPIO_DEV_LCD_G3, GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
	{GPIO_42, {GPIO_DEV_I2C1_SCL, GPIO_DEV_I2S2_DIN, GPIO_DEV_LIN_SLEEP, GPIO_DEV_SCR_RSTN, GPIO_DEV_LCD_G2, GPIO_DEV_DEBUG30, GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
	{GPIO_43, {GPIO_DEV_I2C1_SDA, GPIO_DEV_I2S2_DOUT, GPIO_DEV_INVALID, GPIO_DEV_SCR_VCC, GPIO_DEV_LCD_B7, GPIO_DEV_DEBUG31, GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
	{GPIO_44, {GPIO_DEV_CAN_TX, GPIO_DEV_SPI0_SCK, GPIO_DEV_ADC10, GPIO_DEV_INVALID, GPIO_DEV_LCD_B6, GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_I2S3_CLK}},\
	{GPIO_45, {GPIO_DEV_CAN_RX, GPIO_DEV_SPI0_CSN, GPIO_DEV_ADC11, GPIO_DEV_INVALID, GPIO_DEV_LCD_B5, GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_I2S3_SYNC}},\
	{GPIO_46, {GPIO_DEV_CAN_STANDBY, GPIO_DEV_SPI0_MOSI, GPIO_DEV_ENET_PHY_INT, GPIO_DEV_TOUCH14, GPIO_DEV_LCD_B4, GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_I2S3_DIN}},\
	{GPIO_47, {GPIO_DEV_INVALID, GPIO_DEV_SPI0_MISO, GPIO_DEV_ENET_MDC, GPIO_DEV_TOUCH15, GPIO_DEV_LCD_B3, GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_I2S3_DOUT}},\
	{GPIO_48, {GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_ENET_MDIO, GPIO_DEV_INVALID, GPIO_DEV_LCD_R2, GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
	{GPIO_49, {GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_ENET_RXD0, GPIO_DEV_INVALID, GPIO_DEV_LCD_R1, GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
	{GPIO_50, {GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_ENET_RXD1, GPIO_DEV_INVALID, GPIO_DEV_LCD_R0, GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
	{GPIO_51, {GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_ENET_RXDV, GPIO_DEV_INVALID, GPIO_DEV_LCD_G1, GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
	{GPIO_52, {GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_ENET_TXD0, GPIO_DEV_INVALID, GPIO_DEV_LCD_G0, GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
	{GPIO_53, {GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_ENET_TXD1, GPIO_DEV_INVALID, GPIO_DEV_LCD_B2, GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
	{GPIO_54, {GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_ENET_TXEN, GPIO_DEV_INVALID, GPIO_DEV_LCD_B1, GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
	{GPIO_55, {GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_ENET_REF_CLK, GPIO_DEV_INVALID, GPIO_DEV_LCD_B0, GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
	{GPIO_64, {GPIO_DEV_UART5_RXD, GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
	{GPIO_65, {GPIO_DEV_UART5_TXD, GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_INVALID, GPIO_DEV_INVALID}},\
}

#if CONFIG_GPIO_DEFAULT_SET_SUPPORT
/*
 typedef struct {
	 uint32_t gpio_id:				 6;  //gpio_id_t

	 uint32_t second_func_en:		 1;  //gpio_func_mode_t
	 uint32_t second_func_dev:		 8;  //gpio_dev_t

	 uint32_t io_mode:				 2;  //gpio_io_mode_t
	 uint32_t pull_mode:			 2;  //gpio_pull_mode_t

	 uint32_t int_en:				 1;  //gpio_int_mode_t
	 uint32_t int_type: 			 2;  //gpio_int_type_t

	 uint32_t low_power_io_ctrl:	 2;  //gpio_lowpower_mode_t

	 uint32_t driver_capacity:		2;	//gpio_driver_capacity_t
 }gpio_default_map_t;
 */

#if CONFIG_SPE
#define GPIO_0_DEFAULT_MAP {GPIO_0,  GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_I2C1_SCL, GPIO_IO_DISABLE, GPIO_PULL_UP_EN, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3},
#define GPIO_1_DEFAULT_MAP {GPIO_1,  GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_I2C1_SDA, GPIO_IO_DISABLE, GPIO_PULL_UP_EN, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3},
#else
#define GPIO_0_DEFAULT_MAP
#define GPIO_1_DEFAULT_MAP
#endif

#define GPIO_DEFAULT_DEV_CONFIG  \
{\
	GPIO_0_DEFAULT_MAP \
	GPIO_1_DEFAULT_MAP \
	{GPIO_2,  GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_SDIO_HOST_CLK, GPIO_IO_DISABLE, GPIO_PULL_UP_EN, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3},\
	{GPIO_3,  GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_SDIO_HOST_CMD, GPIO_IO_DISABLE, GPIO_PULL_UP_EN, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3},\
	{GPIO_4,  GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_SDIO_HOST_DATA0, GPIO_IO_DISABLE, GPIO_PULL_UP_EN, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3},\
	{GPIO_5,  GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0},\
	{GPIO_6,  GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_I2S1_CLK, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0},\
	{GPIO_7,  GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_I2S1_SYNC, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0},\
	{GPIO_8,  GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_INVALID, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_KEEP_INPUT_STATUS, GPIO_DRIVER_CAPACITY_0},\
	{GPIO_9,  GPIO_SECOND_FUNC_DISABLE, GPIO_DEV_I2S1_DOUT, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_KEEP_INPUT_STATUS, GPIO_DRIVER_CAPACITY_0},\
	{GPIO_10, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_UART0_RXD, GPIO_IO_DISABLE, GPIO_PULL_UP_EN, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0},\
	{GPIO_11, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_UART0_TXD, GPIO_IO_DISABLE, GPIO_PULL_UP_EN, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0},\
	{GPIO_12, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_USB0_DP, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0},\
	{GPIO_13, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_USB0_DN, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0},\
	{GPIO_14, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_LCD_CLK, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0},\
	{GPIO_15, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_LCD_DISP, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0},\
	{GPIO_16, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_LCD_DE, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0},\
	{GPIO_17, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_LCD_HSYNC, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0},\
	{GPIO_18, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_LCD_VSYNC, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0},\
	{GPIO_19, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_LCD_R7, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0},\
	{GPIO_20, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_LCD_R6, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0},\
	{GPIO_21, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_LCD_R5, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0},\
	{GPIO_22, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_LCD_R4, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0},\
	{GPIO_23, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_LCD_R3, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0},\
	{GPIO_24, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_LCD_G7, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0},\
	{GPIO_25, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_LCD_G6, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0},\
	{GPIO_26, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_LCD_G5, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0},\
	{GPIO_27, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_JPEG_MCLK, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0},\
	{GPIO_28, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_I2S1_MCLK, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0},\
	{GPIO_29, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_JPEG_PCLK, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0},\
	{GPIO_30, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_JPEG_HSYNC, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0},\
	{GPIO_31, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_JPEG_VSYNC, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0},\
	{GPIO_32, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_JPEG_PXDATA0, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0},\
	{GPIO_33, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_JPEG_PXDATA1, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0},\
	{GPIO_34, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_JPEG_PXDATA2, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0},\
	{GPIO_35, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_JPEG_PXDATA3, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0},\
	{GPIO_36, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_JPEG_PXDATA4, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0},\
	{GPIO_37, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_JPEG_PXDATA5, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0},\
	{GPIO_38, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_JPEG_PXDATA6, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0},\
	{GPIO_39, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_JPEG_PXDATA7, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_0},\
	{GPIO_40, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_LCD_G4, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1},\
	{GPIO_41, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_LCD_G3, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1},\
	{GPIO_42, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_LCD_G2, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1},\
	{GPIO_43, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_LCD_B7, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1},\
	{GPIO_44, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_LCD_B6, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1},\
	{GPIO_45, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_LCD_B5, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1},\
	{GPIO_46, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_LCD_B4, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1},\
	{GPIO_47, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_LCD_B3, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1},\
	{GPIO_48, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_LCD_R2, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1},\
	{GPIO_49, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_LCD_R1, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1},\
	{GPIO_50, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_LCD_R0, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1},\
	{GPIO_51, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_LCD_G1, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1},\
	{GPIO_52, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_LCD_G0, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1},\
	{GPIO_53, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_LCD_B2, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1},\
	{GPIO_54, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_LCD_B1, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1},\
	{GPIO_55, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_LCD_B0, GPIO_IO_DISABLE, GPIO_PULL_DISABLE, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_1},\
	{GPIO_64, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_UART5_RXD, GPIO_IO_DISABLE, GPIO_PULL_UP_EN, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3},\
	{GPIO_65, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_UART5_TXD, GPIO_IO_DISABLE, GPIO_PULL_UP_EN, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3},\
}


#endif

/* uart gpio pin map */
#define UART0_TX_PIN  CONFIG_UART0_TX_PIN
#define UART0_RX_PIN  CONFIG_UART0_RX_PIN
#define UART0_CTS_PIN CONFIG_UART0_CTS_PIN
#define UART0_RTS_PIN CONFIG_UART0_RTS_PIN

#define UART1_TX_PIN  CONFIG_UART1_TX_PIN
#define UART1_RX_PIN  CONFIG_UART1_RX_PIN

#define UART2_TX_PIN  CONFIG_UART2_TX_PIN
#define UART2_RX_PIN  CONFIG_UART2_RX_PIN

#define UART3_TX_PIN  CONFIG_UART3_TX_PIN
#define UART3_RX_PIN  CONFIG_UART3_RX_PIN

#define UART4_TX_PIN  CONFIG_UART4_TX_PIN
#define UART4_RX_PIN  CONFIG_UART4_RX_PIN

#define UART5_TX_PIN  CONFIG_UART5_TX_PIN
#define UART5_RX_PIN  CONFIG_UART5_RX_PIN

/* sdio host */
#if CONFIG_SDCARD_BUSWIDTH_4LINE
#define SDIO_HOST_GPIO_PIN_NUMBER    6
#else
#define SDIO_HOST_GPIO_PIN_NUMBER    3
#endif
#define SDIO_HOST_GPIO_CLK_INDEX     0
#define SDIO_HOST_GPIO_CMD_INDEX     1
#define SDIO_HOST_GPIO_DATA0_INDEX   2
#define SDIO_HOST_GPIO_DATA1_INDEX   3

#if (CONFIG_PIN_SDIO_GROUP_0)
#define SDIO_GPIO_MAP \
{\
	{GPIO_14, GPIO_DEV_SDIO_HOST_CLK},\
	{GPIO_15, GPIO_DEV_SDIO_HOST_CMD},\
	{GPIO_16, GPIO_DEV_SDIO_HOST_DATA0},\
	{GPIO_17, GPIO_DEV_SDIO_HOST_DATA1},\
	{GPIO_18, GPIO_DEV_SDIO_HOST_DATA2},\
	{GPIO_19, GPIO_DEV_SDIO_HOST_DATA3},\
}
#else
#define SDIO_GPIO_MAP \
{\
	{GPIO_2, GPIO_DEV_SDIO_HOST_CLK},\
	{GPIO_3, GPIO_DEV_SDIO_HOST_CMD},\
	{GPIO_4, GPIO_DEV_SDIO_HOST_DATA0},\
	{GPIO_5, GPIO_DEV_SDIO_HOST_DATA1},\
	{GPIO_10, GPIO_DEV_SDIO_HOST_DATA2},\
	{GPIO_11, GPIO_DEV_SDIO_HOST_DATA3},\
}
#endif



#define GPIO_PWM_MAP_TABLE \
{ \
	{GPIO_47, GPIO_DEV_PWM0},\
	{GPIO_48, GPIO_DEV_PWM1},\
	{GPIO_49, GPIO_DEV_PWM2},\
	{GPIO_50, GPIO_DEV_PWM3},\
	{GPIO_51, GPIO_DEV_PWM4},\
	{GPIO_52, GPIO_DEV_PWM5},\
	{GPIO_53, GPIO_DEV_PWM6},\
	{GPIO_54, GPIO_DEV_PWM7},\
	{GPIO_55, GPIO_DEV_PWM8},\
	{GPIO_8, GPIO_DEV_PWM9},\
	{GPIO_28, GPIO_DEV_PWM10},\
	{GPIO_9, GPIO_DEV_PWM11},\
}


#define GPIO_MAP_TABLE(DEV_NUM, MODE_NUM, table) \
struct {\
	uint64_t gpio_bits;\
	gpio_dev_t devs[DEV_NUM];\
} table[MODE_NUM]

#define GPIO_I2C1_MAP_TABLE \
{\
	{BIT(0)|BIT(1), {GPIO_DEV_I2C1_SCL, GPIO_DEV_I2C1_SDA}},\
	{BIT64(42)|BIT64(43), {GPIO_DEV_I2C1_SCL, GPIO_DEV_I2C1_SDA}},\
}
#define GPIO_I2C1_USED_GPIO_NUM 2

#define GPIO_I2S_MAP_TABLE \
{\
	{BIT(6)|BIT(7)|BIT(8)|BIT(9), {GPIO_DEV_I2S1_CLK, GPIO_DEV_I2S1_SYNC, GPIO_DEV_I2S1_DIN, GPIO_DEV_I2S1_DOUT}},\
	{BIT64(40)|BIT64(41)|BIT64(42)|BIT64(43), {GPIO_DEV_I2S1_CLK, GPIO_DEV_I2S1_SYNC, GPIO_DEV_I2S1_DIN, GPIO_DEV_I2S1_DOUT}},\
}
#define GPIO_I2S_USED_GPIO_NUM 4

#if CONFIG_I2S_GPIO_GROUP_0
#define I2S_GPIO_MAP \
{ \
    { GPIO_6,  GPIO_DEV_I2S1_CLK  }, \
    { GPIO_7,  GPIO_DEV_I2S1_SYNC }, \
    { GPIO_8,  GPIO_DEV_I2S1_DIN  }, \
    { GPIO_9,  GPIO_DEV_I2S1_DOUT }, \
    { GPIO_28, GPIO_DEV_I2S1_MCLK }, \
}
#elif CONFIG_I2S_GPIO_GROUP_1
#define I2S_GPIO_MAP \
{ \
    { GPIO_40, GPIO_DEV_I2S2_CLK  }, \
    { GPIO_41, GPIO_DEV_I2S2_SYNC }, \
    { GPIO_42, GPIO_DEV_I2S2_DIN  }, \
    { GPIO_43, GPIO_DEV_I2S2_DOUT }, \
    { GPIO_28, GPIO_DEV_I2S1_MCLK }, \
}
#elif CONFIG_I2S_GPIO_GROUP_2
#define I2S_GPIO_MAP \
{ \
    { GPIO_44, GPIO_DEV_I2S3_CLK  }, \
    { GPIO_45, GPIO_DEV_I2S3_SYNC }, \
    { GPIO_46, GPIO_DEV_I2S3_DIN  }, \
    { GPIO_47, GPIO_DEV_I2S3_DOUT }, \
    { GPIO_28, GPIO_DEV_I2S1_MCLK }, \
}
#else
#define I2S_GPIO_MAP {}
#endif

#define GPIO_SPI0_MAP_TABLE \
{\
	{BIT(14)|BIT(15)|BIT64(16)|BIT64(17), {GPIO_DEV_SPI0_SCK, GPIO_DEV_SPI0_CSN, GPIO_DEV_SPI0_MOSI, GPIO_DEV_SPI0_MISO}},\
	{BIT64(44)|BIT64(45)|BIT64(46)|BIT64(47), {GPIO_DEV_SPI0_CSN, GPIO_DEV_SPI0_SCK, GPIO_DEV_SPI0_MOSI, GPIO_DEV_SPI0_MISO}},\
}
#define GPIO_SPI0_USED_GPIO_NUM 4

#define GPIO_SDIO_ONE_LINE_MAP_TABLE \
{\
	{BIT(2)|BIT(3)|BIT(4), {GPIO_DEV_SDIO_HOST_CLK, GPIO_DEV_SDIO_HOST_CMD, GPIO_DEV_SDIO_HOST_DATA0}},\
	{BIT(14)|BIT(15)|BIT(16), {GPIO_DEV_SDIO_HOST_CLK, GPIO_DEV_SDIO_HOST_CMD, GPIO_DEV_SDIO_HOST_DATA0}},\
}
#define GPIO_SDIO_ONE_LINE_USED_GPIO_NUM 3

#define GPIO_SDIO_MAP_TABLE \
{\
	{BIT(2)|BIT(3)|BIT(4)|BIT(5)|BIT(10)|BIT(11), {GPIO_DEV_SDIO_HOST_CLK, GPIO_DEV_SDIO_HOST_CMD, GPIO_DEV_SDIO_HOST_DATA0,GPIO_DEV_SDIO_HOST_DATA1,GPIO_DEV_SDIO_HOST_DATA2,GPIO_DEV_SDIO_HOST_DATA3}},\
	{BIT(14)|BIT(15)|BIT(16)|BIT(17)|BIT(18)|BIT(19), {GPIO_DEV_SDIO_HOST_CLK, GPIO_DEV_SDIO_HOST_CMD, GPIO_DEV_SDIO_HOST_DATA0,GPIO_DEV_SDIO_HOST_DATA1,GPIO_DEV_SDIO_HOST_DATA2,GPIO_DEV_SDIO_HOST_DATA3}},\
}
#define GPIO_SDIO_USED_GPIO_NUM 6

#define GPIO_CTRL_LDO_OUTPUT_HIGH_MAP  \
{\
	/* GPIO_2, */\
	/* GPIO_28, */\
}

#define GPIO_CTRL_LDO_OUTPUT_LOW_MAP  \
{\
	/* GPIO_4, */\
	/* GPIO_26, */\
}
/*---multi modules use one gpio to control different ldo---*/
#define GPIO_CTRL_LDO_MAP  \
{\
	{GPIO_13,  GPIO_OUTPUT_STATE_LOW},\
	{GPIO_28,  GPIO_OUTPUT_STATE_LOW},\
}
/*
 * Camera DVP GPIO MAP
 */
#define CAMERA_DVP_MCLK_PIN             (GPIO_27)
#define CAMERA_DVP_PCLK_PIN             (GPIO_29)
#define CAMERA_DVP_HSYNC_PIN            (GPIO_30)
#define CAMERA_DVP_VSYNC_PIN            (GPIO_31)
#define CAMERA_DVP_PXDATA0_PIN          (GPIO_32)
#define CAMERA_DVP_PXDATA1_PIN          (GPIO_33)
#define CAMERA_DVP_PXDATA2_PIN          (GPIO_34)
#define CAMERA_DVP_PXDATA3_PIN          (GPIO_35)
#define CAMERA_DVP_PXDATA4_PIN          (GPIO_36)
#define CAMERA_DVP_PXDATA5_PIN          (GPIO_37)
#define CAMERA_DVP_PXDATA6_PIN          (GPIO_38)
#define CAMERA_DVP_PXDATA7_PIN          (GPIO_39)

#define CAMERA_DVP_MCLK_FUNC            (GPIO_DEV_JPEG_MCLK)
#define CAMERA_DVP_AUXS_FUNC            (GPIO_DEV_CLK_AUXS)
#define CAMERA_DVP_PCLK_FUNC            (GPIO_DEV_JPEG_PCLK)
#define CAMERA_DVP_HSYNC_FUNC           (GPIO_DEV_JPEG_HSYNC)
#define CAMERA_DVP_VSYNC_FUNC           (GPIO_DEV_JPEG_VSYNC)
#define CAMERA_DVP_PXDATA0_FUNC         (GPIO_DEV_JPEG_PXDATA0)
#define CAMERA_DVP_PXDATA1_FUNC         (GPIO_DEV_JPEG_PXDATA1)
#define CAMERA_DVP_PXDATA2_FUNC         (GPIO_DEV_JPEG_PXDATA2)
#define CAMERA_DVP_PXDATA3_FUNC         (GPIO_DEV_JPEG_PXDATA3)
#define CAMERA_DVP_PXDATA4_FUNC         (GPIO_DEV_JPEG_PXDATA4)
#define CAMERA_DVP_PXDATA5_FUNC         (GPIO_DEV_JPEG_PXDATA5)
#define CAMERA_DVP_PXDATA6_FUNC         (GPIO_DEV_JPEG_PXDATA6)
#define CAMERA_DVP_PXDATA7_FUNC         (GPIO_DEV_JPEG_PXDATA7)

#define CAMERA_DVP_I2C_ID               (CONFIG_DVP_CAMERA_I2C_ID)
#define CAMERA_DVP_I2C_BAUD_RATE        (I2C_BAUD_RATE_100KHZ)
#define CAMERA_DVP_I2C_MODE             (I2C_ADDR_MODE_7BIT)

/*
 * LCD RGB GPIO MAP
 */
#define LCD_RGB_R0_PIN 				(GPIO_55)  // GPIO_DEV_LCD_R0, FUNC_CODE_131
#define LCD_RGB_R1_PIN 				(GPIO_54)  // GPIO_DEV_LCD_R1, FUNC_CODE_131
#define LCD_RGB_R2_PIN 				(GPIO_53)  // GPIO_DEV_LCD_R2, FUNC_CODE_131
#define LCD_RGB_R3_PIN 				(GPIO_47)  // GPIO_DEV_LCD_R3, FUNC_CODE_131
#define LCD_RGB_R4_PIN 				(GPIO_46)  // GPIO_DEV_LCD_R4, FUNC_CODE_131
#define LCD_RGB_R5_PIN 				(GPIO_45)  // GPIO_DEV_LCD_R5, FUNC_CODE_131
#define LCD_RGB_R6_PIN 				(GPIO_44)  // GPIO_DEV_LCD_R6, FUNC_CODE_131
#define LCD_RGB_R7_PIN 				(GPIO_43)  // GPIO_DEV_LCD_R7, FUNC_CODE_131
#define LCD_RGB_G0_PIN 				(GPIO_52)  // GPIO_DEV_LCD_G0, FUNC_CODE_131
#define LCD_RGB_G1_PIN 				(GPIO_51)  // GPIO_DEV_LCD_G1, FUNC_CODE_131
#define LCD_RGB_G2_PIN 				(GPIO_42)  // GPIO_DEV_LCD_G2, FUNC_CODE_131
#define LCD_RGB_G3_PIN 				(GPIO_41)  // GPIO_DEV_LCD_G3, FUNC_CODE_131
#define LCD_RGB_G4_PIN 				(GPIO_40)  // GPIO_DEV_LCD_G4, FUNC_CODE_131
#define LCD_RGB_G5_PIN 				(GPIO_26)  // GPIO_DEV_LCD_G5, FUNC_CODE_131
#define LCD_RGB_G6_PIN 				(GPIO_25)  // GPIO_DEV_LCD_G6, FUNC_CODE_131
#define LCD_RGB_G7_PIN 				(GPIO_24)  // GPIO_DEV_LCD_G7, FUNC_CODE_131
#define LCD_RGB_B0_PIN 				(GPIO_50)  // GPIO_DEV_LCD_B0, FUNC_CODE_131
#define LCD_RGB_B1_PIN 				(GPIO_49)  // GPIO_DEV_LCD_B1, FUNC_CODE_131
#define LCD_RGB_B2_PIN 				(GPIO_48)  // GPIO_DEV_LCD_B2, FUNC_CODE_131
#define LCD_RGB_B3_PIN 				(GPIO_23)  // GPIO_DEV_LCD_B3, FUNC_CODE_131
#define LCD_RGB_B4_PIN 				(GPIO_22)  // GPIO_DEV_LCD_B4, FUNC_CODE_131
#define LCD_RGB_B5_PIN 				(GPIO_21)  // GPIO_DEV_LCD_B5, FUNC_CODE_131
#define LCD_RGB_B6_PIN 				(GPIO_20)  // GPIO_DEV_LCD_B6, FUNC_CODE_131
#define LCD_RGB_B7_PIN 				(GPIO_19)  // GPIO_DEV_LCD_B7, FUNC_CODE_131
#define LCD_RGB_CLK_PIN 			(GPIO_18)  // GPIO_DEV_LCD_CLK, FUNC_CODE_131
#define LCD_RGB_DISP_PIN 			(GPIO_17)  // GPIO_DEV_LCD_DISP, FUNC_CODE_131
#define LCD_RGB_DE_PIN 				(GPIO_14)  // GPIO_DEV_LCD_DE, FUNC_CODE_131
#define LCD_RGB_HSYNC_PIN 			(GPIO_16)  // GPIO_DEV_LCD_HSYNC, FUNC_CODE_131
#define LCD_RGB_VSYNC_PIN 			(GPIO_15)  // GPIO_DEV_LCD_VSYNC, FUNC_CODE_131



#define LCD_RGB_R0_FUNC 			(GPIO_DEV_LCD_R0)
#define LCD_RGB_R1_FUNC 			(GPIO_DEV_LCD_R1)
#define LCD_RGB_R2_FUNC 			(GPIO_DEV_LCD_R2)
#define LCD_RGB_R3_FUNC 			(GPIO_DEV_LCD_R3)
#define LCD_RGB_R4_FUNC 			(GPIO_DEV_LCD_R4)
#define LCD_RGB_R5_FUNC 			(GPIO_DEV_LCD_R5)
#define LCD_RGB_R6_FUNC 			(GPIO_DEV_LCD_R6)
#define LCD_RGB_R7_FUNC 			(GPIO_DEV_LCD_R7)

#define LCD_RGB_G0_FUNC 			(GPIO_DEV_LCD_G0)
#define LCD_RGB_G1_FUNC 			(GPIO_DEV_LCD_G1)
#define LCD_RGB_G2_FUNC 			(GPIO_DEV_LCD_G2)
#define LCD_RGB_G3_FUNC 			(GPIO_DEV_LCD_G3)
#define LCD_RGB_G4_FUNC 			(GPIO_DEV_LCD_G4)
#define LCD_RGB_G5_FUNC 			(GPIO_DEV_LCD_G5)
#define LCD_RGB_G6_FUNC 			(GPIO_DEV_LCD_G6)
#define LCD_RGB_G7_FUNC 			(GPIO_DEV_LCD_G7)

#define LCD_RGB_B0_FUNC 			(GPIO_DEV_LCD_B0)
#define LCD_RGB_B1_FUNC 			(GPIO_DEV_LCD_B1)
#define LCD_RGB_B2_FUNC 			(GPIO_DEV_LCD_B2)
#define LCD_RGB_B3_FUNC 			(GPIO_DEV_LCD_B3)
#define LCD_RGB_B4_FUNC 			(GPIO_DEV_LCD_B4)
#define LCD_RGB_B5_FUNC 			(GPIO_DEV_LCD_B5)
#define LCD_RGB_B6_FUNC 			(GPIO_DEV_LCD_B6)
#define LCD_RGB_B7_FUNC 			(GPIO_DEV_LCD_B7)

#define LCD_RGB_CLK_FUNC 			(GPIO_DEV_LCD_CLK)
#define LCD_RGB_DISP_FUNC 			(GPIO_DEV_LCD_DISP)
#define LCD_RGB_HSYNC_FUNC 			(GPIO_DEV_LCD_HSYNC)
#define LCD_RGB_VSYNC_FUNC 			(GPIO_DEV_LCD_VSYNC)
#define LCD_RGB_DE_FUNC 			(GPIO_DEV_LCD_DE)

/*
 * LCD MCU GPIO MAP
 */
#define LCD_MCU_D0_PIN 				(GPIO_47)
#define LCD_MCU_D1_PIN 				(GPIO_46)
#define LCD_MCU_D2_PIN 				(GPIO_45)
#define LCD_MCU_D3_PIN 				(GPIO_44)
#define LCD_MCU_D4_PIN 				(GPIO_43)
#define LCD_MCU_D5_PIN 				(GPIO_42)
#define LCD_MCU_D6_PIN 				(GPIO_41)
#define LCD_MCU_D7_PIN 				(GPIO_40)
#define LCD_MCU_D8_PIN 				(GPIO_21)
#define LCD_MCU_D9_PIN 				(GPIO_20)
#define LCD_MCU_D10_PIN 			(GPIO_19)
#define LCD_MCU_D11_PIN 			(GPIO_18)
#define LCD_MCU_D12_PIN 			(GPIO_17)
#define LCD_MCU_D13_PIN 			(GPIO_16)
#define LCD_MCU_D14_PIN 			(GPIO_15)
#define LCD_MCU_D15_PIN 			(GPIO_14)
#define LCD_MCU_D16_PIN 			(GPIO_48)
#define LCD_MCU_D17_PIN 			(GPIO_49)
#define LCD_MCU_RDX_PIN 		 	(GPIO_26)
#define LCD_MCU_WRX_PIN 		 	(GPIO_25)
#define LCD_MCU_RSX_PIN 		 	(GPIO_24)
#define LCD_MCU_RESET_PIN 		 	(GPIO_23)
#define LCD_MCU_CSX_PIN 		 	(GPIO_22)

#define LCD_MCU_D0_FUNC 			(GPIO_DEV_LCD_B3)
#define LCD_MCU_D1_FUNC 			(GPIO_DEV_LCD_B4)
#define LCD_MCU_D2_FUNC 			(GPIO_DEV_LCD_B5)
#define LCD_MCU_D3_FUNC 			(GPIO_DEV_LCD_B6)
#define LCD_MCU_D4_FUNC 			(GPIO_DEV_LCD_B7)
#define LCD_MCU_D5_FUNC 			(GPIO_DEV_LCD_G2)
#define LCD_MCU_D6_FUNC 			(GPIO_DEV_LCD_G3)
#define LCD_MCU_D7_FUNC 			(GPIO_DEV_LCD_G4)
#define LCD_MCU_D8_FUNC 			(GPIO_DEV_LCD_R5)
#define LCD_MCU_D9_FUNC 			(GPIO_DEV_LCD_R6)
#define LCD_MCU_D10_FUNC 			(GPIO_DEV_LCD_R7)
#define LCD_MCU_D11_FUNC 			(GPIO_DEV_LCD_VSYNC)
#define LCD_MCU_D12_FUNC 			(GPIO_DEV_LCD_HSYNC)
#define LCD_MCU_D13_FUNC 			(GPIO_DEV_LCD_DE)
#define LCD_MCU_D14_FUNC 			(GPIO_DEV_LCD_DISP)
#define LCD_MCU_D15_FUNC 			(GPIO_DEV_LCD_CLK)
#define LCD_MCU_D16_FUNC 			(GPIO_DEV_LCD_R2)
#define LCD_MCU_D17_FUNC 			(GPIO_DEV_LCD_R1)
#define LCD_MCU_RDX_FUNC 		 	(GPIO_DEV_LCD_G5)
#define LCD_MCU_WRX_FUNC 		 	(GPIO_DEV_LCD_G6)
#define LCD_MCU_RSX_FUNC 		 	(GPIO_DEV_LCD_G7)
#define LCD_MCU_RESET_FUNC 		 	(GPIO_DEV_LCD_R3)
#define LCD_MCU_CSX_FUNC 		 	(GPIO_DEV_LCD_R4)

/*
* AUDIO PA GPIO MAP
*/
#define AUD_DAC_PA_CTRL_GPIO		(GPIO_5)
#define AUD_DAC_PA_ENABLE_LEVEL		(1)

/*
* VIDEO PA GPIO MAP
*/
// LCD AND SD POWER CTRL
#define LCD_LDO_CTRL_GPIO                  (GPIO_13)
#define LCD_LDO_CTRL_ACTIVE_LEVEL          (1)

#define SDCARD_LDO_CTRL_GPIO               (GPIO_13)
#define SDCARD_LDO_CTRL_ACTIVE_LEVEL       (1)

// LCD BACKLIGHT CTRL
#define LCD_BACKLIGHT_CTRL_ACTIVE_LEVEL    (1)

#if CONFIG_GPIO_WAKEUP_SUPPORT
#define GPIO_STATIC_WAKEUP_SOURCE_MAP  \
	{\
		/*{GPIO_6, GPIO_INT_TYPE_LOW_LEVEL},*/ \
		{GPIO_10, GPIO_INT_TYPE_FALLING_EDGE},\
		/*{GPIO_40, GPIO_INT_LEVEL_LOW},*/ \
	}

#endif

#define IRDA_PIN    (GPIO_25)

#define GPIO_DEV_TO_IOMX_CODE_MAP \
{\
	[GPIO_DEV_DMIC1_CLK] = FUNC_CODE_DMIC0_CLK, \
	[GPIO_DEV_DMIC1_DAT] = FUNC_CODE_DMIC0_DAT, \
	[GPIO_DEV_DMIC2_CLK] = FUNC_CODE_DMIC1_CLK, \
	[GPIO_DEV_DMIC2_DAT] = FUNC_CODE_DMIC1_DAT, \
	[GPIO_DEV_HDMI_CEC] = FUNC_CODE_HDMI_CEC, \
	[GPIO_DEV_I2S1_DIN] = FUNC_CODE_I2S0_DIN, \
	[GPIO_DEV_I2S1_DOUT] = FUNC_CODE_I2S0_DOUT, \
	[GPIO_DEV_I2S1_CLK] = FUNC_CODE_I2S0_SCK, \
	[GPIO_DEV_I2S1_SYNC] = FUNC_CODE_I2S0_SYNC, \
	[GPIO_DEV_I2S2_DIN] = FUNC_CODE_I2S1_DIN, \
	[GPIO_DEV_I2S2_DOUT] = FUNC_CODE_I2S1_DOUT, \
	[GPIO_DEV_I2S2_CLK] = FUNC_CODE_I2S1_SCK, \
	[GPIO_DEV_I2S2_SYNC] = FUNC_CODE_I2S1_SYNC, \
	[GPIO_DEV_I2S3_DIN] = FUNC_CODE_I2S2_DIN, \
	[GPIO_DEV_I2S3_DOUT] = FUNC_CODE_I2S2_DOUT, \
	[GPIO_DEV_I2S3_CLK] = FUNC_CODE_I2S2_SCK, \
	[GPIO_DEV_I2S3_SYNC] = FUNC_CODE_I2S2_SYNC, \
	[GPIO_DEV_I2S4_DIN] = FUNC_CODE_I2S3_DIN, \
	[GPIO_DEV_I2S4_DOUT] = FUNC_CODE_I2S3_DOUT, \
	[GPIO_DEV_I2S4_CLK] = FUNC_CODE_I2S3_SCK, \
	[GPIO_DEV_I2S4_SYNC] = FUNC_CODE_I2S3_SYNC, \
	[GPIO_DEV_I2S5_DIN] = FUNC_CODE_I2S4_DIN, \
	[GPIO_DEV_I2S5_DOUT] = FUNC_CODE_I2S4_DOUT, \
	[GPIO_DEV_I2S5_CLK] = FUNC_CODE_I2S4_SCK, \
	[GPIO_DEV_I2S5_SYNC] = FUNC_CODE_I2S4_SYNC, \
	[GPIO_DEV_I2S1_MCLK] = FUNC_CODE_I2S_MCLK, \
	[GPIO_DEV_JTAG_TCK] = FUNC_CODE_SWCLK, \
	[GPIO_DEV_JTAG_TMS] = FUNC_CODE_SWDIO, \
	[GPIO_DEV_PWM0] = FUNC_CODE_PWM0_0, \
	[GPIO_DEV_PWM1] = FUNC_CODE_PWM0_1, \
	[GPIO_DEV_PWM2] = FUNC_CODE_PWM0_2, \
	[GPIO_DEV_PWM3] = FUNC_CODE_PWM0_3, \
	[GPIO_DEV_PWM4] = FUNC_CODE_PWM0_4, \
	[GPIO_DEV_PWM5] = FUNC_CODE_PWM0_5, \
	[GPIO_DEV_PWM6] = FUNC_CODE_PWM0_6, \
	[GPIO_DEV_PWM7] = FUNC_CODE_PWM0_7, \
	[GPIO_DEV_PWM8] = FUNC_CODE_PWM0_8, \
	[GPIO_DEV_PWM9] = FUNC_CODE_PWM0_9, \
	[GPIO_DEV_PWM10] = FUNC_CODE_PWM0_10, \
	[GPIO_DEV_PWM11] = FUNC_CODE_PWM0_11, \
	[GPIO_DEV_SPI0_MISO] = FUNC_CODE_SPI0_MISO, \
	[GPIO_DEV_SPI0_MOSI] = FUNC_CODE_SPI0_MOSI, \
	[GPIO_DEV_SPI0_CSN] = FUNC_CODE_SPI0_NSS, \
	[GPIO_DEV_SPI0_SCK] = FUNC_CODE_SPI0_SCK, \
	[GPIO_DEV_SPI1_MISO] = FUNC_CODE_SPI1_MISO, \
	[GPIO_DEV_SPI1_MOSI] = FUNC_CODE_SPI1_MOSI, \
	[GPIO_DEV_SPI1_CSN] = FUNC_CODE_SPI1_NSS, \
	[GPIO_DEV_SPI1_SCK] = FUNC_CODE_SPI1_SCK, \
	[GPIO_DEV_SPI2_MISO] = FUNC_CODE_SPI2_MISO, \
	[GPIO_DEV_SPI2_MOSI] = FUNC_CODE_SPI2_MOSI, \
	[GPIO_DEV_SPI2_CSN] = FUNC_CODE_SPI2_NSS, \
	[GPIO_DEV_SPI2_SCK] = FUNC_CODE_SPI2_SCK, \
	[GPIO_DEV_SPI3_MISO] = FUNC_CODE_SPI3_MISO, \
	[GPIO_DEV_SPI3_MOSI] = FUNC_CODE_SPI3_MOSI, \
	[GPIO_DEV_SPI3_CSN] = FUNC_CODE_SPI3_NSS, \
	[GPIO_DEV_SPI3_SCK] = FUNC_CODE_SPI3_SCK, \
	[GPIO_DEV_I3C_SCL] = FUNC_CODE_I3C_SCL, \
	[GPIO_DEV_I3C_SDA] = FUNC_CODE_I3C_SDA, \
	[GPIO_DEV_I3C_SDA_PURN] = FUNC_CODE_I3C_SDA_PURN, \
	[GPIO_DEV_BT_ANT0] = FUNC_CODE_BT_ANT_0, \
	[GPIO_DEV_BT_ANT1] = FUNC_CODE_BT_ANT_1, \
	[GPIO_DEV_BT_ANT2] = FUNC_CODE_BT_ANT_2, \
	[GPIO_DEV_BT_ANT3] = FUNC_CODE_BT_ANT_3, \
	[GPIO_DEV_CAN_RX] = FUNC_CODE_CAN0_RX, \
	[GPIO_DEV_CAN_STANDBY] = FUNC_CODE_CAN0_STANDBY, \
	[GPIO_DEV_CAN_TX] = FUNC_CODE_CAN0_TX, \
	[GPIO_DEV_CAN1_RX] = FUNC_CODE_CAN1_RX, \
	[GPIO_DEV_CAN1_STANDBY] = FUNC_CODE_CAN1_STANDBY, \
	[GPIO_DEV_CAN1_TX] = FUNC_CODE_CAN1_TX, \
	[GPIO_DEV_I2C0_SCL] = FUNC_CODE_I2C0_SCL, \
	[GPIO_DEV_I2C0_SDA] = FUNC_CODE_I2C0_SDA, \
	[GPIO_DEV_I2C1_SCL] = FUNC_CODE_I2C1_SCL, \
	[GPIO_DEV_I2C1_SDA] = FUNC_CODE_I2C1_SDA, \
	[GPIO_DEV_IRDA] = FUNC_CODE_IRDA0, \
	[GPIO_DEV_IRDA1] = FUNC_CODE_IRDA1, \
	[GPIO_DEV_IRDA2] = FUNC_CODE_IRDA2, \
	[GPIO_DEV_IRDA3] = FUNC_CODE_IRDA3, \
	[GPIO_DEV_LIN_RXD] = FUNC_CODE_LIN0_RXD, \
	[GPIO_DEV_LIN_SLEEP] = FUNC_CODE_LIN0_SLEEP, \
	[GPIO_DEV_LIN_TXD] = FUNC_CODE_LIN0_TXD, \
	[GPIO_DEV_SCR_CLK] = FUNC_CODE_SC0_CLK, \
	[GPIO_DEV_SCR_IO] = FUNC_CODE_SC0_IO, \
	[GPIO_DEV_SCR_RSTN] = FUNC_CODE_SC0_RSTN, \
	[GPIO_DEV_SCR_VCC] = FUNC_CODE_SC0_VCC, \
	[GPIO_DEV_SPDIF0_RX] = FUNC_CODE_SPDIF0_RX, \
	[GPIO_DEV_SPDIF0_TX] = FUNC_CODE_SPDIF0_TX, \
	[GPIO_DEV_SPDIF1_RX] = FUNC_CODE_SPDIF1_RX, \
	[GPIO_DEV_SPDIF1_TX] = FUNC_CODE_SPDIF1_TX, \
	[GPIO_DEV_UART0_CTS] = FUNC_CODE_UART0_CTS, \
	[GPIO_DEV_UART0_RTS] = FUNC_CODE_UART0_RTS, \
	[GPIO_DEV_UART0_RXD] = FUNC_CODE_UART0_RXD, \
	[GPIO_DEV_UART0_TXD] = FUNC_CODE_UART0_TXD, \
	[GPIO_DEV_UART1_RXD] = FUNC_CODE_UART1_RXD, \
	[GPIO_DEV_UART1_TXD] = FUNC_CODE_UART1_TXD, \
	[GPIO_DEV_UART2_RXD] = FUNC_CODE_UART2_RXD, \
	[GPIO_DEV_UART2_TXD] = FUNC_CODE_UART2_TXD, \
	[GPIO_DEV_UART3_RXD] = FUNC_CODE_UART3_RXD, \
	[GPIO_DEV_UART3_TXD] = FUNC_CODE_UART3_TXD, \
	[GPIO_DEV_UART4_RXD] = FUNC_CODE_UART4_RXD, \
	[GPIO_DEV_UART4_TXD] = FUNC_CODE_UART4_TXD, \
}

struct mapping_func_code_fix_gpio{
	gpio_dev_t gdev;
	IOMX_CODE_T code;
	gpio_id_t id;
};

#define MAP_FUNC_CODE_FIX_GPIO \
{\
	{GPIO_DEV_OTP_FRE_EN, FUNC_CODE_126, GPIO_2},\
	{GPIO_DEV_OTP_FRE_SEL, FUNC_CODE_126, GPIO_3},\
	{GPIO_DEV_OTP_FRE_OUT, FUNC_CODE_126, GPIO_4},\
	{GPIO_DEV_CLK13M, FUNC_CODE_126, GPIO_6},\
	{GPIO_DEV_WIFI_ACTIVE, FUNC_CODE_126, GPIO_7},\
	{GPIO_DEV_CLK26M, FUNC_CODE_126, GPIO_22},\
	{GPIO_DEV_LPO_CLK, FUNC_CODE_126, GPIO_24},\
	{GPIO_DEV_WIFI_TX_EN, FUNC_CODE_126, GPIO_26},\
	{GPIO_DEV_FEN_LNA_EN, FUNC_CODE_126, GPIO_27},\
	{GPIO_DEV_WIFI_RX_EN, FUNC_CODE_126, GPIO_28},\
	{GPIO_DEV_DEBUG0, FUNC_CODE_127, GPIO_2},\
	{GPIO_DEV_DEBUG1, FUNC_CODE_127, GPIO_3},\
	{GPIO_DEV_DEBUG2, FUNC_CODE_127, GPIO_4},\
	{GPIO_DEV_DEBUG3, FUNC_CODE_127, GPIO_5},\
	{GPIO_DEV_DEBUG4, FUNC_CODE_127, GPIO_6},\
	{GPIO_DEV_DEBUG5, FUNC_CODE_127, GPIO_7},\
	{GPIO_DEV_DEBUG6, FUNC_CODE_127, GPIO_8},\
	{GPIO_DEV_DEBUG7, FUNC_CODE_127, GPIO_9},\
	{GPIO_DEV_DEBUG8, FUNC_CODE_127, GPIO_14},\
	{GPIO_DEV_DEBUG9, FUNC_CODE_127, GPIO_15},\
	{GPIO_DEV_DEBUG10, FUNC_CODE_127, GPIO_16},\
	{GPIO_DEV_DEBUG11, FUNC_CODE_127, GPIO_17},\
	{GPIO_DEV_DEBUG12, FUNC_CODE_127, GPIO_18},\
	{GPIO_DEV_DEBUG13, FUNC_CODE_127, GPIO_19},\
	{GPIO_DEV_DEBUG14, FUNC_CODE_127, GPIO_24},\
	{GPIO_DEV_DEBUG15, FUNC_CODE_127, GPIO_25},\
	{GPIO_DEV_DEBUG16, FUNC_CODE_127, GPIO_26},\
	{GPIO_DEV_DEBUG17, FUNC_CODE_127, GPIO_27},\
	{GPIO_DEV_DEBUG18, FUNC_CODE_127, GPIO_28},\
	{GPIO_DEV_DEBUG19, FUNC_CODE_127, GPIO_29},\
	{GPIO_DEV_DEBUG20, FUNC_CODE_127, GPIO_30},\
	{GPIO_DEV_DEBUG21, FUNC_CODE_127, GPIO_31},\
	{GPIO_DEV_DEBUG22, FUNC_CODE_127, GPIO_32},\
	{GPIO_DEV_DEBUG23, FUNC_CODE_127, GPIO_33},\
	{GPIO_DEV_DEBUG24, FUNC_CODE_127, GPIO_34},\
	{GPIO_DEV_DEBUG25, FUNC_CODE_127, GPIO_35},\
	{GPIO_DEV_DEBUG26, FUNC_CODE_127, GPIO_36},\
	{GPIO_DEV_DEBUG27, FUNC_CODE_127, GPIO_37},\
	{GPIO_DEV_DEBUG28, FUNC_CODE_127, GPIO_38},\
	{GPIO_DEV_DEBUG29, FUNC_CODE_127, GPIO_39},\
	{GPIO_DEV_DEBUG30, FUNC_CODE_127, GPIO_42},\
	{GPIO_DEV_DEBUG31, FUNC_CODE_127, GPIO_43},\
	{GPIO_DEV_SDIO_HOST_CLK, FUNC_CODE_129, GPIO_2},\
	{GPIO_DEV_SDIO_HOST_CMD, FUNC_CODE_129, GPIO_3},\
	{GPIO_DEV_SDIO_HOST_DATA0, FUNC_CODE_129, GPIO_4},\
	{GPIO_DEV_SDIO_HOST_DATA1, FUNC_CODE_129, GPIO_5},\
	{GPIO_DEV_SDIO_HOST_DATA4, FUNC_CODE_129, GPIO_6},\
	{GPIO_DEV_SDIO_HOST_DATA5, FUNC_CODE_129, GPIO_7},\
	{GPIO_DEV_SDIO_HOST_DATA6, FUNC_CODE_129, GPIO_8},\
	{GPIO_DEV_SDIO_HOST_DATA7, FUNC_CODE_129, GPIO_9},\
	{GPIO_DEV_SDIO_HOST_DATA2, FUNC_CODE_129, GPIO_10},\
	{GPIO_DEV_SDIO_HOST_DATA3, FUNC_CODE_129, GPIO_11},\
	{GPIO_DEV_SDIO_HOST_STB, FUNC_CODE_129, GPIO_12},\
	{GPIO_DEV_SDIO1_HOST_CLK, FUNC_CODE_129, GPIO_14},\
	{GPIO_DEV_SDIO1_HOST_CMD, FUNC_CODE_129, GPIO_15},\
	{GPIO_DEV_SDIO1_HOST_DATA0, FUNC_CODE_129, GPIO_16},\
	{GPIO_DEV_SDIO1_HOST_DATA1, FUNC_CODE_129, GPIO_17},\
	{GPIO_DEV_SDIO1_HOST_DATA2, FUNC_CODE_129, GPIO_18},\
	{GPIO_DEV_SDIO1_HOST_DATA3, FUNC_CODE_129, GPIO_19},\
	{GPIO_DEV_SDIO1_HOST_DATA4, FUNC_CODE_129, GPIO_20},\
	{GPIO_DEV_SDIO1_HOST_DATA5, FUNC_CODE_129, GPIO_21},\
	{GPIO_DEV_SDIO1_HOST_DATA6, FUNC_CODE_129, GPIO_22},\
	{GPIO_DEV_SDIO1_HOST_DATA7, FUNC_CODE_129, GPIO_23},\
	{GPIO_DEV_SDIO1_HOST_STB, FUNC_CODE_129, GPIO_24},\
	{GPIO_DEV_CLK_AUXS_CIS, FUNC_CODE_129, GPIO_27},\
	{GPIO_DEV_CLK_AUXS, FUNC_CODE_129, GPIO_28},\
	{GPIO_DEV_JPEG_PCLK, FUNC_CODE_129, GPIO_29},\
	{GPIO_DEV_JPEG_HSYNC, FUNC_CODE_129, GPIO_30},\
	{GPIO_DEV_JPEG_VSYNC, FUNC_CODE_129, GPIO_31},\
	{GPIO_DEV_JPEG_PXDATA0, FUNC_CODE_129, GPIO_32},\
	{GPIO_DEV_JPEG_PXDATA1, FUNC_CODE_129, GPIO_33},\
	{GPIO_DEV_JPEG_PXDATA2, FUNC_CODE_129, GPIO_34},\
	{GPIO_DEV_JPEG_PXDATA3, FUNC_CODE_129, GPIO_35},\
	{GPIO_DEV_JPEG_PXDATA4, FUNC_CODE_129, GPIO_36},\
	{GPIO_DEV_JPEG_PXDATA5, FUNC_CODE_129, GPIO_37},\
	{GPIO_DEV_JPEG_PXDATA6, FUNC_CODE_129, GPIO_38},\
	{GPIO_DEV_JPEG_PXDATA7, FUNC_CODE_129, GPIO_39},\
	{GPIO_DEV_JPEG_PXDATA8, FUNC_CODE_129, GPIO_40},\
	{GPIO_DEV_JPEG_PXDATA9, FUNC_CODE_129, GPIO_41},\
	{GPIO_DEV_ENET_REF_CLK, FUNC_CODE_129, GPIO_49},\
	{GPIO_DEV_CLK_AUXS_CIS, FUNC_CODE_129, GPIO_59},\
	{GPIO_DEV_SDIO_HOST_STB, FUNC_CODE_129, GPIO_61},\
	{GPIO_DEV_SDIO_HOST_DATA7, FUNC_CODE_129, GPIO_62},\
	{GPIO_DEV_SDIO_HOST_DATA6, FUNC_CODE_129, GPIO_63},\
	{GPIO_DEV_SDIO_HOST_DATA5, FUNC_CODE_129, GPIO_64},\
	{GPIO_DEV_SDIO_HOST_DATA4, FUNC_CODE_129, GPIO_65},\
	{GPIO_DEV_SDIO_HOST_DATA3, FUNC_CODE_129, GPIO_66},\
	{GPIO_DEV_SDIO_HOST_DATA2, FUNC_CODE_129, GPIO_67},\
	{GPIO_DEV_SDIO_HOST_DATA1, FUNC_CODE_129, GPIO_68},\
	{GPIO_DEV_SDIO_HOST_DATA0, FUNC_CODE_129, GPIO_69},\
	{GPIO_DEV_SDIO_HOST_CMD, FUNC_CODE_129, GPIO_70},\
	{GPIO_DEV_SDIO_HOST_CLK, FUNC_CODE_129, GPIO_71},\
	{GPIO_DEV_QSPI1_CLK, FUNC_CODE_130, GPIO_2},\
	{GPIO_DEV_QSPI1_CSN, FUNC_CODE_130, GPIO_3},\
	{GPIO_DEV_QSPI1_IO0, FUNC_CODE_130, GPIO_4},\
	{GPIO_DEV_QSPI1_IO1, FUNC_CODE_130, GPIO_5},\
	{GPIO_DEV_QSPI1_IO2, FUNC_CODE_130, GPIO_6},\
	{GPIO_DEV_QSPI1_IO3, FUNC_CODE_130, GPIO_7},\
	{GPIO_DEV_CLK_AUXS, FUNC_CODE_130, GPIO_10},\
	{GPIO_DEV_ENET_REF_CLK, FUNC_CODE_130, GPIO_21},\
	{GPIO_DEV_QSPI0_CLK, FUNC_CODE_130, GPIO_22},\
	{GPIO_DEV_QSPI0_CSN, FUNC_CODE_130, GPIO_23},\
	{GPIO_DEV_QSPI0_IO0, FUNC_CODE_130, GPIO_24},\
	{GPIO_DEV_QSPI0_IO1, FUNC_CODE_130, GPIO_25},\
	{GPIO_DEV_QSPI0_IO2, FUNC_CODE_130, GPIO_26},\
	{GPIO_DEV_QSPI0_IO3, FUNC_CODE_130, GPIO_27},\
	{GPIO_DEV_ENET_GTCLK, FUNC_CODE_130, GPIO_40},\
	{GPIO_DEV_ENET_TXD3, FUNC_CODE_130, GPIO_41},\
	{GPIO_DEV_ENET_TXD2, FUNC_CODE_130, GPIO_42},\
	{GPIO_DEV_ENET_TXD1, FUNC_CODE_130, GPIO_43},\
	{GPIO_DEV_ENET_TXD0, FUNC_CODE_130, GPIO_44},\
	{GPIO_DEV_ENET_TXEN, FUNC_CODE_130, GPIO_45},\
	{GPIO_DEV_CLK_AUXS_ENET, FUNC_CODE_130, GPIO_46},\
	{GPIO_DEV_ENET_MDC, FUNC_CODE_130, GPIO_47},\
	{GPIO_DEV_ENET_MDIO, FUNC_CODE_130, GPIO_48},\
	{GPIO_DEV_ENET_GRCLK, FUNC_CODE_130, GPIO_49},\
	{GPIO_DEV_ENET_RXDV, FUNC_CODE_130, GPIO_50},\
	{GPIO_DEV_ENET_RXD0, FUNC_CODE_130, GPIO_51},\
	{GPIO_DEV_ENET_RXD1, FUNC_CODE_130, GPIO_52},\
	{GPIO_DEV_ENET_RXD2, FUNC_CODE_130, GPIO_53},\
	{GPIO_DEV_ENET_RXD3, FUNC_CODE_130, GPIO_54},\
	{GPIO_DEV_ENET_PHY_INT, FUNC_CODE_130, GPIO_55},\
	{GPIO_DEV_ENET_PHY_INT, FUNC_CODE_130, GPIO_60},\
	{GPIO_DEV_UART5_RXD, FUNC_CODE_130, GPIO_64},\
	{GPIO_DEV_UART5_TXD, FUNC_CODE_130, GPIO_65},\
	{GPIO_DEV_LCD_DE, FUNC_CODE_131, GPIO_14},\
	{GPIO_DEV_LCD_VSYNC, FUNC_CODE_131, GPIO_15},\
	{GPIO_DEV_LCD_HSYNC, FUNC_CODE_131, GPIO_16},\
	{GPIO_DEV_LCD_DISP, FUNC_CODE_131, GPIO_17},\
	{GPIO_DEV_LCD_CLK, FUNC_CODE_131, GPIO_18},\
	{GPIO_DEV_LCD_B7, FUNC_CODE_131, GPIO_19},\
	{GPIO_DEV_LCD_B6, FUNC_CODE_131, GPIO_20},\
	{GPIO_DEV_LCD_B5, FUNC_CODE_131, GPIO_21},\
	{GPIO_DEV_LCD_B4, FUNC_CODE_131, GPIO_22},\
	{GPIO_DEV_LCD_B3, FUNC_CODE_131, GPIO_23},\
	{GPIO_DEV_LCD_G7, FUNC_CODE_131, GPIO_24},\
	{GPIO_DEV_LCD_G6, FUNC_CODE_131, GPIO_25},\
	{GPIO_DEV_LCD_G5, FUNC_CODE_131, GPIO_26},\
	{GPIO_DEV_JPEG_MCLK, FUNC_CODE_131, GPIO_27},\
	{GPIO_DEV_LCD_G4, FUNC_CODE_131, GPIO_40},\
	{GPIO_DEV_LCD_G3, FUNC_CODE_131, GPIO_41},\
	{GPIO_DEV_LCD_G2, FUNC_CODE_131, GPIO_42},\
	{GPIO_DEV_LCD_R7, FUNC_CODE_131, GPIO_43},\
	{GPIO_DEV_LCD_R6, FUNC_CODE_131, GPIO_44},\
	{GPIO_DEV_LCD_R5, FUNC_CODE_131, GPIO_45},\
	{GPIO_DEV_LCD_R4, FUNC_CODE_131, GPIO_46},\
	{GPIO_DEV_LCD_R3, FUNC_CODE_131, GPIO_47},\
	{GPIO_DEV_LCD_B2, FUNC_CODE_131, GPIO_48},\
	{GPIO_DEV_LCD_B1, FUNC_CODE_131, GPIO_49},\
	{GPIO_DEV_LCD_B0, FUNC_CODE_131, GPIO_50},\
	{GPIO_DEV_LCD_G1, FUNC_CODE_131, GPIO_51},\
	{GPIO_DEV_LCD_G0, FUNC_CODE_131, GPIO_52},\
	{GPIO_DEV_LCD_R2, FUNC_CODE_131, GPIO_53},\
	{GPIO_DEV_LCD_R1, FUNC_CODE_131, GPIO_54},\
	{GPIO_DEV_LCD_R0, FUNC_CODE_131, GPIO_55},\
	{GPIO_DEV_ENET_GTCLK, FUNC_CODE_132, GPIO_13},\
	{GPIO_DEV_ENET_TXD3, FUNC_CODE_132, GPIO_14},\
	{GPIO_DEV_ENET_TXD2, FUNC_CODE_132, GPIO_15},\
	{GPIO_DEV_ENET_TXD1, FUNC_CODE_132, GPIO_16},\
	{GPIO_DEV_ENET_TXD0, FUNC_CODE_132, GPIO_17},\
	{GPIO_DEV_CLK_AUXS_ENET, FUNC_CODE_132, GPIO_18},\
	{GPIO_DEV_ENET_MDC, FUNC_CODE_132, GPIO_19},\
	{GPIO_DEV_ENET_MDIO, FUNC_CODE_132, GPIO_20},\
	{GPIO_DEV_ENET_GRCLK, FUNC_CODE_132, GPIO_21},\
	{GPIO_DEV_ENET_RXDV, FUNC_CODE_132, GPIO_22},\
	{GPIO_DEV_ENET_RXD0, FUNC_CODE_132, GPIO_23},\
	{GPIO_DEV_ENET_RXD1, FUNC_CODE_132, GPIO_24},\
	{GPIO_DEV_ENET_RXD2, FUNC_CODE_132, GPIO_25},\
	{GPIO_DEV_ENET_RXD3, FUNC_CODE_132, GPIO_26},\
	{GPIO_DEV_ENET_TXEN, FUNC_CODE_132, GPIO_28},\
}

#ifdef __cplusplus
}
#endif
