// Copyright 2020-2025 Beken
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#pragma once

#ifdef __cplusplus
extern "C" {
#endif

#include <stdio.h>
#include <driver/hal/hal_gpio_types.h>
#include <driver/hal/hal_io_matrix_types.h>
#include <soc/soc.h>
#include "sdkconfig.h"

/*
 * Camera DVP GPIO MAP
 */
#define CAMERA_DVP_MCLK_PIN             (GPIO_27)
#define CAMERA_DVP_PCLK_PIN             (GPIO_29)
#define CAMERA_DVP_HSYNC_PIN            (GPIO_30)
#define CAMERA_DVP_VSYNC_PIN            (GPIO_31)
#define CAMERA_DVP_PXDATA0_PIN          (GPIO_32)
#define CAMERA_DVP_PXDATA1_PIN          (GPIO_33)
#define CAMERA_DVP_PXDATA2_PIN          (GPIO_34)
#define CAMERA_DVP_PXDATA3_PIN          (GPIO_35)
#define CAMERA_DVP_PXDATA4_PIN          (GPIO_36)
#define CAMERA_DVP_PXDATA5_PIN          (GPIO_37)
#define CAMERA_DVP_PXDATA6_PIN          (GPIO_38)
#define CAMERA_DVP_PXDATA7_PIN          (GPIO_39)

#define CAMERA_DVP_MCLK_FUNC            (GPIO_DEV_JPEG_MCLK)
#define CAMERA_DVP_AUXS_FUNC            (GPIO_DEV_CLK_AUXS)
#define CAMERA_DVP_PCLK_FUNC            (GPIO_DEV_JPEG_PCLK)
#define CAMERA_DVP_HSYNC_FUNC           (GPIO_DEV_JPEG_HSYNC)
#define CAMERA_DVP_VSYNC_FUNC           (GPIO_DEV_JPEG_VSYNC)
#define CAMERA_DVP_PXDATA0_FUNC         (GPIO_DEV_JPEG_PXDATA0)
#define CAMERA_DVP_PXDATA1_FUNC         (GPIO_DEV_JPEG_PXDATA1)
#define CAMERA_DVP_PXDATA2_FUNC         (GPIO_DEV_JPEG_PXDATA2)
#define CAMERA_DVP_PXDATA3_FUNC         (GPIO_DEV_JPEG_PXDATA3)
#define CAMERA_DVP_PXDATA4_FUNC         (GPIO_DEV_JPEG_PXDATA4)
#define CAMERA_DVP_PXDATA5_FUNC         (GPIO_DEV_JPEG_PXDATA5)
#define CAMERA_DVP_PXDATA6_FUNC         (GPIO_DEV_JPEG_PXDATA6)
#define CAMERA_DVP_PXDATA7_FUNC         (GPIO_DEV_JPEG_PXDATA7)

#define CAMERA_DVP_I2C_ID               (CONFIG_DVP_CAMERA_I2C_ID)
#define CAMERA_DVP_I2C_BAUD_RATE        (I2C_BAUD_RATE_100KHZ)
#define CAMERA_DVP_I2C_MODE             (I2C_ADDR_MODE_7BIT)

/*
 * LCD RGB GPIO MAP
 */
#define LCD_RGB_R0_PIN 				(GPIO_55)  // GPIO_DEV_LCD_R0, FUNC_CODE_131
#define LCD_RGB_R1_PIN 				(GPIO_54)  // GPIO_DEV_LCD_R1, FUNC_CODE_131
#define LCD_RGB_R2_PIN 				(GPIO_53)  // GPIO_DEV_LCD_R2, FUNC_CODE_131
#define LCD_RGB_R3_PIN 				(GPIO_47)  // GPIO_DEV_LCD_R3, FUNC_CODE_131
#define LCD_RGB_R4_PIN 				(GPIO_46)  // GPIO_DEV_LCD_R4, FUNC_CODE_131
#define LCD_RGB_R5_PIN 				(GPIO_45)  // GPIO_DEV_LCD_R5, FUNC_CODE_131
#define LCD_RGB_R6_PIN 				(GPIO_44)  // GPIO_DEV_LCD_R6, FUNC_CODE_131
#define LCD_RGB_R7_PIN 				(GPIO_43)  // GPIO_DEV_LCD_R7, FUNC_CODE_131
#define LCD_RGB_G0_PIN 				(GPIO_52)  // GPIO_DEV_LCD_G0, FUNC_CODE_131
#define LCD_RGB_G1_PIN 				(GPIO_51)  // GPIO_DEV_LCD_G1, FUNC_CODE_131
#define LCD_RGB_G2_PIN 				(GPIO_42)  // GPIO_DEV_LCD_G2, FUNC_CODE_131
#define LCD_RGB_G3_PIN 				(GPIO_41)  // GPIO_DEV_LCD_G3, FUNC_CODE_131
#define LCD_RGB_G4_PIN 				(GPIO_40)  // GPIO_DEV_LCD_G4, FUNC_CODE_131
#define LCD_RGB_G5_PIN 				(GPIO_26)  // GPIO_DEV_LCD_G5, FUNC_CODE_131
#define LCD_RGB_G6_PIN 				(GPIO_25)  // GPIO_DEV_LCD_G6, FUNC_CODE_131
#define LCD_RGB_G7_PIN 				(GPIO_24)  // GPIO_DEV_LCD_G7, FUNC_CODE_131
#define LCD_RGB_B0_PIN 				(GPIO_50)  // GPIO_DEV_LCD_B0, FUNC_CODE_131
#define LCD_RGB_B1_PIN 				(GPIO_49)  // GPIO_DEV_LCD_B1, FUNC_CODE_131
#define LCD_RGB_B2_PIN 				(GPIO_48)  // GPIO_DEV_LCD_B2, FUNC_CODE_131
#define LCD_RGB_B3_PIN 				(GPIO_23)  // GPIO_DEV_LCD_B3, FUNC_CODE_131
#define LCD_RGB_B4_PIN 				(GPIO_22)  // GPIO_DEV_LCD_B4, FUNC_CODE_131
#define LCD_RGB_B5_PIN 				(GPIO_21)  // GPIO_DEV_LCD_B5, FUNC_CODE_131
#define LCD_RGB_B6_PIN 				(GPIO_20)  // GPIO_DEV_LCD_B6, FUNC_CODE_131
#define LCD_RGB_B7_PIN 				(GPIO_19)  // GPIO_DEV_LCD_B7, FUNC_CODE_131
#define LCD_RGB_CLK_PIN 			(GPIO_18)  // GPIO_DEV_LCD_CLK, FUNC_CODE_131
#define LCD_RGB_DISP_PIN 			(GPIO_17)  // GPIO_DEV_LCD_DISP, FUNC_CODE_131
#define LCD_RGB_DE_PIN 				(GPIO_14)  // GPIO_DEV_LCD_DE, FUNC_CODE_131
#define LCD_RGB_HSYNC_PIN 			(GPIO_16)  // GPIO_DEV_LCD_HSYNC, FUNC_CODE_131
#define LCD_RGB_VSYNC_PIN 			(GPIO_15)  // GPIO_DEV_LCD_VSYNC, FUNC_CODE_131



#define LCD_RGB_R0_FUNC 			(GPIO_DEV_LCD_R0)
#define LCD_RGB_R1_FUNC 			(GPIO_DEV_LCD_R1)
#define LCD_RGB_R2_FUNC 			(GPIO_DEV_LCD_R2)
#define LCD_RGB_R3_FUNC 			(GPIO_DEV_LCD_R3)
#define LCD_RGB_R4_FUNC 			(GPIO_DEV_LCD_R4)
#define LCD_RGB_R5_FUNC 			(GPIO_DEV_LCD_R5)
#define LCD_RGB_R6_FUNC 			(GPIO_DEV_LCD_R6)
#define LCD_RGB_R7_FUNC 			(GPIO_DEV_LCD_R7)

#define LCD_RGB_G0_FUNC 			(GPIO_DEV_LCD_G0)
#define LCD_RGB_G1_FUNC 			(GPIO_DEV_LCD_G1)
#define LCD_RGB_G2_FUNC 			(GPIO_DEV_LCD_G2)
#define LCD_RGB_G3_FUNC 			(GPIO_DEV_LCD_G3)
#define LCD_RGB_G4_FUNC 			(GPIO_DEV_LCD_G4)
#define LCD_RGB_G5_FUNC 			(GPIO_DEV_LCD_G5)
#define LCD_RGB_G6_FUNC 			(GPIO_DEV_LCD_G6)
#define LCD_RGB_G7_FUNC 			(GPIO_DEV_LCD_G7)

#define LCD_RGB_B0_FUNC 			(GPIO_DEV_LCD_B0)
#define LCD_RGB_B1_FUNC 			(GPIO_DEV_LCD_B1)
#define LCD_RGB_B2_FUNC 			(GPIO_DEV_LCD_B2)
#define LCD_RGB_B3_FUNC 			(GPIO_DEV_LCD_B3)
#define LCD_RGB_B4_FUNC 			(GPIO_DEV_LCD_B4)
#define LCD_RGB_B5_FUNC 			(GPIO_DEV_LCD_B5)
#define LCD_RGB_B6_FUNC 			(GPIO_DEV_LCD_B6)
#define LCD_RGB_B7_FUNC 			(GPIO_DEV_LCD_B7)

#define LCD_RGB_CLK_FUNC 			(GPIO_DEV_LCD_CLK)
#define LCD_RGB_DISP_FUNC 			(GPIO_DEV_LCD_DISP)
#define LCD_RGB_HSYNC_FUNC 			(GPIO_DEV_LCD_HSYNC)
#define LCD_RGB_VSYNC_FUNC 			(GPIO_DEV_LCD_VSYNC)
#define LCD_RGB_DE_FUNC 			(GPIO_DEV_LCD_DE)

#if CONFIG_GPIO_WAKEUP_SUPPORT
#define GPIO_STATIC_WAKEUP_SOURCE_MAP  \
	{\
		/*{GPIO_6, GPIO_INT_TYPE_LOW_LEVEL},*/ \
		{GPIO_10, GPIO_INT_TYPE_FALLING_EDGE},\
		/*{GPIO_40, GPIO_INT_LEVEL_LOW},*/ \
	}

#endif

#define GPIO_DEV_TO_IOMX_CODE_MAP \
{\
	[GPIO_DEV_GPIO_INPUT]  = FUNC_CODE_INPUT, \
	[GPIO_DEV_GPIO_OUTPUT] = FUNC_CODE_OUTPUT, \
	[GPIO_DEV_DMIC0_CLK] = FUNC_CODE_DMIC0_CLK, \
	[GPIO_DEV_DMIC0_DAT] = FUNC_CODE_DMIC0_DAT, \
	[GPIO_DEV_DMIC1_CLK] = FUNC_CODE_DMIC1_CLK, \
	[GPIO_DEV_DMIC1_DAT] = FUNC_CODE_DMIC1_DAT, \
	[GPIO_DEV_HDMI_CEC] = FUNC_CODE_HDMI_CEC, \
	[GPIO_DEV_I2S0_DIN] = FUNC_CODE_I2S0_DIN, \
	[GPIO_DEV_I2S0_DOUT] = FUNC_CODE_I2S0_DOUT, \
	[GPIO_DEV_I2S0_CLK] = FUNC_CODE_I2S0_SCK, \
	[GPIO_DEV_I2S0_SYNC] = FUNC_CODE_I2S0_SYNC, \
	[GPIO_DEV_I2S1_DIN] = FUNC_CODE_I2S1_DIN, \
	[GPIO_DEV_I2S1_DOUT] = FUNC_CODE_I2S1_DOUT, \
	[GPIO_DEV_I2S1_CLK] = FUNC_CODE_I2S1_SCK, \
	[GPIO_DEV_I2S1_SYNC] = FUNC_CODE_I2S1_SYNC, \
	[GPIO_DEV_I2S2_DIN] = FUNC_CODE_I2S2_DIN, \
	[GPIO_DEV_I2S2_DOUT] = FUNC_CODE_I2S2_DOUT, \
	[GPIO_DEV_I2S2_CLK] = FUNC_CODE_I2S2_SCK, \
	[GPIO_DEV_I2S2_SYNC] = FUNC_CODE_I2S2_SYNC, \
	[GPIO_DEV_I2S3_DIN] = FUNC_CODE_I2S3_DIN, \
	[GPIO_DEV_I2S3_DOUT] = FUNC_CODE_I2S3_DOUT, \
	[GPIO_DEV_I2S3_CLK] = FUNC_CODE_I2S3_SCK, \
	[GPIO_DEV_I2S3_SYNC] = FUNC_CODE_I2S3_SYNC, \
	[GPIO_DEV_I2S4_DIN] = FUNC_CODE_I2S4_DIN, \
	[GPIO_DEV_I2S4_DOUT] = FUNC_CODE_I2S4_DOUT, \
	[GPIO_DEV_I2S4_CLK] = FUNC_CODE_I2S4_SCK, \
	[GPIO_DEV_I2S4_SYNC] = FUNC_CODE_I2S4_SYNC, \
	[GPIO_DEV_I2S0_MCLK] = FUNC_CODE_I2S_MCLK, \
	[GPIO_DEV_SWCLK] = FUNC_CODE_SWCLK, \
	[GPIO_DEV_SWDIO] = FUNC_CODE_SWDIO, \
	[GPIO_DEV_PWM0] = FUNC_CODE_PWM0_0, \
	[GPIO_DEV_PWM1] = FUNC_CODE_PWM0_1, \
	[GPIO_DEV_PWM2] = FUNC_CODE_PWM0_2, \
	[GPIO_DEV_PWM3] = FUNC_CODE_PWM0_3, \
	[GPIO_DEV_PWM4] = FUNC_CODE_PWM0_4, \
	[GPIO_DEV_PWM5] = FUNC_CODE_PWM0_5, \
	[GPIO_DEV_PWM6] = FUNC_CODE_PWM0_6, \
	[GPIO_DEV_PWM7] = FUNC_CODE_PWM0_7, \
	[GPIO_DEV_PWM8] = FUNC_CODE_PWM0_8, \
	[GPIO_DEV_PWM9] = FUNC_CODE_PWM0_9, \
	[GPIO_DEV_PWM10] = FUNC_CODE_PWM0_10, \
	[GPIO_DEV_PWM11] = FUNC_CODE_PWM0_11, \
	[GPIO_DEV_SPI0_MISO] = FUNC_CODE_SPI0_MISO, \
	[GPIO_DEV_SPI0_MOSI] = FUNC_CODE_SPI0_MOSI, \
	[GPIO_DEV_SPI0_CSN] = FUNC_CODE_SPI0_NSS, \
	[GPIO_DEV_SPI0_SCK] = FUNC_CODE_SPI0_SCK, \
	[GPIO_DEV_SPI1_MISO] = FUNC_CODE_SPI1_MISO, \
	[GPIO_DEV_SPI1_MOSI] = FUNC_CODE_SPI1_MOSI, \
	[GPIO_DEV_SPI1_CSN] = FUNC_CODE_SPI1_NSS, \
	[GPIO_DEV_SPI1_SCK] = FUNC_CODE_SPI1_SCK, \
	[GPIO_DEV_SPI2_MISO] = FUNC_CODE_SPI2_MISO, \
	[GPIO_DEV_SPI2_MOSI] = FUNC_CODE_SPI2_MOSI, \
	[GPIO_DEV_SPI2_CSN] = FUNC_CODE_SPI2_NSS, \
	[GPIO_DEV_SPI2_SCK] = FUNC_CODE_SPI2_SCK, \
	[GPIO_DEV_SPI3_MISO] = FUNC_CODE_SPI3_MISO, \
	[GPIO_DEV_SPI3_MOSI] = FUNC_CODE_SPI3_MOSI, \
	[GPIO_DEV_SPI3_CSN] = FUNC_CODE_SPI3_NSS, \
	[GPIO_DEV_SPI3_SCK] = FUNC_CODE_SPI3_SCK, \
	[GPIO_DEV_I3C_SCL] = FUNC_CODE_I3C_SCL, \
	[GPIO_DEV_I3C_SDA] = FUNC_CODE_I3C_SDA, \
	[GPIO_DEV_I3C_SDA_PURN] = FUNC_CODE_I3C_SDA_PURN, \
	[GPIO_DEV_BT_ANT0] = FUNC_CODE_BT_ANT_0, \
	[GPIO_DEV_BT_ANT1] = FUNC_CODE_BT_ANT_1, \
	[GPIO_DEV_BT_ANT2] = FUNC_CODE_BT_ANT_2, \
	[GPIO_DEV_BT_ANT3] = FUNC_CODE_BT_ANT_3, \
	[GPIO_DEV_CAN_RX] = FUNC_CODE_CAN0_RX, \
	[GPIO_DEV_CAN_STANDBY] = FUNC_CODE_CAN0_STANDBY, \
	[GPIO_DEV_CAN_TX] = FUNC_CODE_CAN0_TX, \
	[GPIO_DEV_CAN1_RX] = FUNC_CODE_CAN1_RX, \
	[GPIO_DEV_CAN1_STANDBY] = FUNC_CODE_CAN1_STANDBY, \
	[GPIO_DEV_CAN1_TX] = FUNC_CODE_CAN1_TX, \
	[GPIO_DEV_I2C0_SCL] = FUNC_CODE_I2C0_SCL, \
	[GPIO_DEV_I2C0_SDA] = FUNC_CODE_I2C0_SDA, \
	[GPIO_DEV_I2C1_SCL] = FUNC_CODE_I2C1_SCL, \
	[GPIO_DEV_I2C1_SDA] = FUNC_CODE_I2C1_SDA, \
	[GPIO_DEV_IRDA] = FUNC_CODE_IRDA0, \
	[GPIO_DEV_IRDA1] = FUNC_CODE_IRDA1, \
	[GPIO_DEV_IRDA2] = FUNC_CODE_IRDA2, \
	[GPIO_DEV_IRDA3] = FUNC_CODE_IRDA3, \
	[GPIO_DEV_LIN_RXD] = FUNC_CODE_LIN0_RXD, \
	[GPIO_DEV_LIN_SLEEP] = FUNC_CODE_LIN0_SLEEP, \
	[GPIO_DEV_LIN_TXD] = FUNC_CODE_LIN0_TXD, \
	[GPIO_DEV_SCR_CLK] = FUNC_CODE_SC0_CLK, \
	[GPIO_DEV_SCR_IO] = FUNC_CODE_SC0_IO, \
	[GPIO_DEV_SCR_RSTN] = FUNC_CODE_SC0_RSTN, \
	[GPIO_DEV_SCR_VCC] = FUNC_CODE_SC0_VCC, \
	[GPIO_DEV_SPDIF0_RX] = FUNC_CODE_SPDIF0_RX, \
	[GPIO_DEV_SPDIF0_TX] = FUNC_CODE_SPDIF0_TX, \
	[GPIO_DEV_SPDIF1_RX] = FUNC_CODE_SPDIF1_RX, \
	[GPIO_DEV_SPDIF1_TX] = FUNC_CODE_SPDIF1_TX, \
	[GPIO_DEV_UART0_CTS] = FUNC_CODE_UART0_CTS, \
	[GPIO_DEV_UART0_RTS] = FUNC_CODE_UART0_RTS, \
	[GPIO_DEV_UART0_RXD] = FUNC_CODE_UART0_RXD, \
	[GPIO_DEV_UART0_TXD] = FUNC_CODE_UART0_TXD, \
	[GPIO_DEV_UART1_RXD] = FUNC_CODE_UART1_RXD, \
	[GPIO_DEV_UART1_TXD] = FUNC_CODE_UART1_TXD, \
	[GPIO_DEV_UART2_RXD] = FUNC_CODE_UART2_RXD, \
	[GPIO_DEV_UART2_TXD] = FUNC_CODE_UART2_TXD, \
	[GPIO_DEV_UART3_RXD] = FUNC_CODE_UART3_RXD, \
	[GPIO_DEV_UART3_TXD] = FUNC_CODE_UART3_TXD, \
	[GPIO_DEV_UART4_RXD] = FUNC_CODE_UART4_RXD, \
	[GPIO_DEV_UART4_TXD] = FUNC_CODE_UART4_TXD, \
}

struct mapping_func_code_fix_gpio{
	gpio_dev_t gdev;
	IOMX_CODE_T code;
	gpio_id_t id;
};

#define MAP_FUNC_CODE_FIX_GPIO \
{\
	{GPIO_DEV_OTP_FRE_EN, FUNC_CODE_126, GPIO_2},\
	{GPIO_DEV_OTP_FRE_SEL, FUNC_CODE_126, GPIO_3},\
	{GPIO_DEV_OTP_FRE_OUT, FUNC_CODE_126, GPIO_4},\
	{GPIO_DEV_CLK13M, FUNC_CODE_126, GPIO_6},\
	{GPIO_DEV_WIFI_ACTIVE, FUNC_CODE_126, GPIO_7},\
	{GPIO_DEV_CLK26M, FUNC_CODE_126, GPIO_22},\
	{GPIO_DEV_LPO_CLK, FUNC_CODE_126, GPIO_24},\
	{GPIO_DEV_WIFI_TX_EN, FUNC_CODE_126, GPIO_26},\
	{GPIO_DEV_FEM_LNA_EN, FUNC_CODE_126, GPIO_27},\
	{GPIO_DEV_WIFI_RX_EN, FUNC_CODE_126, GPIO_28},\
	{GPIO_DEV_DEBUG0, FUNC_CODE_127, GPIO_2},\
	{GPIO_DEV_DEBUG1, FUNC_CODE_127, GPIO_3},\
	{GPIO_DEV_DEBUG2, FUNC_CODE_127, GPIO_4},\
	{GPIO_DEV_DEBUG3, FUNC_CODE_127, GPIO_5},\
	{GPIO_DEV_DEBUG4, FUNC_CODE_127, GPIO_6},\
	{GPIO_DEV_DEBUG5, FUNC_CODE_127, GPIO_7},\
	{GPIO_DEV_DEBUG6, FUNC_CODE_127, GPIO_8},\
	{GPIO_DEV_DEBUG7, FUNC_CODE_127, GPIO_9},\
	{GPIO_DEV_DEBUG8, FUNC_CODE_127, GPIO_14},\
	{GPIO_DEV_DEBUG9, FUNC_CODE_127, GPIO_15},\
	{GPIO_DEV_DEBUG10, FUNC_CODE_127, GPIO_16},\
	{GPIO_DEV_DEBUG11, FUNC_CODE_127, GPIO_17},\
	{GPIO_DEV_DEBUG12, FUNC_CODE_127, GPIO_18},\
	{GPIO_DEV_DEBUG13, FUNC_CODE_127, GPIO_19},\
	{GPIO_DEV_DEBUG14, FUNC_CODE_127, GPIO_24},\
	{GPIO_DEV_DEBUG15, FUNC_CODE_127, GPIO_25},\
	{GPIO_DEV_DEBUG16, FUNC_CODE_127, GPIO_26},\
	{GPIO_DEV_DEBUG17, FUNC_CODE_127, GPIO_27},\
	{GPIO_DEV_DEBUG18, FUNC_CODE_127, GPIO_28},\
	{GPIO_DEV_DEBUG19, FUNC_CODE_127, GPIO_29},\
	{GPIO_DEV_DEBUG20, FUNC_CODE_127, GPIO_30},\
	{GPIO_DEV_DEBUG21, FUNC_CODE_127, GPIO_31},\
	{GPIO_DEV_DEBUG22, FUNC_CODE_127, GPIO_32},\
	{GPIO_DEV_DEBUG23, FUNC_CODE_127, GPIO_33},\
	{GPIO_DEV_DEBUG24, FUNC_CODE_127, GPIO_34},\
	{GPIO_DEV_DEBUG25, FUNC_CODE_127, GPIO_35},\
	{GPIO_DEV_DEBUG26, FUNC_CODE_127, GPIO_36},\
	{GPIO_DEV_DEBUG27, FUNC_CODE_127, GPIO_37},\
	{GPIO_DEV_DEBUG28, FUNC_CODE_127, GPIO_38},\
	{GPIO_DEV_DEBUG29, FUNC_CODE_127, GPIO_39},\
	{GPIO_DEV_DEBUG30, FUNC_CODE_127, GPIO_42},\
	{GPIO_DEV_DEBUG31, FUNC_CODE_127, GPIO_43},\
	{GPIO_DEV_SDIO_HOST_CLK, FUNC_CODE_129, GPIO_2},\
	{GPIO_DEV_SDIO_HOST_CMD, FUNC_CODE_129, GPIO_3},\
	{GPIO_DEV_SDIO_HOST_DATA0, FUNC_CODE_129, GPIO_4},\
	{GPIO_DEV_SDIO_HOST_DATA1, FUNC_CODE_129, GPIO_5},\
	{GPIO_DEV_SDIO_HOST_DATA4, FUNC_CODE_129, GPIO_6},\
	{GPIO_DEV_SDIO_HOST_DATA5, FUNC_CODE_129, GPIO_7},\
	{GPIO_DEV_SDIO_HOST_DATA6, FUNC_CODE_129, GPIO_8},\
	{GPIO_DEV_SDIO_HOST_DATA7, FUNC_CODE_129, GPIO_9},\
	{GPIO_DEV_SDIO_HOST_DATA2, FUNC_CODE_129, GPIO_10},\
	{GPIO_DEV_SDIO_HOST_DATA3, FUNC_CODE_129, GPIO_11},\
	{GPIO_DEV_SDIO_HOST_STB, FUNC_CODE_129, GPIO_12},\
	{GPIO_DEV_SDIO1_HOST_CLK, FUNC_CODE_129, GPIO_14},\
	{GPIO_DEV_SDIO1_HOST_CMD, FUNC_CODE_129, GPIO_15},\
	{GPIO_DEV_SDIO1_HOST_DATA0, FUNC_CODE_129, GPIO_16},\
	{GPIO_DEV_SDIO1_HOST_DATA1, FUNC_CODE_129, GPIO_17},\
	{GPIO_DEV_SDIO1_HOST_DATA2, FUNC_CODE_129, GPIO_18},\
	{GPIO_DEV_SDIO1_HOST_DATA3, FUNC_CODE_129, GPIO_19},\
	{GPIO_DEV_SDIO1_HOST_DATA4, FUNC_CODE_129, GPIO_20},\
	{GPIO_DEV_SDIO1_HOST_DATA5, FUNC_CODE_129, GPIO_21},\
	{GPIO_DEV_SDIO1_HOST_DATA6, FUNC_CODE_129, GPIO_22},\
	{GPIO_DEV_SDIO1_HOST_DATA7, FUNC_CODE_129, GPIO_23},\
	{GPIO_DEV_SDIO1_HOST_STB, FUNC_CODE_129, GPIO_24},\
	{GPIO_DEV_CLK_AUXS_CIS, FUNC_CODE_129, GPIO_27},\
	{GPIO_DEV_CLK_AUXS, FUNC_CODE_129, GPIO_28},\
	{GPIO_DEV_JPEG_PCLK, FUNC_CODE_129, GPIO_29},\
	{GPIO_DEV_JPEG_HSYNC, FUNC_CODE_129, GPIO_30},\
	{GPIO_DEV_JPEG_VSYNC, FUNC_CODE_129, GPIO_31},\
	{GPIO_DEV_JPEG_PXDATA0, FUNC_CODE_129, GPIO_32},\
	{GPIO_DEV_JPEG_PXDATA1, FUNC_CODE_129, GPIO_33},\
	{GPIO_DEV_JPEG_PXDATA2, FUNC_CODE_129, GPIO_34},\
	{GPIO_DEV_JPEG_PXDATA3, FUNC_CODE_129, GPIO_35},\
	{GPIO_DEV_JPEG_PXDATA4, FUNC_CODE_129, GPIO_36},\
	{GPIO_DEV_JPEG_PXDATA5, FUNC_CODE_129, GPIO_37},\
	{GPIO_DEV_JPEG_PXDATA6, FUNC_CODE_129, GPIO_38},\
	{GPIO_DEV_JPEG_PXDATA7, FUNC_CODE_129, GPIO_39},\
	{GPIO_DEV_JPEG_PXDATA8, FUNC_CODE_129, GPIO_40},\
	{GPIO_DEV_JPEG_PXDATA9, FUNC_CODE_129, GPIO_41},\
	{GPIO_DEV_ENET_REF_CLK, FUNC_CODE_129, GPIO_49},\
	{GPIO_DEV_CLK_AUXS_CIS, FUNC_CODE_129, GPIO_59},\
	{GPIO_DEV_SDIO_HOST_STB, FUNC_CODE_129, GPIO_61},\
	{GPIO_DEV_SDIO_HOST_DATA7, FUNC_CODE_129, GPIO_62},\
	{GPIO_DEV_SDIO_HOST_DATA6, FUNC_CODE_129, GPIO_63},\
	{GPIO_DEV_SDIO_HOST_DATA5, FUNC_CODE_129, GPIO_64},\
	{GPIO_DEV_SDIO_HOST_DATA4, FUNC_CODE_129, GPIO_65},\
	{GPIO_DEV_SDIO_HOST_DATA3, FUNC_CODE_129, GPIO_66},\
	{GPIO_DEV_SDIO_HOST_DATA2, FUNC_CODE_129, GPIO_67},\
	{GPIO_DEV_SDIO_HOST_DATA1, FUNC_CODE_129, GPIO_68},\
	{GPIO_DEV_SDIO_HOST_DATA0, FUNC_CODE_129, GPIO_69},\
	{GPIO_DEV_SDIO_HOST_CMD, FUNC_CODE_129, GPIO_70},\
	{GPIO_DEV_SDIO_HOST_CLK, FUNC_CODE_129, GPIO_71},\
	{GPIO_DEV_QSPI1_CLK, FUNC_CODE_130, GPIO_2},\
	{GPIO_DEV_QSPI1_CSN, FUNC_CODE_130, GPIO_3},\
	{GPIO_DEV_QSPI1_IO0, FUNC_CODE_130, GPIO_4},\
	{GPIO_DEV_QSPI1_IO1, FUNC_CODE_130, GPIO_5},\
	{GPIO_DEV_QSPI1_IO2, FUNC_CODE_130, GPIO_6},\
	{GPIO_DEV_QSPI1_IO3, FUNC_CODE_130, GPIO_7},\
	{GPIO_DEV_CLK_AUXS, FUNC_CODE_130, GPIO_10},\
	{GPIO_DEV_ENET_REF_CLK, FUNC_CODE_130, GPIO_21},\
	{GPIO_DEV_QSPI0_CLK, FUNC_CODE_130, GPIO_22},\
	{GPIO_DEV_QSPI0_CSN, FUNC_CODE_130, GPIO_23},\
	{GPIO_DEV_QSPI0_IO0, FUNC_CODE_130, GPIO_24},\
	{GPIO_DEV_QSPI0_IO1, FUNC_CODE_130, GPIO_25},\
	{GPIO_DEV_QSPI0_IO2, FUNC_CODE_130, GPIO_26},\
	{GPIO_DEV_QSPI0_IO3, FUNC_CODE_130, GPIO_27},\
	{GPIO_DEV_ENET_GTCLK, FUNC_CODE_130, GPIO_40},\
	{GPIO_DEV_ENET_TXD3, FUNC_CODE_130, GPIO_41},\
	{GPIO_DEV_ENET_TXD2, FUNC_CODE_130, GPIO_42},\
	{GPIO_DEV_ENET_TXD1, FUNC_CODE_130, GPIO_43},\
	{GPIO_DEV_ENET_TXD0, FUNC_CODE_130, GPIO_44},\
	{GPIO_DEV_ENET_TXEN, FUNC_CODE_130, GPIO_45},\
	{GPIO_DEV_CLK_AUXS_ENET, FUNC_CODE_130, GPIO_46},\
	{GPIO_DEV_ENET_MDC, FUNC_CODE_130, GPIO_47},\
	{GPIO_DEV_ENET_MDIO, FUNC_CODE_130, GPIO_48},\
	{GPIO_DEV_ENET_GRCLK, FUNC_CODE_130, GPIO_49},\
	{GPIO_DEV_ENET_RXDV, FUNC_CODE_130, GPIO_50},\
	{GPIO_DEV_ENET_RXD0, FUNC_CODE_130, GPIO_51},\
	{GPIO_DEV_ENET_RXD1, FUNC_CODE_130, GPIO_52},\
	{GPIO_DEV_ENET_RXD2, FUNC_CODE_130, GPIO_53},\
	{GPIO_DEV_ENET_RXD3, FUNC_CODE_130, GPIO_54},\
	{GPIO_DEV_ENET_PHY_INT, FUNC_CODE_130, GPIO_55},\
	{GPIO_DEV_ENET_PHY_INT, FUNC_CODE_130, GPIO_60},\
	{GPIO_DEV_UART5_RXD, FUNC_CODE_130, GPIO_64},\
	{GPIO_DEV_UART5_TXD, FUNC_CODE_130, GPIO_65},\
	{GPIO_DEV_LCD_DE, FUNC_CODE_131, GPIO_14},\
	{GPIO_DEV_LCD_VSYNC, FUNC_CODE_131, GPIO_15},\
	{GPIO_DEV_LCD_HSYNC, FUNC_CODE_131, GPIO_16},\
	{GPIO_DEV_LCD_DISP, FUNC_CODE_131, GPIO_17},\
	{GPIO_DEV_LCD_CLK, FUNC_CODE_131, GPIO_18},\
	{GPIO_DEV_LCD_B7, FUNC_CODE_131, GPIO_19},\
	{GPIO_DEV_LCD_B6, FUNC_CODE_131, GPIO_20},\
	{GPIO_DEV_LCD_B5, FUNC_CODE_131, GPIO_21},\
	{GPIO_DEV_LCD_B4, FUNC_CODE_131, GPIO_22},\
	{GPIO_DEV_LCD_B3, FUNC_CODE_131, GPIO_23},\
	{GPIO_DEV_LCD_G7, FUNC_CODE_131, GPIO_24},\
	{GPIO_DEV_LCD_G6, FUNC_CODE_131, GPIO_25},\
	{GPIO_DEV_LCD_G5, FUNC_CODE_131, GPIO_26},\
	{GPIO_DEV_JPEG_MCLK, FUNC_CODE_131, GPIO_27},\
	{GPIO_DEV_LCD_G4, FUNC_CODE_131, GPIO_40},\
	{GPIO_DEV_LCD_G3, FUNC_CODE_131, GPIO_41},\
	{GPIO_DEV_LCD_G2, FUNC_CODE_131, GPIO_42},\
	{GPIO_DEV_LCD_R7, FUNC_CODE_131, GPIO_43},\
	{GPIO_DEV_LCD_R6, FUNC_CODE_131, GPIO_44},\
	{GPIO_DEV_LCD_R5, FUNC_CODE_131, GPIO_45},\
	{GPIO_DEV_LCD_R4, FUNC_CODE_131, GPIO_46},\
	{GPIO_DEV_LCD_R3, FUNC_CODE_131, GPIO_47},\
	{GPIO_DEV_LCD_B2, FUNC_CODE_131, GPIO_48},\
	{GPIO_DEV_LCD_B1, FUNC_CODE_131, GPIO_49},\
	{GPIO_DEV_LCD_B0, FUNC_CODE_131, GPIO_50},\
	{GPIO_DEV_LCD_G1, FUNC_CODE_131, GPIO_51},\
	{GPIO_DEV_LCD_G0, FUNC_CODE_131, GPIO_52},\
	{GPIO_DEV_LCD_R2, FUNC_CODE_131, GPIO_53},\
	{GPIO_DEV_LCD_R1, FUNC_CODE_131, GPIO_54},\
	{GPIO_DEV_LCD_R0, FUNC_CODE_131, GPIO_55},\
	{GPIO_DEV_ENET_GTCLK, FUNC_CODE_132, GPIO_13},\
	{GPIO_DEV_ENET_TXD3, FUNC_CODE_132, GPIO_14},\
	{GPIO_DEV_ENET_TXD2, FUNC_CODE_132, GPIO_15},\
	{GPIO_DEV_ENET_TXD1, FUNC_CODE_132, GPIO_16},\
	{GPIO_DEV_ENET_TXD0, FUNC_CODE_132, GPIO_17},\
	{GPIO_DEV_CLK_AUXS_ENET, FUNC_CODE_132, GPIO_18},\
	{GPIO_DEV_ENET_MDC, FUNC_CODE_132, GPIO_19},\
	{GPIO_DEV_ENET_MDIO, FUNC_CODE_132, GPIO_20},\
	{GPIO_DEV_ENET_GRCLK, FUNC_CODE_132, GPIO_21},\
	{GPIO_DEV_ENET_RXDV, FUNC_CODE_132, GPIO_22},\
	{GPIO_DEV_ENET_RXD0, FUNC_CODE_132, GPIO_23},\
	{GPIO_DEV_ENET_RXD1, FUNC_CODE_132, GPIO_24},\
	{GPIO_DEV_ENET_RXD2, FUNC_CODE_132, GPIO_25},\
	{GPIO_DEV_ENET_RXD3, FUNC_CODE_132, GPIO_26},\
	{GPIO_DEV_ENET_TXEN, FUNC_CODE_132, GPIO_28},\
}

#ifdef __cplusplus
}
#endif
