#pragma once

/*
 * Keep the AP debug UART available. The DUT CLI itself is forwarded from
 * CP UART0 through ap_cmd.
 */
#define GPIO_DEFAULT_DEV_CONFIG \
{ \
    {GPIO_64, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_UART5_RXD, GPIO_DEV_INVALID, GPIO_PULL_UP_EN, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3, GPIO_INIT_ENABLE}, \
    {GPIO_65, GPIO_SECOND_FUNC_ENABLE, GPIO_DEV_UART5_TXD, GPIO_DEV_INVALID, GPIO_PULL_UP_EN, GPIO_INT_DISABLE, GPIO_INT_TYPE_LOW_LEVEL, GPIO_LOW_POWER_DISCARD_IO_STATUS, GPIO_DRIVER_CAPACITY_3, GPIO_INIT_ENABLE}, \
}
