

// Copyright 2025-2026 Beken
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#pragma once

#ifdef __cplusplus
extern "C" {
#endif



/**
 * @brief The kind of test pattern that can be generated by the DSI Host controller
 */
typedef enum {
    MIPI_DSI_PATTERN_NONE,           /*!< No pattern */
    MIPI_DSI_PATTERN_BAR_VERTICAL,   /*!< Vertical BAR pattern, with different colors */
    MIPI_DSI_PATTERN_BAR_HORIZONTAL, /*!< Horizontal BAR pattern, with different colors */
    MIPI_DSI_PATTERN_BER_VERTICAL,   /*!< Vertical Bit Error Rate(BER) pattern */
} mipi_dsi_pattern_type_t;

uint16_t mipi_dsi_gen_write(uint16_t data_len, const uint8_t *data);



bk_err_t mipi_dsi_clock_set(bk_panel_clock_config_t *dsi, bk_lcd_bus_io_t **ret_panel);

bk_err_t mipi_dsi_bus_register(bk_panel_clock_config_t *dsi, bk_lcd_bus_io_t **ret_panel);


/**
 * @brief Set pre-defined pattern to the screen for testing or debugging purpose
 *
 * @param[in] dpi_panel MIPI DPI panel handle, returned frombk_lcd_new_panel_dpi()
 * @param[in] pattern Pattern type
 * @return
 *      - BK_OK: Set pattern successfully
 *      - BK_ERR_INVALID_ARG: Set pattern failed because of invalid argument
 *      - BK_FAIL: Set pattern failed because of other error
 */
bk_err_t mipi_dsi_panel_set_pattern(bk_lcd_bus_io_t *dsi_panel, mipi_dsi_pattern_type_t pattern);



#ifdef __cplusplus
}
#endif


